### ISSUE TITLE
core: clean up cardigann parser

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#10092]
Issues:

* `details` and `comments` parameters have the same function?

https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1463

* `release.Guid` code should be handled in `FixResults`

https://github.com/Jackett/Jackett/blob/14fdea164ce78cfa6b2ca7c288692a1c7a7e891b/src/Jackett.Common/Indexers/BaseIndexer.cs#L287

**Comment by garfield69** [comment]
I think **details** is a link that always takes you to the main details page of a torrent
**comments** is a link that (when available in results), takes you to the # navigation jump point in the details page where the comments are, (and when not available), defaults to essentially the same place as details.

**Comment by ngosang** [comment]
But the code is the same for both. Details doesn't exist in Release object, just `release.Comments`

**Comment by garfield69** [comment]
You're talking about the actual code in cardigann as opposed to what I thought was the intent of the details and comments yaml statements.

All I know is that I have some yaml that look like this example
```yaml
    details:
      selector: a.view-torrent
      attribute: href
    comments:
      selector: a[href*="#comments"]
      attribute: href
```

Are you saying  that if the details statement exists, if replaces the details one?
is that a problem?
