### ISSUE TITLE
[extratorrent-cd] returning age for results <1hr old as 2020y ago

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#10099]
```
<td class="tli"> <a href="//extratorrent.si/torrent/912/The.Simpsons.S32E04.Treehouse.of.Horror.XXXI.XviD-AFG[TGx].html" title="view The.Simpsons.S32E04.Treehouse.of.Horror.XXXI.XviD-AFG[TGx] torrent">The.Simpsons.S32E04.Treehouse.of.Horror.XXXI.XviD-AFG[TGx]</a><span class="c_tor"> in <a href="https://extratorrent.si/category/9/Other+Torrents.html" title="Browse Other">Other</a></span><span class="c_tor">, by</span> <span class="micro"><div class="usr"><div id="uettv828" class="usrm"></div><a href="/profile/ sotnikam /" style="color:#CC0000;"> sotnikam </a></div></span>
--
  | </td>
  | <td><b>4-mins-ago</b></td>
  | <td>289.11 MiB</td>
  | <td class="sn">0</td>
  | <td class="ln">0</td>
  | <td>
  | <div class="r1"></div>
  | </td>
  | </tr>
```
Because it's bold? Not sure. Tried and failed resolving it myself :P

**Comment by garfield69** [comment]
the indexer does not have a timeago block for this date format.
its got one for Today-hh:mm and Y-day-yyyy 
and one for MM-dd-yyyy
so we need to add one for timeago, replacing the `-` with space and using the timeago filter.
something like
```yaml
    date:
      # 4-mins-ago
      selector: td:nth-last-of-type(5):contains("ago")
      optional: true
      filters:
        - name: replace
          args: ["\xA0", "-"]
        - name: replace
          args: ["-", " "]
        - name: timeago
```
also need to add a `:not(:contains("day"))` to the date MM-dd-yyyy block selector to stop it trying to process 4-mins-ago
