### ISSUE TITLE
[enhancement] Cardigann - new keyword default, to set a default when the selector does not match

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10229]
Currently, when a selector does not match, and the optional keyword is included, then you can end up with attributes that are left null.
The work around ATM is to set a text before hand, to preload the attribute, and then code the selector with the optional.
Existing example:
```yaml
    seeders:
      text: 0
    seeders:
      optional: true
      selector: .seeders
```

I'd like to propose an enhancement called default, which essentially does the preload for the optional block.
Suggestion:
```yaml
    seeders:
      default: 0
      selector: .seeders
      optional: true
```
I think this would be a useful enhancement.
But I don't know the ramifications of what I'm proposing in terms of the impact to the Cardigann code, and how much work it will involve, so obviously if it gets too messy or complicated then forget it, the existing method work well enough.
