### ISSUE TITLE
[enhancement] polishtracker convert current c# indexer to use polishtracker API

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#10495]
from https://github.com/Jackett/Jackett/issues/8780#issuecomment-744011022 @sevospl wrote:
>Hi @garfield69 and @ngosang.
>I would love to let you know that PolishTrackers' API has been updated. It now can be fully used by Jackett. I additionaly asked their staff to make sure it's ready to use.
>As a user [you can get an API key](https://pte.nu/user/api) and [API is well documented](https://cdn.pte.nu/docs/index.html).
>TL;DR: there are 2 endpoints: [Torrents List](https://cdn.pte.nu/docs/index.html#torrents-list) and [Torrent Download](https://cdn.pte.nu/docs/index.html#torrent-download).
>This means there is no longer need for cookie method. API would be the preferred way to go and I hope someone would like to take it and implement API method :)

**Comment by ngosang** [comment]
@ilike2burnthing @garfield69 could be implemented in Cardigann JSON?

**Comment by ilike2burnthing** [comment]
Only you have an account.

**Comment by ilike2burnthing** [comment]
Ok, so a few stumbling blocks:
- there's no search function in their API that I can see from the doc
- because we can't do andmatch in json we can't filter results
- the header doesn't appear to be being passed to login, so it always fails
- I couldn't get the login error selector to work, not sure why

<details>
<summary>polishtracker-api.yml</summary>

```yml
---
id: polishtracker-api
name: PolishTracker (API)
description: "PolishTracker is a POLISH Private site for 0DAY / MOVIES / GENERAL"
language: pl-PL
type: private
encoding: UTF-8
links:
  - https://pte.nu/
legacylinks:
  - https://polishtracker.net/

caps:
  categorymappings:
    - {id: 1, cat: PC/0day, desc: "0-Day"}
    - {id: 2, cat: Audio/Video, desc: "Music Video"}
    - {id: 3, cat: PC/0day, desc: "Apps"}
    - {id: 4, cat: Console, desc: "Consoles"}
    - {id: 5, cat: Books, desc: "E-book"}
    - {id: 6, cat: Movies/HD, desc: "Movies HD"}
    - {id: 7, cat: Movies/SD, desc: "Movies SD"}
    - {id: 8, cat: Audio, desc: "Music"}
    - {id: 9, cat: Movies/UHD, desc: "Movies UHD"}
    - {id: 10, cat: PC/Games, desc: "PC Games"}
    - {id: 11, cat: TV/HD, desc: "TV HD"}
    - {id: 12, cat: TV/SD, desc: "TV SD"}
    - {id: 13, cat: XXX, desc: "XXX"}
    - {id: 14, cat: TV/UHD, desc: "TV-UHD"}
    - {id: 15, cat: Audio/Audiobook, desc: "Audiobook"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: apikey
    type: text
    label: APIKey
  - name: info_key
    type: info
    label: About your API key
    default: "Find your API Key by accessing your <a href=\"https://pte.nu/\" target =_blank>PolishTracker</a> account <i>Settings</i> page and clicking on the <b>API</b> section."

#login:
#  path: "https://api.pte.nu/torrents/list"
#  method: get
#  inputs:
#    num: 1
#  error:
#    - selector: ":root:contains(\"Invalid auth token\")"
#      message:
#        text: "The API key was not accepted by {{ .Config.sitelink }}."

search:
  paths:
    # docs: https://cdn.pte.nu/docs/index.html
    - path: "https://api.pte.nu/torrents/list?num=100"
      response:
        type: json

  headers:
    API-key: ["{{ .Config.apikey }}"]

  rows:
    selector: $
# jackett yml json does not currently support andmatch #13083
#    filters:
#      - name: andmatch

  fields:
    _id:
      selector: id
    category:
      selector: category
    title:
      selector: name
    details:
      text: "{{ .Config.sitelink }}torrents/{{ .Result._id }}"
    download:
      text: "https://api.pte.nu/torrents/download/{{ .Result._id }}"
    imdbid:
      selector: imdb_id
    seeders:
      selector: seeders
    leechers:
      selector: leechers
    grabs:
      selector: completed
    date:
      # 2022-08-09T17:37:03.23587+02:00
      selector: added
    size:
      selector: size
    downloadvolumefactor:
      text: 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 3 day (as seconds = 3 x 24 x 60 x 60)
      text: 259200
# json api

```
</details>
