### ISSUE TITLE
Unnecessary redirects with CardigannIndexer?

### ISSUE THREAD

**Issue by darksol736** [Jackett/Jackett#1058]
Hello,

I noticed unexpected redirects for multi-word queries while stepping through the CardigannIndexer code. Is it on purpose or unnecessary traffic with the sites?

For example a manual search of isohunt with "foo bar".
CardigannIndexer generates "https://isohunt.to/torrents/?ihq=foo bar/"
The site replies with a redirect to "https://isohunt.to/torrents/?ihq=foo+bar/". Please note the space was replaced with a + sign.

------
Quick analysis: seems to be an issue with the definitions that have a condition in the search path. Applying the go template does not encode .Query.Keywords.
isohunt.yml:
```
search:
    path: "{{if .Query.Keywords}}torrents/?ihq={{ .Query.Keywords}}/{{else}}/latest.php{{end}}"
```

Encoding of the keywords does happen for other definitions that use the non-raw inputs as they go through GetQueryString(Encoding).
For example kickasstorrent.yml goes straight to "https://katcr.co/new/torrents-search.php?&search=foo+bar"
```
search:
    path: "/new/torrents-search.php"
    inputs:
      $raw: "{{range .Categories}}c{{.}}=1&{{end}}"
      search: "{{ .Query.Keywords }}"
```
Thank you for creating the Cardigann indexer, it seems pretty easy to create new definition files!
