### ISSUE TITLE
[REQ]javtorrent.re 

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#10649]
Public japan adult video share torrent site.

Search engine and torrents working.

http://javtorrent.re

![1](https://user-images.githubusercontent.com/36575395/103248475-c6337c00-497b-11eb-9b3f-7c5bae8983df.JPG)
![2](https://user-images.githubusercontent.com/36575395/103248478-c7fd3f80-497b-11eb-9dbc-ca9ef7c6874e.JPG)

**Comment by garfield69** [comment]
hmm. not working. the posters and download links are provided by an alternate server that is returning not-authorised when jackett tries the href.
example:
http://jtl.re/x/21/h210727155203_s.jpg
http://jtl.re/d/21/h210727155203.torrent

I do not understand.
here is the yml so far:
```yaml
---
id: javtorrent
name: JAVtorrent
description: "JAVtorrent is a JAPANESE Public site for 3X"
language: ja-JP
type: public
encoding: UTF-8
links:
  - http://javtorrent.re/ # https unsupported

caps:
  categorymappings:
    - {id: Censored, cat: XXX, desc: Censored}
    - {id: Uncensored, cat: XXX, desc: Uncensored}
    - {id: IV, cat: XXX, desc: IV}
    - {id: H-Game, cat: XXX, desc: H-Game}

  modes:
    search: [q]

settings: []

search:
  paths:
    - path: "{{ if .Keywords }}?s={{ .Keywords }}{{ else }}new/{{ end }}"

  rows:
    selector: div.base > div:has(a.entry-dl)

  fields:
    category:
      selector: span.cate-ca
    title:
      selector: span.base-t
    details:
      selector: div:first-child a
      attribute: href
    download:
      selector: a.entry-dl
      attribute: href
      filters:
        - name: prepend
          args: "http:"
    poster:
      selector: img
      attribute: src
      filters:
        - name: prepend
          args: "http:"
    date:
      selector: span.meta
      filters:
        - name: regexp
          args: (\d{4}/\d{2}/\d{2})
        - name: append
          args: " +09:00" # JST
        - name: dateparse
          args: "2006/01/02 -07:00"
    size:
      text: "512 MB"
    seeders:
      text: 1
    leechers:
      text: 1
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine n/a
```
this is the row
```html
<div>
    <a href="/uncensored/222703/">
        <img src="//jtl.re/x/21/h210727155203_s.jpg">
        <span class="meta ca-Uncensored">
            <span class="new"></span>
            2021/07/29<span class="cate-ca">Uncensored</span>
        </span>
        <span class="base-t">[SNIS-731] 汗だく汁だくRIONの本気汁ダラダラ熱気ムンムン灼熱性交 【無修正】</span>
    </a>
    <a class="entry-dl" href="//jtl.re/d/21/h210727155203.torrent">DL</a>
</div>
```
