### ISSUE TITLE
Option 'ProxyConnection' is unknown

### ISSUE THREAD

**Issue by schel4ok** [Jackett/Jackett#10711]
In docker-compose I have following setup for jackett
```
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - RUN_OPTS=--ProxyConnection=torproxy:8118
    volumes:
      - ./jackett:/config
    ports:
      - 9117:9117
    restart: always
    networks:
      - linuxserver
```

Everything worked well few month, but today I noticed jacket is not running.
In logs I found `Option 'ProxyConnection' is unknown`
Then I commented `RUN_OPTS` string and jacket started well.

Why this option has been removed?
