### ISSUE TITLE
Missing results in Jackett (search : manual and auto)

### ISSUE THREAD

**Issue by WoisWoi** [Jackett/Jackett#10733]
### Environment

OS: Linux Ubunta Server 20.04 (x64)

Jackett Version: v0.17.197

Last Working Jackett Version: v0.17.197 I guess

Are you using a proxy or VPN? no

### Description

When I do a research with Radarr, Sonarr or manually directly into Jackett, results are missing (compared to the one I get by searching directly on the tracker). In this case, YGGTorrent is the tracker and I'm using FlareSolverr with the hcaptcha-solver. 

### Log

"2021-01-04 23:37:23.6561 Info Manual search in yggtorrent for Supernatural => Found 100 releases "
No error(s) on the search. Is there a limitation to 100 releases found ? I found 346 results on the tracker with the same request.

**Comment by ilike2burnthing** [comment]
URL when searching on ygg:
https://www2.yggtorrent.si/engine/search?name=supernatural&do=search

URL when searching through Jackett (using default indexer settings):
https://www2.yggtorrent.si/engine/search?category=all&name=supernatural&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date

Both return 346 results. The difference is just that the latter is sorted by date (which you can change in the indexer's settings).

We're just retrieving the first page of results (twice, due to https://github.com/Jackett/Jackett/pull/9114 - @xfouloux was that unavoidable? We end up with most/all results duplicated), hence why there are results not included. While we can increase the number of pages retrieved, due to the current setup we'd be requesting 4 pages instead of 2, and still only get 100 unique results - increasing search times for users, and server loads for ygg (which I'm pretty sure are already an issue for them).

Does that explain what you're seeing, or was there a different issue?

**Comment by xfouloux** [comment]
Well it's been a long time since we do not request multiple pages on the YGG Indexer i think, hence the 100 result limit

If there is a way to detect there is more than 1 page of results, then perform the request to page 2, etc etc, i don't remember if there is something like this possible in YML

My pull included the fix about French 'Saison' (season) word to be matched on search, but because of YML indexer limitation, i had not found any other way than doing a second search with a regex replace of "Season" by "Saison" and still a normal search with Season word, then bunch of regex for the results to display "Season" everywhere.

Unless someone find a better way, or do it as a C# indexer, there will always be issues :(

Or maybe the jackett core could be having a remove duplicate function ?

**Comment by xfouloux** [comment]
In any case, i remember that we removed the multiple pages, because sonarr, radarr and such should be precise enough to not make a request that would return lots of results to YGG, but well it could i guess, especially for animes

It really need a big rework in C# someday

**Comment by ilike2burnthing** [comment]
Yea, the request for the second page `...&page=50` was swapped out for the saison fix, so if we wanted the second page, we'd need to (well, should) include it for the fix as well, therefore making 4 requests to the site.

Though we could change it so at least the keywordless search gets the second page, no duplicates:
https://github.com/Jackett/Jackett/blob/4e98e654108562af944adf1f46e8f4f7054e52d6/src/Jackett.Common/Definitions/yggtorrent.yml#L228
```
...&name={{ if .Keywords }}{{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}{{ else }}&page=50{{ end }}&description=...
```
I'll test it in a bit.

**Comment by WoisWoi** [comment]
> 
> 
> Yea, the request for the second page `...&page=50` was swapped out for the saison fix, so if we wanted the second page, we'd need to (well, should) include it for the fix as well, therefore making 4 requests to the site.
> 
> Though we could change it so at least the keywordless search gets the second page, no duplicates:
> 
> https://github.com/Jackett/Jackett/blob/4e98e654108562af944adf1f46e8f4f7054e52d6/src/Jackett.Common/Definitions/yggtorrent.yml#L228
> 
> ```
> ...&name={{ if .Keywords }}{{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}{{ else }}&page=50{{ end }}&description=...
> ```
> 
> I'll test it in a bit.
> 
> EDIT: yep, that worked. Will have another look at the saison fix, but I very much I'll get anywhere.

![image](https://user-images.githubusercontent.com/75491231/103659700-00e57780-4f6d-11eb-9287-4ad9d568a005.png)
The problem is still there, I haven't noticed any differences.

**Comment by ilike2burnthing** [comment]
I've not changed anything for the repo just yet, and when I do it will only affect keywordless searches (what Sonarr/Radarr/*arr use to check for newly posted torrents), not keyword searches.

I'll post when the commit is done, and again when the new stable build is out. Feel free to try out the above if you want, just edit yggtorrent.yml from:
```
...&name={{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}&description=...
```
to:
```
...&name={{ if .Keywords }}{{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}{{ else }}&page=50{{ end }}&description=...
```
and restart Jackett.

**Comment by WoisWoi** [comment]
> 
> 
> I've not changed anything for the repo just yet, and when I do it will only affect keywordless searches (what Sonarr/Radarr/*arr use to check for newly posted torrents), not keyword searches.
> 
> I'll post when the commit is done, and again when the new stable build is out. Feel free to try out the above if you want, just edit yggtorrent.yml from:
> 
> ```
> ...&name={{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}&description=...
> ```
> 
> to:
> 
> ```
> ...&name={{ if .Keywords }}{{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}{{ else }}&page=50{{ end }}&description=...
> ```
> 
> and restart Jackett.

![image](https://user-images.githubusercontent.com/75491231/103694990-1a51e800-4f9c-11eb-960d-ad37a7aaf954.png)
I did this as you sent "2nd page for keywordless search", but still 

Results on sonarr for example :
![image](https://user-images.githubusercontent.com/75491231/103695568-1ffbfd80-4f9d-11eb-90f7-c7a3f351f3e1.png)

some of the missing results from the tracker for this example 
![image](https://user-images.githubusercontent.com/75491231/103698485-b6322280-4fa1-11eb-9fc2-cacd885b9e53.png)

**Comment by ilike2burnthing** [comment]
> it will only affect keywordless searches [...] not keyword searches

Open the search for ygg in Jackett, don't type anything in the query box, and click the search button. This should show the same results as the first two pages on ygg when you perform a keywordless/empty search (sorted by date).

**Comment by xfouloux** [comment]
Because multiple thinking minds can do much better things =) !

Here is what i propose :

If there is no keywords, it returns 4 pages of results (200)
if there is a keyword, then it will do 2 sets of 2 search queries :
 - Searching normally with Sxx
 - Searching with "Saison" Keyword

Working fine, yeah there will be duplicates sometimes when doing a Keyword search, and it's unavoidable. But it doesn't break anything (maybe sonarr when manually sorting sometimes, and well, for radarr it will do 4 times the same search :/ )

```
  paths:
    #Normal Search
    - path: "https://{{ .Config.searchanddlurl }}/{{ if .Config.betasearchengine }}new_search{{ else }}engine{{ end }}/search?category={{ .Config.category }}&name={{ if .Config.betasearchengine }}{{ .Keywords }}{{ else }}{{ re_replace .Keywords \"\\b[^\\s]+\\b\"  \"\"$&\"\"}}{{ end }}&description=&file=&uploader=&sub_category=&do=search&order={{ .Config.type }}&sort={{ .Config.sort }}"
      followredirect: true
    - path: "https://{{ .Config.searchanddlurl }}/{{ if .Config.betasearchengine }}new_search{{ else }}engine{{ end }}/search?category={{ .Config.category }}&name={{ if .Config.betasearchengine }}{{ .Keywords }}{{ else }}{{ re_replace .Keywords \"\\b[^\\s]+\\b\"  \"\"$&\"\"}}{{ end }}&description=&file=&uploader=&sub_category=&do=search&order={{ .Config.type }}&sort={{ .Config.sort }}&page=50"
      followredirect: true
    #Search with Saison word instead of Sxx
    - path: "https://{{ .Config.searchanddlurl }}/{{ if .Config.betasearchengine }}new_search{{ else }}engine{{ end }}/search?category={{ .Config.category }}&name={{ if .Keywords }}{{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}{{ else }}&page=100{{ end }}&description=&file=&uploader=&sub_category=&do=search&order={{ .Config.type }}&sort={{ .Config.sort }}"
      followredirect: true
    - path: "https://{{ .Config.searchanddlurl }}/{{ if .Config.betasearchengine }}new_search{{ else }}engine{{ end }}/search?category={{ .Config.category }}&name={{ if .Keywords }}{{ re_replace .Keywords \"[sS]0(\\d{1,2})\"  \"Saison.$1\"}}&page=50{{ else }}&page=150{{ end }}&description=&file=&uploader=&sub_category=&do=search&order={{ .Config.type }}&sort={{ .Config.sort }}"
      followredirect: true
```

If you think it's a godd alternative @ilike2burnthing i can make a pull req, or you after you test it if you want to ?
