### ISSUE TITLE
kinozal: torrent download link 404

### ISSUE THREAD

**Issue by YouROK** [Jackett/Jackett#11585]
**Jackett Version**: v0.17.931
**Are you using a proxy or VPN?** no

I make this in web of jackett. Add Kinozal tracker and enter login and pass. Than I go to the search enter a torrent name and view results, but when I click on download I get message 404 page not found. When I click to blackhole action success.
File name is:
`'637546181776404994-Kinozal-�'$'\222''еном Venom 2018 �'$'\224''�'$'\221'' 4K, HEVC, HDR, Dolby Vision TV Blu-Ray Remux 2160p.torrent'`

Wouldn't it be better to take a magnet from the page?

Jackett gets a links on site to detail movie:
http://kinozal.tv/details.php?id=1808276

Magnet may found in:
http://kinozal.tv/get_srv_details.php?action=2&id=1808276

Response:
`<ul><li>Инфо хеш: 9DCEBC95F251BBB5F4C39AC30D4CEE7B37ED5B06</li><li>Размер части торрента: 8 МБ</li><li><div class='b ing'>Mosul.2019.BDRip.1080p.mkv <i>11.35 ГБ (12183984114)</i></div></li></ul>`
It remains to pull the infohash and create magnet
magnet:?xt=urn:btih:9DCEBC95F251BBB5F4C39AC30D4CEE7B37ED5B06

**Comment by garfield69** [comment]
The kinozal indexer generates a download link by simply using the details href and replacing `details` with `download`
https://github.com/Jackett/Jackett/blob/6a213c6eabd0264392c48564ff16a9035fd13ca4/src/Jackett.Common/Definitions/kinozal.yml#L177-L182
so `http://kinozal.tv/details.php?id=1839733` becomes `http://kinozal.tv/download.php?id=1839733` which is a simple and usually reliable method.
However, if for some reason, the kinozal web site decides that you are not allowed to download this torrent, then the download.php presents a HTML page instead of the .torrent, for example
![image](https://user-images.githubusercontent.com/6933240/115610394-e927d880-a33c-11eb-9c08-07b967e5ceae.png)
which is why you get the `Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'` error.

Unfortunately at this time, the cardigann processor cannot build a magnet from the infohash from the details page, the logic code can only do so from the primary results page.
There is a similar issue for torrentqq #11389

**Comment by mikeoscar2006** [comment]
@garfield69 Can you tell what is preventing the processor from building a magnet so maybe I can make necessary changes.

**Comment by garfield69** [comment]
The cardigann processor has a procedure called infohash, where you provide the magnet hash and it returns a generated magnet URI built from the hash, a default list of trackers and the filename from the processed title.
the infohash routine is called in yaml from the search block fields section https://github.com/Jackett/Jackett/wiki/Definition-format#search
this example is from the wiki
```yaml
    # [OPTIONAL] auto-generated magnet URI using the infohash
    # When neither the .torrent link or a magnet URI is available, use the infohash statement to auto-generate a
    # magnet URI from an infohash. The magnet's &dn= will be loaded from the .Result.title, and a set of ten of
    # the currently most useful trackers will be added for the &tr= sequence.
    infohash:
      selector: a[href^="index.php?page=torrent-details&id="][title]
      attribute: href
      filters:
        - name: querystring
          args: id
```

however , if the magnet hash is not available in the search results row, and we have to go fetch the torrent details page to find download links, then the cardigann download block is used.
https://github.com/Jackett/Jackett/wiki/Definition-format#download
this procedure does not support the use of the infohash procedure to build a magnet in the same way as the search block does.

**Comment by garfield69** [comment]
>Can you tell what is preventing the processor from building a magnet so maybe I can make necessary changes

I don't know what is preventing the processor from building a magnet, I am not a C# dev, and did not contribute to the design on the Jackett code or understand how it all works.

My feeling is that because the download block is invoked separately from the instance that generated the search results page, then this may mean that the download code only has access to vars that are passed at the time the download code is invoked, (when a user click the download button or the torznab download href is accessed, which may be the same thing), see https://github.com/Jackett/Jackett/wiki/Definition-format#variables-available-in-the-download-block
which does not include the title for instance.
It may be just a case of making additional vars available for the download block code to access, I don't know.

**Comment by mikeoscar2006** [comment]
Thanks for the explanation, will look into it further.

**Comment by mikeoscar2006** [comment]
You're right @garfield69  that if only the title was also accessible, it would be easy to create an infohash procedure maybe even as a filter for the selector.  To provide the title, I've thought of 2 ways:
1. Modify the BaseIndexer or possibly only the Cardigann Indexer to also pass the title alongside the Uri which is the only thing passed as of now. However, I think it would be not recommended to change the fundamental design that much.
2. Since I'm thinking of using infohash as a filter, we can provide a title selector as an argument that will parse the title from the details page itself and generate the magnet.
For now, I can only think of the above 2 ways, probably 2nd only. Lmk what do you think?

**Comment by garfield69** [comment]
not sure I understand option 2... could you mock up a **download** block example
below is a typical download block (not to be confused with the **search** block **fields** **download** section
```yaml
download:
  selectors:
    - selector: a[href^="download.php?id="]
      attribute: href
      filters:
        - name: querystring
          args: url
        - name: urldecode
```

**Comment by mikeoscar2006** [comment]
Yeah, so I'm thinking something like this:
```yml
download:
  selectors:
    - selector: a[href^="download.php?id="]
      attribute: href
      filters:
        - name: infohash2magnet
          args:
            - selector: img[src^="*poster.jpg"]
               attribute: alt-title
```
So a filter that uses the already available infohash2magnet function, and since we also need the title, we can specify a selector as an argument that will parse the title from details page which is present generally.

**Comment by garfield69** [comment]
hmm, i think your example is missing the selector that provides the hash itself.
referring to the wiki, the current infohash looks like this
```yaml
    infohash:
      selector: a[href^="index.php?page=torrent-details&id="][title]
      attribute: href
      filters:
        - name: querystring
          args: id
```
with what ever filters are necessary to isolate the hashkey to pass to the infohash2magnet routine, in the example above it happens to be a querystring, but it could just as easily be a regexp or any of the other standard filters available.

so your mock-up will need to distinguish between the selector that provides the title and the other selector that provides the hash.

but I get the gist of what you are proposing so I'll leave you to ponder the mechanics and see what you come up with.
I wish @ngosang  was here to provide some guidance, he wrote the original and his feedback would be welcome.
