### ISSUE TITLE
redbits/hd-spain VOSE titles mistmatch

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#11615]
### Description

Titles with VOSE are mark as Spanish, when should be marked a English, because this tracker only have Spanish or English, same happens at hd-spain

### Screenshots

![imagen](https://user-images.githubusercontent.com/4247187/116189211-e48e6600-a728-11eb-843b-76663c3f2aa2.png)
![imagen](https://user-images.githubusercontent.com/4247187/116189234-ebb57400-a728-11eb-8780-ef4fdd76533e.png)

### Fix (Not working)

I have tried to add this at redbits.yml (didnt try anything at hd-spain.yml), but isn't working properly, check screenshot

![imagen](https://user-images.githubusercontent.com/4247187/116188979-8d889100-a728-11eb-957f-152f567b3d8d.png)

```
    title:
      selector: a[href*="/torrents/"] a:contains("VOSE") # Select titles with VOSE
      optional: true
      filters:
        - name: re_replace
          args: ["\\[", " "]
        - name: re_replace
          args: ["\\]", " "]
        - name: re_replace
          args: ["(?i)bdfull", "BluRay"] # BDfull  -> BluRay
        - name: re_replace
          args: ["(?i)RedBits", ""] # Delete RedBits
        - name: append
          args: " English" # Add English to fix Sonarr/Radarr language
    title:
      selector: a[href*="/torrents/"] a:not(:contains("VOSE"))
      optional: true
```
