### ISSUE TITLE
[enhancement] use ReleaseInfo.GetBytes for seeders, leechers, files and grabs

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12255]
By using the ReleaseInfo.GetBytes routine to process the seeders, leechers, files and grabs, we can dispense with the filters on some indexers that currently have to clean up these strings.
for example the yaml indexer dark-shadow currently drops the X from the grabs selector value, and cleans up commas and dots for seeders, leechers and grabs.
```yaml
    grabs:
      selector: div.selection_unter_ae
      filters:
        - name: trim
          args: "x"
        - name: replace
          args: [".", ""]
        - name: replace
          args: [",", "."]
    seeders:
      selector: div.selection_unter_aa
      filters:
        - name: replace
          args: [".", ""]
        - name: replace
          args: [",", "."]
    leechers:
      selector: div.selection_unter_aaa
      filters:
        - name: replace
          args: [".", ""]
        - name: replace
          args: [",", "."]
``` 
I will implement the cardigann C# amendments as this is a straight forward replacement of the current use of `ParseUtil.CoerceLong(value);`
