### ISSUE TITLE
[cardigann] ehancement to the BEFORE section of the DOWNLOAD block.

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#12273]
at the moment, the **download** block in the cardigann's yaml supports a **before** sub-block that allows only for a static **path** and **input** vars to be defined.
example from the wiki
```yaml
download:
  # [OPTIONAL] use HTTP POST instead of GET to download the torrent file
  method: post 
  # [OPTIONAL] HTTP request which needs to be done before downloading the file
  before:
    # request target
    path: thanks.php
    # send via HTTP POST
    method: post
    # [OPTIONAL] if the before link requires a query separator other than the default "&" then use this
    queryseparator: ";"
    # list of HTTP arguments which will be included
    inputs:
      # extract the "id" parameter from the search result download URL query string
      infohash: "{{ .DownloadUri.Query.id }}"
      thanks: 1
```

it would be useful if the **before** block could in addition support as an alternative to the path and input a **selector** fetched from whichever page the download block was called from

Take for example the mircrew indexer, this is what I had to code to make it work
https://github.com/Jackett/Jackett/blob/8e6bd9c9bc530df2d2a7f3874d04da9ec31d4865/src/Jackett.Common/Definitions/mircrew.yml#L91-L101

ideally, I would like to use something similar to 
```yaml
download:
  before:
    # thankyou link: ./viewtopic.php?f=52&p=65417&thanks=65417&to_id=54&from_id=3950
    selector: a[id^="lnk_thanks_post"]
    attribute: href
  selectors:
    # details link: https://mircrew-releases.org/viewtopic.php?f=52&t=28752&hilit=2021
    - selector: a[href^="magnet:?xt="]
      attribute: href
```

ATM this indexer is the only one that could use this feature, albeit the current method works well enough, but my proposed alternative method would be more logical and prevent the internal download failed try the next selector method currently employed.
