### ISSUE TITLE
[bug] hardcoded size broken

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#12288]
Bug caused by https://github.com/Jackett/Jackett/commit/f2c760ce8c278f07d732ef9efefdf3e8c0d77473 (v0.18.686 anyway) - hardcoded size with additional optional size selector no longer works, just shows `0 B`

Example - search using OnceSearch on v0.18.686 (0 B) vs v0.18.666 (256 MB)

https://github.com/Jackett/Jackett/blob/0841f453bfa466dfa5a81ea196011301915e04f8/src/Jackett.Common/Definitions/oncesearch.yml#L129-L133

Hardcoded size on its own works, it's only when there's also an optional size selector that it fails.

**Comment by garfield69** [comment]
I've coded a yml solution which also happens to comply with #11917 
But if we find many more of these then I'm going to have to bite the bullet and dig into the C# to come up with a solve.
I'll leave this open so we can track the hits.

**Comment by garfield69** [comment]
notes to self so I can keep track of where I am at.
so using pier720 indexer, grabs returns 3 when the selector is not found,
and returns the found value if the selector is found, replacing the preset as expected.
so the ReleaseInfo.GetBytes routine works as intended.
```yaml
   grabs:
      text: 3
    grabs:
      selector: dd.views span.my_tt.complet
      optional: true
```
but size returns 0 B when the selector is not found (disregarding the preset)
and returns the found value if the selector is found. Confusing %-(
```yaml
 size: 
   text: "1 GB" 
 size: 
   selector: div.list-inner div[style="float:right;"] 
   optional: true 
```
