### ISSUE TITLE
[req]: C# Indexer Implementation based on yml File definition

### ISSUE THREAD

**Issue by montana123** [Jackett/Jackett#12334]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

C# Implementation is currently costly and not many people can do it.

### Describe the solution you'd like

I made the Bit-Titan C# implementation. I could now do several more implementations but I don't have the credentials to most indexers.

For many other requested C# implementations I can see a pattern. I could try adding a functionality to read a definition from yml files and perform the query searches based on those definitions. With this functionality anyone who understands the yml file could implement the C# definitions without actually writing any C# Code.

Does anyone want this or would it be more appreciated that I stick to normal C# implementations? Before starting to try develop this feature I would ask the Jackett Team.

What do you guys think about this? I would try to stick to the current yml definition with a little extra (login in post body, login details in url, and so on..)

I'm kinda new to Jackett development so I still need the current architecture.

If it's not wanted I could also write simple C# implementations like I did with Bit-Titan. In that case I would need some wanted indexer credentials to test it, but I would be more interested to write the yml defintion parser. That way I could learn a thing or two. 

EDIT: Don't know if it belongs here. I didn't know a different place where I could post this.

@garfield69

**Comment by montana123** [comment]
I checked some Code and it looks like that you not always need a C# only for REST Api's or PHP based Web API's. Am I correct?

Well I could write a generalized Version for all the REST API's and PHP based WebApi's (like Bit-Titan). Would that help?

**Comment by garfield69** [comment]
I'm not a C# dev and I did not contribute to the development of Jackett, so my perspective is mostly shaped by what I have picked up by osmosis since joining the team a few years ago, and I mostly specialise in writing yaml indexers for the Jackett Cardigann processor.

Basically, the approach to writing an indexer has thus far been: if a web site can be processed by a yaml indexer then that is the first choice, and resort to writing the indexer in C# as a fallback.

As far as I can tell, the existing version of the Cardigann processor currently only handles web sites whose results are presented in HTML in response to the HTTP GET/PUT query.
And if the web site is returning JSON or XML, or uses JS to dynamically generate HTML in the browser after the GET/PUT query is performed and the stub HTML is returned, or has a one-title-many-torrents structure, or has some other quirk that prevents the current Cardigann's yaml indexer from working, then a C# indexer is required.

If the processing of a JSON (and/or XML) response could be integrated into the Cardigann processor so that the indexer could be written in yaml, then that would be a great addition to Jackett. It would free up dependency on C# devs to contribute C# indexers (whom have been up to now is very short supply).

I assume that this has not been done up to now because it is a large project or because managing/processing a JSON response is not feasible with yaml constraints, I've no idea, only a C# dev willing to spend the time and resources can answer that.

In the short term, if you want to continue completing any of the outstanding C# indexers, then find the relevant open ticket, indicate your interest, and if I still have an active account there I will email you credentials for temporary access during the build.

**Comment by mikeoscar2006** [comment]
Yeah I guess processing JSON APIs with yaml would be a great integration indeed and I think we should implement it. I'll contribute as much as I can so let me know @garfield69 if we should do it :)

**Comment by garfield69** [comment]
I would love to see this developed.
as inspiration, I envisage a yaml for bit-titan that can handle the JSON response using the API as looking something like this:
```yaml
---
id: bit-titan
name: BiT-TiTAN
description: "BiT-TiTAN is a GERMAN Private Torrent Tracker for MOVIES / TV / GENERAL"
language: de-DE
type: private
encoding: UTF-8
links:
  - https://bit-titan.net/

caps:
  categorymappings:
    - {id: 1010, cat: Movies/UHD, desc: "Movies 2160p"}
    - {id: 1020, cat: Movies/HD, desc: "Movies 1080p"}
    - {id: 1030, cat: Movies/HD, desc: "Movies 720p"}
    - {id: 1040, cat: Movies/HD, desc: "Movies x264"}
    - {id: 1050, cat: Movies/HD, desc: "Movies x265"}
    - {id: 1060, cat: Movies/SD, desc: "Movies XviD"}
    - {id: 1070, cat: Movies/3D, desc: "Movies 3D"}
    - {id: 1080, cat: Movies/DVD, desc: "Movies DVD"}
    - {id: 1090, cat: Movies/BluRay, desc: "Movies BluRay"}
    - {id: 1100, cat: Movies/DVD, desc: "Movies HD2DVD"}
    - {id: 1110, cat: Movies/Foreign, desc: "Movies International"}
    - {id: 1120, cat: Movies/HD, desc: "Movies HD Packs"}
    - {id: 1130, cat: Movies/SD, desc: "Movies SD Packs"}
    - {id: 2010, cat: TV/UHD, desc: "TV 2160p"}
    - {id: 2020, cat: TV/HD, desc: "TV 1080p"}
    - {id: 2030, cat: TV/HD, desc: "TV 720p"}
    - {id: 2040, cat: TV/HD, desc: "TV x264"}
    - {id: 2050, cat: TV/HD, desc: "TV x265"}
    - {id: 2060, cat: TV/SD, desc: "TV XviD"}
    - {id: 2070, cat: TV/HD, desc: "TV HD Packs"}
    - {id: 2080, cat: TV/SD, desc: "TV SD Packs"}
    - {id: 2090, cat: TV/Foreign, desc: "TV International"}
    - {id: 3010, cat: TV/Documentary, desc: "Docu 2160p"}
    - {id: 3020, cat: TV/Documentary, desc: "Docu 1080p"}
    - {id: 3030, cat: TV/Documentary, desc: "Docu 720p"}
    - {id: 3040, cat: TV/Documentary, desc: "Docu x264"}
    - {id: 3050, cat: TV/Documentary, desc: "Docu x265"}
    - {id: 3060, cat: TV/Documentary, desc: "Docu XviD"}
    - {id: 3070, cat: TV/Documentary, desc: "Docu HD Packs"}
    - {id: 3080, cat: TV/Documentary, desc: "Docu SD Packs"}
    - {id: 3090, cat: TV/Documentary, desc: "Docu International"}
    - {id: 4010, cat: TV/Sport, desc: "Sport 2160p"}
    - {id: 4020, cat: TV/Sport, desc: "Sport 1080p"}
    - {id: 4030, cat: TV/Sport, desc: "Sport 720p"}
    - {id: 4040, cat: TV/Sport, desc: "Sport SD Sport"}
    - {id: 4050, cat: TV/Sport, desc: "Sport HD Packs"}
    - {id: 4060, cat: TV/Sport, desc: "Sport SD Packs"}
    - {id: 5010, cat: XXX, desc: "XXX 2160p"}
    - {id: 5020, cat: XXX, desc: "XXX 1080p"}
    - {id: 5030, cat: XXX, desc: "XXX 720p"}
    - {id: 5040, cat: XXX, desc: "XXX x264"}
    - {id: 5050, cat: XXX, desc: "XXX x265"}
    - {id: 5060, cat: XXX, desc: "XXX XviD"}
    - {id: 5070, cat: XXX, desc: "XXX HD Packs"}
    - {id: 5080, cat: XXX, desc: "XXX SD Packs"}
    - {id: 5090, cat: XXX, desc: "XXX Sonstiges"}
    - {id: 6010, cat: PC/Games, desc: "Games Windows"}
    - {id: 6020, cat: Console, desc: "Games Linux"}
    - {id: 6030, cat: PC/Mac, desc: "Games MacOS"}
    - {id: 6040, cat: PC/Mobile-Android, desc: "Games Android"}
    - {id: 6050, cat: Console/XBox, desc: "Games Xbox"}
    - {id: 6060, cat: Console/PSP, desc: "Games PlayStation"}
    - {id: 6070, cat: Console/NDS, desc: "Games Nintendo"}
    - {id: 6080, cat: Console, desc: "Games Sonstige"}
    - {id: 7010, cat: PC/0day, desc: "Software Windows"}
    - {id: 7020, cat: PC, desc: "Software Linux"}
    - {id: 7030, cat: PC/Mac, desc: "Software MacOS"}
    - {id: 7040, cat: PC/Mobile-Android, desc: "Software Android"}
    - {id: 8010, cat: Audio/MP3, desc: "Music MP3-Album"}
    - {id: 8020, cat: Audio/MP3, desc: "Music MP3-Charts"}
    - {id: 8030, cat: Audio/MP3, desc: "Music MP3-Sampler"}
    - {id: 8040, cat: Audio/MP3, desc: "Music MP3-Single"}
    - {id: 8050, cat: Audio/Lossless, desc: "Music FLAC-Album"}
    - {id: 8060, cat: Audio/Lossless, desc: "Music FLAC-Charts"}
    - {id: 8070, cat: Audio/Lossless, desc: "Music FLAC-Sampler"}
    - {id: 8080, cat: Audio/Lossless, desc: "Music FLAC-Single"}
    - {id: 8090, cat: Audio/Video, desc: "Music Video"}
    - {id: 9010, cat: Audio/Audiobook, desc: "Books A-Book"}
    - {id: 9020, cat: Books/EBook, desc: "Books E-Book"}
    - {id: 9030, cat: Books, desc: "Books E-Paper"}
    - {id: 9040, cat: Books, desc: "Books E-Learning"}
    - {id: 9060, cat: TV/Anime, desc: "Anime HD"}
    - {id: 9070, cat: TV/Anime, desc: "Anime SD"}
    - {id: 9080, cat: TV/Anime, desc: "Anime Pack"}
    - {id: 9999, cat: Other, desc: "unsort"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: apikey
    type: text
    label: APIKey
  - name: info_key
    type: info
    label: About your API key
    default: "Find or Generate a new key <a href=\"https://bit-titan.net/api_cp.php\" target =_blank>here</a>."
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: 1
    options:
      1: created
      2: seeders
      5: size
      9: title
  - name: type
    type: select
    label: Order requested from site
    default: DESC
    options:
      DESC: desc
      ASC: asc

search:
  paths:
    - path: api.php
      response: JSON
  inputs:
    apiKey: "{{ .Config.apikey }}"
    categories: "{{ if .Categories }}{{ join .Categories \",\" }}{{ else }}0{{ end }}"
    search: "{{ .Keywords }}"
    # searchIn: 0 all, 1 active, 2 dead, 3 highlights, 4 own uploads, 5 uploads bots, 6 onlyupload, 7 multiplier, 8 %download, 9 freeleech
    searchIn: "{{ if .Config.freeleech }}9{{ else }}0{{ end }}"
    # 1 25, 2 50, 3 75, 4 100
    limit: 4
    downloadLink: 1
    # 1 = Sat, 28 Nov 2020 23:29:38 +0100 (DEFAULT VALUE) , 2 = 1606606178 (UNIX TIMESTAMP) , 3 = 28.11.2020 23:29.38 (German Timestamp) ,  4 = 2020-11-28 23:29:38 (Default Datetime)
    timeFormat: 2
    orderBy: "{{ .Config.sort }}"
    order: "{{ .Config.type }}"

  rows:
    selector: results
      filters:
        - name: andmatch
          args: name

  fields:
    id:
      selector: id
    category:
      selector: category
    title:
      selector: name
    details:
      text: "details.php?id={{ .Result.id }}"
    download:
      selector: download
    poster:
      optional: true
      selector: poster
    files:
      optional: true
      selector: files
    seeders:
      selector: seeds
    leechers:
      selector: leechers
    grabs:
      selector: snatchers
    date:
      # unix
      selector: added
    size:
      selector: size
    downloadvolumefactor:
      selector: downloadFactor
    uploadvolumefactor:
      selector: uploadFactor
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 2 day (as seconds = 2 x 24 x 60 x 60)
      text: 172800
# engine n/a
```

please note this is only a suggestion, the actual implemented syntax is completely depended on what you decide is appropriate for such a task
