### ISSUE TITLE
[req]:pornotorrent.net.br

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#12585]
### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name:pornotorrent
- URL:https://pornotorrent.net.br
- Description: mix adult content
- Minimum Seeding Time and Minimum Ratio (if Private): No
- Additional Comments: Search engine working. Site have magnet links.
```
engine: wordpress 5.4.2

**Comment by garfield69** [comment]
this site's details page has download links that look like
`href="https://adf.ly/25475245/https://pornotorrent.net.br/my-interracial-family-vol-2-digital-sin-mg`
even after I strip the advert click bait off the front of the href, the remainder returns a moved redirect

same download issue as #7525
someone else can fix this I not interested in wasting any more of my time of crappy sites like this.

for reference here is the yml I wrote
```yaml
---
id: pornotorrentbr
name: PornoTorrent.br
description: "PornoTorrent.br is a BRAZILIAN Public Torrent Tracker for 3X"
language: pt-BR
type: public
encoding: UTF-8
links:
  - https://pornotorrent.net.br/

caps:
  categorymappings:
    - {id: XXX, cat: XXX, desc: XXX}

  modes:
    search: [q]

settings: []

download:
  selectors:
    # https://adf.ly/25475245/https://pornotorrent.net.br/my-interracial-family-vol-2-digital-sin-mg
    - selector: a[href$="-mg"]
      attribute: href
      filters:
        - name: split
          args: ["/", -1]
        - name: prepend
          args: "{{ .Config.sitelink}}/"
        - name: strdump

search:
  paths:
    - path: /
  inputs:
    s: "{{ .Keywords }}"

  rows:
    selector: ul.lista-filmes > li
    filters:
      - name: andmatch

  fields:
    category:
      text: XXX
    title:
      selector: a
      attribute: title
    details:
      selector: a
      attribute: href
    download:
      selector: a
      attribute: href
    poster:
      selector: img
      attribute: src
    date:
      text: now
    size:
      text: "512 MB"
    seeders:
      text: 1
    leechers:
      text: 1
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# WordPress 5.4.2
```
