### ISSUE TITLE
[1337x] Exception (1337x): error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name: The SSL connection could not be established, see inner exception. (Test)

### ISSUE THREAD

**Issue by foraern** [Jackett/Jackett#12906]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: No
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.20.492-ls55)
File /etc/issue: Ubuntu 18.04.6 LTS \n \l
Jackett variant: CoreLinuxAmdx64
OS version: Unix 4.15.0.166 (64bit OS) (64bit process)
Environment version: 6.0.1 (/app/Jackett/)	
Starting Jackett v0.20.492
```

### Description

An error occurred while testing this indexer
Exception (1337x): error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name: The SSL connection could not be established, see inner exception.

An error occurred while testing this indexer
Exception (eztv): error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name: The SSL connection could not be established, see inner exception.

### Logged Error Messages

```text
sudo docker exec -it jackett /bin/bash

root@137d7e024a6d:/# curl -vvv https://1337x.to/
*   Trying 45.223.138.71...
* TCP_NODELAY set
* Connected to 1337x.to (45.223.138.71) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, Server hello (2):
* error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name

root@137d7e024a6d:/# openssl s_client -connect 1337x.to:443
CONNECTED(00000005)
140302621163968:error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../ssl/record/rec_layer_s3.c:1528:SSL alert number 112
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 310 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

root@05457359e70e:/# curl -vvv https://eztv.re/
*   Trying 45.223.138.71...
* TCP_NODELAY set
* Connected to eztv.re (45.223.138.71) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, Server hello (2):
* error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name

root@05457359e70e:/# openssl s_client -connect eztv.re:443
CONNECTED(00000005)
140032220942784:error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../ssl/record/rec_layer_s3.c:1528:SSL alert number 112
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 309 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by foraern** [comment]
I included eztv in issue, since it's having the same issue, but can split it out into a separate issue if needed.

**Comment by ilike2burnthing** [comment]
Are the results the same for those commands if you run them on your host?

**Comment by foraern** [comment]
> Are the results the same for those commands if you run them on your host?

No, they work fine in host:
`chronos:~/docker-services$ curl -vvv https://1337x.to/
*   Trying 104.31.16.11...
* TCP_NODELAY set
* Connected to 1337x.to (104.31.16.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul  9 00:00:00 2021 GMT
*  expire date: Jul  8 23:59:59 2022 GMT
*  subjectAltName: host "1337x.to" matched cert's "1337x.to"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* Using Stream ID: 1 (easy handle 0x5644e8342600)
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/2
> Host: 1337x.to
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
< HTTP/2 200
< date: Mon, 31 Jan 2022 08:39:51 GMT
< content-type: text/html
< vary: Accept-Encoding
< x-frame-options: DENY
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=faQMBBx4%2FJC4bB8JsFfPtnjYuEvLsIR%2B%2BL6zQa6pQe09oSgWTEmUeRlekH%2FOe9oalVVfTdQZZmxx3mpXUff1xvxAnshgg2BIrq5nNeQMkvMbgMAwZG8RzKheXw%3D%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 6d61a1c3cbf2da76-LIS
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
<
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Torrent Search Engine | 1337x.to</title>
<meta name="description" content="1337x is a search engine to find your favorite torrents.">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/css/jquery-ui.css">
<link rel="stylesheet" href="/css/icons.css">
<link rel="stylesheet" href="/css/scrollbar.css">
<link rel="stylesheet" href="/css/style.css?ver=2.5">
<link rel="shortcut icon" href="/favicon.ico">

<style id="antiClickjack">body{display:none !important;}</style>
<script type="text/javascript" id="antiClickjackJS">
if (self === top) {
var antiClickjack = document.getElementById("antiClickjack");
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
antiClickjack.parentNode.removeChild(antiClickjack);
} else {
top.location = self.location;
}
</script>
<script async src='/cdn-cgi/challenge-platform/h/g/scripts/invisible.js'></script></head>
<body class="search-index-page">
<div class="mobile-menu"></div>
<div class="top-bar">
<div class="container">
<div class="top-bar-left">
</div>
<ul class="top-bar-nav">
<li><a href="/register">Register</a></li>
<li class="active"><a href="/login">Login</a></li>
</ul>
</div>
</div>
<header>
<div class="container">
<a href="#" class="navbar-menu"><span></span><span></span><span></span></a>
<nav>
<ul class="main-navigation">
<li class="green"><a href="/home/" title="Full Home Page">Full Home Page</a></li>
<li><a href="/top-100" title="Top 100 Torrents">Top 100</a></li>
<li><a href="/trending" title="Trending Torrents">Trending</a></li>
<li><a href="/contact" title="Contact">Contact</a></li>
<li><a href="/upload" title="Upload Torrent File">Upload</a></li>
</ul>
</nav>
</div>
</header>
<main class="container">
<div class="row">
<div class="col-8 col-push-2 page-content ">
<div class="logo"><a href="/home/"><img alt="logo" src="/images/logo.svg"></a></div>
<div class="search-box">
<form id="search-index-form" method="get" action="/srch">
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
<input type="search" placeholder="Search for torrents.." id="autocomplete" name="search" class="ui-autocomplete-input form-control">
<button type="submit" class="btn btn-search"><i class="flaticon-search"></i><span>Search</span></button>
</form>
</div>
<div class="news">
<div class="box-info">
<div class="box-info-heading clearfix"><h1> 1337x Domains</h1> <span class="box-info-right box-info-time"><i class="flaticon-time"></i>1 year ago</span></div>
<div class="box-info-detail clearfix">
<p>1337x newest alternative domain is <a href="https://1337x.gd">1337x.gd</a>, for full list of alternative domains see <a href="/about">about</a> page.</p>
</div>
</div>
</div>
</div>
</div>
</main>
<ul class="search-categories">
<li>
<h3><a href="/popular-movies" title="Movies"><span class="icon"><i class="flaticon-movies"></i></span>Movies </a></h3>
<a href="/movie-library/1/" class="library">Library</a>
</li>
<li>
<h3><a href="/popular-tv" title="Television"><span class="icon"><i class="flaticon-tv"></i></span>Television </a></h3>
<a href="/series-library/a/1/" class="library">Library</a>
</li>
<li>
<h3><a href="/popular-games" title="Games"><span class="icon"><i class="flaticon-games"></i></span>Games </a></h3>
</li>
<li>
<h3><a href="/popular-music" title="Musics"><span class="icon"><i class="flaticon-music"></i></span>Music </a></h3>
</li>
<li>
<h3><a href="/popular-apps" title="Applications"><span class="icon"><i class="flaticon-apps"></i></span>Applications </a></h3>
</li>
<li>
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
<h3><a href="/popular-anime" title="Other"><span class="icon"><i class="flaticon-ninja-portrait"></i></span>Anime </a></h3>
</li>
<li>
<h3><a href="/popular-documentaries" title="Documentries"><span class="icon"><i class="flaticon-documentary"></i></span>Documentaries </a></h3>
</li>
<li>
<h3><a href="/popular-other" title="Other"><span class="icon"><i class="flaticon-other"></i></span>Other </a></h3>
</li>
<li>
<h3><a href="/popular-xxx" title="XXX"><span class="icon"><i class="flaticon-xxx"></i></span>XXX </a></h3>
</li>
</ul>
<footer>
<div class="bitcoin">
<div class="bitcoin-icon-wrap">
<span class="bitcoin-icon"><i class="flaticon-bitcoin red"></i></span>
</div>
<span class="bitcoin-text"><span>Bitcoin Donate: </span><a href="bitcoin:3Q1337xL2i6jXrXqZ5aMfhN4wp366GQc44">3Q1337xL2i6jXrXqZ5aMfhN4wp366GQc44</a></span>
</div>
<a class="scroll-top" href="#"><i class="flaticon-up"></i></a>
<ul>
<li><a href="/">Home</a></li>
<li class="active"><a href="/home/">Full Home Page</a></li>
<li><a href="/contact">Dmca</a></li>
<li><a href="/contact">Contact</a></li>
</ul>
<p class="info">1337x 2007 - 2022</p>
</footer>
<script src="/js/jquery-1.11.0.min.js"></script>
<script src="/js/jquery-ui.js"></script>
<script src="/js/auto-searchv2.js"></script>
<script src="/js/main.js"></script>
<script>
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
if (window.top !== window.self) window.top.location.replace(window.self.location.href);
</script>
<script type="text/javascript">(function(){window['__CF$cv$params']={r:'6d61a1c3cbf2da76',m:'PqFDQGRLrSmuHQhbQzAh1qjoSwU7OgURe4fQETRHHt4-1643618391-0-AfsKb3/zaXrqQ15HFiLasYBrOJOtt95sEjTV88bzcYzvL5qFZzLT7U6RZI/Twx8h3gyBIzBpiyz+/dqy2s3OVthkGK/7OrRrwuqvW0DKSZEEiA3+Ni7SnlTHylRObofnTQ==',s:[0xc1c0e7bf5b,0xa98f290a9a],u:'/cdn-cgi/challenge-platform/h/g'}})();</script></body>
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
* Connection #0 to host 1337x.to left intact`

`chronos:~/docker-services$ openssl s_client -connect 1337x.to:443
CONNECTED(00000005)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
   i:C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
 1 s:C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
   i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFLjCCBNSgAwIBAgIQBhTy7YX2of9FwDxEyfQb1jAKBggqhkjOPQQDAjBKMQsw
CQYDVQQGEwJVUzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEgMB4GA1UEAxMX
Q2xvdWRmbGFyZSBJbmMgRUNDIENBLTMwHhcNMjEwNzA5MDAwMDAwWhcNMjIwNzA4
MjM1OTU5WjB1MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQG
A1UEBxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQQ2xvdWRmbGFyZSwgSW5jLjEe
MBwGA1UEAxMVc25pLmNsb3VkZmxhcmVzc2wuY29tMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEw2Ard/LZZh8zIyYzluZM+813stVbMghpUwR7cVIW1zkUzxpp6KFH
XdXy11axUfv40aFFzbRtXwrJYQDZoJ3mR6OCA28wggNrMB8GA1UdIwQYMBaAFKXO
N+rrsHUOlGeItEX62SQQh5YfMB0GA1UdDgQWBBSBNxPW8hCKlK0p3egif26mcj5I
eDA2BgNVHREELzAtgggxMzM3eC50b4IKKi4xMzM3eC50b4IVc25pLmNsb3VkZmxh
cmVzc2wuY29tMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQu
Y29tL0Nsb3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA3oDWgM4YxaHR0cDovL2NybDQu
ZGlnaWNlcnQuY29tL0Nsb3VkZmxhcmVJbmNFQ0NDQS0zLmNybDA+BgNVHSAENzA1
MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNv
bS9DUFMwdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5k
aWdpY2VydC5jb20wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0
LmNvbS9DbG91ZGZsYXJlSW5jRUNDQ0EtMy5jcnQwDAYDVR0TAQH/BAIwADCCAX0G
CisGAQQB1nkCBAIEggFtBIIBaQFnAHYAKXm+8J45OSHwVnOfY6V35b5XfZxgCvj5
TV0mXCVdx4QAAAF6i3ixQwAABAMARzBFAiBVd/jDNSKeCa66mS/GeSTohSOfLktu
rC5wsXdDzbt3swIhAKDAClmoVXgjLDoNioYTpHPwUZIQgB/Plf1ec6T3PM1HAHYA
QcjKsd8iRkoQxqE6CUKHXk4xixsD6+tLx2jwkGKWBvYAAAF6i3ixMwAABAMARzBF
AiEApaMxT/bS7Ze1bOo2XiEP/UZwx+C/g+fFYFzIrxR5B+MCIHLweH3GxT3dedYm
JfZ62Wh2sjtVAW63GMLwjx38X5ZbAHUA36Veq2iCTx9sre64X04+WurNohKkal6O
OxLAIERcKnMAAAF6i3ixXQAABAMARjBEAiB3RpGRk+GsJds1lCcfu0DPoUqA6DFv
2fkvDqmeXx2XZQIgCU61EV+lUuiQMoEyiyYdgP/GevUZHP6NwptXJwjkJx0wCgYI
KoZIzj0EAwIDSAAwRQIgaWbSos6z7xucrvst6O9y18Th+beVBmQ1l5WwahHf4V8C
IQDCMixPJrHUGenFeOHDGtxzI51YO50zl4ufbyP6n8zyWQ==
-----END CERTIFICATE-----
subject=C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com

issuer=C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2621 bytes and written 390 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: BDF1E74BF188841006FD8B469879652DBF2A73DEF6AA5C853F58D7CA0FE88318
    Session-ID-ctx:
    Resumption PSK: 36CEF501870ABEDF96B71E97F8C2FFA7B93E297054D645285AA22C8FF27280DB29031B7264B89359F4950CC9668FB5EA
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - cc 37 6a 0e 6a 90 47 ad-2c 43 f7 36 4e 81 7d cb   .7j.j.G.,C.6N.}.
    0010 - c3 be 8e 3a 73 1c 63 28-cc 4b 6f f2 07 e7 4e d2   ...:s.c(.Ko...N.
    0020 - 11 a2 67 46 85 31 dd 91-48 a1 b1 b6 ec 03 cb 5c   ..gF.1..H......\
    0030 - 99 ab 3f 4d 53 05 6a dc-a6 ad 30 06 02 49 df a0   ..?MS.j...0..I..
    0040 - 76 72 7f 7e 43 73 bc 0a-e3 52 7b df 96 23 b7 06   vr.~Cs...R{..#..
    0050 - cd cd a6 a5 8d ea b5 c6-6f 93 fb 64 a7 26 db 6f   ........o..d.&.o
    0060 - ad 5b 4b 96 e3 16 4c ea-fa fb b5 44 4d fc 09 0f   .[K...L....DM...
    0070 - 3a 2c 2c 0a a3 5c 33 af-e6 23 2d e5 8e 66 dc 05   :,,..\3..#-..f..
    0080 - ba b1 16 ed b5 7e f9 ac-af 2b d9 e4 ea 85 ad 71   .....~...+.....q
    0090 - 36 b9 2f b6 e7 c2 d2 e6-93 fe 2d 0e ba 5a 1d e8   6./.......-..Z..
    00a0 - 75 ae 58 70 fe c9 4d ba-48 a0 d9 6f 1e a5 a6 26   u.Xp..M.H..o...&
    00b0 - 3b c5 cc e0 a1 8e e4 43-91 3f 04 4b fa 97 a8 9f   ;......C.?.K....

    Start Time: 1643618488
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 7D6BC85A8F342EC1263D5CDC9F19A3966220A816FE5C218892508A1A2364F18B
    Session-ID-ctx:
    Resumption PSK: 2A37153513860B95C793CC118247443D5044CA392567311698793A561B829E0D8C6543EB022FE62767DFE1E67780C6FC
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 64800 (seconds)
    TLS session ticket:
    0000 - cc 37 6a 0e 6a 90 47 ad-2c 43 f7 36 4e 81 7d cb   .7j.j.G.,C.6N.}.
    0010 - 66 5a 45 be 14 cc a5 77-42 07 01 21 e7 89 73 64   fZE....wB..!..sd
    0020 - 21 0c c0 32 7d 52 91 76-37 47 8b 2e 70 4b cb f6   !..2}R.v7G..pK..
    0030 - 23 aa 92 d3 0d 19 0a 4c-38 f1 75 0d 5c 50 8c 5e   #......L8.u.\P.^
    0040 - 24 b0 b9 72 bc c5 ee dc-0d 02 2d 04 dc 32 4b eb   $..r......-..2K.
    0050 - b9 98 f6 0c 0e 63 8e 8f-6d 43 05 7f 25 29 b5 d2   .....c..mC..%)..
    0060 - e3 12 85 f9 87 8b 48 ad-c0 58 b6 3e 4f 28 b2 a2   ......H..X.>O(..
    0070 - c4 41 d8 04 5e 5e 87 88-64 0e 40 cb d9 86 0a 37   .A..^^..d.@....7
    0080 - 78 3d 58 8e 63 4e 8a 28-bd 99 76 37 cb 81 b8 76   x=X.cN.(..v7...v
    0090 - 20 a8 00 43 2e da aa 81-f2 2f 7d 51 56 45 1b a7    ..C...../}QVE..
    00a0 - 90 01 fa a0 51 c5 04 af-e6 87 aa a6 5f 54 e0 a7   ....Q......._T..
    00b0 - e5 ec ba 66 5e 91 2a c0-d8 06 a0 14 d7 45 2b 5e   ...f^.*......E+^

    Start Time: 1643618488
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed`

**Comment by foraern** [comment]
Something I just noticed. I went to test via jackett again, and it worked for a bit, but then after a while it stopped working again.

**Comment by foraern** [comment]
Here's my docker-compose.yml for reference

```
---
version: "3"
services:
    plex:
        image: linuxserver/plex:latest
        container_name: plex
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
          - PLEX_CLAIM=claim-BPQHkxubWYzGpCikEr8i
        volumes:
          - ~/docker-services/plex/config:/config
          - /media/maindrive:/media/maindrive
        ports:
          - 32400:32400/tcp 
          - 3005:3005/tcp 
          - 8324:8324/tcp 
          - 32469:32469/tcp 
          - 1900:1900/udp 
          - 32410:32410/udp 
          - 32412:32412/udp 
          - 32413:32413/udp 
          - 32414:32414/udp 
        restart: unless-stopped
    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
        volumes:
          - ~/docker-services/transmission/config:/config
          - /media/maindrive/downloads:/downloads
        ports:
          - 9091:9091
          - 49153:49153
          - 49153:49153/udp
        restart: unless-stopped
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - AUTO_UPDATE=true
          - RUN_OPTS=run options here #optional
        volumes:
          - ~/docker-services/jackett/config:/config
        ports:
          - 9117:9117
        restart: unless-stopped
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=PST
          - UMASK_SET=022 #optional
        volumes:
          - ~/docker-services/sonarr/config:/config
          - /media/maindrive:/media/maindrive
          - /media/maindrive/downloads:/downloads
        ports:
          - 8989:8989
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=PST
        volumes:
          - ~/docker-services/radarr/config:/config
          - /media/maindrive:/media/maindrive
          - /media/maindrive/downloads:/downloads
        ports:
          - 7878:7878
        restart: unless-stopped
    ombi:
        image: linuxserver/ombi
        container_name: ombi
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=PST
          - BASE_URL=/ombi #optional
        volumes:
          - ~/docker-services/ombi/config:/config
        ports:
          - 3579:3579
        restart: unless-stopped
```
