### ISSUE TITLE
[req] divxtotal

### ISSUE THREAD

**Issue by antoniogmartin** [Jackett/Jackett#1293]
Id: divxtotal
Name: DivxTotal
Description: DivxTotal is a SPANISH site for Movies, TV series and Software
SiteLink: https://divxtotal.foo/
Public

**Comment by fryfrog** [comment]
https://github.com/Jackett/Jackett/wiki/How-to-request-a-new-tracker

^ Might help you get it going, maybe even all by yourself. :)

**Comment by antoniogmartin** [comment]
But... What am i supossed to do? Create a file with categories from the webpage?
like this one:
AddMultiCategoryMapping(TorznabCatType.TVAnime,116, 140, 151, 117, 141, 152, 148);

**Comment by ghost** [comment]
@antoniogmartin 
Have a look in here https://github.com/Jackett/Jackett/tree/master/src/Jackett/Definitions for examples of other trackers
and if you are familiar with html you will probably be able to create your own definition

**Comment by RmG152** [comment]
**Main URL**
http://www.newpct.com

**Query**
index.php?l=doSearch&q=FILMORSHOWTOSEARCH&category_=CATEGORY&idioma_=1&bus_de_=All

// Games
AddMultiCategoryMapping( TorznabCatType.PCGames, 47);
// Software
AddMultiCategoryMapping( TorznabCatType.PC, 125);
//Tv-HDTV, ERIE-ES-ES-HDTV, SERIE-VOSTES-ES-SD, SERIE-ES-ES-WEB, SERIE-ES-ES-WEB-RIP
AddMultiCategoryMapping(TorznabCatType.TVSD, 767,924);
//Tv-HDTV-720p, SERIE-ES-ES-HDTV-720p, SERIE-ES-ES-DVDrip, SERIE-ES-ES-BDrip, SERIE-ES-ES-MHD, SERIE-ES-ES-BluRay, SERIE-ES-ES-DVD, SERIE-VOSTES-ES-HD, SERIE-ES-ES-WEB-720p, SERIE-ES-ES-WEB-1080p, SERIE-ES-ES-WEB-RIP-720p, SERIE-ES-ES-WEB-RIP-1080p
AddMultiCategoryMapping(TorznabCatType.TVHD,1469);
//DVDRIP, DVDR-PAL, DVDR-NTSC, DVDR-FULL
AddMultiCategoryMapping(TorznabCatType.MoviesDVD,757,1921);
//BDRIP, HD-BLURAY
AddMultiCategoryMapping(TorznabCatType.MoviesBluRay, 1027);
//mHD-720p, mHD-1080p, HDRIP-720p, HDRIP-1080p
AddMultiCategoryMapping(TorznabCatType.MoviesHD, 1027);
//3d
AddMultiCategoryMapping(TorznabCatType.Movies3D, 1599);
//OtherFilms
AddMultiCategoryMapping(TorznabCatType.MoviesOther, 1921,3049,1527);
//DOCUMENTAIRES, DOCUMENTAIRES-HD
AddMultiCategoryMapping(TorznabCatType.TVDocumentary, 780);
//SERIE-VOSTES-ES-PACK, SERIE-ES-ES-PACK, VOSTES-ES, SUBPACK
AddMultiCategoryMapping(TorznabCatType.TV, 775);
//FILM-VOSTES-ES-PACK, FILM-ES-ES-PACK, FILM-ES, SUBPACK
AddMultiCategoryMapping(TorznabCatType.Movies, 778);
//TVSport
AddMultiCategoryMapping(TorznabCatType.TVSport, 822);
//Other
AddMultiCategoryMapping(TorznabCatType.OtherMisc, 827);

**Comment by imperativeoz** [comment]
Would love this to be added. How can I help? what is the next step?

**Comment by kaso17** [comment]
If you know a little about HTML/CSS selectors you might want to look at https://github.com/Jackett/Jackett/wiki/Definition-format

**Comment by josel2000** [comment]
Yo doy un voto a favor Me interesa también que trabajen español torrent

**Comment by josel2000** [comment]
I give a vote in favor I am interested also in that they work Spanish torrent

**Comment by kijart** [comment]
This can be used as a starting point for elitetorrent.eu and elitetorrent.biz. Could someone help on tests and improvements?

- [elitetorrent-eu.yml.txt](https://github.com/Jackett/Jackett/files/1777440/elitetorrent-eu.yml.txt)
- [elitetorrent-biz.yml.txt](https://github.com/Jackett/Jackett/files/1777441/elitetorrent-biz.yml.txt)

**Comment by xavisbd** [comment]
Hi @kijart if you tell me what I can help you to test.

**Comment by Aokromes** [comment]
newpct group (tumejortorrent, newpct, descargas2020, tvsinpager, torrentlocura): https://github.com/Jackett/Jackett/commit/ef22d43f463a94b7b1a9ec90f846fe64881ac05a

**Comment by rovik0** [comment]
> 
> 
> This can be used as a starting point for elitetorrent.eu and elitetorrent.biz. Could someone help on tests and improvements?
> 
>     * [elitetorrent-eu.yml.txt](https://github.com/Jackett/Jackett/files/1777440/elitetorrent-eu.yml.txt)
> 
>     * [elitetorrent-biz.yml.txt](https://github.com/Jackett/Jackett/files/1777441/elitetorrent-biz.yml.txt)

I'm interested on having elitetorrent listed on jackett, we lack of spanish trackers over here and more and more are getting closed. Is this YML can be used directly with jackett as a working tracker or something? I've no clue how to use it.

**Comment by rovik0** [comment]
elitetorrent-biz.yml.txt looks like Jackett accepts and tests are ok but when I try to add it at Sonarr fails.

**Comment by garfield69** [comment]
yeah, elitetorrent-biz.yml is missing 
```yaml
      tv-search: [q, season, ep]
      movie-search: [q]
```
so Sonarr can't use it

**Comment by rovik0** [comment]
Tryed but no luck... This is the output , what I saw is that the API key is not filled so I was wondering that maybe there are some additional parameters to set up when adding an indexer. 
	
TorznabRssParser	An error occurred while processing feed item from http://x.x.x.x:xxxx/api/v2.0/indexers/elitetorrent-biz/results/torznab/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: Value cannot be null. Parameter name: attribute

**Comment by garfield69** [comment]
I've improved it a bit so it returns valid fields, Sonarr needed the seeders.
```yaml
---
  site: elitetorrent-biz
  name: EliteTorrent.biz
  description: "EliteTorrent.biz is a Public torrent site for TV, movies and documentaries"
  language: es-es
  type: public
  encoding: UTF-8
  links:
    - https://www.elitetorrent.biz/

  caps:
    categories:
      "series": TV
      "peliculas": Movies

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  settings: []

  download:
    selector: a[href^="magnet:?"]
    attribute: href 

  search:
    path: index.php
    inputs:
      s: "{{ .Keywords }}"
      $raw: "&x=0&y=0"
    rows:
      selector: "#principal .miniboxs-ficha li"
    fields:
      title:
        selector: .meta a
      details:
        selector: .meta a
        attribute: href
      download:
        selector: .meta a
        attribute: href
      category:
        selector: .meta a
        attribute: href
        filters:
          - name: split
            args: ["/", 3]
      size:
        selector: .voto1
        filters:
          - name: replace
            args: ["s", ""]
      date:
        text: now
      seeders:
        text: "1"
      leechers:
        text: "1"
      downloadvolumefactor:
        text: "0"
      uploadvolumefactor:
        text: "1"
```
but it still needs work, as the site does not use the SxxExx season/episode scheme, so Sonarr will not find any episodes for TV series. 
Take a look at existing spanish and italian indexers for examples of the processing involved.

**Comment by kijart** [comment]
Thank you all for the improvements and comments, I'll try it next days to see if we are able to create a stable version of it.

**Comment by rovik0** [comment]
Wow this is awesome!! I would like to help but I need some guidance, what can I do?

**Comment by kijart** [comment]
I made some progress, the episodes format are normalized and now Sonarr is working well.

There is any way to retrieve seeders information from the torrent detail page, like for the download block?

Here is the yml file, if there is no way to get seeders information I can create a PR with it, even if is not fully perfect but functional.

```
---
  site: elitetorrent-biz
  name: EliteTorrent.biz
  description: "EliteTorrent.biz is a Public torrent site for TV, movies and documentaries"
  language: es-es
  type: public
  encoding: UTF-8
  links:
    - https://www.elitetorrent.biz/

  caps:
    categories:
      "series": TV
      "peliculas": Movies

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  settings: []

  download:
    selector: a[href^="magnet:?"]
    attribute: href

  search:
    path: index.php
    keywordsfilters:
      # most ES/ITA TV torrents are in XXxYY format, so we search without S/E prefixes and filter later
      - name: re_replace
        args: ["S0?(\\d{1,2})", " $1 "]
      - name: re_replace
        args: ["E(\\d{2,3})", " $1 "]
    inputs:
      s: "{{ .Keywords }}"
      $raw: "&x=0&y=0"
    rows:
      selector: "#principal .miniboxs-ficha li"
    fields:
      title:
        selector: .meta a
        # normalize to SXXEYY format
        filters:
          - name: re_replace
            args: ["(\\d{2})×(\\d{2})", "S$1E$2"]
          - name: re_replace
            args: ["(\\d{1})×(\\d{2})", "S0$1E$2"]
      details:
        selector: .meta a
        attribute: href
      download:
        selector: .meta a
        attribute: href
      category:
        selector: .meta a
        attribute: href
        filters:
          - name: split
            args: ["/", 3]
      size:
        selector: .voto1
        filters:
          - name: replace
            args: ["s", ""]
      date:
        text: now
      seeders:
        text: "1"
      leechers:
        text: "1"
      downloadvolumefactor:
        text: "0"
      uploadvolumefactor:
        text: "1"
```
