### ISSUE TITLE
[req]: Translate category from input to output 

### ISSUE THREAD

**Issue by avengermsoft** [Jackett/Jackett#12948]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

How can I translate an incoming category to an output? 

Sample 1: 
From URL input: `/api/v2.0/indexers/all/results?apikey=&Category[]=2000`
Output JSON `
"Results": [
{
	...
	"CategoryDesc": "Movies",
	"Category": [
		2000,
		100001
	]
	...
}]
`

Sample 2: 
From URL input: `/api/v2.0/indexers/all/results?apikey=&Category[]=5000`
Output JSON `
"Results": [
{
	...
	"CategoryDesc": "TV",
	"Category": [
		5000,
		500001
	]
	...
}]
`

### Describe the solution you'd like

If there are many categories at the input, then the first one from the input list is passed to the output.  If the category is not set, then leave it empty.

**Comment by ilike2burnthing** [comment]
The first number (1000-8020) is the generic Torznab category ID for that result, and is the same for all indexers, e.g. `2000` is `Movies` for every indexer.

The second number (>=100000) is the custom category ID for that result, and is specific to that indexer, e.g. `100073` is `Movies/Bollywood` for 1337x, but is `Saga Fast And Furious` for DivTeam.

https://github.com/Jackett/Jackett/wiki/Jackett-Categories

I'm not really sure what you're asking though.

**Comment by avengermsoft** [comment]
@ilike2burnthing I need to implement such a category definition algorithm:
```
search:
  paths:
    - path: "/api.php?key={{ .Config.apikey }}&s={{ .Keywords }}"
      response:
        type: json

  fields:
    category:
      text: {if isset(.Input.Category[]) then .Input.Category[0] else null}
```
Is it possible?
