### ISSUE TITLE
torrentqq: Error while parsing row

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#13167]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
04-16 22:38:19 Info Starting Jackett v0.20.876 
04-16 22:38:23 Info Environment version: 6.0.4 (/app/Jackett/) 
04-16 22:38:23 Info OS version: Unix 5.15.32.8 (64bit OS) (64bit process) 
04-16 22:38:23 Info Jackett variant: CoreLinuxArm64 
04-16 22:38:23 Info File /etc/issue: Ubuntu 18.04.6 LTS \n \l 
04-16 22:38:23 Info Running in Docker: Yes (image build: v0.20.876-ls61) 
04-16 22:38:23 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads 
04-16 22:38:23 Info App config/log directory: /config/Jackett 
04-16 22:38:23 Info Using proxy: Disabled 
04-16 22:38:23 Info Using FlareSolverr: http://flaresolverr:8191 
04-16 22:38:23 Info Using HTTP Client: HttpWebClient2
```

### Description

"query": "avengers"

### Logged Error Messages

```text
CardigannIndexer (torrentqq): Error while parsing row '
<li class="list-item">
	<div class="wr-num hidden-xs">53</div>
	<div class="wr-subject ellipsis">
		<a href="https://torrentqq139.com/torrent/mov.html?category_id=5" class="hidden-xs">
			<span class="label label-success">영화 &gt;SF/판타지</span>
		</a>
		<span class="label label-primary hidden-xs">우리말더빙</span>
		<a href="https://torrentqq139.com/torrent/mov/141600.html" class="subject font-13 en" title="어벤져스: 엔드게임 avengers.endgame.2019.1080p.bluray.x264-sparks.2-Audio.KorDub-G.Nom">어벤져스: 엔드게임 avengers.endgame.2019.1080p.bluray.x264-sparks.2-Audio.KorDub-G.Nom</a>
		<div class="item-details text-muted font-12 visible-xs ellipsis">
			<span>
				<i class="fa fa-tags"></i>
				<a href="https://torrentqq139.com/torrent/mov.html?category_id=5">영화 &gt; SF/판타지</a>
			</span>
			<span>
				<i class="fa fa-tags"></i>
				우리말더빙</span>
			<span>
				<i class="fa fa-download"></i>
				13.33G</span>
			<span>
				<i class="fa fa-clock-o"></i>
				02-29</span>
		</div>
	</div>
	<div class="wr-size hidden-xs">13.33G</div>
	<div class="wr-date hidden-xs">02-29</div>
</li>':

System.Exception: Error while parsing field=date, selector=, value=02-29: DateTime parsing failed for "2022-02-29": System.Exception: FromFuzzyTime parsing failed
   at Jackett.Common.Utils.DateTimeUtil.FromFuzzyTime(String str, String format) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 100
   at Jackett.Common.Utils.DateTimeUtil.FromUnknown(String str, String format, Nullable`1 relativeFrom) in /home/vsts/work/1/s/src/Jackett.Common/Utils/DateTimeUtil.cs:line 204
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1603
```

**Comment by garfield69** [comment]
this is not a bug in the indexer, but perhaps something in the cardigann date parsing.
the indexer has 
```yaml
    date_day:
      selector: div.wr-date:contains("-")
      optional: true
      filters:
        - name: dateparse
          args: "01-02"
    date_time:
      selector: div.wr-date:contains(":")
      optional: true
      filters:
        - name: dateparse
          args: "15:04"
    date:
      text: "{{ if or .Result.date_time .Result.date_day }}{{ or .Result.date_time .Result.date_day }}{{ else }}now{{ end }}"
```
and the html has
```html
	<div class="wr-date hidden-xs">02-29</div>
```
Debugging shows that the date_day block is matching the dash and dateparsing MM-dd
however this yields:
```
Error while parsing DateTime "02-29", using layout "01-02" (MM-dd): The DateTime represented by the string '02-29' is not supported in calendar 'System.Globalization.GregorianCalendar'.
```
@ngosang  what to do?
