### ISSUE TITLE
Search keyword encoding problem

### ISSUE THREAD

**Issue by firstvip** [Jackett/Jackett#13263]
I'm using the definitions files to support a new site, which has `<meta charset=gb2312>`
Even if I set `encoding: gb2312` in the yml file, the search keyword still uses utf-8 encoding instead of gb2312 encoding.
What should I do?

**Comment by ngosang** [comment]
Encoding is working well:
1. I made a definition with
```
encoding: gb2312`
....
search:
  paths:
    - path: plus/so.php
      method: get
  inputs:
    typeid: 1
    keyword: "{{ .Keywords }}"
```
2. I searched "中英" without the quotes in Jackett and in the site. URLs are equal. If I change the encoding in Jackett to "utf-8" I get other keyword so it's working as expected.

Site URL => http://s.ygdy8.com/plus/so.php?typeid=1&keyword=%D6%D0%D3%A2
Jackett URL =>http://s.ygdy8.com/plus/so.php?typeid=1&keyword=%D6%D0%D3%A2
