### ISSUE TITLE
[req]: Cardigann: add variables support to the keywordsfilters block

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13297]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

as highlighted by #13296, Cardigann does not support the use of variable substitution or the use of conditionals in the keywordsfilters.

### Describe the solution you'd like

add variables support to the keywordsfilters block so that  
```yaml
  keywordsfilters:
    - name: re_replace
      args: ["(?i)S0?(\\d{1,2})E(\\d{1,2})", "{{ if eq .Query.Type \"tvsearch\" }}{{ else }}$1x$2{{ end }}"]
```
is possible.
