### ISSUE TITLE
[req]: searchPath category filter

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#13697]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

ATM, Cardigann has the following method:
https://github.com/Jackett/Jackett/blob/4d33f93e102171b2240b06af8b429b76c865a8e7/src/Jackett.Common/Indexers/CardigannIndexer.cs#L1348-L1360

with the wiki description
```yaml
search:
  paths:
      # [OPTIONAL] list of tracker categories
      # If specified the path will be only used if at least one category from the list is included in
      # the search categories list. A "!" as first entry negates the matching logic (include the path 
      # in any other than the specified categories is in the search categories list)
      categories: ["!", 901, 902]
    - path: torrents.php
      # don't use this path if we're only searching for porn
      categories: ["!", 901, 902]
     - path: xxx.php
      # only use it if we're searching for porn
      categories: [901, 902]
```

So, given this real example from bitbazis
https://github.com/Jackett/Jackett/blob/4d33f93e102171b2240b06af8b429b76c865a8e7/src/Jackett.Common/Definitions/bitbazis.yml#L98-L109

I've added the following debug statements to a build so I could understand what actually happens
```
SearchPath=browse.php
hasInvertMatch=True
mappedCategories=[22,58,69,68,91,33,89,66]
SearchPathCategories=[!,33,66,89]
hasIntersect=True
finalIntersect=True (the searchPath will be skipped)
SearchPath=browse_xxx.php
hasInvertMatch=False
mappedCategories=[22,58,69,68,91,33,89,66]
SearchPathCategories=[33,66,89]
hasIntersect=True
finalIntersect=False (The searchPath will be actioned)
WebClient(HttpWebClient2).GetResultAsync(Method: GET Url: https://bitbazis.net/browse_xxx.php?c22=1&c58=1&c69=1&c68=1&c91=1&c33=1&c89=1&c66=1&search=&sort=4&type=desc&incldead=1)
```
which results in only the browse_xxx path being used, with all the categories that were selected being passed to the query.

All the above is my long winded way of saying that I don't think this is the ideal way to handle searchPath categories

### Describe the solution you'd like

I would like for the SearchPath categories to act as a filter, which is to say, that only those categories that are included in the filter are passed through to the searchPath. If none are filtered through then the searchPath is skipped.

Using the bitbazis example above, I expect to see both searchPath being used, with the following http GETs being produced:
```
https://bitbazis.net/browse.php?c22=1&c58=1&c69=1&c68=1&c91=1&search=&sort=4&type=desc&incldead=0
https://bitbazis.net/browse_xxx.php?&c33=1&c89=1&c66=1&search=&sort=4&type=desc&incldead=1
```

**Comment by garfield69** [comment]
I've generated the following for bitbazis. I don't have time right now to process ygg (its such a complicated site) but I will try to make time later to come up with something.

bitbazis:
given the following caps block
```yaml
caps:
  categorymappings:
    - {id: 85, cat: Movies/SD, desc: "Film/Cam/Hun", default: true}
    - {id: 86, cat: Movies/SD, desc: "Film/Cam/Eng", default: true}
    - {id: 15, cat: Movies/SD, desc: "Film/SD/Hun", default: true}
    - {id: 16, cat: Movies/SD, desc: "Film/SD/Eng", default: true}
    - {id: 17, cat: Movies/DVD, desc: "Film/DVD/Hun", default: true}
    - {id: 19, cat: Movies/DVD, desc: "Film/DVD/Eng", default: true}
    - {id: 83, cat: Movies/HD, desc: "Film/HD/Hun", default: true}
    - {id: 82, cat: Movies/HD, desc: "Film/HD/Eng", default: true}
    - {id: 94, cat: Movies/HD, desc: "Film/FHD/Hun", default: true}
    - {id: 95, cat: Movies/HD, desc: "Film/FHD/Eng", default: true}
    - {id: 92, cat: Movies/UHD, desc: "Film/UHD/Hun", default: true}
    - {id: 93, cat: Movies/UHD, desc: "Film/UHD/Eng", default: true}
    - {id: 64, cat: Movies, desc: "Film/Pack", default: true}
    - {id: 24, cat: Audio/Video, desc: "Videóklip", default: true}
    - {id: 22, cat: TV, desc: "Sorozat/Hun", default: true}
    - {id: 58, cat: TV, desc: "Sorozat/Eng", default: true}
    - {id: 69, cat: TV/Anime, desc: "Mese/SD", default: true}
    - {id: 68, cat: TV/Anime, desc: "Mese/DVD", default: true}
    - {id: 91, cat: TV/Anime, desc: "Mese/HD", default: true}
    - {id: 25, cat: Audio/MP3, desc: "Mp3/Hun", default: true}
    - {id: 26, cat: Audio/MP3, desc: "Mp3/Eng", default: true}
    - {id: 84, cat: Audio/Lossless, desc: "Lossless/Hun", default: true}
    - {id: 71, cat: Audio/Lossless, desc: "Lossless/Eng", default: true}
    - {id: 31, cat: PC/Games, desc: "Játék/PC", default: true}
    - {id: 81, cat: PC/0day, desc: "Program/PC", default: true}
    - {id: 49, cat: PC/0day, desc: "Program/Rip", default: true}
    - {id: 27, cat: Books/EBook, desc: "Könyv/Hun", default: true}
    - {id: 50, cat: Books/EBook, desc: "Könyv/Eng", default: true}
    - {id: 14, cat: PC, desc: "Program/Egyéb", default: true}
    - {id: 65, cat: Other, desc: "Egyéb", default: true}
    - {id: 33, cat: XXX/SD, desc: "SD/XXX", default: false}
    - {id: 89, cat: XXX/x264, desc: "HD/XXX", default: false}
    - {id: 66, cat: XXX/ImageSet, desc: "Képek/XXX", default: false}
    # the following are no longer in the cat list in the search page, but are still in the profile cat list
    - {id: 54, cat: Console, desc: "Játék/Konzol", default: true}
    - {id: 67, cat: PC/Mobile-Android, desc: "Program/Mobil", default: true}
    - {id: 70, cat: Audio/Audiobook, desc: "Hangoskönyv", default: true}
```
and the following search block
```yaml
search:
  paths:
    - path: browse.php
      categories: ["!", 33, 66, 89]
      inputs:
        # 0 all, 1 active, 2 deadonly, 3  myuploads, 4 zeroseed, 6 re-seeded
        incldead: 0
    - path: browse_xxx.php
      categories: [33, 66, 89]
      inputs:
        # 0 active, 1 all, 2 deadonly, 3  myuploads, 4 zeroseed, 6 re-seeded
        incldead: 1
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    search: "{{ .Keywords }}"
    sort: "{{ .Config.sort }}"
    type: "{{ .Config.type }}"
```
then I would expect the following queries would generate these urls
```
http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=redacted&Query=&Tracker[]=bitbazis
https://bitbazis.net/browse.php?c85=1&c86=1&c15=1&c16=1&c17=1&c19=1&c83=1&c82=1&c94=1&c95=1&c92=1&c93=1&c64=1&c24=1&c22=1&c58=1&c69=1&c68=1&c91=1&c25=1&c26=1&c84=1&c71=1&c31=1&c81=1&c49=1&c27=1&c50=1&c14=1&c65=1&c54=1&c67=1&c70=1&sort=4&type=desc&incldead=0
https://bitbazis.net/browse_xxx.php?c33=1&c89=1&c66=1&sort=4&type=desc&incldead=1
```
```
http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=redacted&Query=&Category[]=6000&Tracker[]=bitbazis
https://bitbazis.net/browse_xxx.php?c33=1&c89=1&c66=1&sort=4&type=desc&incldead=1
```
```
http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=redacted&Query=&Category[]=2000&Tracker[]=bitbazis
https://bitbazis.net/browse.php?c85=1&c86=1&c15=1&c16=1&c17=1&c19=1&c83=1&c82=1&c94=1&c95=1&c92=1&c93=1&c64=1&sort=4&type=desc&incldead=0
```
```
http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=redacted&Query=&Category[]=100089&Tracker[]=bitbazis
https://bitbazis.net/browse_xxx.php?c89=1&sort=4&type=desc&incldead=1
```
```
http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=redacted&Query=&Category[]=100071&Category[]=100084&Tracker[]=bitbazis
https://bitbazis.net/browse.php?c84=1&c71=1&sort=4&type=desc&incldead=0
```
```
http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=redacted&Query=&Category[]=100082&Category[]=100083&Category[]=100089&Tracker[]=bitbazis
https://bitbazis.net/browse.php?c83=1&c82=1&sort=4&type=desc&incldead=0
https://bitbazis.net/browse_xxx.php?c89=1&sort=4&type=desc&incldead=1
```
