### ISSUE TITLE
[req]: Use ajax.php for hebits indexer

### ISSUE THREAD

**Issue by DirectorX** [Jackett/Jackett#13808]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

use the ajax page to get clean data
`https://hebits.net/ajax.php?action=browse`

repalce any `torrents.php` with `ajax.php?action=browse`

```
https://hebits.net/torrents.php?action=advanced&imdbgt=0&imdblt=10&freetorrent=2&order_by=time&order_way=desc
```

to

```
https://hebits.net/ajax.php?action=browse&imdbgt=0&imdblt=10&freetorrent=2&order_by=time&order_way=desc
```

### Describe the solution you'd like

see flexget: https://github.com/Flexget/Flexget/blob/301ee85a0b4481b51b6be654d8d378bdfc9db53b/flexget/components/sites/sites/hebits.py#L94

using the json instead of parsing html

**Comment by ilike2burnthing** [comment]
<details>
<summary>hebits.yml</summary>

```yml
---
id: hebits
name: Hebits
description: "The Israeli Tracker"
language: he-IL
type: private
encoding: UTF-8
links:
  - https://hebits.net/

caps:
  categorymappings:
    - {id: 1, cat: Movies, desc: "סרטים (Movies)"}
    - {id: 2, cat: TV, desc: "סדרות (TV)"}
    - {id: 3, cat: TV/Other, desc: "הצגות והופעות (Theater)"}
    - {id: 4, cat: PC/0day, desc: "תוכנות (Apps)"}
    - {id: 5, cat: PC/Games, desc: "משחקים (Games)"}
    - {id: 6, cat: Audio, desc: "מוזיקה (Music)"}
    - {id: 7, cat: Books, desc: "ספרים (Books)"}
    - {id: 8, cat: Movies/Other, desc: "חבילות סרטים (Movies Packs)"}
    - {id: 9, cat: XXX, desc: "פורנו (Porn)"}
    - {id: 10, cat: Other, desc: "שונות (Other)"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]

settings:
  - name: cookie
    type: text
    label: Cookie
  - name: info
    type: info
    label: How to get the Cookie
    default: "<ol><li>Login to this tracker with your browser<li>Open the <b>DevTools</b> panel by pressing <b>F12</b><li>Select the <b>Network</b> tab<li>Click on the <b>Doc</b> button (Chrome Browser) or <b>HTML</b> button (FireFox)<li>Refresh the page by pressing <b>F5</b><li>Click on the first row entry<li>Select the <b>Headers</b> tab on the Right panel<li>Find <b>'cookie:'</b> in the <b>Request Headers</b> section<li><b>Select</b> and <b>Copy</b> the whole cookie string <i>(everything after 'cookie: ')</i> and <b>Paste</b> here.</ol>"
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: time
    options:
      time: created
      seeders: seeders
      size: size
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc

login:
  method: cookie
  inputs:
    cookie: "{{ .Config.cookie }}"
  test:
    path: torrents.php

search:
  paths:
    - path: ajax.php
      response:
        type: json

  inputs:
    searchstr: "{{ if .Query.IMDBID }}{{ .Query.IMDBID }}{{ else }}{{ .Keywords }}{{ end }}"
    order_by: "{{ .Config.sort }}"
    order_way: "{{ .Config.type }}"
    imdbgt: 0
    imdblt: 10
    # 1 freeleech, 2 neutral, 3 50%, 4 2x, 5 3x, 9 75%, 11 only perks, 0 normal
    freetorrent: "{{ if .Config.freeleech }}1{{ else }}{{ end }}"
    action: browse
    $raw: "{{ range .Categories }}filter_cat[{{.}}]=1&{{end}}"

  rows:
    selector: response.results
    attribute: torrents
    multiple: true

  fields:
    _id:
      selector: torrentId
    category:
      selector: ..categoryID
    title_notenglish:
      selector: release:not(:contains("a")):not(:contains("e")):not(:contains("i")):not(:contains("o")):not(:contains("u")):not(:contains("y"))
      optional: true
      filters:
        # space out the book language at the end of the title
        # everything within the outermost quotes below is right to left
        - name: re_replace
          args: ["(אנגלית)$", " - אנגלית"] # English
        - name: re_replace
          args: ["(עברית)$", " - עברית"] # Hebrew
    title_english:
      selector: release
      optional: true
      filters:
        - name: append
          args: "א" # catch English only results
        - name: regexp
          args: "(.+?[a-zA-Z0-9\\]\\)\\}])[א-ת].*" # remove Hebrew labels from end of title, account for titles ending in letters, numbers, and brackets
    title:
      text: "{{ if .Result.title_notenglish }}{{ .Result.title_notenglish }}{{ else }}{{ .Result.title_english }}{{ end }}"
    details:
      text: "{{ .Config.sitelink }}torrents.php?torrentid={{ .Result._id }}"
    download:
      text: "{{ .Config.sitelink }}torrents.php?action=download&id={{ .Result._id }}"
    poster:
      selector: ..cover
    imdbid:
      selector: ..catalogue
    files:
      selector: fileCount
    date:
      selector: time
      filters:
        - name: append
          args: " +02:00" # IST
        - name: dateparse
          args: "2006-01-02 15:04:05 -07:00"
    size:
      selector: size
    grabs:
      selector: snatches
    seeders:
      selector: seeders
    leechers:
      selector: leechers
    _half:
      selector: isHalfFreeleech
    _free:
      selector: isFreeleech
    _x2:
      selector: isUploadX2
    _x3:
      selector: isUploadX3
    _quarter:
      selector: isQuarterLeech
    _neutral:
      selector: isNeutralLeech
    _personal:
      selector: isPersonalFreeleech
    downloadvolumefactor_special:
      optional: true
      text: "{{ if eq .Result._half \"true\" }}0.5{{ else }}{{ end }}{{ if eq .Result._quarter \"true\" }}0.25{{ else }}{{ end }}{{ if eq .Result._neutral \"true\" }}0{{ else }}{{ end }}{{ if eq .Result._free \"true\" }}0{{ else }}{{ end }}{{ if eq .Result._personal \"true\" }}0{{ else }}{{ end }}"
    downloadvolumefactor:
      text: "{{ if .Result.downloadvolumefactor_special }}{{ .Result.downloadvolumefactor_special }}{{ else }}1{{ end }}"
    uploadvolumefactor_special:
      optional: true
      text: "{{ if eq .Result._x3 \"true\" }}3{{ else }}{{ end }}{{ if eq .Result._x2 \"true\" }}2{{ else }}{{ end }}{{ if eq .Result._neutral \"true\" }}0{{ else }}{{ end }}"
    uploadvolumefactor:
      text: "{{ if .Result.uploadvolumefactor_special }}{{ .Result.uploadvolumefactor_special }}{{ else }}1{{ end }}"
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 7 days (as seconds = 7 x 24 x 60 x 60)
      text: 604800
    description:
      selector: ..tags
# Gazelle

```
</details>

<details>
<summary>ajax.php</summary>

```json
"torrents": [
  {
    "torrentId": 84526,
    "release": "Title Goes Here",
    "artists": [],
    "container": "Installer",
    "codec": "",
    "resolution": "",
    "audio": "",
    "subbing": "",
    "isForinge": true,
    "language": "",
    "archive": "RAR-Scene",
    "fileCount": 85,
    "time": "2022-12-23 09:17:25",
    "size": 2050492459,
    "snatches": 8,
    "seeders": 7,
    "leechers": 0,
    "isHalfFreeleech": false,
    "isFreeleech": false,
    "isUploadX2": false,
    "isUploadX3": false,
    "isQuarterLeech": false,
    "isNeutralLeech": false,
    "isPersonalFreeleech": false,
    "canUseToken": false,
    "hasSnatched": false
  }
```
</details>

@garfield69 got everything working apart from the DLVF and ULVF. Can you take a look? No rush.
