### ISSUE TITLE
[req]: TT-Torrent

### ISSUE THREAD

**Issue by showkubii** [Jackett/Jackett#13821]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

~~Private~~ Semi-Private

### Tracker details

```markdown
- Name: TT-Torrent
- URL: https://www.tt-square.com/
- Description: TT-Torrent is a THAI Semi-Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): 0.5
- Additional Comments:
```

**Comment by ilike2burnthing** [comment]
<details>
<summary>tttorrent.yml</summary>

```yml
---
id: tttorrent
name: TT-Torrent
description: "TT-Torrent is a THAI Semi-Private Torrent Tracker for MOVIES / TV / GENERAL"
language: th-TH
type: semi-private
encoding: UTF-8
links:
  - https://www.tt-square.com/

caps:
  categorymappings:
    - {id: 21, cat: TV, desc: "ละครไทย"}
    - {id: 22, cat: TV, desc: "Series"}
    - {id: 46, cat: TV/Anime, desc: "การ์ตูน"}
    - {id: 44, cat: Other, desc: "Template/Scripts"}
    - {id: 41, cat: Books/Technical, desc: "ความรู้/สื่อการสอน"}
    - {id: 40, cat: Books/Other, desc: "ศาสนา"}
    - {id: 1003, cat: Books/Mags, desc: "หนังสือ/นิตยสาร"}
    - {id: 47, cat: TV, desc: "รายการทีวี"}
    - {id: 33, cat: Audio/Lossless, desc: "Lossless (ไทย/เอเชีย)"}
    - {id: 1005, cat: Audio/Lossless, desc: "Lossless (อื่นๆ)"}
    - {id: 31, cat: Audio/MP3, desc: "เพลงไทย"}
    - {id: 42, cat: Audio/Video, desc: "MV/Live (ไทย)"}
    - {id: 43, cat: TV/Documentary, desc: "สารคดี"}
    - {id: 48, cat: TV/Sport, desc: "กีฬา"}
    - {id: 49, cat: Other, desc: "รูปภาพ"}
    - {id: 51, cat: PC/Games, desc: "เกมส์ (พีซี)"}
    - {id: 52, cat: Console, desc: "เกมส์ (อื่นๆ)"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    music-search: [q]
    book-search: [q]

settings:
  - name: email
    type: text
    label: Email
  - name: password
    type: password
    label: Password
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: id
    options:
      id: created
      seeders: seeders
      size: size

login:
  path: login.php
  method: post
  inputs:
    loginID: "{{ .Config.email }}"
    password: "{{ .Config.password }}"
  test:
    path: my.php
    selector: a[href$="logout=yes"]

download:
  before:
    path: torrent.php
    method: post
    inputs:
      recaptcha_response: "recaptcha_response goes here"
      hash_sha1: "{{ .DownloadUri.Query.hash_sha1 }}"

search:
  paths:
    # https://www.tt-square.com/index.php?c33=1&c31=1&freeload=on&search=&sort=id
    - path: index.php
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}{{ if .Config.freeleech }}&freeload=on{{ else }}{{ end }}"
    search: "{{ .Keywords }}"
    sort: "{{ .Config.sort }}"
    # site does not support imdbid searching and does not display imdb links in results.

  rows:
    selector: table > tbody > tr

  fields:
    category:
      selector: div.getcategory
      attribute: id
      filters:
        - name: replace
          args: ["category_a", ""]
    title:
      selector: a[href^="./details.php?hash_sha1="]
    details:
      selector: a[href^="./details.php?hash_sha1="]
      attribute: href
    download:
      selector: a[href^="./details.php?hash_sha1="]
      attribute: href
    poster:
      selector: button[data-image^="https://static.tt-torrent.com/"]
      attribute: data-image
    files:
      selector: td:nth-last-child(5)
    date:
      selector: td:nth-last-child(8) small
      filters:
        - name: append
          args: " +07:00" # ICT
        - name: dateparse
          args: "2006-01-02 15:04:05 -07:00"
    size:
      selector: td:nth-last-child(7)
    grabs:
      selector: td:nth-last-child(4)
    seeders:
      selector: td:nth-last-child(3)
    leechers:
      selector: td:nth-last-child(2)
    downloadvolumefactor:
      case:
        "button:contains(\"ไม่เสียเรโช\")": 0
        "*": 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 0.5
    description:
      selector: td:nth-last-child(8)
      remove: a, small, button
# engine n/a

```
</details>

I think I was on the right path, but not sure how to get `recaptcha_response` on the details page (it's also available on the results page, but I'm fairly sure Cardigann can't get that).

I tried adding the following to the download block, but it didn't like that:

```yml
_recaptcha: 
  selector: input[id="recaptchaResponse"]
  attribute: value
```
