### ISSUE TITLE
Sonarr can't retrieve any results from the indexer

### ISSUE THREAD

**Issue by lfmnovaes** [Jackett/Jackett#1402]
Hi,
I've been using Jackett since couple days ago, and right now I'm facing some problems to add HorribleSubs as a custom Torznab on Sonarr. I tried the exactly same thing with Rarbg and SceneTime, and worked fine.

Showing all working fine: http://i.imgur.com/srkPwGL.png
Test/add HorribleSubs not working on Sonarr: http://i.imgur.com/EFu1tci.png
Test/add SceneTime working on Sonarr: http://i.imgur.com/dxlbdd5.png

Btw, logs don't seems to show any error, and i can search releases from HorribleSubs inside Jackett's WebUI.

Jackett version: 0.7.1437.0
Using Windows 10, full updated.

-------------------------------

**Comment by flightlevel** [comment]
This sounds like the issue https://github.com/Jackett/Jackett/issues/1117#issuecomment-300673229

@CodeMonkey626 's fix should have resolved this for you https://github.com/Jackett/Jackett/commit/3426e66b3ba862dac735a92d5ee215312f58cf01
Can you check your definition file has updated ie, its exactly the same as https://github.com/Jackett/Jackett/blob/master/src/Jackett/Definitions/horriblesubs.yml

**Comment by lfmnovaes** [comment]
Yep, exactly the same. Just to be sure, i copy and pasted these definitions, restarted the background service and did the manual search again, works fine ( http://i.imgur.com/8YsYgDB.png with all files showing 500mb, maybe another issue) like before.
But I still can't add it to Sonarr.

**Comment by flightlevel** [comment]
Please provide Sonarr and Jackett debug logs
https://github.com/Jackett/Jackett#troubleshooting

**Comment by lfmnovaes** [comment]
Enabled Enhanced Logging and did the same steps again, and then stopped Jackett the service.
Jackett log: https://pastebin.com/wXXwwQYs
Sonarr log: https://pastebin.com/w6BmbMsb

**Comment by flightlevel** [comment]
Looks like they might have change their site recently or there is a site setting for the date format?
`2017-05-21 02:11:20.8070 Debug Error while parsing DateTime "05-19", using layout "01-02-06" (MM-dd-yy): String was not recognized as a valid DateTime. `
Its expecting to get a date with the month, day and year, but only getting the month and day instead
@CodeMonkey626 would you be able to have a look?

**Comment by lfmnovaes** [comment]
If helps to tell, I use dd-MM-yyyy on my computer.

**Comment by CodeMonkey626** [comment]
@lfmnovaes For now, disable RSS sync for this indexer and add [HorribleSub' RSS](http://horriblesubs.info/rss.php?res=all) feed directly into Sonarr.

The issue is that while [`/lib/search.php`](http://horriblesubs.info/lib/search.php?value=naruto) returns mm/dd/yy, [`/latest/php`](http://horriblesubs.info/lib/latest.php) only returns mm/dd.

I need to update the definition file to handle this.

**Comment by kaso17** [comment]
@CodeMonkey626 simply adding two datetime filters for the different formats should fix it.

**Comment by CodeMonkey626** [comment]
@kaso17 You mean like this?
```
        filters:
          - name: split
            args: [" ", 0 ]
          - name: replace
            args: ["(", ""]
          - name: replace
            args: [")", ""]
          - name: replace
            args: ["/", "-"]
          - name: dateparse 
            args: "01-02-06"
          - name: dateparse 
            args: "01-02"
```

I was originally trying to use `args: "{{if .Query.Keywords }}01-02-06{{else}}01-02{{end}}"`, but that didn't seem to be working.
