### ISSUE TITLE
[req]: KamePT

### ISSUE THREAD

**Issue by Siriussee** [Jackett/Jackett#14145]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: KamePT
- URL: https://kamept.com
- Description: KamePT is a CHINESE Private Torrent Tracker for Anime and 3X. 
- Minimum Seeding Time and Minimum Ratio (if Private): MR 0.9
- Additional Comments: Yet another NexusPHP-based private tracker. I don't have an invite for now, but I am happy to test it with my account. Thanks in advance!
NexusPHP v1.7.26 2022-09-15
```

**Comment by ilike2burnthing** [comment]
Please provide an HTML dump of https://kamept.com/torrents.php - https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source

**Comment by Siriussee** [comment]
[KamePT __ 种子 - Powered by NexusPHP.html.txt](https://github.com/Jackett/Jackett/files/10949554/KamePT.__.-.Powered.by.NexusPHP.html.txt)
Attached.

**Comment by ilike2burnthing** [comment]
Thanks.

<details>
<summary>kamept.yml</summary>

```yml
---
id: kamept
name: KamePT
description: "KamePT is a CHINESE Private Torrent Tracker for Anime and 3X"
language: zh-CN
type: private
encoding: UTF-8
links:
  - https://kamept.com

caps:
  categorymappings:
    - {id: 410, cat: XXX, desc: "同人AV"}
    - {id: 413, cat: XXX, desc: "男娘"}
    - {id: 414, cat: XXX, desc: "同人VR"}
    - {id: 417, cat: XXX, desc: "Cosplay套图"}
    - {id: 419, cat: XXX, desc: "里番"}
    - {id: 411, cat: XXX, desc: "2D动画"}
    - {id: 423, cat: XXX, desc: "3D动画"}
    - {id: 424, cat: XXX, desc: "单行本"}
    - {id: 435, cat: XXX, desc: "同人志"}
    - {id: 433, cat: XXX, desc: "画师CG"}
    - {id: 415, cat: XXX, desc: "游戏"}
    - {id: 418, cat: XXX, desc: "中文游戏"}
    - {id: 434, cat: XXX, desc: "游戏CG"}
    - {id: 420, cat: XXX, desc: "外语音声"}
    - {id: 421, cat: XXX, desc: "中文音声"}
    - {id: 422, cat: XXX, desc: "视频音声"}

  modes:
    search: [q]
    tv-search: [q, season, ep]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: 2facode
    type: text
    label: 2FA code
  - name: info_2fa
    type: info
    label: "About 2FA code"
    default: "Only fill in the <b>2FA code</b> box if you have enabled <b>2FA</b> on the ZmPT Web Site. Otherwise just leave it empty."
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: 4
    options:
      4: created
      7: seeders
      5: size
      1: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>100</b> on your account profile.

login:
  path: takelogin.php
  method: post
  inputs:
    secret: ""
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    two_step_code: "{{ .Config.2facode }}"
    logout: ""
    securelogin: ""
    ssl: yes
    trackerssl: yes
  error:
    - selector: td.embedded:has(h2:contains("失败"))
    - selector: td.embedded:has(h2:contains("failed"))
  test:
    path: index.php
    selector: a[href*="usercp.php"]

search:
  paths:
    - path: torrents.php
  inputs:
    $raw: "{{ range .Categories }}cat{{.}}=1&{{end}}"
    search: "{{ .Keywords }}"
    # 0 incldead, 1 active, 2 dead
    incldead: 0
    # 0 all, 1 normal, 2 free, 3 2x, 4 2xfree, 5 50%, 6 2x50%, 7 30%
    spstate: "{{ if .Config.freeleech }}2{{ else }}0{{ end }}"
    # 0 title, 1 descr, 3 uploader
    search_area: 0
    # 0 AND, 1 OR, 2 exact
    search_mode: 0
    sort: "{{ .Config.sort }}"
    type: "{{ .Config.type }}"
    notnewword: 1

  rows:
    selector: table.torrents > tbody > tr:has(a[href^="details.php?id="])

  fields:
    category:
      selector: a[href^="?cat="]
      attribute: href
      filters:
        - name: querystring
          args: cat
    title_default:
      selector: a[href^="details.php?id="]
    title_optional:
      optional: true
      selector: a[title][href^="details.php?id="]
      attribute: title
    title:
      text: "{{ if .Result.title_optional }}{{ .Result.title_optional }}{{ else }}{{ .Result.title_default }}{{ end }}"
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php?id="]
      attribute: href
      attribute: href
    poster:
      selector: img[data-src]
      attribute: data-src
    date_elapsed:
      # time type: time elapsed (default)
      selector: td.rowfollow:nth-child(4) > span[title]
      attribute: title
      optional: true
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-dd HH:mm:ss zzz"
    date_added:
      # time added
      selector: td.rowfollow:nth-child(4):not(:has(span))
      optional: true
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-ddHH:mm:ss zzz"
    date:
      text: "{{ if or .Result.date_elapsed .Result.date_added }}{{ or .Result.date_elapsed .Result.date_added }}{{ else }}now{{ end }}"
    size:
      selector: td.rowfollow:nth-child(5)
    seeders:
      selector: td.rowfollow:nth-child(6)
    leechers:
      selector: td.rowfollow:nth-child(7)
    grabs:
      selector: td.rowfollow:nth-child(8)
    downloadvolumefactor:
      case:
        img.pro_free: 0
        img.pro_free2up: 0
        img.pro_50pctdown: 0.5
        img.pro_50pctdown2up: 0.5
        img.pro_30pctdown: 0.3
        "*": 1
    uploadvolumefactor:
      case:
        img.pro_50pctdown2up: 2
        img.pro_free2up: 2
        img.pro_2up: 2
        "*": 1
    minimumratio:
      text: 0.9
    description:
      selector: td.rowfollow:nth-child(2)
      remove: a, img, font, span
# NexusPHP v1.7.26 2022-09-15

```
</details>

Easiest option is to test on Windows. Create a file in `C:\ProgramData\Jackett\Definitions` titled `kamept.yml` (or copy another definition and rename it), open it in Notepad, paste the above into it, and save. Restart Jackett and add the new KamePT indexer.

Run a few searches to make sure all details are correct (titles, categories, dates, size, seeders, freeleech, etc.) and hover your mouse over the titles to make sure posters and descriptions are displayed correctly. Also make sure you can download torrents from Jackett.

Report any errors or issues here.

Are there any actual TV anime categories (not hentai)? If so, please correct them as they're currently all just listed as `XXX`. You may find this list of categories helpful, in case some of the XXX categories would be better renamed - https://github.com/Jackett/Jackett/wiki/Jackett-Categories.
