### ISSUE TITLE
[Req]: HellTorrents

### ISSUE THREAD

**Issue by 60plus** [Jackett/Jackett#14164]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: HellTorrents
- URL: https://helltorrents.com/
- Description: HellTorrents is a POLISH Semi-Private PAY2DL Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and Minimum Ratio (if Private): unknown not listed
- Additional Comments: 
  site is open for registration but need to pay for activation.
  sometimes it loads slowly something to do with claudflare secure connection.
```

**Comment by garfield69** [comment]
While I can set up the indexer using the login and torrents pages, I will not spend money activating my account in order to download.
So @60plus , if you want me to create an indexer I will need you to provide a HTML dump of https://helltorrents.com/torrents.php so that I can see what the download link look like.

To provide a HTML dump follow steps 1,3,4 and 5 from https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-html-source
Thanks.

**Comment by garfield69** [comment]
I cant work on this. If I use the Browser directly I get https://github.com/Jackett/Jackett/issues/14162#issuecomment-1472972169
If I use hide.me I can use the browser, but when I try to use the indexer I coded for Jackett (via hide.me), then flaresolverr times out with `Error solving the challenge`.
[edit] seems they have blocked hide.me 'cause I cant access with browser anymore, despite changing server locations.

Someone else can do this.

here is the indexer so far, untested and probably full of bugs
[edit] Oh, and the category selector is wrong, looks like it will need a case block ;-(
```YAML
---
id: helltorrents
name: HellTorrents
description: "HellTorrents is a POLISH Semi-Private Torrent Tracker for MOVIES / TV / GENERAL"
language: pl-PL
type: semi-private
encoding: UTF-8
links:
  - https://helltorrents.com/

caps:
  categorymappings:
    # Filmy
    - {id: 27, cat: Movies/DVD, desc: "Filmy DVD"}
    - {id: 28, cat: Movies/SD, desc: "Filmy VCD/SVCD"}
    - {id: 30, cat: Movies/SD, desc: "Filmy DivX/XviD"}
    - {id: 31, cat: Movies/HD, desc: "Filmy RMVB"}
    - {id: 71, cat: Movies/3D, desc: "Filmy 3D"}
    - {id: 72, cat: Movies/BluRay, desc: "Filmy BluRay/HDTV 1080p"}
    - {id: 73, cat: Movies/BluRay, desc: "Filmy BluRay/HDTV 720p"}
    - {id: 74, cat: Movies/HD, desc: "Filmy x265/h265"}
    - {id: 75, cat: Movies/HD, desc: "Filmy x264/h264"}
    - {id: 76, cat: Movies/HD, desc: "Filmy HD 1080p AVC"}
    - {id: 77, cat: Movies/UHD, desc: "Filmy i Seriale 4K UHD"}
    - {id: 78, cat: Movies/SD, desc: "Filmy IVO"}
    - {id: 79, cat: Movies/SD, desc: "Filmy TS/CAM/IVO/AUDIO KINO"}
    - {id: 82, cat: Movies, desc: "Teatr"}
    # Seriale
    - {id: 25, cat: TV, desc: "Seriale Polskie"}
    - {id: 26, cat: TV/Foreign, desc: "Seriale Zagraniczne"}
    # Dla Dzieci
    - {id: 32, cat: Movies, desc: "Bajki Pl/Eng"}
    # Gry
    - {id: 34, cat: PC/Games, desc: "Gry PC"}
    - {id: 35, cat: Console/PSP, desc: "PS2/PS3/PS4/PSP"}
    - {id: 36, cat: Console/XBox, desc: "Xbox One/XBOX 360/Xbox"}
    - {id: 37, cat: Console/NDS, desc: "NINTENDO / WII / DS"}
    # Muzyka
    - {id: 38, cat: Audio/Foreign, desc: "Muzyka Zagraniczna"}
    - {id: 39, cat: Audio, desc: "Soundtracki"}
    - {id: 40, cat: Audio/Video, desc: "Teledyski"}
    - {id: 80, cat: Audio, desc: "Muzyka Polska"}
    - {id: 81, cat: Audio/Video, desc: "Koncerty"}
    # GSM/PDA
    - {id: 42, cat: PC/Mobile-Other, desc: "Tapety GSM/PDA"}
    - {id: 43, cat: PC/Mobile-Other, desc: "Programy GSM/PDA"}
    - {id: 44, cat: PC/Mobile-Other, desc: "Filmy GSM/PDA"}
    - {id: 45, cat: PC/Mobile-Other, desc: "Dzwonki GSM/PDA"}
    - {id: 46, cat: PC/Mobile-Other, desc: "Gry GSM/PDA"}
    # Ksiazki
    - {id: 47, cat: Books/EBook, desc: "E-Booki"}
    - {id: 48, cat: Audio/Audiobook, desc: "Audio-Booki"}
    - {id: 49, cat: Books/Mags, desc: "Czasopisma"}
    - {id: 50, cat: Books/Comics, desc: "Komiksy"}
    # Programy
    - {id: 51, cat: PC/0day, desc: "Windows"}
    - {id: 52, cat: PC, desc: "Linux"}
    - {id: 53, cat: PC/Mac, desc: "Macintosh"}
    # Inne
    - {id: 54, cat: Other, desc: "Śmieszne"}
    - {id: 55, cat: Other, desc: "Tapety"}
    - {id: 56, cat: TV/Sport, desc: "Sport"}
    - {id: 57, cat: Other, desc: "Pozostale"}
    # Erotyka
    - {id: 58, cat: XXX/Other, desc: "Czasopisma"}
    - {id: 59, cat: XXX/ImageSet, desc: "Zdjęcia "}
    - {id: 60, cat: XXX/x264, desc: "Filmy"}
    - {id: 61, cat: XXX/Other, desc: "Gry "}
    - {id: 63, cat: XXX/Other, desc: "Hentai+18"}
    # Anime
    - {id: 69, cat: TV/Anime, desc: "Anime Pl"}
    - {id: 70, cat: TV/Anime, desc: "Anime"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: multilang
    type: checkbox
    label: Replace MULTi by another language in release name
    default: false
  - name: multilanguage
    type: select
    label: Replace MULTi by this language
    default: POLISH
    options:
      POLISH: POLISH
      MULTi POLISH: MULTIi POLISH
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrentów na stronę:</b> (Torrents per page) setting to <b>100</b> on your account profile.

login:
  path: login.php
  method: form
  form: form[name="login"]
  inputs:
    uid: "{{ .Config.username }}"
    pwd: "{{ .Config.password }}"
    keeplogged: 1
  error:
    - selector: font[color="#FF0000"]
  test:
    path: index.php
    selector: a[href="logout.php"]

search:
  paths:
    # https://helltorrents.com/torrents.php?order=data&by=DESC&page=0
    - path: torrents.php
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    search: "{{ .Keywords }}"
    page: 0
    # does not support sorting results, or imdbid searching, or have imdb in results
    order: data
    by: DESC

  rows:
    selector: table.header

  fields:
    category:
      selector: a[href^="torrents.php?category="]
      attribute: href
      filters:
        - name: querystring
          args: category
    title_phase1:
      selector: a[href^="details.php?id="]
    title_multilang:
      selector: a[href^="details.php?id="]
      filters:
        - name: re_replace
          args: ["(?i)\\b(MULTI(?!.*(?:POLISH|ENGLISH|\\bPL\\b)))\\b", "{{ .Config.multilanguage }}"]
        - name: re_replace
          args: ["(?i)\\b(pl)\\b", "POLISH"]
    title:
      text: "{{ if .Config.multilang }}{{ .Result.title_multilang }}{{ else }}{{ .Result.title_phase1 }}{{ end }}"
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href*="download.php?id="]
      attribute: href
    poster:
      selector: img
      attribute: src
    date:
      selector: td.pole1
      filters:
        - name: regexp
          args: "Dodano: (\\d{2}/\\d{2}/\\d{4})"
        - name: dateparse
          args: "dd/MM/yyyy"
    size:
      selector: td.pole1
      filters:
        - name: regexp
          args: "Rozmiar: (\\d+\\.\\d+ [T|G|M|K|k]B)"
    seeders:
      selector: td.pole1
      filters:
        - name: regexp
          args: "Seedów: (\\d+)"
    leechers:
      selector: td.pole1
      filters:
        - name: regexp
          args: "Leecherów: (\\d+)"
    grabs:
      selector: td.pole1
      filters:
        - name: regexp
          args: "Ukończone: (\\d+)"
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine n/a
```
