### ISSUE TITLE
[u2]: incorrect downloadvolumefactor

### ISSUE THREAD

**Issue by trim21** [Jackett/Jackett#14457]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Jackett Version v0.21.205
```

### Description

a torrent with 0.3x download and 3x upload is parsed as `<torznab:attr name="downloadvolumefactor" value="0" />` and `<torznab:attr name="uploadvolumefactor" value="3" />`

![image](https://github.com/Jackett/Jackett/assets/13553903/e1e52831-2a1e-4af7-8724-83005c97fcaa)

### Logged Error Messages

```text
null
```

**Comment by trim21** [comment]
`other` doesn't always be 0x download 
![image](https://github.com/Jackett/Jackett/assets/13553903/9f1121e1-ee75-4853-b11a-408002760f37)

**Comment by trim21** [comment]
fix for this:

```yaml
    uploadvolumefactor:
      selector: b:nth-last-child(1)
      filters:
        - name: regexp
          args: (.*)x
    uploadvolumefactor:
      selector: b:nth-last-child(2)
      filters:
        - name: regexp
          args: (.*)x
```

But I don't know hot to chain it into current config...
