### ISSUE TITLE
[req]: make login selectorinputs optional

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#14825]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Tapochek presents a captcha if incorrect credentials have been used more than once from a specific IP. As well as the captcha, there are now also hidden inputs. The login block below works if using the flagged IP address, but fails if using a proxy/VPN, as the selectors cannot be found.

```yml
login:
  path: login.php
  method: form
  form: form[action$="/login.php"]
  captcha:
    type: image
    selector: img[src^="profile.php?mode=confirm&id="]
    input: cfmcd
  inputs:
    login_username: "{{ .Config.username }}"
    login_password: "{{ .Config.password }}"
    autologin: on
    redirect: /
  selectorinputs:
    cookie_test:
      selector: input[name="cookie_test"]
      attribute: value
    confirm_id:
      selector: input[name="confirm_id"]
      attribute: value
    sid:
      selector: input[name="sid"]:not(input[id="dl-sid"])
      attribute: value
  error:
    - selector: h4:contains("Вы ввели")
  test:
    path: index.php
    selector: a[href="./login.php?logout=1"]
```

If wanting to test this, I recommend using a proxy/VPN when entering the wrong credentials, as no matter how many times I enter the correct credentials I'm still getting the captcha on each successive login attempt.

### Describe the solution you'd like

login `selectorinputs` be optional

### Describe alternatives you've considered

login `selectorinputs` support `optional: true`
