### ISSUE TITLE
[req]: Making Off

### ISSUE THREAD

**Issue by AARON8888** [Jackett/Jackett#14834]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: Making Off
- URL: https://www.makingoff.org/
- Description: Making Off is a BRAZILIAN Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): none, uses public trackers
- Additional Comments: IMDb id possible in search (Forum section). No captcha at login.
```

**Comment by AARON8888** [comment]
Do you need invite to fix this issue?

**Comment by ilike2burnthing** [comment]
yes

**Comment by ilike2burnthing** [comment]
[v0.21.1189](https://github.com/Jackett/Jackett/releases/v0.21.1189)

**Comment by AARON8888** [comment]
Did you test with this link: https://indice.makingoff.org/?
Search option not only by title but also by IMDb id.

**Comment by ilike2burnthing** [comment]
We'd lose a lot by using that, like search by category, release names, posters, and description. IMDB search should be easy enough to add to the current indexer, I'll look at that later.

**Comment by garfield69** [comment]
v0.21.1207

**Comment by ilike2burnthing** [comment]
https://makingoff.org/ - Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by ilike2burnthing** [comment]
Site has updated and we might not be able to use the search anymore (or at least I can't figure it out) without rewriting in C#. Each search is given a unique ID, below is `6069`, and cannot be done without one or one be reused:

https://www.makingoff.org/search/6069/?t=post&q=2025&o=relevance

All I got was the updated login block, and the domain now requires `www.` at the start:

<details>
<summary>Updated login block</summary>

```yml
login:
  path: login
  method: form
  form: form[action="/login/login"]
  inputs:
    _xfRedirect: https://makingoff.org/
    login: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    remember: 1
  selectorinputs:
    _xfToken:
      selector: input[name="_xfToken"]
      attribute: value
  error:
    - selector: div.blockMessage--error
  test:
    path: /
    selector: a[href="/conta/"]
```

</details>
