### ISSUE TITLE
[req]: CrabPT (蟹黄堡)

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#15140]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: CrabPT (蟹黄堡)
- URL: https://crabpt.vip/
- Description: CrabPT (蟹黄堡) is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MR 1.0 MST 1d
- Additional Comments: signups currently open
No account activity info
No exam
Engine: NexusPHP v1.10.2 2026-04-11
```
Has JSON API

**Comment by garfield69** [comment]
v0.21.2025

**Comment by garfield69** [comment]
https://crabpt.vip/ HTTP ERROR 500 (Internal Server Error)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://crabpt.vip/ cloudflare Bad gateway Error code 502

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://crabpt.vip/ under maintenance

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://crabpt.vip/ cloudflare Connection timed out Error code 522

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15140#issuecomment-2263555596

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15140#issuecomment-2245837128

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/15140#issuecomment-2245837128

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://crabpt.vip/  The crab roe burger is sifting flour... Please stay tuned~~Estimated completion time: November 30, 21:40
 ( Site under maintenance Time of post 16:20)

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://crabpt.vip/ > cloudflare Web server is down Error code 521

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
- https://crabpt.vip/ > cloudflare Bad gateway Error code 502
- now displaying a banner stating that a new high-performance server is being looked for.

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
until the new server is installed you can expect 502 or timeouts when accessing this site, as per https://github.com/Jackett/Jackett/issues/15140#issuecomment-2993702144

**Comment by garfield69** [comment]
https://crabpt.vip/ > HTTP 500

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://crabpt.vip/ > Maintenance Notice

**Comment by garfield69** [comment]
Upgrade to new server completed.
Online.

**Comment by garfield69** [comment]
- https://crabpt.vip/ > cloudflare Bad gateway Error code 502
- cloudflare Invalid SSL certificate Error code 526
- 404 Not Found nginx

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
Add a JSON API indexer.
We will keep the HTML scraper indexer for those that need imdbid searching or find freeleech filter rather than freeleech search insufficient.

**Comment by garfield69** [comment]
instead of the usual `fetch torrent list` and `view torrent detail` authorities (which was not accepted by the API search test in the login block) I had to give it all the other authorities as well.

**Comment by garfield69** [comment]
everything works EXCEPT the download, which is returning invalid passkey . same issue as https://github.com/Jackett/Jackett/issues/16385#issuecomment-5768698202
<details>
  <summary>crabpt-api</summary>

```yaml
---
id: crabpt-api
name: CrabPT (蟹黄堡) (API)
description: "CrabPT (蟹黄堡) is a CHINESE Private Torrent Tracker for MOVIES / TV / GENERAL"
language: zh-CN
type: private
encoding: UTF-8
requestDelay: 2
links:
  - https://crabpt.vip/

caps:
   categorymappings:
    - {id: 401, cat: Movies, desc: "电影 / Movies"}
    - {id: 402, cat: TV, desc: "电视剧 / TVSeries"}
    - {id: 413, cat: TV/Other, desc: "短剧 / Playlet"}
    - {id: 408, cat: Audio, desc: "音乐 / Music"}
    - {id: 405, cat: TV/Anime, desc: "动漫 / Anime"}
    - {id: 406, cat: Audio/Video, desc: "MV"}
    - {id: 403, cat: TV, desc: "综艺 / TV Shows"}
    - {id: 407, cat: TV/Sport, desc: "体育竞技 / Sports"}
    - {id: 404, cat: TV/Documentary, desc: "纪录片 / Documentary"}
    - {id: 409, cat: Other, desc: "其他 / Other"}
    - {id: 415, cat: Books/Comics, desc: "漫画 / Cartoon"}
    - {id: 414, cat: Console, desc: "游戏 / Game"}
    - {id: 412, cat: Other, desc: "学习 / Study"}
    - {id: 411, cat: Audio/Audiobook, desc: "有声书 / Audiobook"}
    - {id: 410, cat: Books/EBook, desc: "电子书 / Ebook"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: apikey
    type: text
    label: API Token
  - name: info_apikey
    type: info
    label: About your API Token
    default: "Find/Generate an API token from your <a href=\"https://crabpt.vip/usercp.php\" target=\"_blank\">CrabPT</a> account control panel."
  - name: passkey
    type: text
    label: Passkey
  - name: info_passkey
    type: info
    label: About your Passkey
    default: "Find the Passkey from your account control panel."
  - name: freeleech
    type: checkbox
    label: Filter freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: "-id"
    options:
      "-id": created
      "-seeders": seeders
      "-size": size
      "-times_completed": grabs
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "Account retention rules:<ol><li>Veteran User and above will be retained forever</li><li>Elite User and above will not have their account deleted after parking (in the control panel)</li><li> Users with a parked account will be deleted if they do not log in for 400 consecutive days</li><li>Users with a non-parked account will be deleted if they do not log in for 150 consecutive days</li><li>Users who have no traffic (i.e. upload/download data are both 0) will be deleted if they do not log in for 100 consecutive days.</li></ol>"

login:
  path: api/v1/torrents
  method: get
  inputs:
    per_page: 1
  error:
    - selector: :root:contains("login.php?returnto")
      message:
        text: "The API token was not accepted by {{ .Config.sitelink }}."
    - selector: :root:contains("Unauthenticated")
      message:
        text: "The API token was not accepted by {{ .Config.sitelink }}."

search:
  paths:
    - path: api/v1/torrents
      response:
        type: json

  headers:
    Authorization: ["Bearer {{ .Config.apikey }}"]

  inputs:
    $raw: "{{ range .Categories }}&filter[category][in][]={{.}}{{end}}"
    "filter[title]": "{{ .Keywords }}"
    sorts: "{{ .Config.sort }}"
    per_page: 100

  keywordsfilters:
    # the site stores dotted release names but the title filter matches on words
    - name: re_replace
      args: ["\\.", " "]

  rows:
    selector: "data.data{{ if .Config.freeleech }}:not(promotion_info.down_multiplier:contains(1)):not(promotion_info.down_multiplier:contains(.)){{ else }}{{ end }}"

  fields:
    category:
      selector: category
    _id:
      selector: id
    title:
      selector: name
    details:
      text: "{{ .Config.sitelink }}details.php?id={{ .Result._id }}&hit=1"
    download:
      text: "{{ .Config.sitelink }}download.php?id={{ .Result._id }}&passkey={{ .Config.passkey }}"
    infohash:
      selector: hash
    poster:
      selector: cover
    description:
      selector: small_descr
    size:
      selector: size
    files:
      selector: numfiles
    seeders:
      selector: seeders
    leechers:
      selector: leechers
    grabs:
      selector: times_completed
    date:
      # 2026-09-19 16:50
      selector: added
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-dd HH:mm zzz"
    downloadvolumefactor:
      # promotion_info is the EFFECTIVE promotion and accounts for site-wide freeleech events.
      # sp_state is only the stored per-torrent promotion, so it reads 1 on a torrent the site has made free.
      selector: promotion_info.down_multiplier
    uploadvolumefactor:
      selector: promotion_info.up_multiplier
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 1 day (as seconds = 24 x 60 x 60)
      text: 86400
# NexusPHP v1.10.2 2026-04-11
```

</details>
