### ISSUE TITLE
[req]: Hebits indexer remove imdbid from tv-search mode

### ISSUE THREAD

**Issue by BuSHari** [Jackett/Jackett#15224]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

When searching for epsidoes from sonarr i'll get all episodes of a show because it search bu imdbid, need to use with q

### Describe the solution you'd like

Please remove imdbid from tv-search mode, for example:
```yml
  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]
```
