### ISSUE TITLE
[req]: Add a globalfreeleech statement and selector to cardigann so that we can detect global freeleech on torrent search page

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15242]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

A common problem across many different private sites is that when they have a Global Freeleech event, the Cardigann indexers do not set a freeleech flag for all the results it returns. 

### Describe the solution you'd like

Set up a new yaml statement and selector so that Cardigann can detect if the torrent search page has a Global Freeeleech event happening, and force a freeleech flag for all results returned.
Suggested example:
```yaml
 search:
  paths:
    - path: torrents.php
      globalfreeleech:
        selector: div.alert__content:contains("FREELEECH IS ON")
      inputs:
        search: "{{ .Keywords }}"
```
the selector would be optional in that if its not found no error is generated
But if found then all rows will have the freeleech flag set.

### Describe alternatives you've considered

open to suggestions.
