### ISSUE TITLE
Custom Indexer stopped working after update

### ISSUE THREAD

**Issue by felipemarinho97** [Jackett/Jackett#15251]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
docker:latest
```

### Description

When using the lates docker image I gat this error and none of my custom indexers work with Radarr & Sonarr.
`04-16 14:35:12 Warn [bludv_indexer] Invalid Release: 'https://bludv.xyz/familia-e-tudo-1a-temporada-2024-06-03-2024/'. No categories provided.`

Using oldest versions, everything is normal. Someone may just introduced a breaking change with the latest versions.

This is my indexer:
```
---
id: bludv_indexer
name: BluDV Indexer
description: "BluDV - Custom indexer on OCI"
language: pt-BR
type: public
encoding: UTF-8
links:
  - https://vlambdas.oci.darklyn.online/

caps:
  categorymappings:
    # Video
    - { id: 200, cat: Movies, desc: "Video" }
    - { id: 201, cat: Movies, desc: "Movies" }
    - { id: 202, cat: Movies, desc: "Movies DVDR" }
    - { id: 203, cat: Audio/Video, desc: "Music Videos" }
    - { id: 204, cat: Movies/Other, desc: "Movie Clips" }
    - { id: 205, cat: TV, desc: "TV Shows" }
    - { id: 206, cat: TV/Other, desc: "Handheld" }
    - { id: 207, cat: Movies/HD, desc: "HD - Movies" }
    - { id: 208, cat: TV/HD, desc: "HD - TV shows" }
    - { id: 209, cat: Movies/3D, desc: "3D" }
    - { id: 210, cat: Movies/SD, desc: "CAM/TS" }
    - { id: 211, cat: Movies/UHD, desc: "UHD/4k - Movies" }
    - { id: 212, cat: TV/UHD, desc: "UHD/4k - TV shows" }
    - { id: 299, cat: Movies/Other, desc: "Video Other" }

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
  allowrawsearch: true

settings: []

search:
  paths:
    - path: "indexers/bludv?q={{ .Keywords }}"
      response:
        type: json

  keywordsfilters:
    - name: tolower

  rows:
    selector: $.results
    count:
      selector: $.count

  fields:
    _id:
      selector: title
    download:
      selector: magnet_link
    title:
      selector: title
    description:
      selector: original_title
    details:
      selector: details
    infohash:
      selector: info_hash
    date:
      selector: date
    size:
      selector: size
    seeders:
      selector: seed_count
    leechers:
      selector: leech_count
    imdb:
      selector: imdb
# json engine n/a#

```

### Logged Error Messages

```text
`04-16 14:35:12 Warn [bludv_indexer] Invalid Release: 'https://bludv.xyz/familia-e-tudo-1a-temporada-2024-06-03-2024/'. No categories provided.`
```

**Comment by ilike2burnthing** [comment]
I had previously tagged you in https://github.com/Jackett/Jackett/issues/15030 to see if you wanted us to add an indexer to Jackett. Do you, or is it just for personal use?

It looks like you've taken the `categorymappings` block from thepiratebay.yml, but it doesn't appear there are any categories returned in your JSON. If categories cannot be added (even as simple as `TV` and `Movies`), then just replace the `categorymappings` block with:

```yml
  categories:
    Other: Other
```

and add the following to the `fields` block:

```yml
    category:
      text: Other
```

**Comment by garfield69** [comment]
Or, for a little more variety you could use:
```yaml
caps:
  categorymappings:
    - { id: Movie, cat: Movies, desc: "Movies" }
    - { id: TV, cat: TV, desc: "TV" }
```
and 
```yaml
  fields:
    category_is_tv_show:
      selector: title
      filters:
        - name: regexp
          args: "\\b(S\\d+(?:E\\d+)?)\\b"
    category:
      text: "{{ if .Result.category_is_tv_show }}TV{{ else }}Movie{{ end }}"
```
