### ISSUE TITLE
[hdolimpo] Regex for spanish language substitution does not handle multi releases other than english

### ISSUE THREAD

**Issue by goioCodes** [Jackett/Jackett#15279]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Environment version: 6.0.29 (C:\ProgramData\Jackett\)
OS version: Microsoft Windows NT 10.0.19045.0 (64bit OS)
Jackett variant: CoreWindows
Running in Docker: No
ThreadPool MaxThreads: 1023 workerThreads, 1000 completionPortThreads
App config/log directory: C:\ProgramData\Jackett
Using proxy: Disabled
Using FlareSolverr: No
Using HTTP Client: HttpWebClient2
```

### Description

HD-Olimpo includes language tags in the form of a dash-separated string of 2 or 3 letter codes, which do not necessarily adhere to the ISO codes. Here are some example release names:

La conserje Pokémon (2023) S01 [PACK][NF WEB-DL 1080p AVC ES-JA DD+ 5.1 Subs][HDO]
Guardianes de la Noche - Tren Infinito (2020) [FullBluRay 1080p AVC ES-CA-JAP DTS-HD MA 5.1 Subs][HDO]
Saben aquell (2023) [WEB-DL 1080p AVC ES-CAT DD+ 5.1 Subs]HDO

The problem: ES tag followed by any language other than EN will cause the conversion from ES -> SPANiSH to fail. The above releases all fail to show SPANiSH as language.

This is due to the regular expression for ES expecting spaces on both sides, while ES-EN and EN-ES are handled separately. If it's not possible to accept a dash after ES for some reason, the combinations ES-CAT, ES-CA, ES-JP, ES-JA, and ES-JAP are common enough that they should have a specific case written for them.

### Logged Error Messages

```text
Not relevant
```

### Screenshots

![image](https://github.com/Jackett/Jackett/assets/32550964/e46b834b-9c5a-4ddf-b479-dd070a5c6666)
![image](https://github.com/Jackett/Jackett/assets/32550964/be3abb80-8eff-42a7-b03c-fa19548d93d1)
![image](https://github.com/Jackett/Jackett/assets/32550964/3ed6cfc9-04ca-4ca9-b184-becec9c014d2)

**Comment by ilike2burnthing** [comment]
Quite a lot needs to change about the current title filters (these go back years, and it turns out I merged one of the PRs that added much of it). I'm kind of surprised they haven't caused more issues before now.

See my questions and comments in the code below, see if you can respond to them:

```yml
    title:
      selector: name
      filters:

# do these really need to be removed?
#        - name: re_replace
#          args: ["[\\[\\]]", ""]
#        - name: re-replace
#          args: ["(?i)\\bHD-?Olimpo\\b", ""]

# needs to be more specific and to use boundaries, currently:
# a full house > a BRDISK house
# fully loaded > BRDISKy loaded
#        - name: re_replace
#          args: ["(?i)(full(bluray)?)", "BRDISK"]

        - name: re_replace
          args: ["\\bE-AC-3\\b", "EAC3"]
        - name: re_replace
          args: ["(?i)\\b(es-en|en-es)\\b", "MULTi SPANiSH ENGLiSH"]
        - name: re_replace
          args: ["(?i)\\bes-cat?\\b", "MULTi SPANiSH CATALAN"]
        - name: re_replace
          args: ["(?i)\\bes-(ja|ja?p)\\b", "MULTi SPANiSH JAPANESE"]

# what is the third language? if it can vary,
# then are the other two always English and Spanish?
#        - name: re_replace
#          args: ["(?i)\\btriaudio\\b", "MULTi SPANiSH ENGLiSH"]

# not specific enough, not sure it can be made more specific
#        - name: re_replace
#          args: ["(?i)\\bdual\\b", "MULTi SPANiSH"]
#        - name: re_replace
#          args: ["(?i)\\bspa\\b", "SPANiSH"]

# not specific enough, especially for a Spanish tracker,
# not sure it can be made more specific
#        - name: re_replace
#          args: [" ES ", " SPANiSH "]
#        - name: re_replace
#          args: ["(?i)\\bvas\\b", "BASQUE"]

        - name: re_replace
          args: ["(?i)\\b(espa[ñn]ol|castellano|esp)\\b", "SPANiSH"]
        - name: re_replace
          args: ["(?i)\\b(ingl[ée]s|[ei]ng)\\b", "ENGLiSH"]
        - name: re_replace
          args: ["(?i)\\bcat\\b", "CATALAN"]
        - name: re_replace
          args: ["(?i)\\bfr[ae]\\b", "FRENCH"]
        - name: re_replace
          args: ["(?i)\\b(jap|jp)\\b", "JAPANESE"]
        - name: re_replace
          args: ["(?i)\\bita\\b", "ITALiAN"]
        - name: re_replace
          args: ["(?i)\\brus\\b", "RUSSiAN"]
        - name: re_replace
          args: ["(?i)\\bger\\b", "GERMAN"]
        - name: re_replace
          args: ["(\\s|\\.)+", "$1"]
        - name: re_replace
          args: ["^\\.", ""]
```

I used to have an account, but it was banned for inactivity (that's the problem with having accounts for a few hundred trackers). If you want me to take a closer look at this, you could open a support ticket with the tracker staff and ask them to reinstate the account `nahik99374` and email address `jacketttest [AT] gmail [DOT] com`, then link to this issue 👋
