### ISSUE TITLE
[req]: Cardigann - change Flaresolverr Info to a YML bool

### ISSUE THREAD

**Issue by bakerboy448** [Jackett/Jackett#15334]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

Simplify Cardigann YML and make Flaresolverr trackers easier to manage by creating a NeedsFlaresolverr Boolean

### Describe the solution you'd like

see above

### Describe alternatives you've considered

Continue to need to specify details for each site in multiple lines.

**Comment by ilike2burnthing** [comment]
Perhaps do something similar for cookie and UA instructions as well? Not exactly that, but see also: https://github.com/Jackett/Jackett/issues/7780.

**Comment by garfield69** [comment]
I think we might want to be able to determine where in the config the info block is inserted, so that we can decide the order and placement in between other config page elements.
To that end, I suggest defining types info_flaresolverr, info_cookie and info_useragent that would go in the settings block of a yaml indexer. The name can be anything unique, as usual, and the type keyworkds would trigger cardigann to insert the common info strings into the config page.
Examples:
```yaml
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: flaresolverr
    type: info_flaresolver
```
and
```yaml
settings:
  - name: cookie
    type: text
    label: Cookie
  - name: info
    type: info_cookie
  - name: useragent
    type: text
    label: User-Agent
  - name: user_agent
    type: info_useragent
```
