### ISSUE TITLE
[req]:  SkrBT

### ISSUE THREAD

**Issue by a799841185** [Jackett/Jackett#15701]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: SkrBT
- URL: https://skrbtgb.top/ https://skrbtun.top/ https://skrbtso.top/
- Description: SkrBT is a CHINESE Public tracker for MOVIES / TV / GENERAL
```
Current domains list at https://soskr.top/

**Comment by garfield69** [comment]
If the three domains are for different web sites then please raise separate requests for the other two so we can track them individually

**Comment by garfield69** [comment]
Well this sucks.
My search path 
`https://skrbtgb.top/search?keyword=2024&sos=date&sofs=all&sot=all&soft=all&som=auto&p=1`
gets redirected to some custom challenge path
`https://skrbtgb.top/recaptcha/v4/challenge?url=https://skrbtgb.top&s=1`
which fails

there is little point using the cookie method as that challenge gets used often so the user would be copy/pasting cookies regularly ;-(

Cannot proceed with this indexer.
I've included the yml here in case someone can figure out how to use it.

<details>
  <summary>SkrBT</summary>
```YAML
---
id: skrbt
name: SkrBT
description: "SkrBT is a CHINESE Public tracker for MOVIES / TV / GENERAL"
language: zh-CN
type: public
encoding: UTF-8
links:
  # Current domain list at https://soskr.top/
  - https://skrbtgb.top/
  - https://skrbtun.top/
  - https://skrbtso.top/

caps:
  categories:
    Other: Other

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: info_category_8000
    type: info_category_8000

download:
  infohash:
    hash:
      selector: a[href^="magnet:?xt"]
      attribute: href
      filters:
        - name: regexp
          args: ([A-F|a-f|0-9]{40})
    title:
      selector: h3
      filters:
        - name: validfilename

search:
  paths:
    - path: search
  inputs:
    keyword: "{{ if .Keywords }}{{ .Keywords }}{{ else }}{{ .Today.Year }}{{ end }}"
    sos: date
    sofs: all
    sot: all
    soft: all
    som: auto
    p: 1

  rows:
    selector: ul:not(:has(a[href*="/play/video/"]))
    filters:
      - name: andmatch

  fields:
    category:
      text: Other
    title:
      selector: a.rrt
    details:
      selector: a.rrt
      attribute: href
    download:
      selector: a.rrt
      attribute: href
    size:
      selector: span.rrmiv:nth-child(1)
    files:
      selector: span.rrmiv:nth-child(2)
    date:
      selector: span.rrmiv:nth-child(3)
      filters:
        - name: append
          args: " +08:00" # CST
        - name: dateparse
          args: "yyyy-MM-dd HH:mm:ss zzz"
    seeders:
      text: 1
    leechers:
      text: 1
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine n/a
```
