### ISSUE TITLE
emuwarez.it is not working in Sonarr / Radarr

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#15768]
### Have you checked our Troubleshooting page for your issue?

- [X] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Environment

```markdown
Using HTTP Client: HttpWebClient2
Using FlareSolverr: http://flaresolverr:8191
Using proxy: Disabled
App config/log directory: /config/Jackett
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
Running in Docker: Yes (image build: v0.22.1116-ls623)
File /etc/issue: Welcome to Alpine Linux 3.20
Jackett variant: CoreLinuxMuslArm64
OS version: Unix 6.1.21.8 (64bit OS) (64bit process)
Environment version: 8.0.11 (/app/Jackett/)
Starting Jackett v0.22.1116
```

### Description

Sonarr / Radarr is not working well because of the name of the files. They must include SPANISH word in order to be downloaded.
Since all content is in Spanish from Spain I don't see any problem in doing the same fix you did here =>
https://github.com/Jackett/Jackett/blob/3c0191795eefe8624e9ab967931483e7185f7131/src/Jackett.Common/Definitions/torrentland.yml#L115C1-L126C27
```
    title_vose:
      selector: a.view-torrent:contains("VOSE")
      optional: true
      filters:
        - name: append
          args: " ENGLiSH"
    title_notvose:
      selector: a.view-torrent:not(:contains("VOSE"))
      optional: true
      filters:
        - name: append
          args: " SPANiSH"
```

### Logged Error Messages

```text
.
```
