### ISSUE TITLE
Connection error on NAS using qbittorent

### ISSUE THREAD

**Issue by hohaha045** [Jackett/Jackett#15908]
### Have you checked our Troubleshooting page for your issue?

- [x] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Have you ACTUALLY checked all these?

YES.

### Environment

```markdown
03-12 11:31:10 Info Using HTTP Client: HttpWebClient2
03-12 11:31:10 Info Using FlareSolverr: No
03-12 11:31:10 Info Using proxy: Disabled
03-12 11:31:10 Info App config/log directory: /config/Jackett
03-12 11:31:10 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
03-12 11:31:10 Info Running in Docker: Yes (image build: v0.22.1589-ls703)
03-12 11:31:10 Info File /etc/issue: Welcome to Alpine Linux 3.21
03-12 11:31:10 Info Jackett variant: CoreLinuxMuslAmdx64
03-12 11:31:10 Info OS version: Unix 4.4.302.0 (64bit OS) (64bit process)
03-12 11:31:10 Info Environment version: 8.0.14 (/app/Jackett/)
03-12 11:31:09 Info Starting Jackett v0.22.1589
```

### Description

I've read the qbitorrent[ doc ](https://github.com/qbittorrent/search-plugins/wiki/How-to-configure-Jackett-plugin)on how to connect jackett, the troubleshooting page, the wiki, but because my setup there's little to no info on how to fixes my issue.

My setup jackett + qbittorent on synology nas

My file Hierarchy

```
/volume1/
│
├── docker/
│   ├── gluetun/
│   ├── jackett/
│   └── qbittorrent-gluetun/
│       ├── gluetun/
│       ├── qbittorrent/
│           └── nova3/
│               └── engines/
│
└── downloads/
    └── torrents/
        ├── completed/
        ├── incomplete/
        └── torrent/
```

And my container YAML config
```
services:
  gluetun:
   ...

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1027
      - PGID=100
      - TZ=${TZ}
      - WEBUI_PORT=8090
    volumes:
      - /volume1/docker/qbittorrent-gluetun/qbittorrent:/config
      - /volume1/downloads/torrents:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  gluetun-qbittorrent-port-manager:
...

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1027
      - PGID=100
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /volume1/docker/jackett:/config
      - /volume1/downloads/torrents:/torrent
    ports:
      - 9117:9117
    restart: unless-stopped
```

Inside `/volume1/docker/qbittorrent-gluetun/qbittorrent/qBittorrent/nova3/engines/jackett.json`
```
{
    "api_key": "1vx22-----------------------",
    "thread_count": 500,
    "tracker_first": false,
    "url": "http://192.168.1.150:9117"
}
```

And my jackett config

<img width="772" alt="Image" src="https://github.com/user-attachments/assets/541596c5-34b6-45ed-8dd0-122e5f5e6543" />

I am not sure which step I made a mistake, as far as I understand, setting the `jackett.json` would be enough for jackett to connect to qbittorent, yet, its not working at the moment, so I have not idea what's going on.

### Logged Error Messages

```text
Jackett: connection error getting indexer list! Right-click this row.....
*But search engine is showing the correct URL of jackett( 192.168.1.150:9117)
```
