### ISSUE TITLE
[req]: BTSearch

### ISSUE THREAD

**Issue by hsp1020** [Jackett/Jackett#15950]
### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [x] I have checked older issues, open and closed

### Type

Public

### Tracker details

```markdown
- Name: BTSearch
- URL: https://btsearch.19950817.xyz (https://www.btsearch.love/)
- Description: BTSearch is a Public DHT Crawler
- Additional Comments: Might be possible to use API using `content-type=application/json` header, and then we can use `limit=100`.
I assume `hot` is either downloads or seeds.
Strip `?keyword=xxx` from details link.
```

**Comment by garfield69** [comment]
accessing the api directly results is a 403 forbidden
unable to figure out what authorisation is needed to be included, some one else can have a go.

<details>
  <summary>yaml</summary>

```YAML
---
id: btsearch
name: BTSearch
description: "BTSearch is a Public DHT Crawler"
language: en-US
type: public
encoding: UTF-8
links:
  - https://btsearch.19950817.xyz/
legacylinks:
  - https://www.btsearch.love/

caps:
  categorymappings:
    - {id: Other, cat: Other, desc: Other}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: info_category_8000
    type: info_category_8000
  - name: sort
    type: select
    label: Sort requested from site
    default: created_at
    options:
      created_at: created
      seeders: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc

search:
  paths:
    # https://btsearch.19950817.xyz/api/search?keyword=2025&limit=100&offset=0&mode=&time=&sort=created_at&sort_type=asc&size=
    - path: api/search
      response:
        type: json
  allowEmptyInputs: true

  inputs:
    keyword: "{{ if .Keywords }}{{ .Keywords }}{{ else }}{{ .Today.Year }}{{ end }}"
    limit: 100
    offset: 0
    # (blank) Exact, fuzzy
    mode: ""
    # (blank) All, day, week, month, year
    time: ""
    sort: "{{ .Config.sort }}"
    sort_type: "{{ .Config.type }}"
    # (blank) All, 0-100, 100-500, 500-1000, 1000-5000, 5000-
    size: ""

  rows:
    selector: data

  fields:
    category:
      text: Other
    title:
      selector: name
    _id:
      selector: id
    details:
      # https://btsearch.19950817.xyz/en/torrent/313132?keyword=2025
      text: "en/torrent/{{ .Result._id }}"
    infohash:
      selector: hash
    files:
      selector: count
    seeders:
      text: 1
    leechers:
      text: 1
    date:
      # 2023-05-24T04:32:19.716Z
      selector: created_at
    size:
      selector: size
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# JSON
```
