### ISSUE TITLE
[req]: ArabicSource

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#15996]
### Have you read our Contributing Guidelines?

- [x] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [x] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: ArabicSource
- URL: https://arabicsource.net/
- Description: ArabicSource is an ARABIC Private Torrent Tracker for TV / MOVIES
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MR 1.01
- Additional Comments: 
engine: TS Special Edition v.8.0
registration: Invitation only ATM
account retention: The maximum number of days you can stay away from the site is 40 days, and only if you suspend the account, you will get a grace period of 180 days, but you must contact the administration in advance so that this is added to your personal account and you are not exposed to expulsion.
```

**Comment by garfield69** [comment]
It was all going swimmingly, but then I discovered that you need to post a comment to enable downloads, and despite coding a comment.php before block for the download, it appears my comment is not accepted :-( and I cant figure out why.
Will take a break and look afresh another time.

**Comment by garfield69** [comment]
So I suspect that comment.php on this site expects the message to be in the post body, which Cardigann does not provide an option to do, it only allows to url parameters to be built.
So I tried using the TSajaxquickcomment JS, which resolves to using ts_ajax.php, but this needs to know the last comment index number, which I cannot extract since Cardigann does not provide that ability either.
So I do not think I can write this indexer with yaml, it will need a volunteer to write in in C# :-(
The yaml is included below if it is of use for anyone 
<details>
  <summary>ArabicSource.yml</summary>

```yaml
---
id: arabicsource
name: ArabicSource
description: "ArabicSource is an ARABIC Private Torrent Tracker for MOVIES / TV"
language: ar-SA
type: private
encoding: UTF-8
links:
  - https://arabicsource.net/

caps:
  categorymappings:
    - {id: 52, cat: Movies, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies"}
    - {id: 53, cat: Movies/HD, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies 1080p)"}
    - {id: 55, cat: Movies/3D, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies 3D"}
    - {id: 78, cat: Movies/UHD, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies 4K"}
    - {id: 54, cat: Movies/HD, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies 720p"}
    - {id: 56, cat: Movies/DVD, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies DVD"}
    - {id: 58, cat: Movies/HD, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies HDTV1080p"}
    - {id: 57, cat: Movies, desc: "(أفلام الرسوم المدبلجة) dubbed animated movies TVRip"}
    - {id: 72, cat: Movies, desc: "(الأفلام العربية) Arabic films"}
    - {id: 15, cat: Other, desc: "(الحصرية) VIP"}
    - {id: 42, cat: Movies, desc: "(الحصرية أفلام) VIP movies"}
    - {id: 20, cat: TV/Anime, desc: "(الحصرية رسوم) VIP cartoons "}
    - {id: 41, cat: Audio/Video, desc: "(الحصرية مسرحيات) VIP plays"}
    - {id: 21, cat: TV, desc: "(الحصرية مسلسلات) VIP series"}
    - {id: 35, cat: Audio/Video, desc: "(المسرحيات العربية) Arabic plays"}
    - {id: 5, cat: TV, desc: "(المسلسلات العربية) Arabic series"}
    - {id: 81, cat: TV/Foreign, desc: "(المسلسلات العربية الآسيوية) Arabic series Asian"}
    - {id: 79, cat: TV/Foreign, desc: "(المسلسلات العربية التركية) Arabic series Turkish "}
    - {id: 80, cat: TV/Foreign, desc: "(المسلسلات العربية الهندية) Arabic series Hindi"}
    - {id: 69, cat: Movies, desc: "(الوسائط المترجمة) Translated media"}
    - {id: 70, cat: Movies, desc: "(الوسائط المترجمة فلام رسوم) Translated Animated Movies"}
    - {id: 71, cat: Movies, desc: "(الوسائط المترجمة لأفلام الأجنبية) Translated Foreign films"}
    - {id: 77, cat: Movies, desc: "(الوسائط المترجمة الأفلام الهندية) Translated Indian movies"}
    - {id: 86, cat: Movies, desc: "(الوسائط المترجمة مسلسلات الرسوم المترجمة) Translated cartoon series"}
    - {id: 14, cat: TV, desc: "(رمضانيات) Ramadan"}
    - {id: 7, cat: TV/Anime, desc: "(مسلسلات الرسوم المدبلجة) Dubbed cartoon series"}
    - {id: 61, cat: TV/Anime, desc: "(مسلسلات الرسوم المدبلجة) Dubbed cartoon series1080p"}
    - {id: 62, cat: TV/Anime, desc: "(مسلسلات الرسوم المدبلجة) Dubbed cartoon series 720p"}
    - {id: 63, cat: TV/Anime, desc: "(مسلسلات الرسوم المدبلجة) Dubbed cartoon series DVD"}
    - {id: 65, cat: TV/Anime, desc: "(مسلسلات الرسوم المدبلجة) Dubbed cartoon series HDTV1080p"}
    - {id: 64, cat: TV/Anime, desc: "(مسلسلات الرسوم المدبلجة) Dubbed cartoon series TVRip"}
    - {id: 31, cat: Other, desc: "(وسائط منوعات) Miscellaneous media"}
    - {id: 67, cat: Other, desc: "(وسائط منوعات إسلاميات) Miscellaneous media Islamic Studies"}
    - {id: 32, cat: Other, desc: "(وسائط منوعات تربوي) Miscellaneous media Educational"}
    - {id: 76, cat: Audio, desc: "(وسائط منوعات صوتيات) Miscellaneous media Phonetics"}
    - {id: 68, cat: TV/Anime, desc: "(وسائط منوعات كرتون كلاسيك) Miscellaneous media Classic Cartoon"}
    - {id: 66, cat: TV/Documentary, desc: "(وسائط منوعات وثائقيات) Miscellaneous media Documentaries"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: thankyou
    type: text
    label: Thank You Comment
  - name: info
    type: info
    label: Thank you comment
    default: This site requires you to leave a Thank You comment before you can download. Enter your personalised comment above.
  - name: freeleech
    type: checkbox
    label: Filter freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: added
    options:
      added: created
      seeders: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: vip
    type: checkbox
    label: Include VIP results
    default: false
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>40</b> on your account profile. The Default is <i>15</i>.
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "The maximum number of days you can stay away from the site is 40 days, and only if you suspend the account, you will get a grace period of 180 days, but you must contact the administration in advance so that this is added to your personal account and you are not exposed to expulsion."

login:
  path: login.php
  method: form
  form: form[action="takelogin.php"]
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    logout: ""
  error:
    - selector: table:contains("error has occured")
    - selector: table:contains("Incorrect username or password")
  test:
    path: index.php
    selector: a[href*="/logout.php?logouthash="]

download:
# does not work :-(, maybe message needs to be in post body which cardigann can't do.
#  before:
#    path: comment.php
#    method: post
#    inputs:
#      action: add
#      tid: "{{ .DownloadUri.Query.id }}"
#      message: "{{ .Config.thankyou }}"
#      submit: Save
#  before:
    # <input type="button" class="button" value="Submit" name="quickcomment" id="quickcomment" onclick="javascript:TSajaxquickcomment('8618', '2');"/>
    # the JS resolves to a call to the path below with the input parms
#    path: ts_ajax.php
#    method: post
#    inputs:
#      ajax_quick_comment: 1
#      id: "{{ .DownloadUri.Query.id }}"
#      lcid: the last comment index number, in the example above its 2, but I've no way to extract it :-(
#      text: "{{ .Config.thankyou }}"
  selectors:
    # the download is not allowed unless a comment is posted on the details page
    - selector: a[href*="download.php?id="]
      attribute: href

search:
  paths:
    - path: browse.php
      method: post
  keywordsfilters:
    - name: re_replace
      args: ["[\\s]+", "%"]
  inputs:
    do: search
    keywords: "{{ if .Query.IMDBID }}{{ .Query.IMDBID }}{{ else }}{{ .Keywords }}{{ end }}"
    # t_name, t_description, t_both, t_uploader, t_genre
    search_type: "{{ if .Query.IMDBID }}t_genre{{ else }}t_name{{ end }}"
    # does not support multi category searching so defaulting to all.
    category: 0
    # yes, no
    include_dead_torrents: yes
    sort: "{{ if .Config.freeleech }}free{{ else }}{{ .Config.sort }}{{ end }}"
    order: "{{ if .Config.freeleech }}asc{{ else }}{{ .Config.type }}{{ end }}"

  rows:
    selector: "table.sortable tr:has(a[href*=\"download.php?id=\"]){{ if .Config.vip }}{{ else }}:not(:has(a[href$=\"&category=15\"])):not(:has(a[href$=\"&category=20\"])):not(:has(a[href$=\"&category=21\"])):not(:has(a[href$=\"&category=41\"])):not(:has(a[href$=\"&category=42\"])){{ end }}{{ if .Config.freeleech }}:has(img[src$=\"/freedownload.gif\"]){{ else }}{{ end }}"

  fields:
    category:
      selector: a[href*="?category="]
      attribute: href
      filters:
        - name: querystring
          args: category
    title:
      selector: a[href*="details.php?id="]
    details:
      selector: a[href*="details.php?id="]
      attribute: href
    download:
      selector: a[href*="details.php?id="]
      attribute: href
    poster:
      selector: img[src*="/torrents/images/"]
      attribute: src
    date:
      selector: td:nth-child(2)
      # auto adjusted by site account profile
      filters:
        - name: regexp
          args: "(\\d{2}-\\d{2}-\\d{4} \\d{2}:\\d{2})"
        - name: dateparse
          args: "dd-MM-yyyy HH:mm"
    size:
      selector: td:nth-last-child(5)
    grabs:
      selector: td:nth-last-child(4)
    seeders:
      selector: td:nth-last-child(3)
    leechers:
      selector: td:nth-last-child(2)
    downloadvolumefactor:
      case:
        img[src$="/freedownload.gif"]: 0
        img[src$="/silverdownload.gif"]: 0.5
        "*": 1
    uploadvolumefactor:
      case:
        img[src$="/x2.gif"]: 2
        "*": 1
    minimumratio:
      text: 1.05
# TS Special Edition v.8.0
```
