### ISSUE TITLE
[req]: Cookies for HD-Torrents indexer

### ISSUE THREAD

**Issue by alekz88** [Jackett/Jackett#15998]
### Is there already a request for your feature?

- [x] I have checked older issues, open and closed

### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

Please add a Cookies field (or a generic Cookie request-header placeholder) to the HD-Torrents indexer so that users behind Cloudflare can paste cf_clearance and other session cookies. FlareSolverr is depreciated on this site.

**Comment by garfield69** [comment]
Yes all the hd-torrents domains are using cloudflare.
But before I invest time and effort creating a cookie version of this C# indexer, I should note that the indexer is working for me using docker Jackett in combination with docker 21hsmw/flaresolverr:nodriver
Is this not an option for you?

**Comment by alekz88** [comment]
> Yes all the hd-torrents domains are using cloudflare. But before I invest time and effort creating a cookie version of this C# indexer, I should note that the indexer is working for me using docker Jackett in combination with docker 21hsmw/flaresolverr:nodriver Is this not an option for you?

Thank you! I believe that using cookies allows for a more straightforward and transparent approach, enabling users to manage their sessions directly without relying on additional layers of complexity. This method also provides greater control over the authentication process, which is particularly important for maintaining access to long term.I believe that adding a Cookies field will greatly enhance the usability of this indexer for users who encounter Cloudflare challenges. 

Thank you for considering this request!

**Comment by garfield69** [comment]
That sounds fine in principle, but the whole point of the cloudflare challenge is to satisfy the site that you are a human and not automation.
For most sites, cloudflare can generate a challenge quite often, depending on the number of incoming requests that exceed certain thresholds. For instance, when a site is on high alert due to DDoS attacks, the rate of how often a query is chosen to be challenged can climb significantly.
Which can make it impractical to use the cookie method, because it is ridiculous to manually fetch session cookies from a browser and paste it into the indexer config every time you want to use the indexer.

I will clone the indexer and create a test version that uses cookies.
However I will not publish it until I can be satisfied that the cookies will last at least 6 hours before cloudflare forces you to refresh.

**Comment by ilike2burnthing** [comment]
> I should note that the indexer is working for me using docker Jackett in combination with docker `21hsmw/flaresolverr:nodriver`
**Is this not an option for you?**

@alekz88 have you tried that version of FlareSolverr?

We can't just create cookie versions of every indexer for which the site uses CF, especially when there's a working fork of FlareSolverr (at least 2 actually), and the cookies will need constantly replaced.

**Comment by alekz88** [comment]
> That sounds fine in principle, but the whole point of the cloudflare challenge is to satisfy the site that you are a human and not automation. For most sites, cloudflare can generate a challenge quite often, depending on the number of incoming requests that exceed certain thresholds. For instance, when a site is on high alert due to DDoS attacks, the rate of how often a query is chosen to be challenged can climb significantly. Which can make it impractical to use the cookie method, because it is ridiculous to manually fetch session cookies from a browser and paste it into the indexer config every time you want to use the indexer.
> 
> I will clone the indexer and create a test version that uses cookies. However I will not publish it until I can be satisfied that the cookies will last at least 6 hours before cloudflare forces you to refresh.

Thank you! I completely understand why you want to be sure the cookie approach is usable in practice. From my side, a cookie-based variant would still be the preferred solution because running FlareSolverr + headless-Chrome inside TrueNAS adds 300-400 MB RAM and extra maintenance that I’d rather avoid for just one tracker. Even if Cloudflare occasionally shortens the lifetime, I’m fine refreshing the cookie manually when that happens, it’s still easier for my setup than keeping another container alive.

**Comment by alekz88** [comment]
> Switching to cookies will affect other users, so wanting to not run an extra container isn't really a good argument IMO.

IMO it doesn't make sense to make an extra container mandatory when there is a simpler solution with cookies (can't both options coexist?).

**Comment by ilike2burnthing** [comment]
The idea of tools like Jackett and Prowlarr is to aid with automation tools like Sonarr and Radarr. If you have to update the cookies of your indexers manually every few hours to days, you're defeating that purpose.

While for you it may be one indexer, if we do it for your case, why wouldn't we do it for the dozens of other indexers which require it? That then leads to a lot of extra unnecessary work when it comes to maintaining these duplicate indexers.

**Comment by garfield69** [comment]
It is clear from the team feedback that I should not continue working on this.
If the indexer had been written in yaml I would have suggested making a personal copy of it and posting it in your local alternate indexers folder with the cookie login coded.
Unfortunately the indexer is written in C# (because the site alters the results page depending on user classes and the yaml code does not have the logic to easily cope) so you cannot have a personal copy of this indexer.

**Comment by garfield69** [comment]
I managed to convert the C# indexer to yaml without loosing any functionality. #16002 
Which means you can now use a private cookie version if you want.
- identify your private Indexer folder by starting Jackett, scrolling to the bottom of the log and looking for `Loading Cardigann indexers from:`. Use the first folder in the list
- open a plain text editor and copy/paste the code below
- save as  as hdtorrentscookie to your private Indexer folder
- restart Jackett and have at it.

<details>
  <summary>hdtorrentscookie </summary>

```yaml
---
id: hdtorrentscookie
name: HD-Torrents Cookie
description: "HD-Torrents (HDT) is a Private Torrent Tracker for HD MOVIES / TV / MUSIC / 3X"
language: en-US
type: private
encoding: UTF-8
links:
  - https://hdts.ru/
  - https://hd-torrents.org/
  - https://hd-torrents.net/
  - https://hd-torrents.me/

caps:
  categorymappings:
    - {id: 70, cat: Movies/BluRay, desc: "Movie/UHD/Blu-Ray"}
    - {id: 1, cat: Movies/BluRay, desc: "Movie/Blu-Ray"}
    - {id: 71, cat: Movies/UHD, desc: "Movie/UHD/Remux"}
    - {id: 2, cat: Movies/HD, desc: "Movie/Remux"}
    - {id: 5, cat: Movies/HD, desc: "Movie/1080p/i"}
    - {id: 3, cat: Movies/HD, desc: "Movie/720p"}
    - {id: 64, cat: Movies/UHD, desc: "Movie/2160p"}
    - {id: 63, cat: Audio, desc: "Movie/Audio Track"}
    - {id: 72, cat: TV/UHD, desc: "TV Show/UHD/Blu-ray"}
    - {id: 59, cat: TV/HD, desc: "TV Show/Blu-ray"}
    - {id: 73, cat: TV/UHD, desc: "TV Show/UHD/Remux"}
    - {id: 60, cat: TV/HD, desc: "TV Show/Remux"}
    - {id: 30, cat: TV/HD, desc: "TV Show/1080p/i"}
    - {id: 38, cat: TV/HD, desc: "TV Show/720p"}
    - {id: 65, cat: TV/UHD, desc: "TV Show/2160p"}
    - {id: 44, cat: Audio, desc: "Music/Album"}
    - {id: 61, cat: Audio/Video, desc: "Music/Blu-Ray"}
    - {id: 62, cat: Audio/Video, desc: "Music/Remux"}
    - {id: 57, cat: Audio/Video, desc: "Music/1080p/i"}
    - {id: 45, cat: Audio/Video, desc: "Music/720p"}
    - {id: 66, cat: Audio/Video, desc: "Music/2160p"}
    - {id: 58, cat: XXX, desc: "XXX/Blu-ray"}
    - {id: 78, cat: XXX, desc: "XXX/Remux"}
    - {id: 74, cat: XXX, desc: "XXX/UHD/Blu-ray"}
    - {id: 48, cat: XXX, desc: "XXX/1080p/i"}
    - {id: 47, cat: XXX, desc: "XXX/720p"}
    - {id: 67, cat: XXX, desc: "XXX/2160p"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]
    music-search: [q]

settings:
  - name: cookie
    type: text
    label: Cookie
  - name: info_cookie
    type: info_cookie
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: data
    options:
      data: created
      size: size
      seeds: seeders
      filename: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>100</b> on your account profile.
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "If you do not log in for 50 days, your account will be disabled for inactivity. If you are VIP you won't be disabled until the VIP period is over."
  - name: info_flaresolverr
    type: info_flaresolverr

login:
  method: cookie
  inputs:
    cookie: "{{ .Config.cookie }}"
  test:
    path: /
    selector: a[href^="logout.php?check_hash="]

search:
  paths:
    - path: torrents.php
  inputs:
    $raw: "{{ range .Categories }}category[]={{.}}&{{end}}"
    search: "{{ if .Query.IMDBID }}{{ .Query.IMDBID }}{{ else }}{{ .Keywords }}{{ end }}"
    # 0 All, 1 ActiveOnly, 2 DeadOnly, 5 Free, 6 50, 7 25, 8 75
    active: "{{ if .Config.freeleech }}5{{ else }}0{{ end }}"
    # 0 title, 3 title and descr, 1 genre, 2 imdb
    options: 0
    order: "{{ .Config.sort }}"
    by: "{{ .Config.type }}"

  keywordsfilters:
    # manually url encode parenthesis to prevent "hacking" detection, remove . as not used in titles
    - name: re_replace
      args: ["\\.", " "]
    - name: re_replace
      args: ["\\(", "%28"]
    - name: re_replace
      args: ["\\)", "%29"]

  rows:
    selector: "table.mainblockcontenttt > tbody > tr:has(td.mainblockcontent):not(:first-of-type){{ if .Config.freeleech }}:has(img[src=\"images/sign_free.png\"]){{ else }}{{ end }}"

  fields:
    _has_freeleech:
      case:
        ":root table.navus tr td:nth-child(2):contains(\" VIP\")": yes
        ":root table.navus tr td:nth-child(2):contains(\" Uploader\")": yes
        ":root table.navus tr td:nth-child(2):contains(\" HD Internal\")": yes
        ":root table.navus tr td:nth-child(2):contains(\" Moderator\")": yes
        ":root table.navus tr td:nth-child(2):contains(\" Administrator\")": yes
        ":root table.navus tr td:nth-child(2):contains(\" Owner\")": yes
        "*": no
    category:
      selector: a[href^="torrents.php?category="]
      attribute: href
      filters:
        - name: querystring
          args: category
    title:
      selector: a[href^="details.php?id="]
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php?id="]
      attribute: href
    imdbid:
      selector: a[href*="imdb.com/title/tt"]
      attribute: href
    genre:
      selector: td:nth-child(3) span
    description:
      text: "{{ .Result.genre }}"
    date:
      # auto adjusted by site account profile
      selector: td:nth-child(7)
      filters:
        - name: dateparse
          args: "HH:mm:ss  dd/MM/yyyy"
    size:
      selector: td:nth-child(8)
    seeders:
      selector: td:nth-last-child(3)
    leechers:
      selector: td:nth-last-child(2)
    grabs:
      selector: td:nth-last-child(1)
    downloadvolumefactor_freeleech:
      case:
        img[src$="no_ratio.png"]: 0
        img[src$="free.png"]: 0
        img[src$="50.png"]: 0.5
        img[src$="25.png"]: 0.75
        img[src$="75.png"]: 0.25
        "*": 1
    downloadvolumefactor:
      text: "{{ if eq .Result._has_freeleech \"yes\" }}0{{ else }}{{ .Result.downloadvolumefactor_freeleech }}{{ end }}"
    uploadvolumefactor:
      case:
        img[src$="no_ratio.png"]: 0
        "*": 1
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 2 days (as seconds = 2 x 24 x 60 x 60)
      text: 172800
# engine n/a
```
