### ISSUE TITLE
[Req] GayTorrent.ru

### ISSUE THREAD

**Issue by PoshSparks** [Jackett/Jackett#1663]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

Jackett version:  
Mono version (if not using Windows):  

-------------------------------
NOTE: this is primarily an Adult site for gay men... 

However, does provide ebooks, TV and Movies (non-porn) of gay interests... 
I have invitations if required... any assistance would be gratefully appreciated... 

I have attempted to create the yml file (kinda created, copied from waffle.yml... seemed the most similar)...  
Though technical by nature, I am no programmer... and am far out of my league... 

```
  site: GayTorrent-ru
  name: GayTorrent-ru
  description: "World largest gay porn library for free with a stunning forum and 24/7 Chat"
  language: en-us
  type: private
  encoding: UTF-8
  links:
    - https://gaytorrent.ru/

  caps:
    categorymappings:
     {id:62 , cat: XXX , desc:"Amateur"}
     {id:29 , cat: XXX , desc:"Anal"}
     {id:46 , cat: XXX , desc:"Anime Games"}
     {id:30 , cat: XXX , desc:"Asian"}
     {id:43 , cat: XXX , desc:"Bareback"}
     {id:19 , cat: XXX , desc:"BDSM"}
     {id:17 , cat: XXX , desc:"Bears"}
     {id:44 , cat: XXX , desc:"Black"}
     {id:50 , cat: Books/Magazines , desc:"Books &amp; Magazines"}
     {id:9 , cat: XXX , desc:"Chubbies"}
     {id:7 , cat: XXX , desc:"Clips"}
     {id:48 , cat: Books/Comics  , desc:"Comic &amp; Yaoi"}
     {id:5 , cat: XXX , desc:"Daddies / Sons"}
     {id:34 , cat: XXX , desc:"Fetish"}
     {id:27 , cat: XXX , desc:"Grey / Older"}
     {id:32 , cat: XXX , desc:"Group-Sex"}
     {id:63 , cat: XXX , desc:"Homemade"}
     {id:12 , cat: XXX , desc:"Hunks"}
     {id:33 , cat: XXX , desc:"Images"}
     {id:53 , cat: XXX , desc:"Interracial"}
     {id:57 , cat: XXX , desc:"Jocks"}
     {id:35 , cat: XXX , desc:"Latino"}
     {id:36 , cat: XXX , desc:"Mature"}
     {id:58 , cat: PC , desc:"Media Programs"}
     {id:37 , cat: XXX , desc:"Member"}
     {id:54 , cat: XXX , desc:"Middle Eastern"}
     {id:38 , cat: XXX , desc:"Military"}
     {id:39 , cat: XXX , desc:"Oral-Sex"}
     {id:47 , cat: XXX , desc:"Shemale"}
     {id:56 , cat: XXX , desc:"Softcore"}
     {id:40 , cat: XXX , desc:"Solo"}
     {id:45 , cat: XXX , desc:"Themed Movie"}
     {id:1 , cat: TV , desc:"TV / Episodes"}
     {id:41 , cat: XXX , desc:"Twinks"}
     {id:42 , cat: XXX , desc:"Vintage"}
     {id:51 , cat: XXX , desc:"Voyeur"}
     {id:65 , cat: XXX , desc:"Wrestling and Sports"}
     {id:28 , cat: XXX , desc:"Youngblood"}
    modes:
      search: [q]

  login:
    path: login_check
    method: post
    inputs:
      _username: "{{ .Config.username }}"
      _password: "{{ .Config.password }}"
    test:
      path: index.php

  download:
    selector: a[href^="download.php/"]

  search:
    path: browse.php
    inputs:
      $raw: "{{range .Categories}}filter_cat[{{.}}]=1&{{end}}"
      q: "{{ .Query.Keywords }}"
    rows:
      selector: table#browsetable > tbody > tr:has(a[href^="/details.php?id="])
    fields:
      category:
        selector: a[href^="/browse.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: c
      title:
        selector: td:nth-child(2)
      download:
        selector: a[href^="/details.php?id="]
        attribute: href
        filters:
          - name: replace
            args: ["/details.php?id=", "/download.php?id="]
      details:
        selector: a[href^="/details.php?id="]
        attribute: href
      grabs:
        selector: td:nth-child(7)
        filters:
          - name: regexp
            args: ([\d,]+)
      files:
        selector: td:nth-child(3)
      size:
        selector: td:nth-child(6)
      seeders:
        selector: td:nth-child(8)
      leechers:
        selector: td:nth-child(9)
      date:
        selector: td:nth-child(5)
        filters:
          - name: dateparse
            args: "2 April 2017 +05:50"
      downloadvolumefactor:
        case:
          "img[title=\"Free Torrent!\"]": "0"
          "*": "1"
      uploadvolumefactor:
        case:
          "*": "1"
```

**Comment by JigSawFr** [comment]
Thank you for your submit, but as it's a invite only tracker, we need an invite to test our work.

**Comment by PoshSparks** [comment]
sure thing, just let me know an email address to send the invite....

**Comment by JigSawFr** [comment]
@PoshSparks Have you tested your definition with success ? If so, can you provide homepage "test" success and 2 manual search query (with one category, and all for second). Please attach logs.
As I will not use this account, you will loose one invite. (and I don't know tracker policy about invitee)

**Comment by thebluepotato** [comment]
@PoshSparks If you still need someone to test or fix it (I've had my share of trials with the KickAssTorrents definition), you can send an invite my way (and I'd actually use the account afterwards too 😇)

**Comment by PoshSparks** [comment]
apologies... I've been unavailable for the last couple of days...   JigSawFr... I'll work on getting some testing completed shortly.. 

note, I don't mind sparing one or two invites at this time...  as I don't send many invites out to begin with...:)  Just let me know an email address to send an invite to..

**Comment by thebluepotato** [comment]
@PoshSparks my email : jonas[dot]zaugg[at]yahoo[dot]com

**Comment by PoshSparks** [comment]
invite sent...

**Comment by PoshSparks** [comment]
also, I have an update...

did do some testing... got further this time... found some syntax issues... I am now able to add the indexer... alas, can't search anything... 
```
  site: GayTorrent-ru
  name: GayTorrent-ru
  description: "World largest gay porn library for free with a stunning forum and 24/7 Chat"
  language: en-us
  type: private
  encoding: UTF-8
  links:
    - https://www.gaytorrent.ru/

  caps:
    categorymappings:
     - {id: 62 , cat: XXX , desc: "Amateur"}
     - {id: 29 , cat: XXX , desc: "Anal"}
     - {id: 46 , cat: XXX , desc: "Anime Games"}
     - {id: 30 , cat: XXX , desc: "Asian"}
     - {id: 43 , cat: XXX , desc: "Bareback"}
     - {id: 19 , cat: XXX , desc: "BDSM"}
     - {id: 17 , cat: XXX , desc: "Bears"}
     - {id: 44 , cat: XXX , desc: "Black"}
     - {id: 50 , cat: Books/Magazines , desc: "Books &amp; Magazines"}
     - {id: 9 , cat: XXX , desc: "Chubbies"}
     - {id: 7 , cat: XXX , desc: "Clips"}
     - {id: 48 , cat: Books/Comics  , desc: "Comic &amp; Yaoi"}
     - {id: 5 , cat: XXX , desc: "Daddies / Sons"}
     - {id: 34 , cat: XXX , desc: "Fetish"}
     - {id: 27 , cat: XXX , desc: "Grey / Older"}
     - {id: 32 , cat: XXX , desc: "Group-Sex"}
     - {id: 63 , cat: XXX , desc: "Homemade"}
     - {id: 12 , cat: XXX , desc: "Hunks"}
     - {id: 33 , cat: XXX , desc: "Images"}
     - {id: 53 , cat: XXX , desc: "Interracial"}
     - {id: 57 , cat: XXX , desc: "Jocks"}
     - {id: 35 , cat: XXX , desc: "Latino"}
     - {id: 36 , cat: XXX , desc: "Mature"}
     - {id: 58 , cat: PC , desc: "Media Programs"}
     - {id: 37 , cat: XXX , desc: "Member"}
     - {id: 54 , cat: XXX , desc: "Middle Eastern"}
     - {id: 38 , cat: XXX , desc: "Military"}
     - {id: 39 , cat: XXX , desc: "Oral-Sex"}
     - {id: 47 , cat: XXX , desc: "Shemale"}
     - {id: 56 , cat: XXX , desc: "Softcore"}
     - {id: 40 , cat: XXX , desc: "Solo"}
     - {id: 45 , cat: XXX , desc: "Themed Movie"}
     - {id: 1 , cat: TV , desc: "TV / Episodes"}
     - {id: 41 , cat: XXX , desc: "Twinks"}
     - {id: 42 , cat: XXX , desc: "Vintage"}
     - {id: 51 , cat: XXX , desc: "Voyeur"}
     - {id: 65 , cat: XXX , desc: "Wrestling and Sports"}
     - {id: 28 , cat: XXX , desc: "Youngblood"}
    modes:
      search: [q]

  login:
    path: login_check
    method: post
    inputs:
      _username: "{{ .Config.username }}"
      _password: "{{ .Config.password }}"
    test:
      path: index.php

  download:
    selector: a[href^="download.php/"]

  search:
    path: browse.php
    inputs:
      $raw: "{{range .Categories}}filter_cat[{{.}}]=1&{{end}}"
      q: "{{ .Query.Keywords }}"
    rows:
      selector: table#browsetable > tbody > tr:has(a[href^="/details.php?id="])
    fields:
      category:
        selector: a[href^="/browse.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: c
      title:
        selector: td:nth-child(2)
      download:
        selector: a[href^="/details.php?id="]
        attribute: href
        filters:
          - name: replace
            args: ["/details.php?id=", "/download.php?id="]
      details:
        selector: a[href^="/details.php?id="]
        attribute: href
      grabs:
        selector: td:nth-child(7)
        filters:
          - name: regexp
            args: ([\d,]+)
      files:
        selector: td:nth-child(3)
      size:
        selector: td:nth-child(6)
      seeders:
        selector: td:nth-child(8)
      leechers:
        selector: td:nth-child(9)
      date:
        selector: td:nth-child(5)
        filters:
          - name: dateparse
            args: "2 April 2017 +05:50"
      downloadvolumefactor:
        case:
          "img[title=\"Free Torrent!\"]": "0"
          "*": "1"
      uploadvolumefactor:
        case:
          "*": "1"

```

**Comment by thebluepotato** [comment]
Yeah I'm guessing the login part isn't working in your definition here. I'll try to fix it tonight!
EDIT: @JigSawFr as I'm quite nearly done with the working definition, I hope you haven't begun yourself (so we don't do the same work twice).

**Comment by thebluepotato** [comment]
@PoshSparks I've added PR #1689. It works flawlessly for what I've tested but since you seem to know the site better, please test it too and report on #1689 what doesn't work.

**Comment by PoshSparks** [comment]
@thebluepotato,

    gave an update... outside of cleaning up some of my category mappings, looks good to go... 

fyi, i have one more tracker, similar to this one, if your interested... I do not believe an invite is needed as it appears to be open registration...   let me know, I will submit a separate ticket for it..

**Comment by thebluepotato** [comment]
@PoshSparks Did the cleanups you asked for, now it's pending approval.
Regarding the other tracker: might it be Gay-Torrents.net? In that case, please check out #1690.

**Comment by PoshSparks** [comment]
your awesome! that was it!..  :)

**Comment by garfield69** [comment]
https://www.gaytor.rent/ > cloudflare A timeout occurred Error code 524

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
site on new engine, indexer requires updating

**Comment by garfield69** [comment]
v0.24.2045

**Comment by ilike2burnthing** [comment]
In case we need to switch to `grid` at some point the future (only down side is it's missing `description`):

<details>
<summary>gaytorrentru - grid</summary>

```yml
---
id: gaytorrentru
name: GAYtorrent.ru
description: "GayTorrent.ru is a Private Torrent Tracker for GAY 3X"
language: en-US
type: private
encoding: UTF-8
links:
  - https://www.gaytor.rent/
legacylinks:
  - https://www.gaytorrent.ru/

settings:
  - name: cookie
    type: text
    label: Cookie
  - name: info_cookie
    type: info_cookie
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: info_hidden
    type: info
    label: "Hidden categories"
    default: "Results for categories hidden in account profile will not be visible."
  - name: info_limit
    type: info
    label: "Download Ratio"
    default: "GayTorrent.ru has a daily download slot limit as defined by your ratio, your uploads, your donations, etc. If downloads <b>fail</b> then you have exceeded your allocation. Access the web site to find more info <a href=\"https://www.gaytor.rent/rationator.php\" target=\"_blank\">here</a>"
  - name: sort
    type: select
    label: Sort requested from site
    default: added
    options:
      added: created
      seeds: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "Unused accounts (both upload and download are zero) are disabled by the system after 60 days of no login. Used accounts with prior activity (upload and/or download) are disabled by the system after 240 days of no login."

caps:
  categorymappings:
    - {id: 69, cat: XXX, desc: "AI"}
    - {id: 62, cat: XXX, desc: "Amateur"}
    - {id: 29, cat: XXX, desc: "Anal"}
    - {id: 46, cat: XXX, desc: "Anime Games"}
    - {id: 30, cat: XXX, desc: "Asian"}
    - {id: 43, cat: XXX, desc: "Bareback"}
    - {id: 19, cat: XXX, desc: "BDSM"}
    - {id: 17, cat: XXX, desc: "Bears"}
    - {id: 59, cat: XXX, desc: "Bisexual"}
    - {id: 44, cat: XXX, desc: "Black"}
    - {id: 50, cat: Books, desc: "Books & Magazines"}
    - {id: 9, cat: XXX, desc: "Chubbies"}
    - {id: 7, cat: XXX, desc: "Clips"}
    - {id: 48, cat: Books/Comics, desc: "Comic & Yaoi"}
    - {id: 5, cat: XXX, desc: "Daddies / Sons"}
    - {id: 67, cat: XXX, desc: "Dildos"}
    - {id: 66, cat: XXX, desc: "Fan Sites"}
    - {id: 34, cat: XXX, desc: "Fetish"}
    - {id: 68, cat: XXX, desc: "Fisting"}
    - {id: 27, cat: XXX, desc: "Grey / Older"}
    - {id: 32, cat: XXX, desc: "Group-Sex"}
    - {id: 63, cat: XXX, desc: "Homemade"}
    - {id: 12, cat: XXX, desc: "Hunks"}
    - {id: 33, cat: XXX/ImageSet, desc: "Images"}
    - {id: 53, cat: XXX, desc: "Interracial"}
    - {id: 57, cat: XXX, desc: "Jocks"}
    - {id: 35, cat: XXX, desc: "Latino"}
    - {id: 36, cat: XXX, desc: "Mature"}
    - {id: 58, cat: PC, desc: "Media Programs"}
    - {id: 37, cat: XXX, desc: "Member"}
    - {id: 54, cat: XXX, desc: "Middle Eastern"}
    - {id: 38, cat: XXX, desc: "Military"}
    - {id: 39, cat: XXX, desc: "Oral-Sex"}
    - {id: 64, cat: XXX, desc: "Scat"}
    - {id: 56, cat: XXX, desc: "Softcore"}
    - {id: 40, cat: XXX, desc: "Solo"}
    - {id: 61, cat: XXX, desc: "Straight older"}
    - {id: 60, cat: XXX, desc: "Straight younger"}
    - {id: 45, cat: Movies, desc: "Themed Movie"}
    - {id: 47, cat: XXX, desc: "Trans"}
    - {id: 70, cat: XXX, desc: "Trans/FTM"}
    - {id: 1, cat: TV, desc: "TV / Episodes"}
    - {id: 41, cat: XXX, desc: "Twinks"}
    - {id: 42, cat: XXX, desc: "Vintage"}
    - {id: 51, cat: XXX, desc: "Voyeur"}
    - {id: 65, cat: XXX, desc: "Wrestling and Sports"}
    - {id: 28, cat: XXX, desc: "Youngblood"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    book-search: [q]

login:
  # using cookie method because login page has embedded Cloudflare turnstile
  method: cookie
  inputs:
    cookie: "{{ .Config.cookie }}"
  test:
    path: my.php
    selector: a[href$="/logout.php"]

search:
  paths:
    - path: search.php
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    search: "{{ .Keywords }}"
    view: grid
    # 0 active, 1 both, 2 dead
    incldead: 1
    # where to search: name,     descr,    filename, freeleech only, wishlist
    # where to search: inname=1, indesc=1, infn=1,   infl=1,         inbook=1
    inname: 1
    infl: "{{ if .Config.freeleech }}1{{ else }}{{ end }}"
    page: 0
    orderby: "{{ .Config.sort }}"
    sort: "{{ .Config.type }}"

  headers:
    Referer: ["{{ .Config.sitelink }}search.php?view=grid"]

  rows:
    selector: div.dc-search-grid > article

  fields:
    category:
      selector: span.dc-grid-main-cat
      attribute: data-cat-id
    title:
      selector: a.dc-grid-card-title
    title_download:
      text: "{{ .Result.title }}"
      filters:
        - name: urlencode
    details:
      selector: a.dc-grid-card-title
      attribute: href
    _id:
      selector: a.dc-grid-card-title
      attribute: href
      filters:
        - name: querystring
          args: id
    download:
      # turn href="download.php/0738d444362fa610a08fb87b5c1bec798ca1731adbf3175b/GUARATORO.torrent
      # into href="/download.php?id=0738d444362fa610a08fb87b5c1bec798ca1731adbf3175b&n=GUARATORO.torrent&p=dodownload
      text: "download.php?id={{ .Result._id }}&n={{ .Result.title_download }}.torrent&p=dodownload"
    poster:
      # //pic.gaytor.rent/tpics/2026/24/33749943.jpg
      selector: img.dc-grid-card-slide
      attribute: src
    grabs:
      selector: span.dc-grid-card-snat
    files:
      selector: span.dc-grid-card-files
    size:
      selector: span.dc-grid-card-size
    seeders:
      selector: span.dc-grid-card-seeders
    leechers:
      selector: span.dc-grid-card-leechers
    date:
      selector: span.dc-grid-card-age
      attribute: title
      filters:
        - name: replace
          args: ["Uploaded: ", ""]
        - name: append
          args: " +02:00" # EET
        - name: dateparse
          args: "yyyy-MM-dd HH:mm:ss zzz"
    downloadvolumefactor:
      case:
        span.dc-grid-card-fl: 0
        "*": 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 1.0
# engine n/a

```
</details>
