### ISSUE TITLE
[Enhancement REQ] Additional Cardigann features

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#2036]
First off, a caveat: I am still learning about how to write Cardigann definitions, so it is possible that the following could actually be achieved now with Cardigann statements, and I just need to be shown how. :smile: 

I have come across several instances when adding new Cardigann definitions, where the sites I am attempting to support have methods that I cannot currently support via Cardigann.    
I believe with the addition of a few enhancements I could support these sites with Cardigann instead of having to resort to c#.

Scenario 1: 
A site uses a unique key to indicate that the search does not contain any Categories, or that all categories should be used during the search without having to list all of them in the search parameters.
For instance, gfxnext.org uses `f[]=-1` to indicate that the search should include all categories.
It would be useful if I could code something like:
```yaml
  search:
    paths:
      - path: /tracker.php
        method: post
    inputs:
      "f[]": "{{ if .Query.hasCategories }}{{ range .Categories }}{{.}}{{ end }}{{ else }}-1{{ end }}"
```

Scenario 2:
A site accepts only one category for its searches. The use of `range .Category` automatically iterates across all the categories the user has selected.
It would be useful if I could limit  the number of categories processed by the `range` command.
For example, suppose I want to only use the first category if present and ignore any others selected:
```yaml
  search:
    paths:
      - path: /tracker.php
    inputs:
      $raw: "{{range .Categories, 1}}c={{.}}&{{end}}"
```

Feedback welcome, especially if you know how to solve these issues within the existing Cardigann code structure :-)
IF the consensus is that it is not worth the effort, then I guess I would have to resort to providing the definitions for these sites in c# :disappointed:
