### ISSUE TITLE
[bug] settings password 'type' dependant on 'label' ?!?

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#2114]
I'm coding a Spanish definition, and set up a settings block as follows:
```yaml
  settings:
    - name: username
      type: text
      label: "Nombre de usuario (Username)"
    - name: password
      type: password
      label: "Contraseña (Password)"
```

However, when the form is displayed, the password type is *text* and not *password*
![image](https://user-images.githubusercontent.com/6933240/32687681-c7bbd138-c726-11e7-80a3-50f9bee6c4f3.png)

The password type is only set to *password* when the settings block is like this:
```yaml
  settings:
    - name: username
      type: text
      label: Username
    - name: password
      type: password
      label: Password
```
then and only then is the password type set correctly
![image](https://user-images.githubusercontent.com/6933240/32687711-7296ec50-c727-11e7-9eef-3a7bb4c59ace.png)

It appears to me that the password *type* is dependant on the *label* being set to *Password* ?
