### ISSUE TITLE
[B2S-Share & Speed-Share] YAML Conditional

### ISSUE THREAD

**Issue by DarkSupremo** [Jackett/Jackett#2169]
Related to this pull request: #2168 

This changes (with same regex) would be needed on B2S-Share and Speed-Share too, but i saw that they are coded in yml.

Would be needed something like that:

```yml
title:
    selector: a[href^="torrents-details.php?id="]
    filters:
    - name: re_replace
      args: ["(Ep[\\.]?[ ]?)|([S]\\d\\d[Ee])", "E"]
```

But, how could i limit that filter only to animes?

I saw that there's an ```case```, but it looks that it's only to simple tests (if regex is found, output some string) and do not allow nested tests like that:
```yml
title:
        case:
          "a[href^=\"torrents.php?cat=11\"]":
            selector: a[href^="torrents-details.php?id="]
            filters:
              - name: re_replace
                args: ["(Ep[\\.]?[ ]?)|([S]\\d\\d[Ee])", "E"]
          "*": 
            selector: a[href^="torrents-details.php?id="]
```

Also tried that, but doesn't seens to work like that:
```yml
title:
        selector: a[href^="torrents-details.php?id="]
        filters:
          - name: re_replace
            categorymappings: [11]
            args: ["(Ep[\\.]?[ ]?)|([S]\\d\\d[Ee])", "E"]
```

I looked into ```{{if}} {{else}}``` too, but i don't see how it could be used in this case, since it only check for field presence

**Comment by garfield69** [comment]
I don't have access to bj-share, so the following example is untested, but may give you some ideas to try out: 
```yaml
      title:
        optional: true
        selector: a[href^="torrents-details.php?id="]:has(a[href^="torrents.php?cat=11"])
        filters:
          - name: re_replace
            args: ["(Ep[\\.]?[ ]?)|([S]\\d\\d[Ee])", "E"]
      title:
        optional: true
        selector: a[href^="torrents-details.php?id="]:not(a[href^="torrents.php?cat=11"])
```
or it may turn out to be a complete waste of time ;-)

**Comment by Guizzoni** [comment]
I've tried it on B2S-Share and it doesn't work

The "torrents.php?cat=11" href belongs to another "td" so i dont think we can use a ":has" here.
Here's the source code if you want to take a look [https://pastebin.com/kfPftNjZ](https://pastebin.com/kfPftNjZ)

**Comment by Guizzoni** [comment]
@DarkSupremo
Perhaps you can adapt something like this: https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/yggtorrent.yml#L124

**Comment by DarkSupremo** [comment]
@Guizzoni 
Yeah, i saw that... but for this work, i need an way to determine the current category in IF, and as i saw, that IF only looks into configs (login / pass) at this point..

**Comment by DarkSupremo** [comment]
So, it worked:
```yaml
fields:
      is_anime:
        optional: true
        selector: a[href^="torrents.php?cat=11"]
        attribute: href
        filters:
        - name: querystring
          args: cat
      title_anime:
        selector: a[href^="torrents-details.php?id="]
        filters:
        - name: re_replace
          args: ["(Ep[\\.]?[ ]?)|([S]\\d\\d[Ee])", "E"]
      title_normal:
        selector: a[href^="torrents-details.php?id="]
      title:
        text: "{{if .Result.is_anime }}{{ .Result.title_anime }}{{else}}{{ .Result.title_normal }}{{end}}"
```
