### ISSUE TITLE
[REQ] Torrent.LT

### ISSUE THREAD

**Issue by karkaaa** [Jackett/Jackett#2279]
Tracker Name : Torrent.ai
Type : Movie, TV, Music, Anime, Games, Software, Other
Private tracker.
Has torrent files.
Indexer URL : http://www.torrent.ai
Indexer language : English

![scr](https://user-images.githubusercontent.com/34538939/33986961-efd1cdca-e0c7-11e7-8d5e-81a5a2ad89bc.PNG)

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by karkaaa** [comment]
Ok. I made CAPS and LOGIN. Now i am stuck in the search... I add page source and .yml. Maybe you can help?

Page source: https://pastebin.com/2FSkkqGx
.yml: https://pastebin.com/69LPn0Fm

**Comment by kaso17** [comment]
Try ` tr[class^="torrents_table_row_"]` as selector for search/rows/selector 
Then you've to adjust the individual field selectors, etc.

**Comment by karkaaa** [comment]
Now i have this error:

```
System.Exception: Error while parsing field=category, selector=a[href^="cats%5B%5D="], value=<null>: Selector "a[href^="cats%5B%5D="]" didn't match <tr class="torrents_table_row_even">                                                                   <td style="text-align: center;" class="torrent_cat_image ">                         <a href="torrents?search=grand&amp;cats%5B%5D=63" title="Sport / Cars">
                        <img src="http://cdn.torrent.tl/lt/images/categories/7_2_SPORT_CARS.png">
                </a>
        </td>                     <td class="torrent_name torrent_info" data-id="682733" title="Formula1 2017 Abu Dhabi Grand Prix Practice Three  ...">                         <a href="t682733-Sport-Cars-Formula1-2017-Abu-Dhabi-Grand-Prix-Practice-Three-1080p-HDTV-x264-VERUM" data-poster-preview="http://i33.fastpic.ru/big/2014/0331/41/ae01bef82944c0e93cdbfe596b88c141.jpg">Formula1 2017 Abu Dhabi Grand Prix Practice Three  ...</a>                     <span class="torrent_added"> 2017-11-25 18:25                        <i>(prieš 3 sav.)</i>                         </span>                                                                                                                        </td>                     <td style="text-align: center;">                                             </td>                                         <td style="text-align: center;">
                <a title="Parsisiųsti .torrent" href="download?id=682733" class="torrent_size">
                        <i class="fa fa-download floatIcon" aria-hidden="true">                 </i> 3.85 GB</a>
        </td>                                         <td colspan="2" style="text-align: center;">
                <span class="torrent_seeders">0</span>
                <span class="torrent_leechers">0</span>
        </td>                     <td class="torrent_uploader">
                <span title="Anonimas" style="background: transparent url(http://cdn.torrent.tl/lt/images/usericon/bright3/Anonimus.png) scroll no-repeat left center; background-size:17px; padding: 2px 0px 2px 20px;">Anonimas</span>
        </td>                 </tr>
```

**Comment by garfield69** [comment]
replace your definition content with this one (my first untested draft based on the html you provided) and test it.   Its a first draft, so there may be errors, but you should be able to figure out corrections.
Had to change the categories, the `cat:` must conform to https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt#L608-L695. 
Use https://github.com/Jackett/Jackett/wiki/Definition-format for yaml syntax reference.

report any errors that you cannot figure out solutions for.
Test successful login as well as invalid logins. 

possible next likely issues: validating downloads, possible mandatory thank-yous,  and handling download/upload freeleech/ratios/etc.
```yaml
---
  site: torrentai
  name: Torrent.ai
  description: "Torrent'ai is Private site for TV / MOVIES / GENERAL"
  language: lt-lt
  type: private
  encoding: UTF-8
  links:
    - http://www.torrent.ai/lt/

  caps:
    categorymappings:
      - {id: 27, cat: TV, desc: "Animacija"}
      - {id: 35, cat: TV/Anime, desc: "Anime"}
      - {id: 31, cat: Movies/DVD, desc: "Filmai / DVD"}
      - {id: 33, cat: Movies, desc: "Filmai / LTU"}
      - {id: 43, cat: Movies, desc: "Filmai / LT-Subs"}
      - {id: 34, cat: Movies, desc: "Filmai / Eng"}
      - {id: 32, cat: Movies, desc: "Filmai / Rus"}
      - {id: 1, cat: PC/Games, desc: "Žaidimai / PC"}
      - {id: 50, cat: Console/PS4, desc: "Žaidimai / PlayStation"}
      - {id: 51, cat: Console/Xbox 360, desc: "Žaidimai / XBOX-360"}
      - {id: 73, cat: Console, desc: "Žaidimai / Priedai"}
      - {id: 36, cat: Console/Other, desc: "Žaidimai / Kita"}
      - {id: 52, cat: Movies, desc: "HD / Animacija"}
      - {id: 53, cat: TV/Documentary, desc: "HD / Dokumentika"}
      - {id: 54, cat: Movies/HD, desc: "HD / Filmai"}
      - {id: 55, cat: Audio/Video, desc: "HD / Music videos"}
      - {id: 56, cat: TV/HD, desc: "HD / Serialai"}
      - {id: 72, cat: Movies/3D, desc: "HD / 3D"}
      - {id: 74, cat: Movies, desc: "HD / LT"}
      - {id: 37, cat: Movies/Other, desc: "HD / Kita"}
      - {id: 57, cat: Audio/MP3, desc: "Muzika / VA"}
      - {id: 26, cat: Audio, desc: "Muzika / DJ Sets"}
      - {id: 6, cat: Audio, desc: "Muzika / Albumai"}
      - {id: 29, cat: Audio/Video, desc: "Muzika / Video Klipai"}
      - {id: 42, cat: TV, desc: "Serialai / Eng"}
      - {id: 58, cat: TV, desc: "Serialai / LTU"}
      - {id: 59, cat: TV, desc: "Serialai / Rus"}
      - {id: 45, cat: TV, desc: "Serialai / Animacija"}
      - {id: 10, cat: PC/0day, desc: "Soft / PC"}
      - {id: 44, cat: PC/Mac, desc: "Soft / MAC"}
      - {id: 61, cat: PC, desc: "Soft / PDA"}
      - {id: 75, cat: PC/Phone-Other, desc: "Soft / Kita"}
      - {id: 62, cat: TV/Sport, desc: "Sport / Basketball"}
      - {id: 40, cat: TV/Sport, desc: "Sport / Kita"}
      - {id: 63, cat: TV/Sport, desc: "Sport / Cars"}
      - {id: 65, cat: TV/Sport, desc: "Sport / Fights"}
      - {id: 66, cat: TV/Sport, desc: "Sport / Football"}
      - {id: 69, cat: TV, desc: "TV / LT"}
      - {id: 70, cat: TV, desc: "TV / RU"}
      - {id: 39, cat: TV/Documentary, desc: "TV / Dokumentika"}
      - {id: 28, cat: TV/Other, desc: "TV / Kita"}
      - {id: 21, cat: XXX, desc: "pr0n"}
      - {id: 71, cat: XXX/Packs, desc: "pr0n / pack"}
      - {id: 30, cat: Other, desc: "Kita"}
      - {id: 41, cat: Books, desc: "E-Books"}

    modes:
      search: [q]
      tv-search: [q, season, ep]

  login:
    path: account-login.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
    error:
      - selector: p.error_text
    test:
      path: torrents

  search:
    paths:
      - path: torrents.php
    inputs:
      $raw: "{{range .Categories}}cats[]={{.}}&{{end}}"
      search: "{{ .Keywords }}"
    rows:
      selector: div.torrents_container > table.torrents_table > tr[class^="torrents_table_row_"]
      filters:
        - name: andmatch
          args: 50
    fields:
      title:
        selector: td[class$="torrent_info"] a
      details:
        selector: td[class$="torrent_info"] a
        attribute: href
      banner:
        selector: td[class$="torrent_info"] a
        attribute: data-poster-preview
      category:
        selector: td[class^="torrent_cat_image"] a
        attribute: href
        filters:
          - name: querystring
            args: cats[]
      seeders:
        selector: td span.torrent_seeders
      leechers:
        selector: td span.torrent_leechers
      download:
        selector: td a.torrent_size
        attribute: href
      size:
        selector: td a.torrent_size
      downloadvolumefactor:
        text: 1
      uploadvolumefactor:
        text: 1
      date:
        selector: td[class$="torrent_info"] span
        remove: div, i
        filters:
          - name: dateparse
            args: "2006-01-02 15:04"
```

**Comment by karkaaa** [comment]
NICE!!!

I changed this and work.

FROM: 
```
 search:
    paths:
      - path: torrents
    rows:
      selector: div.torrents_container > table.torrents_table > tr[class^="torrents_table_row_"]
```

TO:
```
 search:
    paths:
      - path: torrents.php
    rows:
      selector: table> tbody > tr[class^="torrents_table_row_"]
```
