### ISSUE TITLE
[HELP] Parse date in other language

### ISSUE THREAD

**Issue by Albvadi** [Jackett/Jackett#2439]
Jackett version:  0.8.602.0
Mono version (if not using Windows): Windows 7

-------------------------------
Hi,
i´m trying parse a date string in spanish format, but I get an invalid format error.

Example:

- Definition:
    ```yaml
    date:
        selector: td.fecha
        attribute: title
        filters:
          - name: dateparse
            args: "Monday 2 January 2006, 15:04"
    ```
- Example string: Domingo 11 Enero 2015, 22:37
- Error:
    ```log
    01-18 11:24:22 Debug Error while parsing DateTime "Domingo 11 Enero 2015, 22:37", using layout "Monday 2 January 2006, 15:04" (dddd d MMMM yyyy, HH:mm): String was not recognized as a valid DateTime.
    ```
I tried to replace spanish words by the english equivalent and works:
```yaml
date:
  selector: td.fecha
  attribute: title
  filters:
    - name: replace
      args: ["Domingo", "Sunday"]
    - name: replace
      args: ["Enero", "January"]
    - name: dateparse
      args: "Monday 2 January 2006, 15:04"
    - name: strdump
```
So... is it the unique solution to use 19 replaces (7 per day + 12 per month)?? 
Like:
```yaml
  filters:
    - name: replace
      args: ["Domingo", "Sunday"]
    - name: replace
      args: ["Lunes", "Monday"]
    - name: replace
      args: ["Martes", "Tuesday"]
      #
      #
      #
    - name: replace
      args: ["Enero", "January"]
    - name: replace
      args: ["Febrero", "February"]
      #
      #
      #
```

Thanks!
