### ISSUE TITLE
horrible-subs: generates errors during dateheaders processing.

### ISSUE THREAD

**Issue by powerdude** [Jackett/Jackett#2480]
the following error is in the log when manually searching:

Error while parsing DateTime "Tue, 03 Oct 2017 00:00:00 -4", using layout "01-02" (MM-dd): String was not recognized as a valid DateTime.

Jackett version:  0.8.626.0
Mono version (if not using Windows):  

-------------------------------

**Comment by garfield69** [comment]
If you want us to fix this you are going to need to tell us which indexer you were using for the search ;-)

**Comment by powerdude** [comment]
sorry for not providing that.  Here are the indexers i'm using: l337x, anidex, bt-scene, ettv, extv, horrible subs, rarbg, showrss, the pirate bay, world wide torrents, yts, isohunt2, kickasstorrent, kickasstorrent(thekat.nz)

**Comment by garfield69** [comment]
the errors are coming from horrible-subs, from the dateheaders block:
```yaml
      dateheaders:
        selector: table.release-info
        filters:
          - name: split
            args: [" ", 0 ]
          - name: replace
            args: ["(", ""]
          - name: replace
            args: [")", ""]
          - name: replace
            args: ["/", "-"]
          - name: dateparse 
            args: "01-02-06"
          - name: dateparse 
            args: "01-02"
```
So every time this definition processes a date record, either the first or the second dateparse will generate a debug-error when the enhanced log is enabled.
```
2018-01-26 17:43:49.8886 Debug Error while parsing DateTime "01-25", using layout "01-02-06" (MM-dd-yy): String was not recognized as a valid DateTime.
2018-01-26 17:50:14.6796 Debug Error while parsing DateTime "Thu, 25 Jan 2018 00:00:00 +13", using layout "01-02" (MM-dd): String was not recognized as a valid DateTime.
```
@kaso17  any thoughts on how we might be able to prevent this?
