### ISSUE TITLE
[req] metal-tracker.com

### ISSUE THREAD

**Issue by joelstitch** [Jackett/Jackett#282]
Can someone please guide me on the right direction as to what I need to do to add a custom tracker, in this case metal-tracker.com. Thanks

**Comment by flightlevel** [comment]
There is some info over here to get started https://github.com/Jackett/Jackett/issues/130
and this would a good example to follow https://github.com/Jackett/Jackett/commit/29ef28b6d795deb6bf8e9ab8da03a6b1492d8a40

**Comment by joelstitch** [comment]
It sorts of explains what you need but not how to do it.

**Comment by flightlevel** [comment]
You would need some basic programming skills, let us know where you are stuck

**Comment by kaso17** [comment]
Please send an invite to kaso1717 -at- gmail.com and I'll add it.

**Comment by armani316** [comment]
I believe Metal-Tracker is a semi-private tracker; it requires registration, but signup is always open:
http://en.metal-tracker.com/user/registration.html

**Comment by joelstitch** [comment]
Yeah registration is always free

**Comment by armani316** [comment]
@joelstitch Cool, let's see if the team approves adding support to it in Jackett. Thanks!

**Comment by kaso17** [comment]
Jackett as of this weekend supports public trackers (again). So no more problems with this one.

**Comment by haudankaivajasi** [comment]
Is there any plans to add metal-tracker site to Jackett in the future or am I missing something?

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by joelstitch** [comment]
I've tried but could not get it to work.

**Comment by garfield69** [comment]
Hmm. It looks like metal-tracker.com uses a *form* for its *search*.    
I don't think I can code a *Cardigann definition* for this site, as I don't believe Jackett currently supports `method: form` in the `search` section.     
@kaso17  Am I right about this?
If I can't use *yaml*, do Jackett's c# indexer methods currently support using *search forms*?
Do you know of an existing example I could model from?
Thanks.

**Comment by kaso17** [comment]
Pretty much all trackers use a form for searching, most of them use the GET method for sending that form (arguments are added to the URL).
If metal-tracker is using POST for sending data (`<form action="..." method="post">`) just use `method: post` in the search block.
form would be only needed in case there's some kind of CSRF token or similar. But It's not supported. But it would be the first tracker which needs this.
You can also try submitting the parameters via the standard get, many trackers which use POST also support GET.

**Comment by garfield69** [comment]
I am going to need help on this one, because I think I am using `method: post` correctly, but the search results returned by metal-tracker.com indicate that my search input parameters are ignored.
```yaml
---
  site: metaltracker
  name: Metal Tracker
  description: "Metal Tracker is a Semi-Private site dedicated to HEAVY METAL MUSIC. This definition is for the English site."
  language: en-us
  type: semi-private
  encoding: UTF-8
  links:
    - http://en.metal-tracker.com/

  caps:
    categories:
      "Books": Audio/Audiobook
      "Video": Audio/Video
      "Music": Audio/MP3

    modes:
      search: [q]
      music-search: [q, album, artist, label, year]

  login:
    path: /user/login.html
    method: form
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
      go: "Enter"
    error:
      - selector: div.errorSummary
        message:
          selector: div.errorSummary ul li
    test:
      path: /torrents/search.html
      selector: li li:has(a[href="/user/logout.html"])

  search:
    path: /torrents/search.html
    method: post
    inputs:
      SearchTorrentsForm%5BnameTorrent%5D: "{{ .Keywords }}"
      go-search: "Search"
    rows:
      selector: .smallalbum
    fields:
      title:
        selector: a h3
      banner:
        selector: .thumb a img
        attribute: src
      details:
        selector: .thumb a
        attribute: href
      download:
        selector: .center a[href^="/torrents/download/id/"]
        attribute: href
      date:
          text: "now"
      seeders:
        selector: .center font:nth-of-type(1)
      leechers:
        selector: .center font:nth-of-type(2)
      downloadvolumefactor:
          text: "0"
      uploadvolumefactor:
          text: "1"
      category:
        selector: .smallalbum
        remove: div.thumb, div.center, a
        case:
          ":contains(\"Type: Music\")": "Music"
          ":contains(\"Type: Video\")": "Video"
          ":contains(\"Type: Books\")": "Books"
      size:
        selector: .smallalbum
        filters:
          - name: regexp
            args: "Size:\\s+([\\w\\d\\.,]+ \\w\\w)"
```
a manual search of `faith no more` only ever returns results of an *empty* search.
here is the debug log of my last test run:
[metal-tracker.log](https://github.com/Jackett/Jackett/files/1403723/metal-tracker.log)

**Comment by kaso17** [comment]
for some reason it's using GET

If you access in the browser, does it work?
http://en.metal-tracker.com/torrents/search.html?SearchTorrentsForm[nameTorrent]=faith+no+more&go-search=Search 

Otherwise please try the multi path syntax:
```
  search:
    paths:
      - path: /torrents/search.html
        method: post
    inputs:
      "SearchTorrentsForm[nameTorrent]": "{{ .Keywords }}"
      go-search: "Search"
```
