### ISSUE TITLE
Help with updating Jpopsuki

### ISSUE THREAD

**Issue by beschoenen** [Jackett/Jackett#2923]
I'm trying to update the Jpopsuki definition to exclude some metadata that's currently in the title, but it's kinda tricky.

Example titles:
```
西野カナ -​ 君って + アイラブユー (CDTV祝25周年SP 2018.​04.​07)	[MPEG2 /​ HDTV]
清春 -​ 090731 Liquid Room	[ISO /​ DVD] [2009.​10.​30]
```

The last `[.*]` should be removed, but it's more tricky than it looks, cause they're optional and sometimes part of a valid title.

The HTML does have a good structure to exclude the metadata, but it's a little hard to do this in via the yaml.

```html
<td>
    <span>
        [<a href="torrents.php?action=download&id=358356" title="Download">DL</a> | <a href="reports.php?action=report&amp;id=358356" title="Report">RP</a>]
    </span>
    <a href="artist.php?id=14487" title="View Artist">E-girls</a> - <a href="torrents.php?id=251368&amp;torrentid=358356" title="Gomen Nasai no Kissing You + Pain, pain (CDTV 25th Anniversary SP 2018.04.07) (View Torrent)">ごめんなさいのKissing You + Pain, pain (CDTV祝25周年SP 2018.04.07)</a> [MPEG2 / HDTV / <strong>Freeleech!</strong>]
    <br>
    <div class="tags">
        <a href="torrents.php?searchtags=japanese">japanese</a>, <a href="torrents.php?searchtags=live">live</a>
    </div>
</td>
```

The yaml definition remove a lot of junk already:
```yaml
title:
selector: td:nth-child(3)
remove: span, div.tags, a[title="View Comments"]
filters:
  - name: replace
    args: [" ()", ""]
  - name: replace     
    args: [" / Freeleech!", ""]
  - name: regexp
    args: ""
```

The best thing would be to select `a[title="View Artist"]` and the other `a` (which sometimes is `a[title="View Torrent"]` and combine them:

```
$Artist - $Torrent
```

Is this possible via yaml or is there any other/better way to remove the optional metadata/release date tag block?
