### ISSUE TITLE
[Req] Il corsaro blu

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3098]
Hi, this's a new traker:
https://www.ilcorsaroblu.org

Contains:
movie
tv show
games
music
software
books
...

The good is that the interface is very similar to arabafenice and/or shareisland
But the traker is not private!!! And have release that is difficult to find around, so if pretty good

Unfortunately I don't know how to develop the plug-in, is pretty a strange world for the the system how it works, I read the faq about the html but I cant' find the logic behind, so if anyone can help me to create the plug-in for the traker I can start to try to make it

Jo

**Comment by Jorman** [comment]
Hi, I'm trying to add the traker, I really don't know nothing about the functions to make it works, so I duplicated a one that is similar (shareisland). Because no registration is needed to search (I think is optional) I set it to public, so no login phase, one problem solved for now!

Then I try to understand the way the code works, so here where I'm
https://pastebin.com/v7FUj17Y
But don't works! I think the
```
    rows:
      selector: div.b-content > table > tbody > tr > td > table.lista > tbody > tr:has(a[href*="_torrent-"])
```
is not good, then I've to start from this, right?
See here
![test](https://user-images.githubusercontent.com/5203988/40270951-9756eda2-5b96-11e8-933a-fb23717dd55e.PNG)
Is the good thinking or I'm totally in the wrong way?

The problem is that I don't know how to "fix" this 1st simple step

Any idea/help?

Jo

**Comment by kaso17** [comment]
looks ok to me, check the enhanced log for errors.

**Comment by Jorman** [comment]
Maybe the 1st step is done, I see this on the error log

```
CardigannIndexer (ilcorsaroblu): Error while parsing row '<tr>           <td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=12">
			<img src="https://www.ilcorsaroblu.org/style/ilCorSaRoBlu/images/categories/adult.png" border="0" alt="Adult" title="Adult">			
		</a>
	</td>                      <td class="lista" valign="middle" onmouseover="this.className='post'" onmouseout="this.className='lista'" style="padding-left:10px;overflow:auto;">
		<a href="Playboy_Real_Couples___Sex_In_Dangerous_Places_torrent-123397.html" onmouseover=" return overlib('<img src=torrentimg/nocover.jpg width=200 border=0>', CENTER);" onmouseout="return nd();">Playboy Real Couples   Sex In Dangerous Places torrent</a> (<span style="color:red">EXT</span>)&nbsp;&nbsp;<img src="images/new.png">		 </td>                                 <td align="center" width="30" class="lista" style="white-space:wrap;padding-left:10px;">---                                             </td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=aa3a65817b04c163ecc3a4ec0a1ef79172c3bdd3&amp;f=Playboy+Real+Couples+-+Sex+In+Dangerous+Places.torrent.torrent">
			<img src="images/download.gif" border="0" alt="Scarica Torrent" title="Scarica Torrent">			
		</a> </td>  		              <td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">20/05/2018</td>           <td align="center" width="30" class="lista #FFFF00" style="text-align: center;">4</td>           <td align="center" width="30" class="lista #FFFF00" style="text-align: center;">8</td>           <td align="center" width="30" class="lista" style="text-align: center;">39663</td>                                 <td align="center" width="30" class="lista">699.74 MB</td>                                 <td align="center" width="45" class="lista" style="text-align: center;">N/D</td>                      <td align="center" width="45" class="lista" style="text-align: center;">N/D<br>		
	</td>                                           </tr>':

System.Exception: Error while parsing field=title, selector=a[href^="index.php?page=torrent-details"], value=<null>: Selector "a[href^="index.php?page=torrent-details"]" didn't match <tr>           <td align="center" width="45" class="lista" style="text-align: center;">
		<a href="index.php?page=torrents&amp;category=12">
			<img src="https://www.ilcorsaroblu.org/style/ilCorSaRoBlu/images/categories/adult.png" border="0" alt="Adult" title="Adult">			
		</a>
	</td>                      <td class="lista" valign="middle" onmouseover="this.className='post'" onmouseout="this.className='lista'" style="padding-left:10px;overflow:auto;">
		<a href="Playboy_Real_Couples___Sex_In_Dangerous_Places_torrent-123397.html" onmouseover=" return overlib('<img src=torrentimg/nocover.jpg width=200 border=0>', CENTER);" onmouseout="return nd();">Playboy Real Couples   Sex In Dangerous Places torrent</a> (<span style="color:red">EXT</span>)&nbsp;&nbsp;<img src="images/new.png">		 </td>                                 <td align="center" width="30" class="lista" style="white-space:wrap;padding-left:10px;">---                                             </td>
	<td align="center" width="20" class="lista" style="text-align: center;">
		<a href="download.php?id=aa3a65817b04c163ecc3a4ec0a1ef79172c3bdd3&amp;f=Playboy+Real+Couples+-+Sex+In+Dangerous+Places.torrent.torrent">
			<img src="images/download.gif" border="0" alt="Scarica Torrent" title="Scarica Torrent">			
		</a> </td>  		              <td align="center" width="85" class="lista" style="white-space:wrap; text-align:center;">20/05/2018</td>           <td align="center" width="30" class="lista #FFFF00" style="text-align: center;">4</td>           <td align="center" width="30" class="lista #FFFF00" style="text-align: center;">8</td>           <td align="center" width="30" class="lista" style="text-align: center;">39663</td>                                 <td align="center" width="30" class="lista">699.74 MB</td>                                 <td align="center" width="45" class="lista" style="text-align: center;">N/D</td>                      <td align="center" width="45" class="lista" style="text-align: center;">N/D<br>		
	</td>                                           </tr>
  at Jackett.Common.Indexers.CardigannIndexer+<PerformQuery>d__29.MoveNext () [0x01626] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1453 
```

So Is about the selection for download, right?

**Comment by kaso17** [comment]
no:
`System.Exception: Error while parsing field=title, selector=a[href^="index.php?page=torrent-details"], value=<null>: Selector "a[href^="index.php?page=torrent-details"]" didn't match`

title selector didn't match

**Comment by Jorman** [comment]
Ok, so
```
    rows:
      selector: div.b-content > table > tbody > tr > td > table.lista > tbody > tr:has(a[href*="_torrent-"])
```
Tell to script to consider only href that inside of it has `*_torrent-*`
![1](https://user-images.githubusercontent.com/5203988/40279397-51bd0fe0-5c42-11e8-91b6-6aa810a20c99.PNG)
Right?

Then, if I go over the 1st results I go to the torrent page, that derive from `*_torrent-*`
![2](https://user-images.githubusercontent.com/5203988/40279485-ad2fbc8c-5c43-11e8-85db-93b074b3cf8c.PNG)

So next step is to analyze the page
`https://www.ilcorsaroblu.org/Ulisse___Splendori_Di_Sicilia_torrent-123465.html`
Right?

The page cointain this
![3](https://user-images.githubusercontent.com/5203988/40279516-40b6790a-5c44-11e8-8b4e-0115711729e8.PNG)
The page contains 4 kind of download
```
download.php
download_magnet.php
download1.php
download2.php
```
Each one with the id of all, the problem start now, the code report
```
    fields:
      download:
        selector: a[href^="download.php?id="]
        attribute: href
      title: # shortened title?
        selector: a[href^="index.php?page=torrent-details"]
        # normalize to SXXEYY format
        filters:
          - name: re_replace # replace special characters with " " (space)
            args: ["[^a-zA-Z0-9]|\\.", " "]
          # normalize to SXXEYY format
          - name: re_replace
            args: ["(\\d{2})x(\\d{2})", "S$1E$2"]
          - name: re_replace
            args: ["(\\d{1})x(\\d{2})", "S0$1E$2"]
          - name: re_replace #Stagione X --> S0X
            args: ["Stagione (\\d{0,1}\\s)", "S0$1"]
          - name: re_replace #Stagione XX --> SXX
            args: ["Stagione (\\d{2}\\s)", "S$1"]
          - name: re_replace #/ Episodio [YY-YY --> EYY-YY
            args: ["(\\s\\/\\sEpisodio|\\s\\/\\sEpisodi|\\sEpisodio|\\s\\|\\sEpisodio|\\sEpisodi)\\s\\[", "E"]
          - name: re_replace #/ Completa [episodi  YY-YY --> EYY-YY
            args: ["(\\s\\/\\sCompleta\\s\\[episodi\\s)", "E"]
          - name: re_replace #remove  di YY] | remove /YY]
            args: ["(\\sdi\\s\\d{1,2}|\\/\\d{1,2})\\]", " "]
          - name: re_replace #remove various
            args: ["(Serie completa|Completa|\\[in pausa\\])", ""]
          # fine prova
      title: # long titles?
        optional: true
        selector: a[title][href^="index.php?page=torrent-details"]
        attribute: title
        filters:
          - name: replace
            args: ["Vedi Dettagli: ", ""]
          # inizio prova
          - name: re_replace # replace special characters with " " (space)
            args: ["[^a-zA-Z0-9]|\\.", " "]
          # normalize to SXXEYY format
          - name: re_replace
            args: ["(\\d{2})x(\\d{2})", "S$1E$2"]
          - name: re_replace
            args: ["(\\d{1})x(\\d{2})", "S0$1E$2"]
          - name: re_replace #Stagione X --> S0X
            args: ["Stagione (\\d{0,1}\\s)", "S0$1"]
          - name: re_replace #Stagione XX --> SXX
            args: ["Stagione (\\d{2}\\s)", "S$1"]
          - name: re_replace #/ Episodio [YY-YY --> EYY-YY
            args: ["(\\s\\/\\sEpisodio|\\s\\/\\sEpisodi|\\sEpisodio|\\s\\|\\sEpisodio|\\sEpisodi)\\s\\[", "E"]
          - name: re_replace #/ Completa [episodi  YY-YY --> EYY-YY
            args: ["(\\s\\/\\sCompleta\\s\\[episodi\\s)", "E"]
          - name: re_replace #remove  di YY] | remove /YY]
            args: ["(\\sdi\\s\\d{1,2}|\\/\\d{1,2})\\]", " "]
          - name: re_replace #remove various
            args: ["(Serie completa|Completa|\\[in pausa\\])", ""]
          # fine prova
```
If I follow the logic, the script search for fields and set the download filed to
`a[href^="download.php?id="]`
Then the selector of title
```
      title: # shortened title?
        selector: a[href^="index.php?page=torrent-details"]
```
must match for the very first selector (`tr:has(a[href*="_torrent-"]`) right?

But I think the selection of the torrent page is about this details sections
```
      category:
        selector: a[href^="index.php?page=torrents&category="]
        attribute: href
        filters:
          - name: querystring
            args: category
      details:
        selector: a[href^="index.php?page=torrent-details&id="]
        attribute: href
      banner:
        optional: true
        selector: a[href^="index.php?page=torrent-details&id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "src=(.+?) "
```
so selector must be again
`a[href*="_torrent-"]`
Right?

**Comment by Jorman** [comment]
Ok, maybe I found the "logic" I try after to make a post to ask some, now the test of the traker works, I've to fix the category and later I'll ask some

**Comment by Jorman** [comment]
Ok, maybe I'm closer! Here the actual code
https://pastebin.com/K6EhDPdX

I fixed all categories and seems to works! the test works, I don't have yet tried to download ... I'll

The question now is
Look at the screen I'll attach, I've 2 kind of download button, one is the regular download.php page and the other one is a magneg link, how can I handle both of that?
I think is here where I've to handle it, right? Before I said that the script go on every page he found in the list but I think is wrong, the script try to extract all info in the table list, right?
So in this case how I can handle the magnet link? Like an optional value?
```
Like:
    fields:
      download:
        selector: a[href^="download.php?id="]
        attribute: href
      download:
        optional: true
        selector: a[href^="magnet:?"]
        attribute: href
```

Can works?

Jo

**Comment by Jorman** [comment]
Download for now don't works
```
05-20 19:29:43 Error Error downloading ilcorsaroblu https://www.ilcorsaroblu.org/download.php?id=29600aca2acc5977e0da405554dbbdf1c7b5ee80&f=The.Big.Bang.Theory.11x18.L.Eccitazione.Per.Gates..ITA.ENG.1080p.WEB-DLMux.H.264-Morpheus.mkv.torrent.torrent BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
  at BencodeNET.Parsing.BencodeParser.Parse (BencodeNET.IO.BencodeStream stream) [0x0008f] in <f57c6b848225428ca6216f5cbc1c09fa>:0
  at BencodeNET.Parsing.BencodeParser.Parse (System.IO.Stream stream) [0x00008] in <f57c6b848225428ca6216f5cbc1c09fa>:0
  at BencodeNET.Parsing.BencodeParser.Parse (System.Byte[] bytes) [0x00007] in <f57c6b848225428ca6216f5cbc1c09fa>:0
  at Jackett.Controllers.DownloadController+<Download>d__5.MoveNext () [0x001ab] in <64b7bf99651e4985b9007c1d19a3eb36>:0
```

**Comment by kaso17** [comment]
the download.php is only generating a 10 second delayed redirect to itorrents.org
You should fill the magnet field with a magnet link. It's not directly available but the important part (the hash) can be extracted from the download link. Check some other public trackers, there are several other indexers which extract the magnet hash and build a magnet link using append/prepend filters.

Using the hash you can also build an direct itorrents link for the download field like this:
`https://itorrents.org/torrent/EECC490562C3844D5430C1D2C2F87DBF7473538D.torrent`

**Comment by Jorman** [comment]
About the magnet link I tried the previous one solution and this one
```
      download:
        optional: true
        selector: a[href^="download.php?id="]
        attribute: href
      magnet:
        optional: true
        selector: td:nth-child(4) a
        attribute: href
```
Because a single line can't have download.php and magnet I set both, download and magnet, as optional so if one is not present don't fail! But don't works. Take a look at this rel
https://www.ilcorsaroblu.org/index.php?page=torrents&search=Yamakasi&category=0&options=0&active=0
contain only magnet, but the script can't fine any results! I activated the enchanged log but I don't see errors
https://pastebin.com/j3VnxxY9

Any clue?

**Comment by Jorman** [comment]
So, I've to build the itorrent link where the magnet is not present, I found a simple regex method to extract the hash
[here the regex](https://regex101.com/r/DEfanh/2)
[or this regex](https://regex101.com/r/DEfanh/3)
I don't have yet found a good way to build the final link

What about the rel with the magnet link? I can't find any rel during a search

**Comment by Jorman** [comment]
I tried this
```
      download:
        optional: true
        selector: a[href^="download.php?id="]
        attribute: href
        filters:
          - name: regexp
            args: "/(\\w{35,})"
          - name: toupper
          - name: prepend
            args: http://itorrents.org/torrent/
          - name: append
            args: ".torrent"
        magnet:
        optional: true
        selector: td:nth-child(4) a
        attribute: href
```
The url on table is
`https://www.ilcorsaroblu.org/download.php?id=29600aca2acc5977e0da405554dbbdf1c7b5ee80&f=The.Big.Bang.Theory.11x18.L.Eccitazione.Per.Gates..ITA.ENG.1080p.WEB-DLMux.H.264-Morpheus.mkv.torrent.torrent`
So in theory I filter the entire url and I select only a string that contain more than 35 alphanumeric character in a row, then I prepend and append ... (I found this on torrentz2 traker)
I got this error message
```
05-20 22:48:32 Error Error downloading ilcorsaroblu http://itorrents.org/torrent/.torrent System.Exception: Remote server returned NotFound
  at Jackett.Common.Indexers.BaseWebIndexer+<Download>d__3.MoveNext () [0x001fb] in C:\projects\jackett\src\Jackett.Common\Indexers\BaseIndexer.cs:317
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357
  at Jackett.Common.Indexers.CardigannIndexer+<Download>d__32.MoveNext () [0x0032d] in C:\projects\jackett\src\Jackett.Common\Indexers\CardigannIndexer.cs:1645
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /SRC/.MYSCRIPT/tmp/mono-5.12.0.226/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357
  at Jackett.Controllers.DownloadController+<Download>d__5.MoveNext () [0x00128] in <64b7bf99651e4985b9007c1d19a3eb36>:0
```
The url was not complete, like if the hash is not present, what I miss?

**Comment by kaso17** [comment]
the first / in your regex looks wrong.
I suggest you just use the querystring filter instead of regex:
```
- name: querystring
  args: id
```

**Comment by Jorman** [comment]
Don't have to escape? Strange on torrentz2 is the same, look
```
      download-itorrents:
        selector: dt a
        attribute: href
        filters:
          - name: regexp
            args: "/(\\w+)"
          - name: toupper
          - name: prepend
            args: http://itorrents.org/torrent/
          - name: append
            args: ".torrent"
      download:
        text: "{{if .Config.itorrents-links}}{{ .Result.download-itorrents }}{{else}}{{end}}"
```

I'll try to find and use the querystring.

Any idea about the missing rel when magnet is present?

**Comment by Jorman** [comment]
You right! querystring works, capture the link but no download at all, see the error
```
05-21 13:29:35 Error Error downloading ilcorsaroblu http://itorrents.org/torrent/29600ACA2ACC5977E0DA405554DBBDF1C7B5EE80.torrent BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found '<' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
  at BencodeNET.Parsing.BencodeParser.Parse (BencodeNET.IO.BencodeStream stream) [0x0008f] in <f57c6b848225428ca6216f5cbc1c09fa>:0
  at BencodeNET.Parsing.BencodeParser.Parse (System.IO.Stream stream) [0x00008] in <f57c6b848225428ca6216f5cbc1c09fa>:0
  at BencodeNET.Parsing.BencodeParser.Parse (System.Byte[] bytes) [0x00007] in <f57c6b848225428ca6216f5cbc1c09fa>:0
  at Jackett.Controllers.DownloadController+<Download>d__5.MoveNext () [0x001ab] in <64b7bf99651e4985b9007c1d19a3eb36>:0
```
But now the url is correct

Any idea?

**Comment by kaso17** [comment]
any chance that the torrent file wasn't available on itorrents at that time? it looks like the link returned HTML output.

what do you mean with missing rel for the magnet link?
for the magnet link you just need the hash, a filename (use the title or the filename form the URL) and optinal some trackers. Either hardcode some trackers or don't inlcude any (clients will use DHT, etc.)

**Comment by Jorman** [comment]
About the 1st problem I don't know, maybe. I'll try again with other rel.

About the missing rel for the magnet, happen that some rel (I don't know why) have a magnet link instead the hash id, see the image below
![1](https://user-images.githubusercontent.com/5203988/40307570-54554472-5d03-11e8-8523-e038f23d2430.PNG)

So the 1st rel have
`https://www.ilcorsaroblu.org/download.php?id=d2397280a785519b921d1f4450a5aa326da1052e&f=InazumaElevenGOGalaxy_21_25_720p.torrent.torrent`
The second one have
`https://www.ilcorsaroblu.org/magnet:?xt=urn:btih:861f0b84e12620118fd00060f124503ea9a45899&dn=TuttoSport+21+Maggio+2018&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce`

So I tried with
```
      download:
        optional: true
        selector: a[href^="download.php?id="]
        attribute: href
        filters:
          - name: querystring
            args: id
          - name: toupper
          - name: prepend
            args: http://itorrents.org/torrent/
          - name: append
            args: ".torrent"
        magnet:
        optional: true
        selector: td:nth-child(4) a
        attribute: href
```
But don't find the rel with magnet! see this example
https://github.com/Jackett/Jackett/issues/3098#issuecomment-390503800

**Comment by kaso17** [comment]
I guess `td:nth-child(4) a` will always match. Try changing it to a[href^="magnet:"]

**Comment by Jorman** [comment]
Yes, `td:nth-child(4) a` always point to download href, but sometimes contain
`download.php?id=`
sometimes contain
`magnet:?xt=`

How can I handle it? Maybe with an if
If contain download.php the final link must be, else final link is

**Comment by Jorman** [comment]
I'm working on this
```
      normal_download:
        optional: true
        selector: a[href^="download.php?id="]
        attribute: href
        
      download:
        text: "{{ .Result.normal_download }}doaction1{{else}}doaction2{{end}}"
```
I'm on the right way? Now I only have to figure out how to create doaction1 and doaction2 to create the real download link

**Comment by Jorman** [comment]
So, now I'm here
```
      is_normal:
        optional: true
        selector: a[href^="download.php?id="]
        attribute: href
      normal_download:
        optional: true
        selector: td:nth-child(4) a
        attribute: href
        filters:
          - name: querystring
            args: id
          - name: toupper
          - name: prepend
            args: http://itorrents.org/torrent/
          - name: append
            args: ".torrent"
      magnet_download:
        optional: true
        selector: a[href^="magnet:"]
        attribute: href
      download:
        text: "{{if .Result.is_normal }}{{ .Result.normal_download }}{{else}}{{ .Result.magnet_download }}{{end}}"
```
but if I manually search Yamakasi I can't find nothing, but in reality is a magnet link is present
[Link to search](https://www.ilcorsaroblu.org/index.php?page=torrents&search=Yamakasi&category=0&options=0&active=0)
If I search Yamakasi, with enchanged log, I only see all the html page

[This is the full file](https://pastebin.com/K17FeaEu)

Any idea?
