### ISSUE TITLE
[Req] http://forums.mvgroup.org

### ISSUE THREAD

**Issue by ldexterldesign** [Jackett/Jackett#315]
https://forums.sonarr.tv/t/research-http-forums-mvgroup-org-integration/10496

Hey,

Thanks for amazing software

I recently registered with http://forums.mvgroup.org/ (they have a great selection of [old UK] TV) and wondered if it's possible to integrate this tracker with https://sonarr.tv/ ? The website is public, but, to my knowledge, requires a login to access content.

I've acquainted myself with one of the website's admins - what are the questions I should be asking in order to discover if my request is possible?

Cookies/RSS / username/password logins - apologies, I'm new to this :grimacing:

Hope to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by kaso17** [comment]
Looks like a public tracker (no invite needed) to me. The current Jacket policy is not to support public trackers.
But it should be possible to write a cardigann definition file which uses http://forums.mvgroup.org/forumtracker.php?filter=&withsubs=
You'll need some basic knowledge about HTTP and CSS selectors.
Have a look at the existing definitions in the Definitions directory.

**Comment by ldexterldesign** [comment]
Hey @kaso17,

Thanks for reply

Hope you're well

Cool, I'll look into this when I install https://github.com/cardigann/cardigann

I'm assuming by "definitions directory" you mean https://github.com/cardigann/cardigann#definitions ?

Cheers

**Comment by SirSilent** [comment]
Just wanted to post that although it's public, it's the best tracker around for BBC documentary series. RSS feeds can be found here once you are logged in:

**Comment by SirSilent** [comment]
Just wanted to post that although it's public, it's the best tracker around for BBC documentary series. RSS feeds can be found here once you are logged in: 

https://forums.mvgroup.org/rss.php?torrentsonly=1

Along with the URL that @kaso17 provided, there are actually two trackers here. Main tracker and Forum Tracker where you can search for releases.

Main Tracker: http://forums.mvgroup.org/maintracker.php
Forum Tracker: http://forums.mvgroup.org/forumtracker.php

In all honesty I'd be happy enough with RSS being converted for Sonarr, but search would be awesome if possible too.

**Comment by SirSilent** [comment]
@kaso17 can this issue be reopened? The reason you gave about not supporting public trackers is no longer the case I'm assuming, as there are loads in Jackett now.

**Comment by flightlevel** [comment]
Why not have a go at adding yourself, here is some information https://github.com/Jackett/Jackett/wiki/Definition-format happy to assist if you get stuck

**Comment by ldexterldesign** [comment]
> The reason you gave about not supporting public trackers is no longer the case I'm assuming, as there are loads in Jackett now

Is this u-turn discussion public, if so can someone link me to the issue?

Personally, really glad you opened up to public indexers/trackers again

Yours hopefully

**Comment by garfield69** [comment]
@kaso17  I could use your help again ;-)
with the MVGroup definition I'm writing for this ticket, I would like to optionally provide subtitle filtering with the search.
so I originally set up the Settings section like this:
```yaml
  settings:
    - name: withsubs
      type: select
      label: Subtitles
      default: "none"
      options:
        "" : "none"
        "eng": "English"
        "alb": "Albanian"
        "ara": "Arabic"
[...etc...]
  search:
    paths:
      - path: "/maintracker.php"
    inputs:
      "withsubs": "{{ .Config.withsubs }}"
```
But this does not work because the select does not like the first option `"" : "none"`, probably becuase of the empty quotes.
So next I thought to make the first option `"_" : "none"` and use a re_replace to remove the `_`, but I cannot figure out the regex to do this.
I'm using this but it does not work.
`      "withsubs": "{{ re_replace .Config.withsubs \"[^a-z]+\" \"\" }}"`
Any ideas?

**Comment by kaso17** [comment]
A simple
`"withsubs": "{{ re_replace .Config.withsubs \"_\" \"\" }}"` should work

**Comment by garfield69** [comment]
no luck.
Here is my current definition
```yaml
---
  site: mvgroupmain
  name: MVGroup Main
  description: "MVGroup is a Semi-Private site dedicated to UK TV and DOCUMENTARIES. This definition is for the Main Tracker site."
  language: en-us
  type: semi-private
  encoding: UTF-8
  links:
    - http://forums.mvgroup.org/

  caps:
    categorymappings:
      - {id: 1, cat: Other, desc: "Other"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  settings:
    - name: username
      type: text
      label: Username
    - name: password
      type: password
      label: Password
    - name: hidef
      type: checkbox
      label: Show MVGroup HiDef Releases only
      default: false
    - name: withsubs
      type: select
      label: Subtitles
      default: "_"
      options:
        "_" : "none"
        "alb": "Albanian"
        "ara": "Arabic"
        "arm": "Armenian"
        "ass": "Assyrian"
        "bos": "Bosnian"
        "bul": "Bulgarian"
        "cat": "Catalan"
        "chi": "Chinese, simplified"
        "zho": "Chinese, traditional"
        "hrv": "Croatian"
        "cze": "Czech"
        "dan": "Danish"
        "dut": "Dutch"
        "eng": "English"
        "est": "Estonian"
        "fin": "Finnish"
        "fre": "French"
        "glg": "Galician"
        "geo": "Georgian"
        "ger": "German"
        "ell": "Greek"
        "heb": "Hebrew"
        "hin": "Hindi"
        "hun": "Hungarian"
        "ice": "Icelandic"
        "ind": "Indonesian"
        "ita": "Italian"
        "jpn": "Japanese"
        "kaz": "Kazakh"
        "kor": "Korean"
        "lav": "Latvian"
        "lit": "Lithuanian"
        "ltz": "Luxembourgish"
        "mac": "Macedonian"
        "may": "Malay"
        "nor": "Norwegian"
        "per": "Persian"
        "pol": "Polish"
        "por": "Portuguese"
        "rum": "Romanian"
        "rus": "Russian"
        "scc": "Serbian"
        "slo": "Slovak"
        "slv": "Slovenian"
        "spa": "Spanish"
        "swe": "Swedish"
        "tha": "Thai"
        "tur": "Turkish"
        "ukr": "Ukrainian"
        "vie": "Vietnamese"
    - name: seed
      type: checkbox
      label: Only released and seeded torrents
      default: false
    - name: info
      type: info
      label: Category for Sonarr and Radarr
      default: MVGroup does not use categories. In your Sonarr or Radarr Torznab Indexer settings, set the category to 100001.

  login:
    path: index.php?act=Login&CODE=00
    method: form
    form: form[action^="?act=Login"]
    inputs:
      "UserName": "{{ .Config.username }}"
      "PassWord": "{{ .Config.password }}"
      "Privacy": "1"
      "CookieDate": "0"
      "CODE": "01"
      "referer": "http://forums.mvgroup.org/"
      "act": "Login"
      "submit": "Log me in"
    error:
      - selector: div.borderwrap:has(div.tablepad)
        message:
          selector: div.borderwrap div.tablepad
    test:
      path: index.php?http://forums.mvgroup.org/
      selector: tr td.nav_mem div span[id="member_menu"]

  search:
    paths:
      - path: maintracker.php
    inputs:
      "seed": "{{ if .Config.seed }}1{{else}}0{{end}}"
      "withsubs": "{{ re_replace .Config.withsubs \"_\" \"\" }}"
      "filter": "{{ if .Config.hidef }}hd+{{else}}{{end}}{{ .Keywords }}"
      
    rows:
      selector: tr:has(a.magnetlink)
    fields:
      title:
        # fallback title (to prevent abend if neither optional is found)
        text: "title not found"
      title:
        optional: true
        selector: td.singleindent a[href^="/index.php?showtopic="]
      title:
        optional: true
        selector: td.doubleindent
      details:
        optional: true
        selector: td.singleindent a[href^="/index.php?showtopic="]
        attribute: href
      download:
        selector: td a.torrentlink
        attribute: href
      magnet:
        selector: td a.magnetlink
        attribute: href
      category:
        text: "1"
      date:
        selector: td:nth-of-type(3)
        filters:
          - name: dateparse
            args: "2006/01/02"
      seeders:
        selector: td:nth-of-type(4)
      leechers:
        selector: td:nth-of-type(5)
      grabs:
        selector: td:nth-of-type(6)
      downloadvolumefactor:
        text: "0"
      uploadvolumefactor:
        text: "1"
```
with the withsubs set to none (which is the default) the url generated is `http://forums.mvgroup.org/maintracker.php?seed=1&withsubs=%7b%7b+re_replace+.Config.withsubs+%22_%22+%22%22+%7d%7d&filter=`
