### ISSUE TITLE
Clarification needed about new traker script

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3162]
Hi, I'm trying to make some tracker script to extend the number of italian tracker.

I've some question about the script, I searched but I (think) don't find so much information.

1.
I've one tracker that when I search some, the results are reported over more than one page, so for example max 15 result's for page and after a search I see 3 pages. In that case how can I do a for each loop?
I think the best way is to see if the results there's a `<div class="paginacion">` that is the actual code that indicate to me that there's more than one page and then parse all the page results. Or there's a quite more simple way?

2.
I've the same tracker that don't have a torrent page with all the latest torrent and don't have also the categories, but have one page for movie and one page for tv show, where here are published the latest rel, a kind of rss but without the rss! What is the best way to handle that situation?

Thank you for any idea or help.

Jo

**Comment by kaso17** [comment]
1.) most indexers only support searching the first page. This limitation is tracked in #975.
some indexers request multiple pages.
Examples:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/frozenlayer.yml#L46-L49 
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/isohunt2.yml#L52-L66

2.) You probably have to build the path similar to frozenlayer above (if .keywords use search, else use movies/tv) with one path for movie/tv.
Some tracker search engines can be tricked by searching for wildcard characters like %, *, space or combinations of them (`% %`) to get the latest torrents. You might want to try that first.

**Comment by kaso17** [comment]
1) it's a limitation but so far no one worked on a solution for it (Implementing a generic way of dealing with pagination is not a trivial task). Once this is implemented the corresponding control structures will be added to the definition format. 

2. technically there's no difference between a "rsssync" (get latest torrents) and a search for a specific keyword. The same code is executed, etc.. A "rsssync" is simply a search with an empty keyword string.
You can use a `{{ if .Keywords }}` to detect if the keywords variables is empty ("rsssync") or it's a specific search (not empty)

If you have trouble with a selector not matching the best thing is to remove the optional. Then you'll get a error message showing the selector, the input (the row) and the result. Looking at the input you should be able to find out why the selector didn't match. Additionally the strdump/hexdump filters can be used to debug selector/filter results (https://github.com/Jackett/Jackett/wiki/Definition-format#hexdump)

Regarding the download problem:
In some cases you can generate the download link from other information available on the results page.
Several indexers e.g. use the details link and convert it to the download link by e.g. replacing details.php with download.php (download is using the same IDs, etc. as details).
If this is not possible just set the download link to the details page and configure the selector of the top level download block to the selector needed to get the real download link from the details page.
Example:
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/ettv.yml#L64-L65

**Comment by Jorman** [comment]
Ok, I got the logic, in that particular torrent if I use an approach like
https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/frozenlayer.yml#L46-L49
works good on "large" search but if I search the exact stuff, reports no founds ... so I think for now I leave it as is.

I tried the ettv aproach but I don't think I've understand why on ettv or 1337x works, I really don't get how is possible, I can't find a logic :D

I added the configuration for the magnet or the link and I pointed to magnet so
the download block before the search point to the right (I think) place
```
  settings:
    - name: downloadlink
      type: select
      label: Download link
      default: "magnet:"
      options:
        "http://dl.solotorrent.net/" : "Torrent file"
        "magnet:": "magnet"

  download:
    selector: u li a[href^="{{ .Config.downloadlink }}"]
    attribute: href
    filters:
      - name: re_replace # replace special characters with " " (space)
        args: ["\\s", ""]

  search:
```
![see](https://user-images.githubusercontent.com/5203988/40746995-489fc246-645c-11e8-8d44-1c1322e4884f.PNG)
I've to filter the space, the href contain. And in the second download section I've
```
    fields:
      download:
        selector: h3 > a
        attribute: href
```

Like always I miss some but I can't find what
