### ISSUE TITLE
Tracker request - Il Corsaro Verde

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#3189]
Always me!

Another great torrent tracker for my local language!

Il Corsaro Vede:
~~https://www.icv-crew.org~~
https://www.icv-crew.com/

It's a private tracker without invite so free to register!

I already start at loking in it but there's always a kind of different problem!
The website is basically a forum with release, is quite good organized so each forum is one category.
I don't know if is better to make only search or I can map every forum to the relative category and extract the exact path, so when one search can search in the right forum

The other question/problem is the search itself, start here
https://www.icv-crew.org/forum/index.php?action=search
but end here
https://www.icv-crew.org/forum/index.php?action=search2

So I don't know how to "intercept" all the data "input filed" and forum selection, to build the search string, then I don't know how to "request" the search2 page, is a strange functionality that I never see out there, or I don't pay attention to it!

Any ideas?

**Comment by kaso17** [comment]
This one won't work due to limitations of the definition format.
It needs to be implemented as native (C#) indexer like other forum based trackers too (e.g. 7tor and rutracker)

**Comment by kaso17** [comment]
ok, it might actually work, the search request is a post request (method: post) but you can use standard get values too. E.g. https://www.icv-crew.org/forum/index.php?action=search2&search=simpsons&submit=Ricerca&advacned=0

**Comment by bonny1992** [comment]
Ok, after a way too much time I may have the time to get my head on this, if kaso is cool with this.

There are a couple of problems, btw.
There is a limitation of 60 seconds between every search, how can we surpass this?
Also, to get the magnet link (if I recall correctly, this is needed by Jackett, right?) there is a "Thank you" button on top of the post, can we click on it?

**Comment by bonny1992** [comment]
As I could have seen, in every topic there is exactly one download link, but often is hidden behind a "thank you" mechanism, there is something I can refer to?

**Comment by bonny1992** [comment]
@garfield69 thank you for pointing me to this.
I have one more question by the way.
Even though the links are often hidden behind the "thank you" mechanism, there is sometimes where instead the magnet is in plain view (there is still only one link per topic, as I could have seen). The "before" can be facultative?

**Comment by garfield69** [comment]
I suspect that on indexers written in yaml download before code block can not be set up as optional....if this is a requirement then the indexer would probably need to be written in c#.
@kaso17 can you confirm that what I've just said is correct? Thanks.

**Comment by kaso17** [comment]
If the thank you link can be generated from information available on the search result page implementing this can be with the current before mechanism. If it's only available from the details page then a small Cardigann extension would be necessary (I can take care of that).

**Comment by bonny1992** [comment]
I don't sincerely know because we need the msg number, the topic id and member id (all obtainable from search result page), but we also need the cookie for the connection to SMF.
Here's the CURL needed to do the request (which will return the text of the entire topic):
`curl 'https://URL/forum/index.php?action=thank;msg=119461;member=15;topic=50311;refresh=1;ajax=1;xml=1' -H 'pragma: no-cache' -H 'cookie: displayCookieConsent=y; SMFCookie68=LONG_COOKIE; PHPSESSID=SESSID_PHP' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,is;q=0.6' -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: URL' -H 'x-requested-with: XMLHttpRequest' -H 'referer: https://URL/forum/index.php?topic=50311.msg119461' --compressed`

**Comment by bonny1992** [comment]
Oh now I understood, maybe.
The cookie must be set from the "settings" page of the indexer, right?

**Comment by Jorman** [comment]
Hi @bonny1992 
Sorry that I can't help in anyway or maybe I can but I don't know c++

But when I have to test all, I make a copy of jackett, then I edit the configuration to change the port, then I remove all indexer except the one I'm testing ... but at the end I've to reload every time jackett :D

**Comment by Jorman** [comment]
Hi @garfield69 
I just noticed the todo in progress label for this.
Can I ask you if you have any kind of eta for this? After tnt suspended activity, I think this's the most available for our country.
I only ask some information about, my only sorrow  is that I can't help in any way

**Comment by garfield69** [comment]
waiting on a c# volunteer to code.

**Comment by Jorman** [comment]
Hi, any news or update with this tracker?

**Comment by garfield69** [comment]
as it happens, I am currently working on **TheOdyssey** #8054, a similar Italian tracker that is using the same web engine, **SMF 2.0.**

If I can get my yaml indexer for this site to work, then I can also do the same for **verde** and I will post here that news.

But if I discover that the odyssey indexer cannot be written with the current implementation of Cardigann's yaml processor, then this too will need rewriting in C#, and this will be in the same boat as **verde**, which is currently pending a C# volunteer to devote time to coding.

When any such volunteer begins work on **verde** we will update this post. until then, there will be no further news.

**Comment by Jorman** [comment]
Thanks for your support!

**Comment by garfield69** [comment]
is this site filtering IP addresses only?
https://www.icv-crew.org/ returns me ERR_NAME_NOT_RESOLVED

**Comment by buzzqw** [comment]
the server is under maintenace. few days and will be back

**Comment by garfield69** [comment]
thanks for the update.

**Comment by buzzqw** [comment]
New url https://www.icv-crew.com/forum/

**Comment by YfheA3r** [comment]
I'm working on a C# indexer that will work both for this and for #8054 since they use a similar system and i have a few question:
-How can i return multiple magnets with the Download function? (both site have multiple magnets per thread and i can't split them in different ReleaseInfo since that would require sending the "thank you" to all the search result)
-Is there a way to cache a index with all the (Title, ThreadUrl) pair that you can find in the auto-generated threads lists? (i don't want to use SMF integrated search function since it work horribly and almost never find what your looking for)

Examples of thread list:
https://www.icv-crew.com/forum/index.php?topic=45255.0
http://theodyssey.cc/index.php?topic=12.0

**Comment by garfield69** [comment]
@cadatoiva  or @ngosang  a C# question https://github.com/Jackett/Jackett/issues/3189#issuecomment-623123130

**Comment by ngosang** [comment]
I can't see the download links so my answer can be inaccurate.
> -How can i return multiple magnets with the Download function? (both site have multiple magnets per thread and i can't split them in different ReleaseInfo since that would require sending the "thank you" to all the search result)

You can't. Each torrent/release can have 1 .torrent link or/and 1 magnet. In those cases we generate several ReleaseInfo (one per magnet). Usually each magnet has different qualities or uploader so the titles are different. We are not sending "thank you" or interacting with the website in other trackers. There are some feature requests related but I think we have enough keeping the search/download feature. Maybe we can help you when we see the code.

> -Is there a way to cache a index with all the (Title, ThreadUrl) pair that you can find in the auto-generated threads lists? (i don't want to use SMF integrated search function since it work horribly and almost never find what you're looking for)

Yes, there is a cache but is not working well so I don't recommend it. Please, try to make as few requests as possible, even if the results are worse. Normally each search should be only 1 request to the site. We have thousands of users and we don't want to get banned or DDoS the site.

**Comment by cadatoiva** [comment]
There is a download function that will let you do a thank you for the link someone wants to download with a separate release-info. Not sure how it works in C# since I've only seen it in the Cardigann system, but it's there underneath Cardigann for all C# indexers to use.

**Comment by Jorman** [comment]
Hi, any news/update on this tracker?
I think remain the best alternative to tntvillage

**Comment by ngosang** [comment]
No. We don't have a C# developer to work on this. PRs are welcome.

**Comment by monelivorno** [comment]
Hi, is there any development for this tracker? after the death of TNTVillage it is to be considered the most supplied and best managed Italian tracker.
Do you think it will take a long time to develop?

Thank you

**Comment by garfield69** [comment]
> is there any development for this tracker?

It seems that there have been no C# volunteers so far.

**Comment by monelivorno** [comment]
Hi maybe it's a stupid question, but if I hire a freelance C # programmer do you think he would be able to come up with an indexer or do you think that for the project you need a person who is always behind any bugs etc?

Being able to index that site would be truly spectacular for me

**Comment by YfheA3r** [comment]
I already tried to make a C# indexer for this site, the problem is that from what i understand Jackett want the magnet link of every search result and you would need to "thanks" every post present in search result to get the magnets which is not a good idea.
Another problem is that Jackett doesn't support multiple magnets per search result.
There is also a speed problem, the integrated search of SMF is really bad and to get good result the best way is to parse the "Index" thread in every section, this would take at least 1 minute for every search if we don't find a way to cache the list.

To search the site I've made a simple Java program that work in this way:
1)Login and get the cookies
2)Download and parse all index thread and save the merged result as JSON (Only a list of threads no magnets here, there is no need to download the list every time)
3)Load the JSON and do a fuzzy search on the thread name
4)List result
5)When i click on a result the program send a "thank you" to the thread and parse the response to get the magnets
 
I don't think something like this is possible in Jackett

**Comment by Zhoth** [comment]
Hi guys, any news on this tracker? Here in Italy it's the best one and without it we lose many high quality releases.

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/3189#issuecomment-851449100

**Comment by antanilol** [comment]
I just discovered Jackett and I was looking for this tracker too, fortunately I am a C# developer but unfortunately I don't know Jackett and Torznab/Newznab. Can someone give me a hint of where to start to build an indexer? I'll look into it when I have some free time

**Comment by ilike2burnthing** [comment]
For examples of current C# indexers - https://github.com/Jackett/Jackett/tree/master/src/Jackett.Common/Indexers

Currently there's no documentation for C# indexers, but there is for yaml indexers which may help you find your footing - https://github.com/Jackett/Jackett/wiki/Definition-format

Torznab categories - https://github.com/Jackett/Jackett/wiki/Jackett-Categories

See our contributing guide, including environment setup - https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#contributing-code

**Comment by MattiaCalabrese** [comment]
Hello guys, I tried implementing the indexer using the yml definition and I think I almost got it working.
I am still not sure if it could work with posts having multiple magnet links (maybe they could be filtered by season/episode in order to obtain a single url from that list) and some things are still missing (such as categories or filters).
At the moment, I managed to reach the search results page but then an exception is raised stating "The string did not match the expected pattern".
If someone wants to try understanding why the error occurs, this is what I've done:
`---
id: ilcorsaroverde
name: Il Corsaro Verde
description: "Il Corsaro Verde"
language: it-IT
type: private
encoding: UTF-8
links:
  - https://www.icv-crew.com/
legacylinks:
  - https://www.icv-crew.com/

caps:
  categorymappings:
    - {id: 0, cat: Unknown, desc: ""}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: sort
    type: select
    label: Sort requested from site
    default: 3
    options:
      3: created
      5: seeders
      4: size
      2: title
  - name: type
    type: select
    label: Order requested from site
    default: 2
    options:
      2: desc
      1: asc
  - name: info
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>100</b> on your account profile.

login:
  method: form
  path: forum/index.php
  form: form#frmLogin
  inputs:
    user: "{{ .Config.username }}"
    passwrd: "{{ .Config.password }}"
  error:
    - selector: form#frmLogin
  test:
    path: forum/index.php
    # [OPTIONAL] check this selector (must match)
    selector: li#button_logout

download:
  before:
    pathselector:
      selector: a.thank_you_button_link
      attribute: href
  selectors:
    - selector: a[href^="magnet:?xt="]
      attribute: href

search:
  paths:
    - path: forum/index.php?action=search2
      method: post
      followredirect: false
  inputs:
    search: "{{ if .Query.IMDBID }}{{ .Query.IMDBIDShort }}{{ else }}{{ .Keywords }}{{ end }}"

  rows:
    selector: table > tbody > tr > td#sp_center" > form > div.search_results_posts

  fields:
    title:
      selector: div.topic_details a[href~=topic]
    category:
      selector: div.topic_details a[href~=board]
    download:
      selector: div.topic_details a[href~=topic]
      attribute: href
# xbtitFM v1.16
`

**Comment by garfield69** [comment]
>The string did not match the expected pattern

most likely due to the single quote on the rows selector.

**Comment by MattiaCalabrese** [comment]
>  most likely due to the single quote on the rows selector.
Oops, I missed it. 
By the way, after some other tweaks, it roughly works now!

<img width="1360" alt="Screenshot 2021-11-10 at 19 01 40" src="https://user-images.githubusercontent.com/48023568/141168233-895886a0-cf80-4e2a-8d87-72cfaa17bdc4.png">
<img width="1156" alt="Screenshot 2021-11-10 at 19 01 23" src="https://user-images.githubusercontent.com/48023568/141168239-cecfdd12-32e9-45b0-b140-fc7721f09ea6.png">

**Comment by monelivorno** [comment]
> > molto probabilmente a causa della singola virgoletta nel selettore di righe.
> 
> Ops, me lo ero perso. A proposito, dopo alcune altre modifiche, ora funziona più o meno!
> 
> <img alt="Schermata 2021-11-10 alle 19 01 40" width="1360" src="https://user-images.githubusercontent.com/48023568/141168233-895886a0-cf80-4e2a-8d87-72cfaa17bdc4.png">
> 
> <img alt="Schermata 2021-11-10 alle 19 01 23" width="1156" src="https://user-images.githubusercontent.com/48023568/141168239-cecfdd12-32e9-45b0-b140-fc7721f09ea6.png">

Hi Mattia, could you attach the new code? so I add it and do some tests.

Grazie mille :-)

**Comment by MattiaCalabrese** [comment]
> Hi Mattia, could you attach the new code? so I add it and do some tests.

Of course! I was trying to map categories and other information but I'm running through some problems..
[ilcorsaroverde.txt](https://github.com/Jackett/Jackett/files/7520189/ilcorsaroverde.txt)
.

**Comment by monelivorno** [comment]
> > Hi Mattia, could you attach the new code? so I add it and do some tests.
> 
> Of course! I was trying to map categories and other information but I'm running through some problems...
> 
> [ilcorsaroverde.txt](https://github.com/Jackett/Jackett/files/7520189/ilcorsaroverde.txt)

Sorry but I can't get it to work correctly, opening the console I see that it gives results in line with the searched pattern but does not return them correctly in Jackett.

I would like to actively contribute to developing it but I don't know how to program.

How can I help you?

**Comment by MattiaCalabrese** [comment]
> Sorry but I can't get it to work correctly

I just tried it again and it works for me. I guess you didn't uncomment the commented lines, I couldn't get it working with categories and dates mapping.
Note that many ISPs in Italy block all the requests to the website, so you need a proxy or a vpn: maybe, that's the problem.

**Comment by ilike2burnthing** [comment]
Updated the indexer:
<details>
<summary>ilcorsaroverde.yml</summary>

```yml
---
id: ilcorsaroverde
name: Il Corsaro Verde
description: "Il Corsaro Verde (iCV-CreW) is a ratioless ITALIAN Private Torrent Tracker for MOVIES / TV / GENERAL"
language: it-IT
type: private
encoding: UTF-8
links:
  - https://www.icv-crew.com/

caps:
  # dont forget to update the $raw input in the search block
  # commented out categories are just discussion forums
  categorymappings:
    #CIURMA
#    - {id: "150", cat: Other, desc: "Regole per Postare"}
    - {id: "140", cat: Other/Misc, desc: "Bozze - Sezione fruibile a tutti i nuovi Releaser"}
    #INFORMAZIONI E REGOLE DEL FORUM 
#    - {id: "108", cat: Other, desc: "Manifesto Generale"}
#    - {id: "30", cat: Other, desc: "Disclaimer"}
#    - {id: "76", cat: Other, desc: "Statuto"}
#    - {id: "31", cat: Other, desc: "Comunicazioni dello STAFF"}
#    - {id: "32", cat: Other, desc: "Guide sull'uso del Forum"}
#    - {id: "124", cat: Other, desc: "iCV Community"}
    #PROGETTI
#    - {id: "172", cat: Audio, desc: "Progetto - Discografie"}
#    - {id: "109", cat: Movies, desc: "Progetto - Filmografie"}
#    - {id: "110", cat: Books, desc: "Progetto - Biblico"}
#    - {id: "137", cat: Other, desc: "Progetto - Releaser/Crew"}
#    - {id: "126", cat: Movies, desc: "Progetto - Cine Vintage "}
    #MUSICA
    - {id: "19", cat: Audio, desc: "Musica Audio - Tutti i formati"}
    - {id: "20", cat: Audio/Video, desc: "Musica Video - Standard Definition - High Definition"}
#    - {id: "135", cat: Audio, desc: "Richieste Titoli Musica"}
    #VIDEO
    - {id: "6", cat: Movies/SD, desc: "Video - Screener"}
    - {id: "7", cat: Movies/SD, desc: "Video - Standard Definition"}
    - {id: "9", cat: Movies/HD, desc: "Video - High Definition H.264"}
    - {id: "74", cat: Movies/HD, desc: "Video - High Definition HEVC/H.265"}
    - {id: "11", cat: Movies/BluRay, desc: "Video - Blu-ray Full "}
    - {id: "8", cat: Movies/DVD, desc: "Video - DVD"}
    - {id: "95", cat: Movies, desc: "Video - Dispositivi Mobili (Portable)"}
    - {id: "79", cat: Movies, desc: "Video - TVRip - Standard Definition - High Definition"}
    - {id: "14", cat: TV/Other, desc: "Video - Documentari - Sportivi - Spettacoli - Lirica - Standard Definition - High Definition "}
#    - {id: "134", cat: Movies, desc: "Richieste Titoli Video"}
    #SERIE TV
    - {id: "12", cat: TV/SD, desc: "Serie TV - Standard Definition "}
    - {id: "102", cat: TV/HD, desc: "Serie TV - High definition H.264"}
    - {id: "161", cat: TV/HD, desc: "Serie TV - High definition HEVC/H.265"}
#    - {id: "103", cat: TV, desc: "L'angolo di Giuseppe-iCV & littlelinx"}
#    - {id: "160", cat: TV, desc: "L'angolo di Pir8"}
#    - {id: "169", cat: TV, desc: "L'angolo di TV-P2P"}
#    - {id: "133", cat: TV, desc: "Richieste Titoli Serie TV"}
    #CARTONI ANIMATI - ANIME 
    - {id: "17", cat: Movies/SD, desc: "Cartoni Animati - Standard Definition - High Definition"}
    - {id: "18", cat: TV/HD, desc: "Cartoni Animati - Serie TV Standard Definition - High Definition"}
    - {id: "15", cat: TV/Anime, desc: "Anime - Standard Definition - High Definition"}
    - {id: "16", cat: TV/Anime, desc: "Anime - Serie TV Standard Definition - High Definition"}
    - {id: "89", cat: Movies/HD, desc: "Cartoni Animati - Anime - Serie Tv e Non - High Definition - HEVC/H.265"}
#    - {id: "132", cat: TV/Anime, desc: "Richieste Titoli Cartoni Animati - Anime"}
    #EBOOK - FUMETTI - RIVISTE - QUOTIDIANI
    - {id: "25", cat: Books/EBook, desc: "Ebook"}
    - {id: "26", cat: Audio/Audiobook, desc: "Ebook Audio"}
    - {id: "170", cat: Books/Comics, desc: "Fumetti"}
    - {id: "28", cat: Books/Mags, desc: "Riviste - Quotidiani"}
    - {id: "47", cat: Other, desc: "Wallpapers - Poster - Calendari"}
#    - {id: "131", cat: Movies, desc: "Richieste Titoli Ebook - Fumetti - Riviste"}
    #SOFTWARE
    - {id: "21", cat: PC/0day, desc: "Windows Software"}
#    - {id: "22", cat: PC, desc: "Windows Guide e altre in generale"}
#    - {id: "92", cat: PC, desc: "Windows Supporto "}
    - {id: "138", cat: PC/Mac, desc: "macOS Software"}
#    - {id: "162", cat: PC/Mac, desc: "macOS Guide"}
#    - {id: "163", cat: PC/Mac, desc: "macOS Supporto"}
#    - {id: "164", cat: PC/Mac, desc: "Hackintosh Guide"}
#    - {id: "165", cat: PC/Mac, desc: "Hackintosh Supporto"}
    - {id: "23", cat: PC, desc: "Linux Software"}
#    - {id: "168", cat: PC, desc: "Linux Guide"}
#    - {id: "93", cat: PC, desc: "Linux Supporto"}
    - {id: "24", cat: PC, desc: "Guide & Tutorial Video"}
#    - {id: "129", cat: PC, desc: "Richieste Titoli Software"}
    #GAMES
    - {id: "36", cat: PC/Games, desc: "Games - Pc Windows"}
    - {id: "158", cat: PC/Mac, desc: "Games - macOS"}
    - {id: "37", cat: Console/XBox 360, desc: "Games - Console Microsoft Xbox 360"}
    - {id: "38", cat: Console/PS3, desc: "Games - Console Sony PS3"}
    - {id: "152", cat: Console/PS4, desc: "Games - Console Sony PS4"}
#    - {id: "99", cat: PC/Games, desc: "Games - Supporto"}
#    - {id: "123", cat: PC/Games, desc: "Games - Guide"}
#    - {id: "130", cat: PC/Games, desc: "Richieste Titoli Games"}
    #ANDROID
    - {id: "58", cat: PC/Mobile-Android, desc: "Android Apps"}
#    - {id: "144", cat: PC/Mobile-Android, desc: "Android Guide"}
#    - {id: "128", cat: PC/Mobile-Android, desc: "Richieste Titoli Android"}
    #TEAM GRAFICO
#    - {id: "88", cat: Other, desc: "Vetrina Grafica"}
#    - {id: "100", cat: Other, desc: "Tutorial Photoshop CC"}
    #TAVERNA DEI CORSARI
#    - {id: "39", cat: Other, desc: "Presentati alla Community"}
#    - {id: "112", cat: Other, desc: "Assistenza Forum"}
#    - {id: "33", cat: Other, desc: "Chiacchiere in generale"}
#    - {id: "83", cat: Other, desc: "Commenti Titoli "}
#    - {id: "136", cat: Other, desc: "Sondaggi"}
#    - {id: "145", cat: Other, desc: "il CorSaRo VeRde App"}
    #ARCHIVIO FORUM
    - {id: "171", cat: PC/0day, desc: "Windows Software obsoleto"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: info30s
    type: info
    label: 30s Delay for Searches
    default: The site forces a 30s delay between searches, so you may get zero results if you perform searches too close together.

login:
  method: form
  path: forum/index.php
  form: form#frmLogin
  inputs:
    user: "{{ .Config.username }}"
    passwrd: "{{ .Config.password }}"
    cookieneverexp: on
  error:
    - selector: p[class="error"]
  test:
    path: forum/index.php
    selector: li#button_logout

download:
  before:
    pathselector:
      selector: a.thank_you_button_link
      attribute: href
  selectors:
    - selector: a[href^="magnet:?xt="]
      attribute: href

search:
  paths:
    - path: forum/index.php?action=search2
      method: post
  inputs:
    $raw: "{{ if .Categories }}{{ range .Categories }}brd[]={{.}}&{{end}}{{ else }}brd[]=140&brd[]=19&brd[]=20&brd[]=6&brd[]=7&brd[]=9&brd[]=74&brd[]=11&brd[]=8&brd[]=95&brd[]=79&brd[]=14&brd[]=12&brd[]=102&brd[]=161&brd[]=17&brd[]=18&brd[]=15&brd[]=16&brd[]=89&brd[]=25&brd[]=26&brd[]=170&brd[]=28&brd[]=47&brd[]=21&brd[]=138&brd[]=23&brd[]=24&brd[]=36&brd[]=158&brd[]=37&brd[]=38&brd[]=152&brd[]=58&brd[]=171{{ end }}"
    search: "{{ if .Keywords }}{{ .Keywords }}{{ else }}{{ .Today.Year }}{{ end }}"
    searchtype: 1
    userspec: "*"
    sort: id_msg|desc
    show_complete: 1
    subject_only: 1
    minage: 0
    maxage: 9999

  keywordsfilters:
    - name: re_replace
      args: ["(\\w+)", " +$1"] # prepend + to each word, all keywords must be 2 characters or more

  rows:
    selector: div.search_results_posts

  fields:
    category:
      selector: a[href*="index.php?board="]
      attribute: href
      filters:
        - name: querystring
          args: board
        - name: split
          args: [".", 0]
    title:
      selector: a[href*="index.php?topic="]
      filters:
        # normalize to SXXEYY format
        - name: re_replace # Stagione XX a YY --> SXX-YY
          args: ["(?i)\\bStagion[ei]\\s?(\\d{2,})\\s[ae]\\s(\\d{2,})\\b", "S$1-$2"]
        - name: re_replace # Stagione XX --> SXX
          args: ["(?i)\\bStagion[ei]\\s?(\\d{2,})\\b", "S$1"]
        - name: re_replace # Stagione X a YY --> S0X-YY
          args: ["(?i)\\bStagion[ei]\\s?(\\d{1})\\s[ae]\\s(\\d{2,})\\b", "S0$1-$2"]
        - name: re_replace # Stagione X a Y --> S0X-0Y
          args: ["(?i)\\bStagion[ei]\\s?(\\d{1})\\s[ae]\\s(\\d{1})\\b", "S0$1-$02"]
        - name: re_replace # Stagione X --> S0X
          args: ["(?i)\\bStagion[ei]\\s?(\\d{1})\\b", "S0$1"]
        - name: re_replace # rimozioni varie
          args: ["(?i)(Serie completa|Completat?a?|in pausa)", ""]
        # cleanup for Sonarr
        - name: re_replace # EP 3 4 to E3-4
          args: ["(?i)\\sEP\\s(\\d{1,2})\\s(E?\\s?\\d{1,2})\\s", " E$1-$2 "]
        - name: re_replace # S02E04 05 to S02E04-05
          args: ["(?i)\\sS(\\d{1,2})\\s?E\\s?(\\d{1,2})\\s(E?\\s?\\d{1,2})\\s", " S$1E$2-$3 "]
        - name: re_replace
          args: ["(?i)HDTVRIP", "HDTV"]
    details:
      selector: a[href*="index.php?topic="]
      attribute: href
    download:
      selector: a[href*="index.php?topic="]
      attribute: href
    date:
      selector: span.smalltext em
      filters:
        - name: replace
          args: ["Gennaio", "January"]
        - name: replace
          args: ["Febbraio", "February"]
        - name: replace
          args: ["Marzo", "March"]
        - name: replace
          args: ["Aprile", "April"]
        - name: replace
          args: ["Maggio", "May"]
        - name: replace
          args: ["Giugno", "June"]
        - name: replace
          args: ["Luglio", "July"]
        - name: replace
          args: ["Agosto", "August"]
        - name: replace
          args: ["Settembre", "September"]
        - name: replace
          args: ["Ottobre", "October"]
        - name: replace
          args: ["Novembre", "November"]
        - name: replace
          args: ["Dicembre", "December"]
        - name: append
          args: " +01:00" # CET
        - name: dateparse
          args: "02 January 2006, 15:04:05 -07:00"
    size:
      text: 512 MB
    poster:
      selector: img.bbc_img
      attribute: src
      filters:
        - name: replace
          args: ["https://www.icv-crew.com/forum/proxy.php?request=", ""]
        - name: urldecode
    imdbid:
      selector: a[href*="imdb.com/title/tt"]
      attribute: href
    seeders:
      text: 1
    leechers:
      text: 1
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# SMF 2.0.15

```
</details>

It's a bit of a weird site, it uses public trackers instead of its own private one, it updates old posts instead of posting new torrents separately, so you end up with 2021 releases that are dated 2017, and most of the categories are just discussion forums, so the indexer has to be really awkwardly written for when categories aren't specified.

Size, seeds, and peers are all hidden behind the thank you button, so nothing we can do about that.

Test that out, let me know if you find any issues, and I'll come back to it tomorrow.
