### ISSUE TITLE
AwesomeHD doesn't break down results by release?

### ISSUE THREAD

**Issue by Isomorpheuss** [Jackett/Jackett#3837]
Is this intentional? Instead of breaking down the results by each release it seems to be one result (with the file size corresponding to the max file size of all releases for that movie?).

**Comment by garfield69** [comment]
probably the indexer has fallen behind on changes that the web site has made to their html results page.
I don't have a login for this private tracker, so you could wait to see if @kaso17  does and has the time to investigate, *OR* you could expedite this a bit by performing the following task:
Please provide the **full enhanced log** file. 
1. scroll down to the bottom of the Jackett Dashboard and *tick* the *enhanced Logging* checkbox
2. scroll up a bit and *click* on the *apply server settings* button
3. repeat the test
4. find the *log.txt* file (linux `~/.config/Jackett/`, windows `%ProgramData%\Jackett`)
5. edit it with a plain text editor, redacting any personal details, usernames, passwords, passkeys, hashes etc.
6. save, then drag-drop it here for us to take a look at.
Thanks.

**Comment by Isomorpheuss** [comment]
I'm a developer. I'll just fix it if I can.

I have it partially working now. But, I haven't gotten the titles working properly. Each row doesn't contain the title information; they only contain the details for the release e.g. `CHD / x264 / 720p / Blu-ray / DTS / AHD Gold + DXVA`. The title is in some header elsewhere.

Is there a way to store that title somehow and then append it to each of the releases?

**Comment by Isomorpheuss** [comment]
Related
https://github.com/cardigann/cardigann/issues/42#issuecomment-251064696

**Comment by garfield69** [comment]
Hmm. 
@Isomorpheuss  I don't think the Jackett Cardigann processor supports title-header rows yet, but given we already do something similar for dates, I shouldn't think it would be too difficult to clone and customise it for titles. 
@kaso17  it looks like we could use a variation of the dateheaders block in this case, but for titles, as described in the wiki https://github.com/Jackett/Jackett/wiki/Definition-format#search
```yaml
      dateheaders: # optional selector for rows containing dates.
                   # Use this if the torrent result rows don't contain a publish date but
                   # a previous row contains the date.
                   # The indexer will go back and parse the first sibling element matching
                   # the selector as date for that torrent.
        selector: ":has(td.colhead[title]:contains(\"Torrents from\") > b)"
```
What do you think?
