### ISSUE TITLE
[REQ]arenabg.com

### ISSUE THREAD

**Issue by celeroll** [Jackett/Jackett#3989]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue. Duplicating issues makes it more difficult for everyone to follow. Your issue may have already been solved in the past as well.

Provide a description of the feature request or bug, the more details the better.
If you are experiencing an issue with a tracker, a **full enhanced log must be included**. Instructions for obtaining logs are here: https://github.com/Jackett/Jackett#troubleshooting

**Jackett version**:  
**Mono version** (if not using Windows):  

-------------------------------
Please add support for this tracker. 
Registrations are open.

https://arenabg.com

semi-private bulgarian tracker

**Comment by celeroll** [comment]
I think the tracker is semi privat! To be able to download you need to login.

**Comment by ward0** [comment]
are you sure its not a fake one? why not use .to or .bg?

**Comment by garfield69** [comment]
@ward0 huh? please provide the full addressess that you are referring to.  https://arenabg.bg/ https://arenabg.to/ do not resolve for me.

**Comment by celeroll** [comment]
> are you sure its not a fake one? why not use .to or .bg?

100% sure its NOT fake. It is exisiting since 15 years. But @garfield69  has added info into my first post that the tracker is public, but to be able to download you have to register (open registrations).

**Comment by celeroll** [comment]
How can I help to get this tracker into release?
One example for a category movies:
https://arenabg.com/torrents/type:movies/

**Comment by garfield69** [comment]
I've registered. when free time allows I'll take a look at try to build an indexer.

**Comment by garfield69** [comment]
@kaso17  I'm having trouble with arenabg.com.

for torrent searching I have to use their form with a POST, but I get back a redirect which seems to fool Jackett into a 0-results error.
It seems that the site creates a search-session url for the returned results, which I don't think cardigann can handle.
here is the relevant enhanced log
```
2018-10-21 17:25:35.9256 Debug WebClient(HttpWebClient).GetString(Url:https://arenabg.com/torrents/)
2018-10-21 17:25:37.2368 Debug WebClient(HttpWebClient): Returning Redirect => https://arenabg.com/torrents/search:high+castle/time:jrHyVCRUHEiFq12VigHS8_tCLm1yYsf6QBwx5Ln4Pyc/
2018-10-21 17:25:37.2458 Info Manual search for "high castle" on arenabg with 0 results.
```
if I use the returned redirect link from a browser I see the results I expect.
The **time:** in the redirect link is a generated string by the site in response to the search POST, it is not part of the POST data I prepare, and seems to change every day (or perhaps every login session).

any idea how to handle this?
is this a case of having to switch to using c# instead of yaml?

this is my indexer so far:
```yaml
---
  site: arenabg
  name: ArenaBG
  description: "ArenaBG is a BULGARIAN Semi-Private Torrent Tracker for 0DAY / GENERAL"
  language: bg-BG
  type: semi-private
  encoding: UTF-8
  links:
    - https://arenabg.com/

  caps:
    categorymappings:
      - {id: "movies", cat: Movies, desc: "Movies"}
      - {id: "arenabgtv", cat: Movies, desc: "Movies / ArenaBG.TV"}
      - {id: "xvid", cat: Movies, desc: "Movies / XviD"}
      - {id: "dvd-r", cat: Movies, desc: "Movies / DVD-R"}
      - {id: "x264", cat: Movies, desc: "Movies / x264"}
      - {id: "animemanga", cat: Movies, desc: "Movies / Anime &amp; Manga"}
      - {id: "documentaries", cat: Movies, desc: "Movies / Documentaries"}
      - {id: "blu-ray", cat: Movies, desc: "Movies / Blu-ray"}
      - {id: "boxset", cat: Movies, desc: "Movies / Boxset"}
      - {id: "x264boxset", cat: Movies, desc: "Movies / x264 Boxset"}
      - {id: "tvepisodeshd", cat: Movies, desc: "Movies / HDTV"}
      - {id: "3d", cat: Movies, desc: "Movies / 3D"}
      - {id: "movies-hd", cat: Movies, desc: "Movies / Movies HD"}
      - {id: "x265", cat: Movies, desc: "Movies / x265"}
      - {id: "series", cat: TV, desc: "Series"}
      - {id: "hdtv", cat: TV, desc: "Series / TV Episodes HD"}
      - {id: "tvepisodes", cat: TV, desc: "Series / TV Episodes"}
      - {id: "tvboxset", cat: TV, desc: "Series / TV Boxset"}
      - {id: "tvboxsethd", cat: TV, desc: "Series / TV Boxset HD"}
      - {id: "music", cat: Audio, desc: "Music"}
      - {id: "mp3", cat: Audio, desc: "Music / MP3"}
      - {id: "music-video", cat: Audio, desc: "Music / Video"}
      - {id: "flac", cat: Audio, desc: "Music / FLAC"}
      - {id: "music-dvd", cat: Audio, desc: "Music / DVD"}
      - {id: "music-ape", cat: Audio, desc: "Music / APE"}
      - {id: "music-dts", cat: Audio, desc: "Music / DTS"}
      - {id: "musicwavpack", cat: Audio, desc: "Music / WavePack"}
      - {id: "musicost", cat: Audio, desc: "Music / OST"}
      - {id: "games", cat: PC, desc: "Games"}
      - {id: "games-iso", cat: PC, desc: "Games / PC ISO"}
      - {id: "pc-rip", cat: PC, desc: "Games / PC RIP"}
      - {id: "ps2", cat: Console, desc: "Games / PS2"}
      - {id: "psp", cat: Console, desc: "Games / PSP"}
      - {id: "xbox", cat: Console, desc: "Games / XBOX"}
      - {id: "xbox-360", cat: Console, desc: "Games / XBOX-360"}
      - {id: "ps3", cat: Console, desc: "Games / PS3"}
      - {id: "wii", cat: Console, desc: "Games / WII"}
      - {id: "PS4", cat: Console, desc: "Games / PS4"}
      - {id: "software", cat: PC, desc: "Software"}
      - {id: "pc-iso", cat: PC, desc: "Software / PC ISO"}
      - {id: "pdasmartphone", cat: PC, desc: "Software / Smartphone"}
      - {id: "tutorial", cat: PC, desc: "Software / Tutorial"}
      - {id: "android", cat: PC, desc: "Software / Android"}
      - {id: "ios", cat: PC, desc: "Software / iOS"}
      - {id: "misc", cat: Other, desc: "Misc"}
      - {id: "other", cat: Other, desc: "Misc / Other"}
      - {id: "e-books", cat: Other, desc: "Misc / e-Books"}
      - {id: "sports", cat: Other, desc: "Misc / Sports"}
      - {id: "0-day", cat: Other, desc: "Misc / 0-Day"}
      - {id: "xxx", cat: XXX, desc: "XXX"}
      - {id: "porn", cat: XXX, desc: "XXX / Porn"}
      - {id: "xxx-hd", cat: XXX, desc: "XXX / XXX HD"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  login:
    path: /
    method: form
    form: form[action="/users/"]
    inputs:
      email: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
      action: login
    error:
      - selector: div.row div div.alert i.fa-warning
        message:
          selector: div.row div div.alert
    test:
      path: /
      selector: a[href="/users/logout/"]

  download:
    selector: a[href^="magnet:?"]

  search:
    paths:
      - path: /torrents/
        method: post
    inputs:
      text: "{{ if .Keywords }}{{ .Keywords }}{{else}}{{end}}"
      "text_mobile": ""
      type: 0
      audio: 0
      subtitles: 0
      action: search

    rows:
      selector: tr:has(td.category)
    fields:
      title:
        # use the second div for full title
        selector: td.filename div:nth-child(2) a
      details:
        selector: td.filename div a
        attribute: href
      category:
        selector: td.category a
        attribute: href
        filters:
          - name: re_replace
            args: ["/torrents/type:(.+?)/", "$1"]
      download:
        selector: td.filename div a
        attribute: href
      size:
        selector: td:nth-child(4)
      date:
          # 08:49:09
        selector: td:nth-child(3):has(":")
        optional: true
        filters:
          - name: dateparse
            args: "15:04:05"
      date:
          # 2018-10-19
        selector: td:nth-child(3):has("-")
        optional: true
        filters:
          - name: dateparse
            args: "2006-01-02"
      seeders:
        selector: td:nth-child(6)
        filters:
          - name: replace
            args: ["-", "0"]
          - name: replace
            args: ["DHT", "0"] # torrent can only be downloaded via DHT
      leechers:
        selector: td:nth-child(7)
        filters:
          - name: replace
            args: ["-", "0"]
      grabs:
        selector: td:nth-child(8)
        filters:
          - name: replace
            args: ["-", "0"]
      banner:
        selector: td.filename div:nth-child(2) a
        attribute: onmouseover
        filters:
          - name: regexp
            args: src=\\'([^\s\\]+)
      downloadvolumefactor:
        text: "0"
      uploadvolumefactor:
        text: "1"
```
