### ISSUE TITLE
[REQ] mojblink

### ISSUE THREAD

**Issue by corshamboy** [Jackett/Jackett#4090]
https://www.mojblink.si/ 
Slovenian Private
Please can you add this website to the list of trackers it is one of the best i can send a invite if required they are a members only service with a strict sharing rule but have good quality items and is easy to use and is Slovenian based thanks

**Comment by kaso17** [comment]
If you know a little HTML/CSS you can try to add it yourself.
See https://github.com/Jackett/Jackett/wiki/Definition-format for details.
If you've any questions feel free to ask.

If the tracker already provides some kind of API (e.g. gazelle based trackers) please let us know. Then the Cardigann definition approach might be not not the best solution

**Comment by corshamboy** [comment]
Hi thanks for getting back to me but i do have any programing knowledge to do what you advised to do thanks Richard

**Comment by garfield69** [comment]
site not responding
![image](https://user-images.githubusercontent.com/6933240/52195358-71387980-28bc-11e9-9e5c-25342518acab.png)

**Comment by garfield69** [comment]
never mind, just slow is all.

**Comment by garfield69** [comment]
If you send an invite to garfield69 at outlook.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by krniki** [comment]
I can provide an invite, if somebody is going to work on this.

**Comment by garfield69** [comment]
@krniki wrote:
> I can provide an invite, if somebody is going to work on this.

If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
Registration completed. Thank you.
Pending inviter to confirm my account.

**Comment by garfield69** [comment]
Seems I can login now, thank you.

**Comment by garfield69** [comment]
Bugger. Found a fly in my soup.

Everything was working perfectly, I can search and get results, download, etc.
However, the site has one quirk. 
If you search for a title and there is only one result, the site does not present the search results page, but jumps straight to the details page.
I have tried to get the cardigann processor to handle this, but it appears that when the site redirects to the details page it also wants a login check, and for some reason, cardigann fails to provide the cookie saved from the login at the start of the session or some other crap.

I'm going to need a C# dev to analyse what is going on. I'll provide temp credentials for some volunteer to investigate.
this is the yaml indexer so far:
```yaml
---
id: mojblink
name: MOJBLiNK
description: "MOJBLiNK is a Private Slovanian Torrent Tracker for MOVIES / TV / GENERAL"
language: sl
type: private
encoding: UTF-8
followredirect: true
links:
  - https://www.mojblink.si/

caps:
  categorymappings:
    - {id: 50, cat: Movies, desc: "BLiNK"}
    - {id: 20, cat: Books/EBook, desc: "eBook eBOOK"}
    - {id: 52, cat: Books/Other, desc: "eBook Education"}
    - {id: 53, cat: Books/Mags, desc: "eBook Magazine"}
    - {id: 62, cat: PC/Mobile-Android, desc: "GAMES Android"}
    - {id: 12, cat: Console/NDS, desc: "GAMES Nintendo DS"}
    - {id: 8, cat: PC/Games, desc: "GAMES PC"}
    - {id: 7, cat: PC/Games, desc: "GAMES PCRip"}
    - {id: 13, cat: Console/PS3, desc: "GAMES Playstation"}
    - {id: 124, cat: Console/PS4, desc: "GAMES PS4"}
    - {id: 16, cat: Console/PSP, desc: "GAMES PSP"}
    - {id: 65, cat: Console/Wii, desc: "GAMES Wii"}
    - {id: 15, cat: Console/XBox, desc: "GAMES Xbox"}
    - {id: 21, cat: Other, desc: "IMAGES Pics"}
    - {id: 68, cat: Other, desc: "IMAGES Wallpaper"}
    - {id: 70, cat: Movies/SD, desc: "Impatient CAM"}
    - {id: 71, cat: Movies/SD, desc: "Impatient DVDSCR"}
    - {id: 72, cat: Movies/SD, desc: "Impatient TC"}
    - {id: 73, cat: Movies/SD, desc: "Impatient TS"}
    - {id: 75, cat: Movies/SD, desc: "Impatient WEBRip"}
    - {id: 121, cat: Movies/UHD, desc: "MOVIES 4K"}
    - {id: 6, cat: Movies, desc: "MOVIES Animation"}
    - {id: 37, cat: TV/Anime, desc: "MOVIES Anime"}
    - {id: 40, cat: Movies/BluRay, desc: "MOVIES BD25"}
    - {id: 39, cat: Movies/BluRay, desc: "MOVIES BD50"}
    - {id: 41, cat: Movies/BluRay, desc: "MOVIES BDRip"}
    - {id: 4, cat: Movies/BluRay, desc: "MOVIES BluRay 1080p"}
    - {id: 3, cat: Movies/BluRay, desc: "MOVIES BluRay 720p"}
    - {id: 43, cat: Movies/BluRay, desc: "MOVIES BRRip x264"}
    - {id: 44, cat: Movies/BluRay, desc: "MOVIES BRRip XviD"}
    - {id: 25, cat: TV/Documentary, desc: "MOVIES Documentary"}
    - {id: 46, cat: Movies/DVD, desc: "MOVIES DVD"}
    - {id: 47, cat: Movies/DVD, desc: "MOVIES DVDRip x264"}
    - {id: 115, cat: Movies/DVD, desc: "MOVIES DVDRip x265"}
    - {id: 1, cat: Movies/DVD, desc: "MOVIES DVDRip XviD"}
    - {id: 48, cat: Movies/DVD, desc: "MOVIES HD2DVD"}
    - {id: 123, cat: Movies/HD, desc: "MOVIES HDRip"}
    - {id: 74, cat: Movies/WEB-DL, desc: "MOVIES Web-DL"}
    - {id: 120, cat: Movies/HD, desc: "MOVIES x265"}
    - {id: 55, cat: Audio/Video, desc: "MUSIC BD"}
    - {id: 23, cat: Audio/Video, desc: "MUSIC DVD"}
    - {id: 56, cat: Audio/Lossless, desc: "MUSIC FLAC"}
    - {id: 11, cat: Audio/MP3, desc: "MUSIC MP3"}
    - {id: 57, cat: Audio/Video, desc: "MUSIC MP4"}
    - {id: 58, cat: Audio/Video, desc: "MUSIC Video"}
    - {id: 26, cat: PC/Mobile-Android, desc: "PROGRAM Android"}
    - {id: 27, cat: PC/Mobile-iOS, desc: "PROGRAM iOS"}
    - {id: 78, cat: PC, desc: "PROGRAM Linux"}
    - {id: 79, cat: PC/Mac, desc: "PROGRAM Mac"}
    - {id: 9, cat: PC/ISO, desc: "PROGRAM PC ISO"}
    - {id: 80, cat: PC/0day, desc: "PROGRAM PC Win"}
    - {id: 5, cat: TV/HD, desc: "TV HDTV"}
    - {id: 82, cat: TV/HD, desc: "TV HDTVRip"}
    - {id: 2, cat: TV/SD, desc: "TV TVRip"}
    - {id: 85, cat: Movies/HD, desc: "UpLINK HEVC"}
    - {id: 86, cat: Movies/HD, desc: "UpLINK MPEG4"}
    - {id: 122, cat: XXX/Other, desc: "XXX Games"}
    - {id: 88, cat: XXX/Other, desc: "XXX Magazine"}
    - {id: 10, cat: XXX/x264, desc: "XXX Movies"}
    - {id: 89, cat: XXX/Pack, desc: "XXX Packs"}
    - {id: 90, cat: XXX/ImageSet, desc: "XXX Pics"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: 4
    options:
      4: created
      7: seeders
      5: size
      1: title
  - name: type
    type: select
    label: Order requested from site
    default: DESC
    options:
      DESC: desc
      ASC: asc
  - name: info_tpp
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>50</b> on your account profile.

login:
  path: takelogin.php
  method: post
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    submitme: "Prijava"
  error:
    - selector: div.content-wrapper:contains("Prijava ni uspela!")
  test:
    path: /
    selector: a[href*="/odjava?hash_insert="]

search:
  paths:
    # https://www.mojblink.si/brskanje?cat=0&search=justice+league&searchin=title&incldead=1&only_free=1
    - path: brskanje
      followredirect: true
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    search: "{{ .Keywords }}"
    # title, titledescr, descr
    searchin: title
    # 0 active, 1 all, 2 dead
    incldead: 1
    only_free: "{{ if .Config.freeleech }}1{{ else }}{{ end }}"
    st: 1
    sort: "{{ .Config.sort }}"
    type: "{{ .Config.type }}"
#  keywordsfilters:
#    - name: re_replace
#      args: ["(\\w+)", " +$1"] # prepend + to each word

  rows:
    # results page, single result details page
    selector: div.bgPreview, body.details

  fields:
    # clean up the details page
    cleanup:
      selector: body.details
      remove: header, section, script, aside
      optional: true
      filters:
        - name: strdump
          args: details
    category:
      selector: a[href^="/brskanje/"]
      attribute: href
      filters:
        - name: regexp
          args: (\d+)
    title:
      # from results page
      selector: a[href^="/podrobnosti/"]
      attribute: title
      optional: true
    title:
      # from details page
      selector: h1
      optional: true
    details:
      # from results page
      selector: a[href^="/podrobnosti/"]
      attribute: href
      optional: true
    details:
      # from details page
      selector: img#torrent-poster-image
      attribute: onError
      optional: true
      filters:
        - name: replace
          args: ["PosterError(", "/podrobnosti/"]
        - name: replace
          args: [");", ""]
    download:
      selector: a[href^="/download/"]
      attribute: href
    poster:
      # from results page
      selector: div.bgPreview
      attribute: data-original
    poster:
      # from details page
      selector: img#torrent-poster-image
      attribute: src
    imdb:
      selector: a[href^="/preusmeri?url="]
      attribute: href
      filters:
        - name: replace
          args: ["/preusmeri?url=", ""]
    files:
      # results, details
      selector: div.release-info__meta span, li[data-tab="tab__torrent_files"] span
    date:
      # results
      selector: div.release-info__meta:contains("Naložil:"):contains("Včeraj"), div.release-info__meta:contains("Naložil:"):contains("Danes"), div.release-info__meta:contains("Uploaded:"):contains("Včeraj"), div.release-info__meta:contains("Uploaded:"):contains("Danes")
      optional: true
      filters:
        - name: replace
          args: ["Uploaded: ", ""]
        - name: replace
          args: ["Naložil: ", ""]
        - name: replace
          args: ["Včeraj,", "Yesterday"]
        - name: replace
          args: ["Danes,", "Today"]
        - name: fuzzytime
    date:
      # results
      selector: div.release-info__meta:contains("Naložil:"):contains("."), div.release-info__meta:contains("Uploaded:"):contains(".")
      optional: true
      filters:
        - name: replace
          args: ["Uploaded: ", ""]
        - name: replace
          args: ["Naložil: ", ""]
        - name: append
          args: " +00:00" # auto adjusted by site account profile
        - name: dateparse
          args: "02.01.2006 15:04:05 -07:00"
    date:
      # details
      selector: div.entry-meta span:contains("Včeraj"), div.entry-meta span:contains("Danes")
      optional: true
      filters:
        - name: replace
          args: [", ", ""]
        - name: replace
          args: ["Naložil: ", ""]
        - name: replace
          args: ["Včeraj,", "Yesterday"]
        - name: replace
          args: ["Danes,", "Today"]
        - name: fuzzytime
    date:
      # details
      selector: div.entry-meta span:contains(".")
      optional: true
      filters:
        - name: replace
          args: [", ", ""]
        - name: append
          args: " +00:00" # auto adjusted by site account profile
        - name: dateparse
          args: "02.01.2006 15:04:05 -07:00"
    size:
      selector: a[href^="/download/"]
    seeders:
      # results, results, details
      selector: span[title="Sejalci"], span[title="Seeders"], li[data-tab="tab__peers_seeders"] span
    leechers:
      # results, results, details
      selector: span[title="Odjemalci"], span[title="Leechers"], li[data-tab="tab__peers_leechers"] span
    downloadvolumefactor:
      case:
        span.torrent-FL: 0
        "*": 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 4 days (as seconds = 4 x 24 x 60 x 60)
      text: 345600
# engine n/a
```
