### ISSUE TITLE
[req]: DivTeam

### ISSUE THREAD

**Issue by RicardoVelaC** [Jackett/Jackett#4671]
I would to add [DivTeam](https://divteam.com) to Jackett but I don't know if it compatible with cardigann indexer

I have some invitations

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will take a look.

**Comment by RicardoVelaC** [comment]
You have it

**Comment by garfield69** [comment]
registration and login successful. Thank you.

**Comment by garfield69** [comment]
at first glance it does appear to be suitable, for example, here is a torrent search:
https://divteam.com/index.php?page=torrents&search=daredevil&category=20;64;18;48;17&options=0&active=1
yields 3 hits that can be HTML scraped.

let me know if you're going to code the definition yourself or if you want me to do it. Cheers.

**Comment by RicardoVelaC** [comment]
Great, I don't know how to code from scratch. If you can maybe it will be better.

**Comment by garfield69** [comment]
try out Jackett pre-release v0.10.776

**Comment by RicardoVelaC** [comment]
Great, works perfect!!

**Comment by garfield69** [comment]
https://divteam.com/ been returning `Estamos en mantenimiento, volveremos en breve` for 3 days now.

**Comment by garfield69** [comment]
divteam site appears to be back in working order

**Comment by RicardoVelaC** [comment]
They've been in maintenance for 3 days, yes now everything works again.

**Comment by garfield69** [comment]
well that did not last long. site currently returning ERR_CONNECTION_TIMED_OUT

**Comment by garfield69** [comment]
back again, all good.

**Comment by garfield69** [comment]
https://divteam.com/ returning ERR_NAME_RESOLUTION_FAILED
just me, or is the site broken, gone or moved to a new domain?

**Comment by garfield69** [comment]
back online.

**Comment by ilike2burnthing** [comment]
https://divteam.com/
`Mantenimiento En breve reabriremos.`
`Maintenance We will soon reopen.`

**Comment by RicardoVelaC** [comment]
Now they are online, it's work Ok with Jackett v0.17.168

**Comment by garfield69** [comment]
https://divteam.com/ returns DNS_PROBE_FINISHED_NXDOMAIN (domain not found)

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
I'm getting
```
403 Forbidden
You are Banned from this site!
```

anyone else?

**Comment by ilike2burnthing** [comment]
Working ok here.

**Comment by garfield69** [comment]
ok. tah.

**Comment by MarkPott** [comment]
Hi @garfield69 can this indexer be removed? 

It's not allowed on this tracker to use RSS or automations and using this is like collecting points toward a ban (I know... got myself banned).

**Comment by garfield69** [comment]
Will do.

**Comment by garfield69** [comment]
v0.22.2056

**Comment by AARON8888** [comment]
Hi @MarkPott . The rules in tracker does not mention anything about "to use RSS or automations and using this is like collecting points toward a ban". The most important thing is to login once per three months and good ratio.
Maybe you´re banned due to other reasons, but not this one. I use Jackett to search many times in DivTeam without any problem more than a year.

So, @garfield69, please reconsider to add again this indexer therefore.

**Comment by garfield69** [comment]
I've asked a team member to validate (I don't have access but assumed the request was valid) and will restore if confirmed OK.

**Comment by ilike2burnthing** [comment]
From their FAQ (via machine translation):

> No, DivTeam does not host RSS feeds, nor does it condone any automation, bots, or indexing systems external to the community.
>
>External systems may be considered an attempt at fraudulent use of DivTeam, as well as a security issue for the community, and may result in instant banning of the user.
>
>We firmly believe that since uploaders and staff dedicate so much time to preparing, maintaining, and running the community, it's not enough to ask for a user to come in and enjoy the thanks, etc.

My account is also still active, but I'd say that's pretty definitive.

**Comment by acrespog** [comment]
No, please! I've been a Divteam user for years, and I only download via Jackett+Sonarr/Radarr. I'm a Senior user with an excellent ratio, and most users are like me. The admins encourage us to visit the website and use the community, but that is never a reason for bans, and they've stated this before. Please don't remove support for this tracker, as many of us use it daily. And no, that's not why the user above got banned.

**Comment by acrespog** [comment]
> Hi [@garfield69](https://github.com/garfield69) can this indexer be removed?
> 
> It's not allowed on this tracker to use RSS or automations and using this is like collecting points toward a ban (I know... got myself banned).

@MarkPott  You weren't banned for that. Ask around, and you'll see that's not the reason. It's likely for not accessing the site, not sharing, or similar reasons, as it's a very, very tolerant community. I've uploaded tens of TBs and downloaded a few TBs, all through Jackett/Sonarr/Radarr (100%), with a 24/7 NAS, and I've been doing that for years without any issues.

@garfield69 Please restore Divteam support. If someone doesn't want to use it, they don't have to, but for those of us who use it daily, this is causing a huge problem.

**Comment by garfield69** [comment]
Given that the DivTeam website's FAQ clearly states ` DivTeam does not host RSS feeds, nor does it condone any automation, bots, or indexing systems external to the community`, we will **not** officially support a Jackett indexer for this site, **until** we see an **OK from Admin**.
Until that OK is forthcoming, you may choose to use a personal indexer at your own risk.
- Restart your Jackett, 
- View the log from the dashboard and look for an info line like `Loading Cardigann indexers from:` near the bottom of the log. 
- The first folder is a good place to store personal copies of indexers.
- Use a plain text editor to create file divteam.yml at that location, and copy/paste the content of 
<details>

  <summary>Divteam.yml</summary>


```yaml
---
id: divteam
name: DivTeam
description: "DivTeam is a SPANISH Private Torrent Tracker for MOVIES / GENERAL"
language: es-ES
type: private
encoding: UTF-8
links:
  - https://divteam.com/

caps:
  categorymappings:
    - {id: 60, cat: Movies/HD, desc: "MicroHD 720p"}
    - {id: 77, cat: Movies/HD, desc: "MicroHD 1080p"}
    - {id: 78, cat: Movies/UHD, desc: "MicroHD 4K"}
    - {id: 64, cat: TV/HD, desc: "Pack Series"}
    - {id: 65, cat: TV/HD, desc: "Pack Series VOSE"}
    - {id: 80, cat: Movies/HD, desc: "BDRip X265 1080p"}
    - {id: 81, cat: Movies/UHD, desc: "UHDRip x265 4K"}
    - {id: 82, cat: Movies/WEB-DL, desc: "Pelis Web-DL 1080"}
    - {id: 83, cat: Movies/WEB-DL, desc: "Pelis Web-DL 720"}
    - {id: 84, cat: Movies/UHD, desc: "UHD Remux x265"}
    - {id: 91, cat: Movies/HD, desc: "BDRip x264"}
    - {id: 89, cat: Movies/HD, desc: "BDRemux"}
    - {id: 88, cat: Movies/BluRay, desc: "Full HD"}
    - {id: 90, cat: Movies/BluRay, desc: "UHD Full"}
    - {id: 92, cat: Movies/UHD, desc: "Web-DL UHD"}
    - {id: 23, cat: TV/Sport, desc: "Deportes"}
    - {id: 20, cat: TV/HD, desc: "Series"}
    - {id: 31, cat: TV/HD, desc: "Series VOSE"}
    - {id: 69, cat: Movies, desc: "Ciclo Cine Clasico"}
    - {id: 70, cat: Movies, desc: "Ciclo Clint Eastwood"}
    - {id: 71, cat: Movies, desc: "Ciclo Studio Ghibli"}
    - {id: 72, cat: Movies, desc: "Ciclo George A. Romero"}
    - {id: 73, cat: Movies, desc: "Saga Fast And Furious"}
    - {id: 74, cat: Movies, desc: "Saga Crepúsculo"}
    - {id: 75, cat: Movies, desc: "Saga The Purge"}
    - {id: 79, cat: Movies, desc: "Saga Star Wars"}
    - {id: 76, cat: Movies, desc: "x-men saga"}
    - {id: 85, cat: Movies, desc: "Sean Connery"}
    - {id: 6, cat: Books/EBook, desc: "EBooks"}
    - {id: 58, cat: Books/Mags, desc: "Kiosko"}
    - {id: 24, cat: TV/Documentary, desc: "Documentales"}
    - {id: 32, cat: TV/Documentary, desc: "Documentales VOSE"}
    - {id: 49, cat: Books/Technical, desc: "eLearning"}
    - {id: 68, cat: Books/Technical, desc: "eLearning Multimedia"}
    - {id: 87, cat: Audio/Audiobook, desc: "Audiolibros"}
    - {id: 0, cat: Other, desc: "Otros"} # results can have a category of 0, but searching by category 0 returns all results

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings:
  - name: cookie
    type: text
    label: Cookie
  - name: info_cookie
    type: info_cookie
  - name: freeleech
    type: checkbox
    label: Filter freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: 3
    options:
      3: created
      5: seeders
      4: size
      2: title
  - name: type
    type: select
    label: Order requested from site
    default: 2
    options:
      2: desc
      1: asc
  - name: info_results
    type: info
    label: Results Per Page
    default: For best results, change the <b>Torrents per page:</b> setting to <b>100</b> on your account profile.
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "In principle, the STAFF reserves the right to delete any user who has not accessed the tracker in 90 days or has not downloaded/uploaded any contribution in the last 180 days, if you are going to be away for a while, park the account from your panel."

login:
  # using cookie method because login page has embedded Google reCAPTCHA
  method: cookie
  inputs:
    cookie: "{{ .Config.cookie }}"
  test:
    path: index.php
    selector: a[href="logout.php"]

search:
  paths:
    # https://divteam.com/index.php?page=torrents&search=daredevil&category=20;23;31;65;64;60;63;69;70;71;72;73;74;75;76;77;78;80;81;82;83;84&active=1
    - path: index.php
  inputs:
    page: torrents
    category: "{{ range .Categories }}{{.}};{{end}}"
    search: "{{ .Keywords }}"
    # 0 title, 1 title&desc, 2 descr, 3 uploaders, 5 gold, 6 silver, 9 2x, 10 3x, 11 4x, 12 5x
    # note the options are exclusive, so searching for gold means the search keywords are ignored
    options: 0
    # 0 all, 1 activeonly, 2 deadonly
    active: 0
    order: "{{ .Config.sort }}"
    by: "{{ .Config.type }}"
    # does not support imdbid search and does not supply imdb link in results.

  rows:
    selector: "table.table.table-bordered > tbody > tr:has(a[href^=\"download.php?id=\"]){{ if .Config.freeleech }}:has(img[src$=\"gold.gif\"]){{ else }}{{ end }}, table.table.table-bordered > tbody > tr:has(a[href^=\"download.php?id=\"]){{ if .Config.freeleech }}:has(img[src$=\"freeleech.gif\"]){{ else }}{{ end }}"

  fields:
    download:
      selector: a[href^="download.php?id="]
      attribute: href
    title_vose:
      selector: a[href^="index.php?page=torrent-details"][onmouseover]:contains("VOSE")
      optional: true
      filters:
        - name: append
          args: " English"
    title_notvose:
      selector: a[href^="index.php?page=torrent-details"][onmouseover]:not(:contains("VOSE"))
      optional: true
      filters:
        - name: append
          args: " MULTi/SPANiSH" # DivTeam doesn't bring languages. Usually Original + Spanish.
        - name: re_replace
          args: ["\\.+", "."] # More than 1 dot -> .
        - name: re_replace
          args: ["^\\.", ""] # Delete first dot
        - name: replace
          args: ["UHDRip", "Bluray-2160p"] # Fix for Radarr
        - name: replace
          args: ["2160p BDRip", "Bluray-2160p"] # Fix for Radarr
    title:
      text: "{{ if .Result.title_vose }}{{ .Result.title_vose }}{{ else }}{{ .Result.title_notvose }}{{ end }}"
    poster:
      selector: a[onmouseover][href^="index.php?page=torrent-details"]
      attribute: onmouseover
      filters:
        - name: regexp
          args: "src=(.*?) "
    category:
      selector: a[href^="index.php?page=torrents&category="]
      attribute: href
      filters:
        - name: querystring
          args: category
    details:
      selector: a[href^="index.php?page=torrent-details"]
      attribute: href
    size:
      selector: td:nth-child(4)
    date:
      selector: td:nth-child(6)
      # auto adjusted by site account profile
      filters:
        - name: dateparse
          args: "dd/MM/yyyy"
    seeders:
      selector: td:nth-last-child(4)
    leechers:
      selector: td:nth-last-child(3)
    grabs:
      selector: td:nth-last-child(2)
    downloadvolumefactor:
      case:
        img[src="images/freeleech.gif"]: 0
        img[src="images/gold.png"]: 0
        img[src="images/silver.png"]: 0.5
        "*": 1
    uploadvolumefactor:
      case:
        img[src="images/2x.png"]: 2
        img[src="images/3x.png"]: 3
        img[src="images/4x.png"]: 4
        img[src="images/5x.png"]: 5
        "*": 1
    minimumratio:
      text: 0.7
    minimumseedtime:
      # 2 days (as seconds = 2 x 24 x 60 x 60)
      text: 172800
# xbtit customised

```
</details>
and save.

- Restart Jackett to load.
