### ISSUE TITLE
[torrentscsv] Parse error: Error reading JArray from JsonReader. Path

### ISSUE THREAD

**Issue by buckmelanoma** [Jackett/Jackett#4676]
Hello.  I'm attempting to write a definition for [torrents.csv](https://torrents-csv.ml) but I'm having some difficulty.  The [site returns json](https://torrents-csv.ml/service/search?q=test) from it's search endpoint but Jackett seems to be completely geared towards parsing HTML.  The docs for Definitions don't really shed much light on this kind of data.  I've managed to get as far as being able to query the server through jackett but can't seem to manage to split the returned data into the fields jackett wants.  Here's my definition so far (based of btbit.yml) and [the source for torrents.csv](https://gitlab.com/dessalines/torrents.csv):
```
    site: torrentscsv
    name: Torrents.csv
    description: "torrents.csv"
    language: en-us
    type: public
    encoding: UTF-8
    links:
            - "https://torrents-csv.ml"

    caps:
      categories:
        "Movie": Movies
        "Package": PC/0day
        "Other": Other
        "Software": PC
        "Mirror": PC/ISO
        "Music": Audio
        "Picture": Other/Misc
        "Document": Books

      modes:
        search: [q]
        tv-search: [q, season, ep]
        movie-search: [q]

    settings: []

    search:
            paths:
                    - path: "/service/search?q={{ .Keywords }}&size=1"
            rows:
                    selector: selector: "body:contains(\"infohash\")"
            fields:
                    title:
                            selector: "body:contains(\"name\")"
                    download:
                            selector: "body:contains(\"infohash\")"
                    downloadvolumefactor:
                            text: "0"
                    uploadvolumefactor:
                            text: "1"
```
