### ISSUE TITLE
[REQ] Add new tracker - LimitOfEden

### ISSUE THREAD

**Issue by pipopop** [Jackett/Jackett#4747]
Invitation mode (I can send you an invitation).
Adress: http://www.limit-of-eden.com
Type: General
Language: french

Here is the headers and cap section:

```Header:

site: LoE
name: Limit Of Eden
description: no description
language:en (in the html code) / fr-fr (the real language used)
type: private
encoding: charset=iso-8859-1
links:
- http://www.limit-of-eden.com/wqreyt/
legacylinks:
- http://www.limit-of-eden.com/

Caps
caps:
	categorymappings:
      - {id: 100, cat: Movies, desc: "Films - TVRIP"}
      - {id: 4, cat: Movies, desc: "Films - 3D"}
      - {id: 99, cat: Movies, desc: "Films - 4K_UHD"}
      - {id: 92, cat: Movies, desc: "Films - Bluray"}
      - {id: 55, cat: Movies, desc: "Films - HD 1080"}
      - {id: 35, cat: Movies, desc: "Films - HD 720"}
      - {id: 84, cat: Movies, desc: "Films - HD-light"}
      - {id: 98, cat: Movies, desc: "Films - HD-RIP"}
      - {id: 93, cat: Movies, desc: "Films - HDTV"}
      - {id: 1, cat: Movies, desc: "Films - DVD-R"}
      - {id: 2, cat: Movies, desc: "Films - DVD-RIP"}
      - {id: 95, cat: Movies, desc: "Films - BR-RIP"}
      - {id: 77, cat: Movies, desc: "Films - DVD_SCR"}
      - {id: 48, cat: Movies, desc: "Films - BD-RIP"}
      - {id: 42, cat: Movies, desc: "Films - CAM-HD"}
      - {id: 76, cat: Movies, desc: "Films - CAM-TS"}
      - {id: 78, cat: Movies, desc: "Films - Web Rip"}
      - {id: 94, cat: Movies, desc: "Films - WEB-DL"}
      - {id: 79, cat: Movies, desc: "Films - Cine-Club"}
      - {id: 82, cat: Movies, desc: "Films - VO"}
      - {id: 47, cat: Movies, desc: "Films - VOST-FR"}
      - {id: 52, cat: Movies, desc: "Films - XXX"}
      - {id: 75, cat: PCMac, desc: "Jeux - MAC"}
      - {id: 10, cat: PCGames, desc: "Jeux - PC"}
      - {id: 11, cat: Console, desc: "Jeux - 3DS"}
      - {id: 43, cat: Console, desc: "Jeux - PS3"}
      - {id: 12, cat: Console, desc: "Jeux - PSP"}
      - {id: 13, cat: Console, desc: "Jeux - Xbox"}
      - {id: 14, cat: Console, desc: "Jeux - Xbox360"}
      - {id: 44, cat: Console, desc: "Jeux - Wii"}
      - {id: 17, cat: Console, desc: "Jeux - DS"}
      - {id: 7, cat: TV, desc: "TV - TV DVD"}
      - {id: 51, cat: TV, desc: "TV - Sport"}
      - {id: 85, cat: TV, desc: "Series TV - HD_VOSTFR"}
      - {id: 41, cat: TV, desc: "Series TV - VF"}
      - {id: 5, cat: TV, desc: "Series TV - VOSTFR"}
      - {id: 6, cat: TV, desc: "Series TV - HDFR"}
      - {id: 89, cat: TV, desc: "Series TV - TV-VO"}
      - {id: 64, cat: TV, desc: "Series TV - Tv Pack"}
      - {id: 87, cat: PCPhoneIOS, desc: "Apps - Iphone"}
      - {id: 61, cat: PCPhoneAndroid, desc: "Apps - Android"}
      - {id: 18, cat: PC, desc: "Apps - P-C"}
      - {id: 19, cat: PCMac, desc: "Apps - Mac"}
      - {id: 88, cat: Audio, desc: "Autre - Audio books"}
      - {id: 96, cat: Movies, desc: "Autre - BD"}
      - {id: 74, cat: Movies, desc: "Autre - Divers"}
      - {id: 97, cat: Movies, desc: "Autre - BD adultes"}
      - {id: 9, cat: Movies, desc: "Autre - Documentaires"}
      - {id: 80, cat: Movies, desc: "Autre - Web Series"}
      - {id: 27, cat: Movies, desc: "Autre - SPECTACLE"}
      - {id: 36, cat: Movies, desc: "Autre - E-Books"}
      - {id: 63, cat: Movies, desc: "Autre - Presse"}
      - {id: 22, cat: Audio, desc: "Music - MP3"}
      - {id: 54, cat: Audio, desc: "Music - FLAC"}
      - {id: 25, cat: Audio, desc: "Music - Video"}
      - {id: 62, cat: Audio, desc: "Music - Concerts"}
      - {id: 60, cat: TVAnime, desc: "Anime - Hentai"}
      - {id: 59, cat: TVAnime, desc: "Anime - Manga"}
      - {id: 101, cat: TVAnime, desc: "Anime - WEB-DL"}
      - {id: 91, cat: TVAnime, desc: "Anime - Anime-1080p"}
      - {id: 90, cat: TVAnime, desc: "Anime - Anime-720p"}
      - {id: 102, cat: TVAnime, desc: "Anime - Anime-BRRIP"}
      - {id: 28, cat: TVAnime, desc: "Anime - All"}


settings:
- name: username # internal variable
type: text # input type
label: Pseudo # Display name
- name: password
type: password
label: Mot de passe

Login :
method: form
path: wqreyt/account-login.php
submitpath:wqreyt/account-login.php

search:
paths:
- path: wqreyt/torrents.php
method: form / get
submitpath:torrents-search.php
inputs:
name="search" id="searchinput" type="text"
```

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by pipopop** [comment]
Done ! bit I don't know if it require a native C# indexer or not. I hope not. Have a good day !

**Comment by garfield69** [comment]
registration and login successful. Thank you.

**Comment by garfield69** [comment]
@kaso17 I'm having trouble generating the download link for this site.
the relelvant html
```html
<div id='alert' style='position:fixed;top:300px;left:400px;display:none'><p class='myBlock-cap rounded' style='width:500px'>Avant de télécharger...</p><div class='myBlock-con rounded' style ='width:485px;font-size:28px;color:#600000;text-shadow:2px 2px #200000; text-align:center;margin-top:3px;padding-bottom:10px'>
			S'il vous plait, remerciez l'uploader pour son travail ..<img src='images/smilies/2ange.gif'>..
			<p style='text-align:right'><button onclick='javascript:openAlert(false);'>OK</button></p></div>
</div>
<div id='thanks' style='position:fixed;top:300px;left:400px;display:none'>
<p class='myBlock-cap rounded' style='width:500px'>Cliquez sur OK pour enregistrer votre remerciement...</p>
<div class='myBlock-con rounded' style ='width:485px;font-size:28px;color:#600000;text-shadow:2px 2px #200000; text-align:center;margin-top:3px;padding-bottom:10px'>
			N'oubliez pas qu'un petit commentaire est toujours apprécié ! ..<img src='images/smilies/bravo1.gif'>..
			<p style='text-align:right'><button onclick='javascript:openThanks(false);'>OK</button></p></div>
</div>
<script >
var audioElement = document.createElement('audio');
function play_sound(title) {
//	alert(title);
    audioElement.setAttribute('src','https:\/\/www.amazon.fr\/gp\/dmusic\/get_sample_url.html\/ref=dm_trk_smpl_gsu?ie=UTF8&ASIN='+title+'&DownloadLocation=WEBSITE');
    audioElement.setAttribute('autoplay', 'autoplay');
    audioElement.load();
    audioElement.play();
}
function stop_sound(){
	audioElement.pause();
}
function openAlert(action){
if (action==true)
 $('alert').style.display='block';
else
 $('alert').style.display='none';
 }
 function openThanks(action){
if (action==true){
	$('thanks').style.display='block';
	var id = '78975';
	new Ajax.Request('thanks.php?torrent='+id,{
		method:'get'
		});
}
else{
 $('thanks').style.display='none';
 location.reload();
 }
 }
 function addFavorite(torid){
	 new Ajax.Request('manage_favorites.php?id='+torid+'&action=add',{
		 method:'get',
		 onSuccess:function(Transport){
			 alert('Le Torrent '+torid+' a été ajouté à vos favoris');
		}
	})
 }
 </script>
```

it requires a thank you before the download link is made available, using method get
so I set up the following:
```yaml
  download:
    before:
      path: wqreyt/thanks.php
      inputs:
        torrent: "{{ .DownloadUri.Query.id }}"
    selector: a[onclick*="download.php?id="]
    attribute: onclick
    filters:
      - name: replace
        args: ["location.href='", "wqreyt/"]
      - name: replace
        args: ["'", ""]
```

however when i test it the jackett log shows that the url generated is
```log
Feb 24, 2019 05:17:56 PM Debug WebClient(HttpWebClient).GetBytes(Url:http://www.limit-of-eden.com/wqreyt/thanks.php?orrent=78975)
```

as you can see the **torrent** keyword has been truncated to **orrent** ?!?

Anyway, I got around it temporarily by coding 
```yaml
      inputs:
        _torrent: "{{ .DownloadUri.Query.id }}"
```

but then comes the next problem: the download href is burried in the onlick attribute
```html
<div id = "Téléchargement" class='myBlock-con'>
<table width=100%>
<tr>
<td style='width:8%; text-align:center; margin-top:30px'>
<a href='javascript:;' onclick="location.href='download.php?id=78975&pass=e4***redacted***61'" onmouseover="return overlib('<table bgcolor=blue border=2><td style=\'font-size:14px;padding:10px\'>Attention: Ne cliquez pas sur ce bouton si vous le comptez pas télécharger le fichier,<br>car ceci vous enlève immédiatement un de vos slots.<br>Les slots sont restitués dès que le téléchargement des fichiers est complété,<br>donc si vous ne téléchargez pas ce fichier, votre slot restera bloqué.<br>Mettez plutôt ce lien dans vos favoris en cliquant sur le bouton rouge avec une étoile à l\'extrême-droite.</td></table>');" onmouseout="return nd();"><img src="images/download/general.png" border="0"></a>
</td>
<td class='text' style='width: 22%; padding-left:10px; text-align:left'><span style='color:orange'>Remerciez et cliquez sur le bouton à gauche pour télécharger.</span><BR>Santé: <img src=images/health_10.gif><BR>Seeders: <font color=green>5</font><BR>Leechers: <font color=red>0</font><BR>Vitesse: Pas d'activité<BR>Complétés: 4&nbsp;[<a href='torrents-completed.php?id=78975'>Qui a complété</a>] &nbsp;[<a href='torrents-reseed.php?id=78975'>Demande de partage</a>]<br>Vérifié: Saturday 23 February <BR></td>
<td style='width:40%;  margin-top:30px'></td>
<td class='text' style='width:15%'>&nbsp;</td>
<td style='margin-top:30px'><a href='report.php?torrent=78975'><img src="images/reporter.png" border=0"></a>&nbsp;<img src="images/bookmark.png" onmouseover= "return overlib('Mettre ce torrent dans vos favoris')"; onMouseout="return nd()" onclick="addFavorite(78975)"></td>
</tr>
</table>
</div>
```

but the url that gets used is not the selector I prepared in the first **download** block, but the one in the search block
```log
Feb 24, 2019 05:18:06 PM Debug WebClient(HttpWebClient).GetBytes(Url:http://www.limit-of-eden.com/wqreyt/thanks.php?torrent=78772)
Feb 24, 2019 05:18:06 PM Debug WebClient(HttpWebClient): Returning OK => 2 bytes
Feb 24, 2019 05:18:06 PM Debug CardigannIndexer (limitofeden): handleRequest() remote server returned OK
Feb 24, 2019 05:18:06 PM Debug WebClient(HttpWebClient).GetString(Url:http://www.limit-of-eden.com/wqreyt/torrents-details.php?id=78772&hit=1)
Feb 24, 2019 05:18:06 PM Debug WebClient(HttpWebClient): Returning OK => <!-- Exception ajoutee a la ligne 80 pour Nolo -->
<script>
 function fermeture(){
// alert('ok');
 //window.top.opener = null;
 window.open(window.location,'_blank');
 window.close();
 }
</script>
<script>location.assign('torrents-details.php?id=78772');</script> 
Feb 24, 2019 05:18:06 PM Error CardigannIndexer (limitofeden): Download selector a[onclick*="download.php?id="] didn't match:
<!-- Exception ajoutee a la ligne 80 pour Nolo -->
<script>
 function fermeture(){
// alert('ok');
 //window.top.opener = null;
 window.open(window.location,'_blank');
 window.close();
 }
</script>
<script>location.assign('torrents-details.php?id=78772');</script> 
Feb 24, 2019 05:18:06 PM Error Error downloading limitofeden http://www.limit-of-eden.com/wqreyt/torrents-details.php?id=78772&hit=1
Feb 24, 2019 05:18:06 PM Info Executed action method Jackett.Server.Controllers.DownloadController.Download (JackettConsole), returned result Microsoft.AspNetCore.Mvc.NotFoundResult in 913.0103ms.
Feb 24, 2019 05:18:06 PM Info Executing HttpStatusCodeResult, setting HTTP status code 404
```

any thoughts on how to resolve this?

**Comment by pipopop** [comment]
Really sorry for the double post. I didn't find it.

**Comment by garfield69** [comment]
I'm going to put this on the todo queue and mark it as help required.
for anyone wanting to progress this further, here is the indexer so far:
```yaml
---
  site: limitofeden
  name: Limit Of Eden
  description: "Limit Of Eden (LoE) is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL"
  language: fr-fr
  type: private
  encoding: iso-8859-1
  links:
    - http://www.limit-of-eden.com/

  caps:
    categorymappings:
      # movies
      - {id: 4, cat: Movies/3D, desc: "Films - 3D"}
      - {id: 99, cat: Movies/UHD, desc: "Films - 4K UHD"}
      - {id: 48, cat: Movies/BluRay, desc: "Films - BD-RIP"}
      - {id: 92, cat: Movies/BluRay, desc: "Films - BluRay"}
      - {id: 95, cat: Movies/BluRay, desc: "Films - BR-RIP"}
      - {id: 42, cat: Movies/HD, desc: "Films - CAM-HD"}
      - {id: 76, cat: Movies/HD, desc: "Films - CAM-TS"}
      - {id: 79, cat: Movies, desc: "Films - Cine-Club"}
      - {id: 1, cat: Movies/DVD, desc: "Films - DVD-R"}
      - {id: 2, cat: Movies/DVD, desc: "Films - DVD-RIP"}
      - {id: 77, cat: Movies/DVD, desc: "Films - DVD SCR"}
      - {id: 55, cat: Movies/HD, desc: "Films - HD 1080"}
      - {id: 35, cat: Movies/HD, desc: "Films - HD 720"}
      - {id: 84, cat: Movies/HD, desc: "Films - HD-light"}
      - {id: 98, cat: Movies/HD, desc: "Films - HD-RIP"}
      - {id: 93, cat: Movies/HD, desc: "Films - HD-TV"}
      - {id: 100, cat: Movies, desc: "Films - TV-RIP"}
      - {id: 82, cat: Movies, desc: "Films - VO"}
      - {id: 47, cat: Movies, desc: "Films - VOST-FR"}
      - {id: 78, cat: Movies/WEBDL, desc: "Films - Web Rip"}
      - {id: 94, cat: Movies/WEBDL, desc: "Films - WEB-DL"}
      - {id: 52, cat: XXX, desc: "Films - XXX"}
      # games
      - {id: 11, cat: Console/3DS, desc: "Jeux - 3DS"}
      - {id: 17, cat: Console/NDS, desc: "Jeux - DS"}
      - {id: 75, cat: PC/Mac, desc: "Jeux - MAC"}
      - {id: 10, cat: PC/Games, desc: "Jeux - PC"}
      - {id: 43, cat: Console/PS3, desc: "Jeux - PS3"}
      - {id: 12, cat: Console/PSP, desc: "Jeux - PSP"}
      - {id: 44, cat: Console/Wii, desc: "Jeux - Wii"}
      - {id: 13, cat: Console/Xbox, desc: "Jeux - Xbox"}
      - {id: 14, cat: Console/Xbox 360, desc: "Jeux - Xbox360"}
      # tv
      - {id: 51, cat: TV/Sport, desc: "TV - Sport"}
      - {id: 7, cat: TV, desc: "TV - TV DVD"}
      - {id: 6, cat: TV/HD, desc: "Series TV - HD FR"}
      - {id: 85, cat: TV/HD, desc: "Series TV - HD VOSTFR"}
      - {id: 89, cat: TV, desc: "Series TV - TV-VO"}
      - {id: 41, cat: TV, desc: "Series TV - VF"}
      - {id: 5, cat: TV, desc: "Series TV - VOSTFR"}
      - {id: 64, cat: TV, desc: "Series TV - Tv Pack"}
      # software
      - {id: 61, cat: PC/Phone-Android, desc: "Apps - Android"}
      - {id: 87, cat: PC/Phone-IOS, desc: "Apps - Iphone"}
      - {id: 19, cat: PC/Mac, desc: "Apps - Mac"}
      - {id: 18, cat: PC/0day, desc: "Apps - PC"}
      # music
      - {id: 62, cat: Audio, desc: "Music - Concerts"}
      - {id: 54, cat: Audio/Lossless, desc: "Music - FLAC"}
      - {id: 22, cat: Audio/MP3, desc: "Music - MP3"}
      - {id: 25, cat: Audio/Video, desc: "Music - Video"}
      - {id: 88, cat: Audio/Audiobook, desc: "Autre - Audio books"}
      - {id: 96, cat: Movies, desc: "Autre - BD"}
      - {id: 97, cat: XXX, desc: "Autre - BD adultes"}
      - {id: 74, cat: Movies, desc: "Autre - Divers"}
      - {id: 9, cat: TV/Documentary, desc: "Autre - Documentaires"}
      - {id: 36, cat: Books/Ebook, desc: "Autre - E-Books"}
      - {id: 63, cat: Books, desc: "Autre - Presse"}
      - {id: 27, cat: Movies, desc: "Autre - SPECTACLE"}
      - {id: 80, cat: Movies/WEBDL, desc: "Autre - Web Series"}
      # anime
      - {id: 28, cat: TV/Anime, desc: "Anime - All"}
      - {id: 91, cat: TV/Anime, desc: "Anime - Anime 1080p"}
      - {id: 90, cat: TV/Anime, desc: "Anime - Anime 720p"}
      - {id: 102, cat: TV/Anime, desc: "Anime - Anime BRRIP"}
      - {id: 60, cat: TV/Anime, desc: "Anime - Hentai"}
      - {id: 59, cat: TV/Anime, desc: "Anime - Manga"}
      - {id: 101, cat: TV/Anime, desc: "Anime - WEB-DL"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  login:
    path: wqreyt/account-login.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
    error:
      - selector: div.error-cap
    test:
      path: wqreyt/index.php
      selector: a[href="account-logout.php"]

  download:
    before:
      path: wqreyt/thanks.php
      inputs:
        _torrent: "{{ .DownloadUri.Query.id }}"
    selector: a[onclick*="download.php?id="]
    attribute: onclick
    filters:
      - name: replace
        args: ["location.href='", "wqreyt/"]
      - name: replace
        args: ["'", ""]

  search:
    paths:
      # http://www.limit-of-eden.com/wqreyt/torrents-search.php?search=daredevil&incldead=1&freeleech=0&highspeed=0&lang=0&sort=id&order=desc&c51=1
      - path: wqreyt/torrents-search.php
    inputs:
      $raw: "{{range .Categories}}c{{.}}=1&{{end}}"
      search: "{{ .Keywords }}"
      incldead: 1
      highspeed: 0
      freeleech: 0
      lang: 0
      sort: "id"
      order: "desc"
    rows:
      selector: table.ttable_headinner tr:has(a[href^="torrents-details.php?id="])
    fields:
      title:
        selector: a[href^="torrents-details.php?id="]
      details:
        selector: a[href^="torrents-details.php?id="]
        attribute: href
      download:
        selector: a[href^="torrents-details.php?id="]
        attribute: href
      category:
        selector: a[href^="torrents.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: cat
      banner:
        selector: a[href^="torrents-details.php?id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "src=(.*?) width="
      date:
        selector: a[href^="torrents-details.php?id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "\\sAjouté: (.*?)\\s</div>"
          - name: dateparse
            args: "2006-01-02 15:04:05"
      size:
        selector: td:nth-child(10)
      grabs:
        selector: td:nth-child(11)
      seeders:
        selector: td:nth-child(12)
      leechers:
        selector: td:nth-child(13)
      downloadvolumefactor:
        case:
          "img[src=\"images/check.png\"]": "0"
          "*": "1"
      uploadvolumefactor:
        case:
          "*": "1"
```

**Comment by garfield69** [comment]
bugger. I was hoping 9413006524a7f4b731ea9e5c1103a4244bbfd4fd would help me complete this one.
but I complete the thank you, because I see my thanks registered,
but I then get returned this http instead of the one with the download link.
```
2020-01-14 18:40:33.0819 Error CardigannIndexer (limitofeden): Download selector a[onclick*="download.php?id="] didn't match:
<!-- Exception ajoutee a la ligne 80 pour Nolo -->
<script>
 function fermeture(){
// alert('ok');
 //window.top.opener = null;
 window.open(window.location,'_blank');
 window.close();
 }
</script>


<script>location.assign('wikis-details.php?id=88426');</script> 
 
2020-01-14 18:40:33.0819 Error Error downloading limitofeden http://www.limit-of-eden.com/wqreyt/wikis-details.php?id=88426&hit=1 System.Exception: Download selector a[onclick*="download.php?id="] didn't match
   at Jackett.Common.Indexers.CardigannIndexer.<Download>d__32.MoveNext()
```
so I'm still stuck. looks like this one may need to be written in C#
this is the yaml so far
```yaml
---
  site: limitofeden
  name: Limit Of Eden
  description: "Limit Of Eden (LoE) is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL"
  language: fr-fr
  type: private
  encoding: iso-8859-1
  links:
    - http://www.limit-of-eden.com/

  caps:
    categorymappings:
      # movies
      - {id: 4, cat: Movies/3D, desc: "Films - 3D"}
      - {id: 99, cat: Movies/UHD, desc: "Films - 4K UHD"}
      - {id: 48, cat: Movies/BluRay, desc: "Films - BD-RIP"}
      - {id: 92, cat: Movies/BluRay, desc: "Films - BluRay"}
      - {id: 95, cat: Movies/BluRay, desc: "Films - BR-RIP"}
      - {id: 42, cat: Movies/HD, desc: "Films - CAM-HD"}
      - {id: 76, cat: Movies/HD, desc: "Films - CAM-TS"}
      - {id: 79, cat: Movies, desc: "Films - Cine-Club"}
      - {id: 1, cat: Movies/DVD, desc: "Films - DVD-R"}
      - {id: 2, cat: Movies/DVD, desc: "Films - DVD-RIP"}
      - {id: 77, cat: Movies/DVD, desc: "Films - DVD SCR"}
      - {id: 55, cat: Movies/HD, desc: "Films - HD 1080"}
      - {id: 35, cat: Movies/HD, desc: "Films - HD 720"}
      - {id: 84, cat: Movies/HD, desc: "Films - HD-light"}
      - {id: 98, cat: Movies/HD, desc: "Films - HD-RIP"}
      - {id: 93, cat: Movies/HD, desc: "Films - HD-TV"}
      - {id: 100, cat: Movies, desc: "Films - TV-RIP"}
      - {id: 82, cat: Movies, desc: "Films - VO"}
      - {id: 47, cat: Movies, desc: "Films - VOST-FR"}
      - {id: 78, cat: Movies/WEBDL, desc: "Films - Web Rip"}
      - {id: 94, cat: Movies/WEBDL, desc: "Films - WEB-DL"}
      - {id: 52, cat: XXX, desc: "Films - XXX"}
      # games
      - {id: 11, cat: Console/3DS, desc: "Jeux - 3DS"}
      - {id: 17, cat: Console/NDS, desc: "Jeux - DS"}
      - {id: 75, cat: PC/Mac, desc: "Jeux - MAC"}
      - {id: 10, cat: PC/Games, desc: "Jeux - PC"}
      - {id: 43, cat: Console/PS3, desc: "Jeux - PS3"}
      - {id: 12, cat: Console/PSP, desc: "Jeux - PSP"}
      - {id: 44, cat: Console/Wii, desc: "Jeux - Wii"}
      - {id: 13, cat: Console/Xbox, desc: "Jeux - Xbox"}
      - {id: 14, cat: Console/Xbox 360, desc: "Jeux - Xbox360"}
      # tv
      - {id: 51, cat: TV/Sport, desc: "TV - Sport"}
      - {id: 7, cat: TV, desc: "TV - TV DVD"}
      - {id: 6, cat: TV/HD, desc: "Series TV - HD FR"}
      - {id: 85, cat: TV/HD, desc: "Series TV - HD VOSTFR"}
      - {id: 89, cat: TV, desc: "Series TV - TV-VO"}
      - {id: 41, cat: TV, desc: "Series TV - VF"}
      - {id: 5, cat: TV, desc: "Series TV - VOSTFR"}
      - {id: 64, cat: TV, desc: "Series TV - Tv Pack"}
      # software
      - {id: 61, cat: PC/Phone-Android, desc: "Apps - Android"}
      - {id: 87, cat: PC/Phone-IOS, desc: "Apps - Iphone"}
      - {id: 19, cat: PC/Mac, desc: "Apps - Mac"}
      - {id: 18, cat: PC/0day, desc: "Apps - PC"}
      # music
      - {id: 62, cat: Audio, desc: "Music - Concerts"}
      - {id: 54, cat: Audio/Lossless, desc: "Music - FLAC"}
      - {id: 22, cat: Audio/MP3, desc: "Music - MP3"}
      - {id: 25, cat: Audio/Video, desc: "Music - Video"}
      - {id: 88, cat: Audio/Audiobook, desc: "Autre - Audio books"}
      - {id: 96, cat: Movies, desc: "Autre - BD"}
      - {id: 97, cat: XXX, desc: "Autre - BD adultes"}
      - {id: 74, cat: Movies, desc: "Autre - Divers"}
      - {id: 9, cat: TV/Documentary, desc: "Autre - Documentaires"}
      - {id: 36, cat: Books/Ebook, desc: "Autre - E-Books"}
      - {id: 63, cat: Books, desc: "Autre - Presse"}
      - {id: 27, cat: Movies, desc: "Autre - SPECTACLE"}
      - {id: 80, cat: Movies/WEBDL, desc: "Autre - Web Series"}
      # anime
      - {id: 28, cat: TV/Anime, desc: "Anime - All"}
      - {id: 91, cat: TV/Anime, desc: "Anime - Anime 1080p"}
      - {id: 90, cat: TV/Anime, desc: "Anime - Anime 720p"}
      - {id: 102, cat: TV/Anime, desc: "Anime - Anime BRRIP"}
      - {id: 60, cat: TV/Anime, desc: "Anime - Hentai"}
      - {id: 59, cat: TV/Anime, desc: "Anime - Manga"}
      - {id: 101, cat: TV/Anime, desc: "Anime - WEB-DL"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  settings:
    - name: username
      type: text
      label: Username
    - name: password
      type: password
      label: Password
    - name: sort
      type: select
      label: Sort requested from site
      default: "id"
      options:
        "id": "created"
        "seeders": "seeders"
        "size": "size"
        "name": "title"
    - name: type
      type: select
      label: Order requested from site
      default: "desc"
      options:
        "desc": "desc"
        "asc": "asc"

  login:
    path: login.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
    error:
      - selector: div.myBlock:contains("Accès refusé")
    test:
      path: wqreyt/index.php
      selector: a[href="account-logout.php"]

  download:
    before:
      path: wqreyt/thanks.php
      inputs:
        _torrent: "{{ .DownloadUri.Query.id }}"
    selector: a[onclick*="download.php?id="]
    attribute: onclick
    filters:
      - name: strdump
      - name: replace
        args: ["location.href='", "wqreyt/"]
      - name: replace
        args: ["'", ""]
      - name: strdump

  search:
    paths:
# http://www.limit-of-eden.com/wqreyt/wikis-search.php?search=&incldead=1&freeleech=0&highspeed=0&lang=0&sort=size&order=desc&c99=1&c55=1&c35=1
      - path: wqreyt/wikis-search.php
    inputs:
      $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
      search: "{{ .Keywords }}"
      # 0 active 1 incldead 2 onlydead
      incldead: 1
      # 0 all 1 normal 2 freeleech
      freeleech: 0
      # 0 all 1 slow 2 fast 
      highspeed: 0
      # 0 all 1 English 2 French(FR) 3 French(QC) 4 etc...
      lang: 0
      sort: "{{ .Config.sort }}"
      order: "{{ .Config.type }}"

    rows:
      selector: table.ttable_headinner tr:has(a[href^="wikis-details.php?id="])

    fields:
      category:
        selector: a[href^="wikis.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: cat
      title:
        selector: a[href^="wikis-details.php?id="]
      details:
        selector: a[href^="wikis-details.php?id="]
        attribute: href
      download:
        selector: a[href^="wikis-details.php?id="]
        attribute: href
      banner:
        selector: a[href^="wikis-details.php?id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "src=(.*?) width="
      date:
        selector: a[href^="wikis-details.php?id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "\\sAjouté: (.*?)\\s<"
          - name: dateparse
            args: "2006-01-02 15:04:05"
      size:
        selector: td:nth-child(10)
      grabs:
        selector: td:nth-child(11)
      seeders:
        selector: td:nth-child(12)
      leechers:
        selector: td:nth-child(13)
      downloadvolumefactor:
        case:
          "img[src=\"images/check.png\"]": 0
          "*": 1
      uploadvolumefactor:
        case:
          "*": 1
# engine n/a
```
