### ISSUE TITLE
[Question] definition

### ISSUE THREAD

**Issue by xfouloux** [Jackett/Jackett#4790]
Hey,

i'm trying to add some path for YGGtorrent in order to make the search more viable.

FOR COMPLETE SEASON SEARCH it is best to add this to the search url
&option_episode[]=1

FOR SELECTING SEASON TO SEARCH I need to add the value 3 to the season value that is searched S03 ==> &option_saison[]=6 and remove the SXX term

so I have done this for now :

```
  search:
    followredirect: true
    keywordsfilters:
      # Full season seach hack: Sonarrv3 send 'Series Name SXX' but it won't match 'Series Name - Saison 01' for example so we remove the 'SXX' ==> 'Series Name'
      - name: re_replace
        args: ["(.*)[sS](\\d{1,4})[Ee](\\d{1,4})$", ""]
      - name: replace
        args: ["\"", ""]
      - name: trim
    paths:
      - path: "https://{{ .Config.searchanddlurl }}/engine/search?
        inputs:
          category: "{{ .Config.category }}"
      
      #
      # FOR COMPLETE SEASON SEARCH
      # &option_episode[]=1
      #
      # FOR SELECTING SEASON TO SEARCH need to add 3 to the season value (S03 ==> &option_saison[]=6)
      # &option_saison[]=6
      # SELECT EPISODE THEN WITH
      # &option_episode[]=X where X is episode number + 1 (E06 ==> &option_episode[]=7)
      #
      
      #COMPLETE SEASON Search
      - path: "https://{{ .Config.searchanddlurl }}/engine/search"
        categorymappings: [2145, "all"]
        inputs:
          category: "2145"
          sub_category: "2184"
          "option_episode[]": "1" # SELECT COMPLETE SEASON
          "option_saison[]": "{{ .Query.Ep }} + 1" # SELECT EP (need to add 1 to the value)
      #ONLY EP IN SEASON
      - path: "https://{{ .Config.searchanddlurl }}/engine/search"
        categorymappings: [2145, "all"]
        inputs:
          category: "2145"
          sub_category: "2184"
          "option_saison[]": "{{ .Query.Season }}" # SELECT SEASON (need to add 3 to the value)
          "option_saison[]": "{{ .Query.Ep }}" # SELECT EP (need to add 1 to the value)
    inputs:
      $raw: ""
      name: "{{if .Config.enhancedAnime}}{{ re_replace .Keywords \"([\\.\\s\\[\\-])(\\d+)$\" \"$1e$2\" }}{{else}}{{ .Keywords }}{{end}}"
      do: "search"
      order: "desc"
      sort: "publish_date"
...
...
```

I do not know how to increase the value of a selected re_replace field for example, is it even possible to do such a thing as filtering ant maths in a inputs field like :

```
 "option_saison[]": "{{  .Query.Season + 3 }}" # SELECT SEASON (need to add 3 to the value)
or
 "option_saison[]": "{{  .Query.Season }} + 3" # SELECT SEASON (need to add 3 to the value)
```
but this don't work.

Also, the  .Query.Season and .Query.Ep are not filled, because sonarr and nzbhydra2 only query jackett with t=search with q=terms and do not use t=tvsearch with q=term season=X ep=X

But when I do t=caps, it is ok because it says :
```
   modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]
```

But since we cannot query with IMDBID or TVDBID it won't use it I assume ?

That's really a bummer, because YGG indexer sometimes do not return all the results correctly

when you search for "TV SHOW NAME S03" for example, it would not return any results
but using the 2 given options it works better.

Can someone help a bit with this ?
