### ISSUE TITLE
Hdtorrentsit error parsing seeders/leechers

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#4839]
Hi

I've a strange error with hdtorrent:
```
CardigannIndexer (hdtorrentsit): Error while parsing row '
<tr>
	<td align="center" style="padding: 0px">
		<a href="browse.php?cat=3">
			<img border="0" src="./pic//cats/HDDVDBD1080Rip.gif" alt="BDRip 1080p">
		</a>
	</td>
	<td align="left" onmousemove="dialog_tor('img_tor',Xmouse,Ymouse,'https://img.ibs.it/images/5050582922622_0_0_300_75.jpg')">
		<a href="details.php?id=14921">
			<b>S. Darko (2009)</b>
		</a>
		<a href="download.php?id=14921&amp;name=Dark.S.Blu.Ray.Rip.DTS%20ITA%20ENG..mkv.torrent">
			<img src="pic/download.gif" border="0" alt="Scaricare" title="Scaricare">
		</a>
		<br>
		<i>2019-02-25 08:58:11</i>
	</td>
	<td align="center">19.45<br>GB</td>
</tr>':

System.Exception: Error while parsing field=seeders, selector=td:nth-child(4), value=<null>: Selector "td:nth-child(4)" didn't match 
<tr>
	<td align="center" style="padding: 0px">
		<a href="browse.php?cat=3">
			<img border="0" src="./pic//cats/HDDVDBD1080Rip.gif" alt="BDRip 1080p">
		</a>
	</td>
	<td align="left" onmousemove="dialog_tor('img_tor',Xmouse,Ymouse,'https://img.ibs.it/images/5050582922622_0_0_300_75.jpg')">
		<a href="details.php?id=14921">
			<b>S. Darko (2009)</b>
		</a>
		<a href="download.php?id=14921&amp;name=Dark.S.Blu.Ray.Rip.DTS%20ITA%20ENG..mkv.torrent">
			<img src="pic/download.gif" border="0" alt="Scaricare" title="Scaricare">
		</a>
		<br>
		<i>2019-02-25 08:58:11</i>
	</td>
	<td align="center">19.45<br>GB</td>
</tr>
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query)
```
Now code seems pretty correct, to me
```
      seeders:
        selector: td:nth-child(4)
        filters:
          - name: re_replace
            args: ["(\\d*) \\(\\+\\d*\\)\n? \\| (\\d*) \\(\\+\\d*\\)", "$1"]
      leechers:
        selector: td:nth-child(4)
        filters:
          - name: re_replace
            args: ["(\\d*) \\(\\+\\d*\\)\n? \\| (\\d*) \\(\\+\\d*\\)", "$2"]
```
![qqqqqqqqq](https://user-images.githubusercontent.com/5203988/54058464-2b8e0a00-41f6-11e9-9fc3-76e1559d83da.PNG)
Do you know if there's a better way to extract the seeders and leechers?
Originally I thought to extract the text beside the link but I never got it working

**Comment by garfield69** [comment]
the issue here appears to be that the seeders and leechers do not always appear in the row block, as shown in the html you dumped from the log.
so add a default seeders selector above the existing entry and add an optional statement to the original, so that when the selector is not found it does not cause an error.
```yaml
      seeders:
        text: 1
      seeders:
        selector: td:nth-child(4)
        optional: true
```
repeat for leechers.

**Comment by Jorman** [comment]
Can be a workaround!
I always see one number inside seeders and leechers.

Do you think this's the best way to "fix" this?
Can depend on the selector of the row?
```
    rows:
      selector: tbody#highlighted tr
```
Because if I apply the workaround I got this
![1111111111111](https://user-images.githubusercontent.com/5203988/54059700-5f6b2e80-41fa-11e9-8f45-cab29ef08e06.PNG)
and is not true
![22222222222](https://user-images.githubusercontent.com/5203988/54059706-685c0000-41fa-11e9-9ee1-6df9be496fad.PNG)

What do you think?

**Comment by garfield69** [comment]
try:
```yaml
      seeders:
        text: 1
      seeders:
        selector: td:nth-child(4) b a font
        optional: true
      leechers:
        text: 1
      leechers:
        selector: td:nth-child(4) b:nth-child(2) a 
        optional: true
```
