### ISSUE TITLE
HD-Forever freeleech token

### ISSUE THREAD

**Issue by bidulle95** [Jackett/Jackett#4979]
hello is it possible to put an option for freeleech token please ?
I wish I could use them

**Comment by garfield69** [comment]
I don't have a login for this site.
@WSHaRK993 are you able to implement this on the cardigann version that you converted a couple months ago?
presumably it's something to do with the download link and the use of the usetoken=1 or usetoken=0 parm...?

**Comment by garfield69** [comment]
what does the download link look like at the moment?
are you wanting to always selectively add or replace the usetoken based on a switch in the config?
an example for you to work with might look something like this:
you first add a settings block with the username and password sections, and add a checkbox:
```
  settings:
    - name: username
      type: text
      label: Username
    - name: password
      type: password
      label: Password
    - name: usetoken
      type: checkbox
      label: Always try to use the FreeLeech Token
      default: false
```
then in your download section in the fields block you can use something like
```
      download-regular:
        selector: a[href^="torrents.php?action=download&"]
        attribute: href
      download-usetoken:
        selector: a[href^="torrents.php?action=download&"]
        attribute: href
        filters:
          - name: append
            args: "&usetoken=1"
      download:
        text: "{{if .Config.usetoken}}{{ .Result.download-usetoken }}{{else}}{{ .Result.download-regular }}{{end}}"
```
or swap the append with a replace if you just need to turn usetoken=0 into usetoken=1
