### ISSUE TITLE
[req]: SiamBit

### ISSUE THREAD

**Issue by xpirat** [Jackett/Jackett#5243]
can you add private tracker: Siambit

**Comment by garfield69** [comment]
full address please?
also, is registration currently open or does one require an invite?

**Comment by xpirat** [comment]
https://siambit.me/

It’s only possible to join siambit getting invited by an already existing member or through donation.

**Comment by xpirat** [comment]
I can invite you. pm your mail

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by garfield69** [comment]
registration and login successful. thank you.

**Comment by garfield69** [comment]
try out Jackett pre-release v0.11.333

**Comment by garfield69** [comment]
to @kaso17  or anyone else who knows:
if the site requires thanks before download, and  the method  is a 
`<a onclick="sndReq('action=say_thank&id=1413966', 'saythank')" >` 
how do I code the `before` block for the download?
would this work?
```yaml
  download:
    before:
      path: say_thank
      method: "post"
      inputs:
        id: "{{ .DownloadUri.Query.id }}"
    selector: a[href^="downloadnew.php?id="]
```

**Comment by garfield69** [comment]
@kaso17  there is some weird stuff happening with the download-before block.
in the end I solved it by adding an underscore to the first input, so it would offset its placement in the url correctly.
```yaml
  download:
    before:
      path: ajax.php
      method: get
      inputs:
        _action: "say_thank"
        id: "{{ .DownloadUri.Query.id }}"
    selector: a[href^="downloadnew.php?id="]
```
if you ever fix what is going on with this we need to remember to remove the underscore from this indexer.
