### ISSUE TITLE
[REQ] RPTScene

### ISSUE THREAD

**Issue by pyr0ball** [Jackett/Jackett#5368]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Private

### Tracker details

```markdown
- Name: RPTScene
- URL: https://rptscene.xyz/
- Description: RPTScene is a Private Torrent Tracker for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): MST 1d
- Additional Comments: 
Account Inactivity: "Be active here, you must login at least once a month. Also, not downloading anything is considered being inactive (except if you're an uploader or VIP). The accounts inactive for 3 months are deleted."
Engine: n/a
registration: invite only ATM
```

**Comment by garfield69** [comment]
try out jackett pre-releaes v0.11.403

**Comment by garfield69** [comment]
https://rptorrents.com/ returning: This page isn’t working HTTP ERROR 500

**Comment by garfield69** [comment]
now returning this page:
```
Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```
this is not a DNS error but a server provider error message.

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://rptorrents.com/ returns This domain name expired on 2023-03-07 22:35:20
which is a strange expiry date but whatever

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
https://rptorrents.com/ - 500 Internal Server Error

**Comment by garfield69** [comment]
v0.21.314

**Comment by garfield69** [comment]
RPT is back with a new domain and engine. Registration is currently open.

**Comment by garfield69** [comment]
Nah, its just RPT as shown in the login and the top left banner of the home page.
The email I got stated that RPTorrents was back with a new more secure source and as an old user I may like to be one of the first to register.

**Comment by ilike2burnthing** [comment]
Ah kk, the welcome message and upload page use `RPTScene`, but everywhere else is `RPT` so wasn't sure.

**Comment by garfield69** [comment]
v0.21.1491

**Comment by garfield69** [comment]
site has switched to a new engine. awaiting credential verification in order to recode the indexer

**Comment by garfield69** [comment]
v0.21.1757

**Comment by garfield69** [comment]
well f**k that didn't last long.
https://rptscene.xyz/ show
![image](https://github.com/Jackett/Jackett/assets/6933240/d7609819-a7e5-4702-a881-9a1b7119774d)

**Comment by garfield69** [comment]
I haven't even published the last domain change yet and already its gone!
https://rpthd.com/ redirects to https://rpthd.com/cgi-sys/defaultwebpage.cgi

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://rpthd.com/ Something amazing will be constructed here..

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5368#issuecomment-1952976557

**Comment by garfield69** [comment]
here we go again. new engine, open registration. I'm waiting for my password reset mail so I can login and replace the indexer yet again.

**Comment by garfield69** [comment]
v0.21.1835

**Comment by ilike2burnthing** [comment]
https://rptscene.xyz/ - ERR_NAME_NOT_RESOLVED
http://rpthd.com/ - parked domain

**Comment by garfield69** [comment]
https://rptscene.xyz/ ERR_CONNECTION_REFUSED

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://rptscene.xyz/ Web server is down Error code 521

**Comment by ilike2burnthing** [comment]
Still has the odd blip, but back up

**Comment by garfield69** [comment]
rptscene -> engine: M-BiTsy PDO

**Comment by garfield69** [comment]
Urg. I'm stuck. I cannot get past the login which jackett apparently triggers flaresolverr
I've tried post, form, and cookie without and with UA. no joy.
here is may last yaml, see if you can get it to work.
<details> <summary> <b> rptscene yaml </b> </summary>
```yaml
---
id: rptscene
name: RPTScene
description: "RPTScene is a ROMANIAN Private tracker for MOVIES / TV / GENERAL"
language: en-US
type: private
encoding: UTF-8
links:
  - https://rptscene.xyz/
legacylinks:
  - https://rpthd.com/

caps:
  categorymappings:
    - {id: 2, cat: PC/0day, desc: "Apps: Windows"}
    - {id: 3, cat: PC/Mac, desc: "Apps: Mac"}
    - {id: 4, cat: PC, desc: "Apps: Linux"}
    - {id: 34, cat: PC/Mobile-Other, desc: "Apps: Mobile"}
    - {id: 38, cat: Books/EBook, desc: "Books: eBooks"}
    - {id: 39, cat: Audio/Audiobook, desc: "Books: Audio"}
    - {id: 35, cat: Console, desc: "Games: Pack"}
    - {id: 1, cat: PC/Games, desc: "Games: PC"}
    - {id: 37, cat: Movies/SD, desc: "Movies: SD"}
    - {id: 6, cat: Movies/Other, desc: "Movies: Cartoons"}
    - {id: 7, cat: Movies/WEB-DL, desc: "Movies: Web-DL"}
    - {id: 32, cat: Movies/UHD, desc: "Movies: 4k"}
    - {id: 9, cat: Movies/HD, desc: "Movies: HD"}
    - {id: 10, cat: Movies/3D, desc: "Movies: 3D"}
    - {id: 11, cat: Movies, desc: "Movies: Pack"}
    - {id: 12, cat: Movies/BluRay, desc: "Movies: Bluray"}
    - {id: 33, cat: Movies/HD, desc: "Movies: Full-HD"}
    - {id: 40, cat: Movies/DVD, desc: "Movies: DVD"}
    - {id: 41, cat: Movies/SD, desc: "Movies: Xvid"}
    - {id: 36, cat: XXX, desc: "Movies: XXX"}
    - {id: 19, cat: Audio/MP3, desc: "Music: MP3"}
    - {id: 20, cat: Audio/Lossless, desc: "Music: Flac"}
    - {id: 22, cat: Audio/Video, desc: "Music: Video"}
    - {id: 23, cat: Audio, desc: "Music: Pack"}
    - {id: 14, cat: TV/HD, desc: "TV: HD"}
    - {id: 15, cat: TV/WEB-DL, desc: "TV: WEB-DL"}
    - {id: 16, cat: TV/SD, desc: "TV: SD"}
    - {id: 17, cat: TV, desc: "TV: Pack"}
    - {id: 18, cat: TV/Documentary, desc: "TV: Documentaries"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid, tmdbid]
    movie-search: [q, imdbid, tmdbid]
    music-search: [q]
    book-search: [q]

settings:
  - name: cookie
    type: text
    label: Cookie
  - name: info_cookie
    type: info_cookie
  - name: useragent
    type: text
    label: User-Agent
  - name: info_useragent
    type: info_useragent
  - name: freeleech
    type: checkbox
    label: Search freeleech only
    default: false
  - name: sort
    type: select
    label: Sort requested from site
    default: added
    options:
      added: created
      seeders: seeders
      size: size
      name: title
  - name: type
    type: select
    label: Order requested from site
    default: desc
    options:
      desc: desc
      asc: asc
  - name: info_results
    type: info
    label: Search results
    default: "If you are not getting results, then access the site with your browser and mark as read all PMs."
  - name: info_activity
    type: info
    label: Account Inactivity
    default: "Be active here, you must login at least once a month. Also, not downloading anything is considered being inactive (except if you're an uploader or VIP). The accounts inactive for 3 months are deleted."

login:
  method: cookie
  test:
    path: /
    selector: a[href$="logout"]

search:
  paths:
    # https://rptscene.xyz/search/browse?keyword=&c32=1&c33=1&incldead=1&freeleech=0&lang=0
    - path: search/browse
  inputs:
    $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
    keywords: "{{ if or .Query.IMDBID .Query.TMDBID }}{{ or .Query.IMDBID .Query.TMDBID }}{{ else }}{{ .Keywords }}{{ end }}"
    # 0 active 1 incl dead 2 only dead
    incldead: 1
    # 0 all 1 not freeleech 2 only freeleech
    freeleech: "{{ if .Config.freeleech }}2{{ else }}0{{ end }}"
    # 0 all, 1 English, 2 Fr, 3 Ge, 4 It, 5 Ro, 6 Sp, 7 Ru
    lang: 0
    sort: "{{ .Config.sort }}"
    order: "{{ .Config.type }}"

  rows:
    selector: table.table-striped > tbody > tr

  headers:
    User-Agent: ["{{ .Config.useragent }}"]

  fields:
    category:
      selector: a[href*="?cat="]
      attribute: href
      filters:
        - name: querystring
          args: cat
    title:
      selector: a[href*="torrent?id="] > b
    details:
      selector: a[href*="torrent?id="]
      attribute: href
    download:
      selector: a[href*="download?id="]
      attribute: href
    date:
      # 2 years ago
      selector: div.row em:last-of-type
      filters:
        - name: timeago
    size:
      selector: td:nth-child(5)
    grabs:
      selector: td:nth-child(6)
    seeders:
      selector: td:nth-child(7)
    leechers:
      selector: td:nth-child(8)
    genre:
      selector: em > span
      filters:
        - name: replace
          args: ["Genre: ", ""]
    description:
      text: "{{ .Result.genre }}"
    downloadvolumefactor:
      case:
        span.badge-success: 0
        "*": 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 1.0
    minimumseedtime:
      # 1 day (as seconds = 24 x 60 x 60)
      text: 86400
# M-BiTsy PDO
```
