### ISSUE TITLE
[REQ] https://home-hd.top

### ISSUE THREAD

**Issue by groenator** [Jackett/Jackett#5395]
Request for a new tracker.

This is a private tracker.

**Comment by groenator** [comment]
Hi,

The registration is open, can you try creating an account? 

Regards,

**Comment by garfield69** [comment]
registration and login successful.

**Comment by groenator** [comment]
Sweet!

Thank you.

**Comment by garfield69** [comment]
@kaso17  or @flightlevel  I have run into a problem with downloading .torrent files from this site.
the jackett log shows
```
2019-06-10 20:25:43.2632 Debug WebClient(HttpWebClient).GetBytes(Url:https://home-hd.top/download_1428) 
2019-06-10 20:25:44.8728 Debug WebClient(HttpWebClient): Returning OK => 59061 bytes 
2019-06-10 20:25:44.8748 Error   d8:announce43:http://tr3.torrent4me.com/ann?uk=5aN5ovnrC313:announce-listll43****redacted the rest of the .torrent dump****r.utf-87:Home-HD5:valued7:comment42:??????? ?????? ??? HOME-HD6:source32:https://home-hd.top/details_1428ee 
2019-06-10 20:25:44.8748 Error Error downloading homehd https://home-hd.top/details_1428&hit=1 System.Exception: BencodeParser failed ---> BencodeNET.Exceptions.InvalidBencodeException`1[BencodeNET.Objects.IBObject]: Failed to parse IBObject. Invalid beginning character of object. Found ' ' at position 0. Valid characters are: 0-9, 'i', 'l' and 'd'
   at BencodeNET.Parsing.BencodeParser.Parse(BencodeStream stream)
   at BencodeNET.Parsing.BencodeParser.Parse(Byte[] bytes)
   at Jackett.Server.Controllers.DownloadController.<Download>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at Jackett.Server.Controllers.DownloadController.<Download>d__5.MoveNext()
2019-06-10 20:25:44.8748 Info Executed action method Jackett.Server.Controllers.DownloadController.Download (JackettConsole), returned result Microsoft.AspNetCore.Mvc.NotFoundResult in 3658.7337ms. 
2019-06-10 20:25:44.8748 Info Executing HttpStatusCodeResult, setting HTTP status code 404 
```
the thing is that if I post the Url directly from a browser the download of the .torrent file is accepted.
what is going on?

**Comment by xfouloux** [comment]
I think it may be the same issue as metal iplay ro

I had to add this bloc :

```
  download:
    method: get
    before:
      path: login.php
      method: "post"
      inputs:
        username: "{{ .Config.username }}"
        password: "{{ .Config.password }}"
```

because it was re checking for auth at the download, worked with my browser but not from jackett, and bypassed it like that.

Try ?!

**Comment by garfield69** [comment]
yeah, nah.
I tried your suggestion, but as I expected, it made no difference.
I think the issue here is that the .torrent file is prefixed with characters (spaces?) that are not part of the bittorrent bencoding specifications. It seems browsers trim these out, and jackett may need to do the same. this is guess work on my part, as i'm not a c# coder so I don't know for sure.

**Comment by garfield69** [comment]
my account on home-hd has been deleted, presumably because I did not upload or contribute.
But since I got stuck with the download link and no one has contributed a solution, I am going to put this back on the todo list, and mark it as help required.
for anyone wishing to pick this up and continue, this is the indexer yaml so far:
```yaml
---
  site: homehd
  name: Home-HD
  description: "HOME-HD is a RUSSIAN Private Torrent Tracker for HD MOVIES / TV"
  language: ru-ru
  type: private
  encoding: UTF-8
  links:
    - https://home-hd.top/

  caps:
    categorymappings:
      - {id: HDAudio, cat: Audio, desc: "Music HD-Музыка"}
      - {id: MusVideo, cat: Audio/Video, desc: "Music Videos Музыкальные Видео"}
      - {id: Animation, cat: TV/Anime, desc: "Animation Анимация"}
      - {id: Movie, cat: Movies, desc: "Movies Фильмы"}
      - {id: TV-Show, cat: TV, desc: "TV Сериалы"}
      - {id: Docum, cat: TV/Documentary, desc: "Documentaries Документалки"}
      - {id: Sport, cat: TV/Sport, desc: "Sport Спорт"}
      - {id: Demo, cat: Other, desc: "Demo"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  settings:
    - name: username
      type: text
      label: Username
    - name: password
      type: password
      label: Password
    - name: striprussian
      type: checkbox
      label: Strip Russian Letters
      default: false

  login:
    path: takelogin.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
      expires: 0
    error:
      - selector: table:contains("failed")
    test:
      path: browse
      selector: a[href="logout"]

#  download:
#    method: get
#    before:
#      path: login.php
#      method: "post"
#      inputs:
#        username: "{{ .Config.username }}"
#        password: "{{ .Config.password }}"
#    selector: a[href^="download_"]

  search:
    paths:
    # https://home-hd.top/browse?search=batman&incldead=0&janr=0&tip=0&webdl=0&3d=0&voice=0&tsearch=&dsearch=
      - path: browse
    inputs:
      search: "{{ .Keywords }}"
      # 0 all 6 simple 5 silver 3 gold 7 diamond 4 without sid?
      incldead: 0
      # category
      janr: 0
      # quality
      tip: 0
      webdl: 0
      3d: 0
      voice: 0
      # must have first word in title
      tsearch: ""
      # look in description
      dsearch: ""
    rows:
      selector: tr.highlight
    fields:
      title:
        selector: a[href^="details_"]
        filters:
          - name: re_replace
            args: ["(\\([А-Яа-яЁё\\W]+\\))|(^[А-Яа-яЁё\\W\\d]+\\/ )|([а-яА-ЯЁё \\-]+,+)|([а-яА-ЯЁё]+)", "{{ if .Config.striprussian }}{{ else }}$1$2$3$4{{ end }}"]
      details:
        selector: a[href^="details_"]
        attribute: href
      category:
        selector: td:nth-child(1) a
        attribute: href
      download:
        selector: a[href^="details_"]
        attribute: href
        filters:
          - name: regexp
            args: "details_(\\d+)"
          - name: prepend
            args: "download_"
      date:
        selector: i
        filters:
          - name: replace
            args: ["января", "January"]
          - name: replace
            args: ["февраля", "February"]
          - name: replace
            args: ["марта", "March"]
          - name: replace
            args: ["апреля", "April"]
          - name: replace
            args: ["мая", "May"]
          - name: replace
            args: ["июня", "June"]
          - name: replace
            args: ["июля", "July"]
          - name: replace
            args: ["августа", "August"]
          - name: replace
            args: ["сентября", "September"]
          - name: replace
            args: ["октября", "October"]
          - name: replace
            args: ["ноября", "November"]
          - name: replace
            args: ["декабря", "December"]
          - name: replace
            args: [" в ", " "]
          - name: dateparse
            args: "2 January 2006 15:04:05"
      size:
        selector: td:nth-child(4)
      seeders:
        selector: td:nth-child(5)
        filters:
          - name: split
            args: [ "|", 0 ]
      leechers:
        selector: td:nth-child(5)
        filters:
          - name: split
            args: [ "|", 1 ]
      downloadvolumefactor:
        case:
          img[src="pic/golden.gif"]: "0"
          img[src="pic/silvers.gif"]: "0.5"
          img[src="pic/bril.gif"]: "0"
          "*": "1"
      uploadvolumefactor:
        case:
          img[src="pic/bril.gif"]: "2"
          "*": "1"
```
