### ISSUE TITLE
[Req] Le Chaudron - Private French Tracker

### ISSUE THREAD

**Issue by skuizy** [Jackett/Jackett#5559]
Title : Limit Of Eden
URL : https://lechaudron.nl/TTV3/Inscription
Type : MOVIES / TV / GENERAL
Language : French
Privacy : Private tracker.

It wont stay open for long

Thanks for all !

Le Chaudron is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL

**Comment by garfield69** [comment]
unfortunately, it appears to me that this site will require a c# indexer.
The download link on the details page after the thanks is given, is a href that invokes an additional javascript call
```html
<a href='javascript:;' onclick="location.href='download.php?id=83800&pass=redactedredactedredacted'" onmouseover="return overlib('<table bgcolor=blue border=2><td style=\'font-size:14px;padding:10px\'>Attention: Ne cliquez pas sur ce bouton si vous le comptez pas télécharger le fichier,<br>car ceci vous enlève immédiatement un de vos slots.<br>Les slots sont restitués dès que le téléchargement des fichiers est complété,<br>donc si vous ne téléchargez pas ce fichier, votre slot restera bloqué.<br>Mettez plutôt ce lien dans vos favoris en cliquant sur le bouton rouge avec une étoile à l\'extrême-droite.</td></table>');" onmouseout="return nd();"><img src="images/download/general.png" border="0"></a>
```
I don't think that the cardigann processor currently allows me to process the onclick attribute and extract the download link and passkey.

if anyone wants to have a go solving the download using the cardigann processor here is the yaml so far with the broken download processing I tried to use:
```yaml
---
  site: limitofeden
  name: Limit Of Eden
  description: "Limit Of Eden (LoE) is a FRENCH Private Torrent Tracker for MOVIES / TV / GENERAL"
  language: fr-fr
  type: private
  encoding: iso-8859-1
  links:
    - http://www.limit-of-eden.com/

  caps:
    categorymappings:
      # movies
      - {id: 4, cat: Movies/3D, desc: "Films - 3D"}
      - {id: 99, cat: Movies/UHD, desc: "Films - 4K UHD"}
      - {id: 48, cat: Movies/BluRay, desc: "Films - BD-RIP"}
      - {id: 92, cat: Movies/BluRay, desc: "Films - BluRay"}
      - {id: 95, cat: Movies/BluRay, desc: "Films - BR-RIP"}
      - {id: 42, cat: Movies/HD, desc: "Films - CAM-HD"}
      - {id: 76, cat: Movies/HD, desc: "Films - CAM-TS"}
      - {id: 79, cat: Movies, desc: "Films - Cine-Club"}
      - {id: 1, cat: Movies/DVD, desc: "Films - DVD-R"}
      - {id: 2, cat: Movies/DVD, desc: "Films - DVD-RIP"}
      - {id: 77, cat: Movies/DVD, desc: "Films - DVD SCR"}
      - {id: 55, cat: Movies/HD, desc: "Films - HD 1080"}
      - {id: 35, cat: Movies/HD, desc: "Films - HD 720"}
      - {id: 84, cat: Movies/HD, desc: "Films - HD-light"}
      - {id: 98, cat: Movies/HD, desc: "Films - HD-RIP"}
      - {id: 93, cat: Movies/HD, desc: "Films - HD-TV"}
      - {id: 100, cat: Movies, desc: "Films - TV-RIP"}
      - {id: 82, cat: Movies, desc: "Films - VO"}
      - {id: 47, cat: Movies, desc: "Films - VOST-FR"}
      - {id: 78, cat: Movies/WEBDL, desc: "Films - Web Rip"}
      - {id: 94, cat: Movies/WEBDL, desc: "Films - WEB-DL"}
      - {id: 52, cat: XXX, desc: "Films - XXX"}
      # games
      - {id: 11, cat: Console/3DS, desc: "Jeux - 3DS"}
      - {id: 17, cat: Console/NDS, desc: "Jeux - DS"}
      - {id: 75, cat: PC/Mac, desc: "Jeux - MAC"}
      - {id: 10, cat: PC/Games, desc: "Jeux - PC"}
      - {id: 43, cat: Console/PS3, desc: "Jeux - PS3"}
      - {id: 12, cat: Console/PSP, desc: "Jeux - PSP"}
      - {id: 44, cat: Console/Wii, desc: "Jeux - Wii"}
      - {id: 13, cat: Console/Xbox, desc: "Jeux - Xbox"}
      - {id: 14, cat: Console/Xbox 360, desc: "Jeux - Xbox360"}
      # tv
      - {id: 51, cat: TV/Sport, desc: "TV - Sport"}
      - {id: 7, cat: TV, desc: "TV - TV DVD"}
      - {id: 6, cat: TV/HD, desc: "Series TV - HD FR"}
      - {id: 85, cat: TV/HD, desc: "Series TV - HD VOSTFR"}
      - {id: 89, cat: TV, desc: "Series TV - TV-VO"}
      - {id: 41, cat: TV, desc: "Series TV - VF"}
      - {id: 5, cat: TV, desc: "Series TV - VOSTFR"}
      - {id: 64, cat: TV, desc: "Series TV - Tv Pack"}
      # software
      - {id: 61, cat: PC/Phone-Android, desc: "Apps - Android"}
      - {id: 87, cat: PC/Phone-IOS, desc: "Apps - Iphone"}
      - {id: 19, cat: PC/Mac, desc: "Apps - Mac"}
      - {id: 18, cat: PC/0day, desc: "Apps - PC"}
      # music
      - {id: 62, cat: Audio, desc: "Music - Concerts"}
      - {id: 54, cat: Audio/Lossless, desc: "Music - FLAC"}
      - {id: 22, cat: Audio/MP3, desc: "Music - MP3"}
      - {id: 25, cat: Audio/Video, desc: "Music - Video"}
      - {id: 88, cat: Audio/Audiobook, desc: "Autre - Audio books"}
      - {id: 96, cat: Movies, desc: "Autre - BD"}
      - {id: 97, cat: XXX, desc: "Autre - BD adultes"}
      - {id: 74, cat: Movies, desc: "Autre - Divers"}
      - {id: 9, cat: TV/Documentary, desc: "Autre - Documentaires"}
      - {id: 36, cat: Books/Ebook, desc: "Autre - E-Books"}
      - {id: 63, cat: Books, desc: "Autre - Presse"}
      - {id: 27, cat: Movies, desc: "Autre - SPECTACLE"}
      - {id: 80, cat: Movies/WEBDL, desc: "Autre - Web Series"}
      # anime
      - {id: 28, cat: TV/Anime, desc: "Anime - All"}
      - {id: 91, cat: TV/Anime, desc: "Anime - Anime 1080p"}
      - {id: 90, cat: TV/Anime, desc: "Anime - Anime 720p"}
      - {id: 102, cat: TV/Anime, desc: "Anime - Anime BRRIP"}
      - {id: 60, cat: TV/Anime, desc: "Anime - Hentai"}
      - {id: 59, cat: TV/Anime, desc: "Anime - Manga"}
      - {id: 101, cat: TV/Anime, desc: "Anime - WEB-DL"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  login:
    path: wqreyt/account-login.php
    method: post
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
    error:
      - selector: div.error-cap
    test:
      path: wqreyt/index.php
      selector: a[href="account-logout.php"]

  ratio:
    path: wqreyt/index.php
    selector: center span:contains("Ratio:")
    filters:
      - name: replace
        args: ["Ratio: ", ""]

  download:
    before:
      path: wqreyt/thanks.php
      inputs:
        _torrent: "{{ .DownloadUri.Query.id }}"
    selector: a[onclick*="download.php?id="]
    attribute: onclick
    filters:
      - name: replace
        args: ["location.href='", "wqreyt/"]
      - name: replace
        args: ["'", ""]

  search:
    paths:
      # http://www.limit-of-eden.com/wqreyt/torrents-search.php?search=daredevil&incldead=1&freeleech=0&highspeed=0&lang=0&sort=id&order=desc&c51=1
      - path: wqreyt/torrents-search.php
    inputs:
      $raw: "{{range .Categories}}c{{.}}=1&{{end}}"
      search: "{{ .Keywords }}"
      incldead: 1
      highspeed: 0
      freeleech: 0
      lang: 0
      sort: "id"
      order: "desc"
    rows:
      selector: table.ttable_headinner tr:has(a[href^="torrents-details.php?id="])
    fields:
      title:
        selector: a[href^="torrents-details.php?id="]
      details:
        selector: a[href^="torrents-details.php?id="]
        attribute: href
      download:
        selector: a[href^="torrents-details.php?id="]
        attribute: href
      category:
        selector: a[href^="torrents.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: cat
      banner:
        selector: a[href^="torrents-details.php?id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "src=(.*?) width="
      date:
        selector: a[href^="torrents-details.php?id="][onmouseover]
        attribute: onmouseover
        filters:
          - name: regexp
            args: "\\sAjouté: (.*?)\\s</div>"
          - name: dateparse
            args: "2006-01-02 15:04:05"
      size:
        selector: td:nth-child(10)
      grabs:
        selector: td:nth-child(11)
      seeders:
        selector: td:nth-child(12)
      leechers:
        selector: td:nth-child(13)
      downloadvolumefactor:
        case:
          "img[src=\"images/check.png\"]": "0"
          "*": "1"
      uploadvolumefactor:
        case:
          "*": "1"
```
