### ISSUE TITLE
Question about definition format

### ISSUE THREAD

**Issue by Yllelder** [Jackett/Jackett#5666]
I'm creating a yaml file for a website.

My problem is that search results don't offer torrent size. The size and year of the movie are on the details page of each individual movie.

```yaml
search:
  fields:
    size:
      selector: (HOW DO I GET THE CSS SELECTOR FROM THE DETAILS PAGE TO INSERT IT HERE?)
```
As much as I study other indexers to learn, I can't find any case like this one.

Thank you.
