### ISSUE TITLE
[REQ] Anilibria

### ISSUE THREAD

**Issue by Ditinex-ru** [Jackett/Jackett#5762]
https://www.anilibria.tv/pages/catalog.php

[edit] https://github.com/anilibria/docs/blob/master/api_v2.md

**Comment by garfield69** [comment]
Public Russian Anime site.

Unfortunately the site is not compatible with current implementation of the Cardigann processor as it has single results posters that lead to a details page with multiple torrent download links.
This will require a c# indexer.

Also it appears to be a purely Russian site, the search engine appears to only match Russian titles.

**Comment by garfield69** [comment]
Jackett 0.16.1771

**Comment by ilike2burnthing** [comment]
https://www.anilibria.tv/ - working

https://api.anilibria.tv/v2//getUpdates?limit=100&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year - working

https://api.anilibria.tv/v2/searchTitles?search=naruto - Error 500 - Internal server error

Happened a few times now - https://github.com/Jackett/Jackett/issues/10580

@dm3ch any insights?

**Comment by kekal** [comment]
I wrote to their support, and they quickly fixed the API back.
Brave new world.
![image](https://user-images.githubusercontent.com/13663141/104132212-6d54e200-5384-11eb-9dc9-7a5d4cf33819.png)

**Comment by ilike2burnthing** [comment]
https://www.anilibria.tv/ - working

https://api.anilibria.tv/v2/getUpdates?limit=100&filter=names%2Cposter.url%2Ccode%2Ctorrents.list%2Cseason.year
AND
https://api.anilibria.tv/v2/searchTitles?search=naruto

```text
{"error":{"code":500,"message":"Connecting to database..."}}
```

**Comment by dm3ch** [comment]
@ilike2burnthing Now links you've provided working for me.

Seems that anilibria had some technical issues

**Comment by garfield69** [comment]
generating `{"error":{"code":500,"message":"Connecting to database..."}}` again

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/5762#issuecomment-1097518157

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
https://api.anilibria.tv/v3/title/updates?filter=names,posters.small.url,code,torrents.list,season.year,description&limit=100 > ERR_INVALID_RESPONSE

**Comment by kekal** [comment]
> https://api.anilibria.tv/v3/title/updates?filter=names,posters.small.url,code,torrents.list,season.year,description&limit=100 > ERR_INVALID_RESPONSE

Working for me 
```
{"list":[{"names":{"ru":"Мгновение Лили","en":"Momentary Lily","alternative":null},"posters":{"small":{"url":"/storage/releases/posters/9879/5NoDRy0TvwxogCKsIdg5SDSF6c9ugd9e.jpg"}},"code":"momentary-lily","torrents":{"list":[{"torrent_id":32087,"episodes":{"first":1,"last":3,"string":"1-3"},"quality":{"string":"WEBRip 1080p","type":"WEBRip","resolution":"1080p","encoder":"h264","lq_audio":null},"leechers":17,"seeders":14,"downloads":540,"total_size":4432883299,"size_string":"4.43 GB","url":"/public/torrent/download.php?id=32087","magnet":"magnet:?xt=urn:btih:927e4c99fd4bc5cd299ee623c87864db272285c2&tr=http%3A%2F%2Ftr.libria.fun%3A2710%2Fannounce","uploaded_timestamp":1737387794,"hash":"927e4c99fd4bc5cd299ee623c87864db272285c2","metadata":null,"raw_base64_file":null},{"torrent_id":32059,"episodes":{"first":1,"last":2,"string":"1-2"},"quality":{"string":"WEBRip 1080p HEVC","type":"WEBRip","resolution":"1080p","encoder":"h265","lq_audio":null},"leechers":2,"seeders":20,"downloads":260,"total_size":1288957383,"size_string":"1.29 GB","url":"/public/torrent/download.php?id=32059","magnet":"magnet:?xt=urn:btih:c6c4f2f8fda6f3d4ec74d5daab548d5de51a1118&tr=http%3A%2F%2Ftr.libria.fun%3A2710%2Fannounce","uploaded_timestamp":1737241425,"hash":"c6c4f2f8fda6f3d4ec74d5daab548d5de51a1118","metadata":null,"raw_base64_file":null}]},"season":{"year":2025},...
```

**Comment by garfield69** [comment]
Yes, clearly was a temporary issue.
Online.

**Comment by garfield69** [comment]
https://api.anilibria.tv/v3/title/updates?filter=names%2Cposters.small.url%2Ccode%2Ctorrents.list%2Cseason.year%2Cdescription&limit=100 > {"error":{"code":504,"message":"Gateway Timeout"}}

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
https://api.anilibria.tv/v3/title/updates?filter=names%2Cposters.small.url%2Ccode%2Ctorrents.list%2Cseason.year%2Cdescription&limit=100 > Returning InternalServerError => {"error":{"code":502,"message":"Bad Gateway"}}

**Comment by garfield69** [comment]
online

**Comment by kekal** [comment]
@garfield69 
As far as I understand, this endpoint is regularly down, and they promote using a new site with a new API.
And yes, they still have no season field.

https://www.anilibria.top/api/docs/v1#/%D0%90%D0%BD%D0%B8%D0%BC%D0%B5%20%3A%3A%20%D0%A0%D0%B5%D0%BB%D0%B8%D0%B7%D1%8B/db2de499f814a375405b077e3c9f081a

**Comment by garfield69** [comment]
Oh joy, so a new domain and a new api. I'll see if I can rework the indexer.

**Comment by garfield69** [comment]
Unfortunately while the new  API lets me pull up a list of the latest torrents easily enough, a keyword search returns just the main root of series/movies in a different layout, requiring a additional separate fetch of the torrents :-(

This is not suitable for processing with our cardigann yaml 
It would require writing the indexer in C#

For now we will continue using the current API and put up with the outages until a C# developer volunteers time and effort.

**Comment by garfield69** [comment]
https://www.anilibria.tv/ > WEB Server is down Error 521

**Comment by garfield69** [comment]
online

**Comment by garfield69** [comment]
Is this PR ready for testing or WIP?

**Comment by garfield69** [comment]
migrated Anilibria yaml indexer to C# with new domain and API v0.22.2072

**Comment by garfield69** [comment]
@impr3ssi0n  seeing missing category from some results.
example:
![Image](https://github.com/user-attachments/assets/bf6e93fa-ef56-477c-9667-e00302ee1000)

**Comment by garfield69** [comment]
Also, as a lower priority task, we should try to carry over the config options from the old yaml indexer which supposedly improved sonarr compatibility.
Key sections:

<details>

  <summary>config settings</summary>

```yaml
settings:
  - name: stripcyrillic
    type: checkbox
    label: Strip Cyrillic Letters
    default: false
  - name: sonarr_compatibility
    type: checkbox
    label: Improve Sonarr compatibility by trying to better parse Season information in release titles.
    default: false
  - name: addrussiantotitle
    type: checkbox
    label: Add RUS to end of all titles to improve language detection by Sonarr and Radarr. Will cause English-only results to be misidentified.
    default: false
```
</details>

<details>

  <summary>title processing</summary>

```yaml
  fields:
    _episodes:
      selector: episodes.string
      optional: true
    category:
      text: "{{ if eq .Result._episodes \"Фильм\" }}Movies{{ else }}Anime{{ end }}"
    title_ru:
      selector: ..names.ru
    title_en:
      selector: ..names.en
    title_en_parsed:
      selector: ..names.en
      filters:
        - name: re_replace
          args: ["(?i)\\bPart\\s*1\\b", "Part One"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*2\\b", "Part Two"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*3\\b", "Part Three"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*4\\b", "Part Four"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*5\\b", "Part Five"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*6\\b", "Part Six"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*7\\b", "Part Seven"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*8\\b", "Part Eight"]
        - name: re_replace
          args: ["(?i)\\bPart\\s*9\\b", "Part Nine"]
        - name: re_replace
          args: ["(?i)\\bseason\\s*(\\d+)\\b", ""]
        - name: re_replace
          args: ["(?i)\\b(\\d+)(st|nd|rd|th)\\s*season[\\s\\.]*", ""]
        - name: re_replace
          args: ["(?i)\\b(\\d+)\\s*season\\b[\\s\\.]*", ""]
        - name: re_replace
          args: ["(?i)\\bseason\\s*([IVXLCDM]+)\\b", ""]
        - name: re_replace
          args: ["\\bI$", ""]
        - name: re_replace
          args: ["\\bII$", ""]
        - name: re_replace
          args: ["\\bIII$", ""]
        - name: re_replace
          args: ["\\bIV$", ""]
        - name: re_replace
          args: ["\\bV$", ""]
        - name: re_replace
          args: ["\\bVI$", ""]
        - name: re_replace
          args: ["\\bVII$", ""]
        - name: re_replace
          args: ["\\bVIII$", ""]
        - name: re_replace
          args: ["\\bIX$", ""]
        - name: re_replace
          args: ["\\bX$", ""]
        - name: re_replace
          args: ["(?i)\\b(\\d+)(?:st|nd|rd|th)?\\b", ""]
        - name: trim
    title_alternative:
      selector: ..names.alternative
      optional: true
      filters:
        - name: re_replace
          args: ["(\\([\\p{IsCyrillic}\\W]+\\))|(^[\\p{IsCyrillic}\\W\\d]+\\/ )|([\\p{IsCyrillic} \\-]+,+)|([\\p{IsCyrillic}]+)", "{{ if .Config.stripcyrillic }}{{ else }}$1$2$3$4{{ end }}"]
        - name: re_replace
          args: ["[\\[\\(\\{<«][\\s\\W]*[\\]\\)\\}>»]", ""]
        - name: re_replace
          args: ["^[\\s&,\\.!\\?\\+\\-_\\|\\/':]+", ""]
        - name: re_replace
          args: ["^OVA$", ""]
    _season_number_en:
      selector: ..names.en
      filters:
        - name: re_replace
          args: ["(?i)\\bPart\\s*\\d+\\s*$", ""]
        - name: re_replace
          args: ["(?i)(^.*\\bseason\\s*(\\d+)\\b\\s*$)", "S$2"]
        - name: re_replace
          args: ["(?i)(^.*\\b(\\d+)(st|nd|rd|th)\\s*season\\b.*$)", "S$2"]
        - name: re_replace
          args: ["(?i)(^.*\\b(\\d+)\\s*season\\b.*$)", "S$2"]
        - name: re_replace
          args: ["(?i)(^.*\\bseason\\s*([IVXLCDM]+)\\b\\s*$)", "$1"]
        - name: re_replace
          args: ["(^.*X$)", "S10"]
        - name: re_replace
          args: ["(^.*IX$)", "S9"]
        - name: re_replace
          args: ["(^.*VIII$)", "S8"]
        - name: re_replace
          args: ["(^.*VII$)", "S7"]
        - name: re_replace
          args: ["(^.*VI$)", "S6"]
        - name: re_replace
          args: ["(^.*V$)", "S5"]
        - name: re_replace
          args: ["(^.*IV$)", "S4"]
        - name: re_replace
          args: ["(^.*III$)", "S3"]
        - name: re_replace
          args: ["(^.*II$)", "S2"]
        - name: re_replace
          args: ["(^.*I$)", "S1"]
        - name: re_replace
          args: ["(?i)(^.*\\b(\\d+)(?:st|nd|rd|th)?\\b\\s*$)", "S$2"]
        - name: re_replace
          args: ["(?i)^(?!S\\d+).*", ""]
    _season_number_alternative:
      selector: ..names.alternative
      optional: true
      filters:
        - name: re_replace
          args: ["(?i)\\bPart\\s*\\d+\\s*$", ""]
        - name: re_replace
          args: ["(?i)(^.*\\bseason\\s*(\\d+)\\b\\s*$)", "S$2"]
        - name: re_replace
          args: ["(?i)(^.*\\b(\\d+)(st|nd|rd|th)\\s*season\\b\\s*$)", "S$2"]
        - name: re_replace
          args: ["(?i)(^.*\\b(\\d+)\\s*season\\b\\s*$)", "S$2"]
        - name: re_replace
          args: ["(?i)(^.*\\bseason\\s*([IVXLCDM]+)\\b\\s*$)", "$1"]
        - name: re_replace
          args: ["(^.*X$)", "S10"]
        - name: re_replace
          args: ["(^.*IX$)", "S9"]
        - name: re_replace
          args: ["(^.*VIII$)", "S8"]
        - name: re_replace
          args: ["(^.*VII$)", "S7"]
        - name: re_replace
          args: ["(^.*VI$)", "S6"]
        - name: re_replace
          args: ["(^.*V$)", "S5"]
        - name: re_replace
          args: ["(^.*IV$)", "S4"]
        - name: re_replace
          args: ["(^.*III$)", "S3"]
        - name: re_replace
          args: ["(^.*II$)", "S2"]
        - name: re_replace
          args: ["(^.*I$)", "S1"]
        - name: re_replace
          args: ["(?i)(^.*\\b(\\d+)(?:st|nd|rd|th)?\\b\\s*$)", "S$2"]
        - name: re_replace
          args: ["(?i)^(?!S\\d+).*", ""]
    _season_number:
      text: "{{ .Result._season_number_en }}"
      filters:
        - name: append
          args: "{{ .Result._season_number_alternative }}"
        - name: re_replace
          args: ["^S1S1$", "S1"]
        - name: re_replace
          args: ["^S1(.+)$", "$1"]
        - name: re_replace
          args: ["^(S\\d+).*$", "$1"]
        - name: re_replace
          args: ["^$", "S1"]
    year:
      selector: ..season.year
    _quality:
      selector: quality.string
    _quality_type:
      selector: quality.type
    _quality_resolution:
      selector: quality.resolution
    _quality_encoder:
      selector: quality.encoder
      filters:
        - name: re_replace
          args: ["(?i)^h", "x"]
    title_parsed:
      text: "{{ if .Config.stripcyrillic }}{{ else }}{{ .Result.title_ru }} / {{ end }}{{ .Result.title_en_parsed }} {{ .Result._season_number}}E{{ .Result._episodes }} [{{ .Result._quality_type }} {{ .Result._quality_resolution }} {{ .Result._quality_encoder }}]"
      filters:
        - name: re_replace
          args: ["\\bS\\d+EФильм\\b", "({{ .Result.year }}) MOVIE"]
        - name: re_replace
          args: ["\\bS\\d+EOVA\\b", "({{ .Result.year }}) OVA"]
        - name: re_replace
          args: ["\\bS\\d+EONA\\b", "({{ .Result.year }}) ONA"]
        - name: re_replace
          args: ["\\bS\\d+EMovie\\b", "({{ .Result.year }}) MOVIE"]
        - name: re_replace
          args: ["\\bS\\d+EП/м фильм\\b", "({{ .Result.year }}) MOVIE"]
        - name: re_replace
          args: ["\\bS\\d+EРекап\\b", "({{ .Result.year }}) RECAP"]
        - name: re_replace
          args: ["\\bS\\d+ETV-Special\\b", "({{ .Result.year }}) SPECIAL"]
        - name: append
          args: "{{ if .Config.addrussiantotitle }} - RUS{{ else }}{{ end }}"
    title_original:
      text: "{{ if .Config.stripcyrillic }}{{ else }}{{ .Result.title_ru }} / {{ end }}{{ .Result.title_en }}{{ if .Result.title_alternative }} / AKA {{ .Result.title_alternative }}{{ else }}{{ end }} ({{ .Result.year }}) [{{ .Result._quality }}]{{ if .Result._episodes }} - E{{ .Result._episodes }}{{ else }}{{ end }}"
      filters:
        - name: re_replace
          args: [" - \\bEФильм\\b", " - MOVIE"]
        - name: re_replace
          args: [" - \\bEMovie\\b", " - MOVIE"]
        - name: re_replace
          args: [" - \\bEП/м фильм\\b", " - MOVIE"]
        - name: re_replace
          args: [" - \\bEOVA\\b", " - OVA"]
        - name: re_replace
          args: [" - \\bEONA\\b", " - ONA"]
        - name: append
          args: "{{ if .Config.addrussiantotitle }} - RUS{{ else }}{{ end }}"
    title:
      text: "{{ if .Config.sonarr_compatibility }}{{ .Result.title_parsed }}{{ else }}{{ .Result.title_original }}{{ end }}"
```
</details>
