### ISSUE TITLE
Il corsaro nero - diacritics

### ISSUE THREAD

**Issue by Jorman** [Jackett/Jackett#5852]
Hi, I'm ready to publish some fix about diacritics and char replacement.

On many indexer diacritics not make the difference but on Il corsaro nero yes, this mean that if you search:
Book Club - Tutto Può Succedere
you find some results
and if you search
Book Club - Tutto Puo Succedere
you'll find other results
Now, on my local language the right movie title is with "ò" so for me make sense maintain the right title, for this I removed the diacritics filter during a keyword search.
I inserted diacritics filter on title extraction but seems that not works.
Looks at the code
```
    fields:
      title:
        selector: td:nth-child(2) a.tab
        attribute: href
        filters:
          - name: split
            args: [ "/", -1 ]
          - name: urldecode
          # - name: re_replace # replace special characters with " " (space)
          #   args: ["[^a-zA-Z0-9\\s]|\\.", " "]
          - name: re_replace # replace special characters with " " (space)
            args: ["[\\[!\"#$%&'()*+,\\-.\\/:;<=>?@[\\]^_`{|}~]", " "]
          - name: diacritics
            args: replace
          - name: re_replace # replace multiple spaces
            args: ["[ ]{2,}", " "]
          # normalize to SXXEYY format
          - name: re_replace # S01 E01 to S01E01
            args: ["(?i)\\bS(\\d+)\\sE(\\d+)\\b", "S$1E$2"]
          - name: re_replace # 01x01 to S01E01
            args: ["(?i)(\\d{2})x(\\d+)", "S$1E$2"]
          - name: re_replace # 1x01 to S01E01
            args: ["(?i)\\b(\\d{1})x(\\d+)", "S0$1E$2"]
          - name: re_replace # Stagione X --> S0X
            args: ["(?i)\\bStagion[ei]\\s?(\\d{1})\\b|\\bSeason'?s?\\s?(\\d{1})\\b", "S0$1$2"]
          - name: re_replace # Stagione XX --> SXX
            args: ["(?i)\\bStagion[ei]\\s?(\\d{2,})\\b|\\bSeason'?s?\\s?(\\d{2,})\\b", "S$1$2"]
          - name: re_replace # Episodio 4 to E4
            args: ["(?i)\\b(?:[\\/\\|]?Episodio\\s?(\\d+)|Puntata\\s?(\\d+))", "E$1$2"]
          - name: re_replace # Episodi 4 5 to E04-05
            args: ["(?i)\\b(?:Puntate\\s*)(\\d+)\\s?(\\d+)", "E0$1-0$2"]
          - name: re_replace # rimozioni varie
            args: ["(?i)(Serie completa|Completat?a?|in pausa)", ""]
      category:
```
And see the resuls on jackett
![aaa](https://user-images.githubusercontent.com/5203988/63039577-e2886300-bec3-11e9-87d9-141f6d25fb6f.PNG)
What happen?
