### ISSUE TITLE
[Ice torrent] Password length limit

### ISSUE THREAD

**Issue by vavavr00m** [Jackett/Jackett#6371]
Password accepts 18 chars only. if more than 18, Jackett fails.

**Comment by garfield69** [comment]
This will require an enhancement to the cardigann c# code to enable, for example, a maxlength keyword to the settings block used by cardigann when presenting the indexer config panel.
suggested example:
```yaml
  settings:
    - name: username
      type: text
      label: Username
      maxlength: 30
    - name: password
      type: password
      label: Password
      maxlength: 18
```
the enhancement would be the equivalent to the maxlength keyword on the html input tag
```html
<form action="/action_page.php">
  Username: <input type="text" name="username" maxlength="30">
  Password: <input type="password" name="password" maxlength="18">
  <input type="submit" value="Submit">
</form>
```
I would welcome any c# dev to volunteer to implement such an enhancement (if its possible) to the cardigann processor's settings block.
