### ISSUE TITLE
[Help] Add [spanish] to nyaa.si if title have [PuyaSubs!]

### ISSUE THREAD

**Issue by vinanrra** [Jackett/Jackett#6635]
Hi, i would like to add [spanish] tag if the title have [PuyaSubs!]

i have tried:

![imagen](https://user-images.githubusercontent.com/4247187/71042438-0686da00-212c-11ea-865a-202358db183e.png)

![imagen](https://user-images.githubusercontent.com/4247187/71042443-0dade800-212c-11ea-849f-4d458d959021.png)

![imagen](https://user-images.githubusercontent.com/4247187/71042455-18687d00-212c-11ea-897a-91aa26197f31.png)

![imagen](https://user-images.githubusercontent.com/4247187/71042472-23231200-212c-11ea-8aeb-eaa296f395e6.png)

But all i have done isnt working, if someone can help me, because [PuyaSubs!] only upload spanish subs and i would like to mark as Spanish for Sonarr.

**Comment by garfield69** [comment]
replace all your title flavours with this block
```yaml
      title:
        selector: td:nth-child(2) a:last-of-type
      title:
        selector: td:nth-child(2) a:last-of-type:contains("[PuyaSubs!] ")
        optional: true
        filters:
          - name: replace
            args: ["[PuyaSubs!] ", ""]
          - name: append
            args:  " Spanish"
```

**Comment by doctorase** [comment]
Where I need to paste this block to setup the spanish search like this way? Thanks

**Comment by garfield69** [comment]
@doctorase  just upgrade your jackett to version 0.12.1470 or newer and it will include this enhancement.

**Comment by trilirante** [comment]
I don't see how this is an enhancement. Before this change PuyaSubs's content was properly marked as spanish and you could even add a tag in sonarr to give it more priority. Right now it gets mixed with other content that has "spanish" in the title. Is it possible to revert this or make it optional?

**Comment by vinanrra** [comment]
> 
> 
> I don't see how this is an enhancement. Before this change PuyaSubs's content was properly marked as spanish and you could even add a tag in sonarr to give it more priority. Right now it gets mixed with other content that has "spanish" in the title. Is it possible to revert this or make it optional?

Before this change ([LINK TO PREVIOUS VERSION](https://github.com/Jackett/Jackett/releases/tag/v0.12.1245)) PuyaSubs content wasnt marked as spanish, 

![imagen](https://user-images.githubusercontent.com/4247187/72681894-4b55b600-3ac8-11ea-8388-b14ceb277c8f.png)

Its true that its a bit confusing, i will try to improve it.

**Comment by trilirante** [comment]
You're correct, content wasn't marked as spanish before. In my opinion to fix the problem you should append "[Spanish]" to the end of the title instead of your suggestion. It would follow the scene schema and will look more cleaner.

**Comment by vinanrra** [comment]
> 
> 
> You're correct, content wasn't marked as spanish before. In my opinion to fix the problem you should append "[Spanish]" to the end of the title instead of your suggestion. It would follow the scene schema and will look more cleaner.

Okay so this will be better:

```yml
      title:
        selector: td:nth-child(2) a:last-of-type
      title:
        selector: td:nth-child(2) a:last-of-type:contains("[PuyaSubs!] ")
        optional: true
        filters:
          - name: append
            args: " [Spanish]"
```

Now will be like:

[PuyaSubs!] .......................................... [Spanish]
