### ISSUE TITLE
[efectodoppler] search not returning results

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#6929]
Tracker: efectodoppler
Search: luis perales

I get results in the website but 0 in Jackett

**Comment by garfield69** [comment]
tricky
![image](https://user-images.githubusercontent.com/6933240/72211665-1d0a3080-3534-11ea-8aa9-880227e45283.png)
the form on the site has artist-name or album/torrent-name
I assumed the album/torrent-name would be the one to use for all general searches
and when I was initially testing this I entered beatles and got results so I assumed all was good.

but I see now that torrent-name is not useful. this is really just the album name. artist is not included apparently.
but If I start using the artist-name field then we cannot search for albums using the jackett dashboard search page.
I can optionally code for lidarr artist or album, but for the dashboard general search I've got to pick one or the other ... so what to do?

**Comment by garfield69** [comment]
```yaml
  search:
    paths:
      - path: torrents.php
    inputs:
      artistname: "{{ or (.Query.Artist) (.Keywords) }}"
      groupname: "{{ .Query.Album }}"
      order_by: "{{ .Config.sort }}"
      order_way: "{{ .Config.type }}"
```
this is probably the better compromise. 
dashboard search uses artist and lidarr can use either or both.
