### ISSUE TITLE
Searching Chinese keyword in The Pirate Bay return totally unrelated result

### ISSUE THREAD

**Issue by JayXon** [Jackett/Jackett#7291]
This is probably the website's bug, however it is very annoying if I have to disable it everytime I search in Chinese, would it be possible for Jackett to detect this case and return nothing instead?

![image](https://user-images.githubusercontent.com/1552641/75089640-e13d9000-550f-11ea-9f0c-08e5eb328d23.png)

**Comment by garfield69** [comment]
TPB web site does indeed appear to return unrelated results when  using simplified Chinese keywords.
But if you search using standard English keywords, and there is no match, TPB returns `o hits. Try adding an asterisk in you search phrase`
So clearly this is an issue at the web site, and the Jackett indexer simply returns what ever the web site does.
And I cant add an andmatch to force the indexer to ignore mismatches, as we are already doing an exception for General Hospital, and the andmatch will interfere with that.
So the answer is no, there is nothing that can be done about this.

**Comment by JayXon** [comment]
It seems TPB simply filter out non English words. How about adding another `re_replace` to check if the entire search phrase is not English and replace it with something in English that will never match anything?
Found some .Net regex doc that might help: https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#supported-named-blocks

**Comment by JayXon** [comment]
A better way would be to add a new feature that will skip this indexer if the search phrase matches a regex?

**Comment by RoloSoze** [comment]
@garfield69 Can anything be done or should this issue be closed?

**Comment by garfield69** [comment]
yes it can be done, I can replace `\p{IsCJKUnifiedIdeographs}` with `#` which will cause TPB to return 0 results.

**Comment by garfield69** [comment]
Jackett 0.15.5

**Comment by ilike2burnthing** [comment]
For searches with multiple words Jackett is now using [this](https://thepiratebay.vip/search/the%23avengers/0/99/100%2C101%2C102%2C103%2C104%2C199%2C200%2C201%2C202%2C203%2C204%2C205%2C206%2C207%2C208%2C209%2C299%2C300%2C301%2C302%2C303%2C304%2C305%2C306%2C399%2C400%2C401%2C402%2C403%2C404%2C405%2C406%2C407%2C408%2C499%2C500%2C501%2C502%2C503%2C504%2C505%2C506%2C599%2C600%2C601%2C602%2C603%2C604%2C605%2C699), replace the space with a hash, or `%23` rather than `%20`.

The result is it now only searches for the first word and has no categories selected.

**Comment by garfield69** [comment]
darn, that was not the intention of this ticket.
will need to reexamine how to implement this.
in the mean time I will revert this change.

**Comment by JayXon** [comment]
Maybe  `^([\\p{IsCJKUnifiedIdeographs}\\W]+)$` instead?

**Comment by ilike2burnthing** [comment]
`args: ["([\\p{IsCJKUnifiedIdeographs}\\W]+)", "."]` seems to solve both search issues:
- when using multiple words it now searches for all words in all categories
- when using simplified Chinese it shows no results
- it also had the added benefit of removing invalid results, as TPB will still show results where there isn't a `.` between keywords, but it will stop showing results with just one word

e.g. searching `daily show` in Jackett will search for `daily.show` in TPB, which will provide results for both `The.Daily.Show.2020.04.13...` and `The Daily Show 2020 04 13...`, but ignore `The Truman Show` and `The Daily Stoic`.

This was a trial and error thing with some quick testing, so definitely double check it.

**Comment by ilike2burnthing** [comment]
Oh, and just checked, `Avengers.720p` still finds `Avengers.​Endgame.​2019.​720p.​..`

**Comment by garfield69** [comment]
Jackett 0.16.18

**Comment by JayXon** [comment]
This issue is back

**Comment by ilike2burnthing** [comment]
@masterwok ping

**Comment by garfield69** [comment]
forgot about this when we converted the old yaml to C# :-(
the relevant yaml section was:
```yaml
    # replace simplified chinese as this confuses TPB search engine #7291
    - name: re_replace
      args: ["([\\p{IsCJKUnifiedIdeographs}\\W]+)", "."]
```

**Comment by garfield69** [comment]
Oh, forgot to mention that the re_replace was in the keywords filter
better show the whole block
```yaml
search:
  paths:
    - path: "{{ if .Keywords }}/search/{{ .Keywords }}/0/{{ .Config.order }}/{{ join .Categories \",\"}}{{else}}/recent{{end}}"
  keywordsfilters:
    # remove it's #8829
    - name: re_replace
      args: ["(?i)(it's\\s)", ""]
    # replace simplified chinese as this confuses TPB search engine #7291
    - name: re_replace
      args: ["([\\p{IsCJKUnifiedIdeographs}\\W]+)", "."]
      # currently, the only uploader for General Hospital puts a space between season and episode
      # this filter searches both formats, so "General Hospital S01E02" becomes "General Hospital S01E02 | (S01 E02)"
    - name: re_replace
      args: ["General Hospital S(\\d{2,3})E(\\d{2,3})", "$0 | \\(S$1 E$2\\)"]
    - name: tolower
```
