### ISSUE TITLE
Jackett with Traefik

### ISSUE THREAD

**Issue by djdaniels90** [Jackett/Jackett#7330]
**Please use the search bar** at the top of the page and make sure you are not creating an already submitted issue.
Check closed issues as well, because your issue may have already been fixed.

Please read our [Contributing Guidelines](https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md) before submitting your issue to ensure a prompt response to your bug.

Will continue to update this ticket with more information, i don't have much time tonight however i put the relevant info for the issue based on what I think it is- routing-related. I am converting my existing setup to a new setup with a traefik proxy and routing is the bane of my existence.  Seems every service has its own routing specific config almost.

### Environment

**OS**:
Unix 4.19.0.0 (64bit OS) (64bit process)
docker container
linuxserver/jackett

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]
(couldn't run this with docker exec will have to debug a bit more than i have time tonight)

**.Net Version**:

**Jackett Version**:
Jackett v0.13.188.0

**Last Working Jackett Version**:
na, new setup

**Are you using a proxy or VPN?** yes traefik

### Description

I have read all the related info on the reverse proxies, not sure how to replicate that with traefik, the only thing missing is forwarded-for headers.  My understanding was that was for link generation.  This is definitely a routing issue. I understand if this might be a question more related to traefik however, once I figure this out I can add a recipe to the reverse proxy docs here.  Seems like traefik settings would be nice to have for sub-domain based routing.

```
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID
      - PGID
      - TZ
      # - RUN_OPTS=run options here #optional
    volumes:
      - ./services/jackett:/config
      - ${JACKET_BLACKHOLE}:/downloads
    # ports:
      # - 9117:9117
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.$INTERNAL_HOST`)"
      - "traefik.http.routers.jackett.entrypoints=web"
```
with the following traefik config (nothing special)

```
  traefik:
    image: "traefik:latest"
    restart: always
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
    networks:
      - backend
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "metrics"
      - "metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
    ports:
      - "80:80"
        #- "443:443"
      - "8080:8080"
```
### Logged Error Messages

I will start compiling more information with logs however there are no log errors being thrown.

### Screenshots

[Place any screenshots of the issue here if needed]
