### ISSUE TITLE
[REQ] world-torrent

### ISSUE THREAD

**Issue by 97carmine** [Jackett/Jackett#7574]
### Have you read our Contributing Guidelines?

- [X] I have read the Contributing Guidelines

### Is there already a request for your tracker?

- [X] I have checked older issues, open and closed

### Type

Semi-Private

### Tracker details

```markdown
- Name: zetorrents
- URL: https://www.zetorrents.pw/
- Description: zetorrents
description: "zetorrents is a FRENCH Semi-Private site for MOVIES / TV / GENERAL
- Minimum Seeding Time and/or Minimum Seeding Ratio (if Private): 
- Additional Comments: 
```

**Comment by ZarTek-Creole** [comment]
my draft : 
---
```
  site: zetorrents
  name: Zetorrents 
  description: "Torrent en Téléchargement: Films, Séries, Mangas, Musique, Jeux, Logiciels, Ebooks"
  language: fr-fr
  type: public
  encoding: UTF-8
  followredirect: true
  links:
    - https://www.zetorrents.co
  legacylinks:
    - https://www.zetorrents.co

  caps:
    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  download:
    selector: a[href^="magnet:?xt="]
    attribute: href

  category:
    selector: a[href^="torrents"]
    attribute: title
                # <a href="/torrents/series">Séries</a>
  search:
    paths:
       - path: "{{ if .Keywords }}recherche/{{ .Keywords }}/1{{else}}{{end}}"

    rows:
      selector: table.table > tbody > tr:has(a)

    fields:
      category:
        selector: a
        attribute: href

      site_date:
        selector: a
        filters:
          # date is at the end of the title, so we get it and name it site_date
          - name: regexp
            args: "(\\d{4})$"
      title:
        selector: a
        attribute: title
        filters:
          - name: replace
            args: [" en Torrent", ""]
          - name: replace
            args: [" FRENCH", " {{ .Result.site_date }} FRENCH"]
          - name: replace
            args: ["MULTI", "{{ .Result.site_date }} MULTI"]
          - name: replace
            args: ["TRUEFRENCH", "{{ .Result.site_date }} TRUEFRENCH"]
          - name: replace
            args: ["VOSTFR", "{{ .Result.site_date }} VOSTFR"]
          # and we delete it at the end
          - name: re_replace
            args: ["(\\w+)$", ""]
      details:
        selector: a
        attribute: href
      download:
        selector: a
        attribute: href
      size:
        selector: td:nth-last-child(3)
      date:
        text: now
      seeders:
        text: 0
      seeders:
        selector: td:nth-last-child(2)
        optional: true
      leechers:
        text: 0
      leechers:
        selector: td:nth-last-child(1)
        optional: true
      downloadvolumefactor:
        text: 0
      uploadvolumefactor:
        text: 1
# engine n/a

```
