### ISSUE TITLE
Definitions search on multi page ?

### ISSUE THREAD

**Issue by McDeffice** [Jackett/Jackett#7612]
Is it possible to extend the search on several pages with a loop?

I have for example: 
```

  search:
    paths:
      - path: "{{if .Keywords}}recherche/{{.Keywords}}{{else}}{{end}}"


```
I would like to loop on the following pages:

```
/recherche/{{.Keywords}}/1
/recherche/{{.Keywords}}/51
/recherche/{{.Keywords}}/101
```

I look over here https://github.com/Jackett/Jackett/wiki/Definition-format

```
 range
 A simple loop over a list variable building a concatenated string.
 
 Syntax: {{ range .Variable }}<prefix>{{.}}<suffix>{{end}}
 
 Example:
 
 # build a query string argument list for the selected categories
 # input: [101,201,301]
 "{{range .Categories}}&cat{{.}}=1{{end}}"
 # output: "&cat101=1&cat201=1&cat301=1"
```

is that a few things how?

```
  search:
    paths:
      - path: "{{if .Keywords}}{{range [1,51,101]}}recherche/{{.Keywords}}/{{.}}{{end}}{{else}}{{end}}"
```

**Comment by RoloSoze** [comment]
#975

**Comment by garfield69** [comment]
you can make multiple path calls by repeating the `- path` statement and adding the page offset
for example
```yaml
  search:
    paths:
      - path: "{{if .Keywords}}recherche/{{.Keywords}}/1{{else}}{{end}}"
      - path: "{{if .Keywords}}recherche/{{.Keywords}}/51{{else}}{{end}}"
```

keep in mind that while we usually aim to return about 100 results, this is depended on how many results are on each page, and its not advisable to do too many page fetches per search, as this can be construed by the site as a DDoS attempt.
