### ISSUE TITLE
[enhancement] add variable substitution to Cardigann Search block Headers section

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7618]
is it possible to implement variable substitution for the headers section of the search block?
for example:
```yaml
  search:
    headers:
      Referer: ["{{ .Config.sitelink }}tracker/index.php?page=torrents&search=fake_referer&active=0"]
    paths:
      - path: tracker/index.php
```
