### ISSUE TITLE
[enhancement] add Cardigann cookie method user optional switch in indexer config panel

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#7780]
There are a few open tickets already skirting around this issue of Cardigann indexers that sometimes require the cookie method to bypass any ReCaptcha challenges for when the CloudflareReSolver does not work.

I would like the following to be explored and if possible implemented.

When Cardigann presents the Config panel to users, I would like to have a permanent checkbox  called cookiebypass, which defaults to false if previously unused, and which can be preset for any yaml indexer that contains a `cookiebypass: true` statement in the yaml header block, for example:
```yaml
---
  site: demonoid
  name: Demonoid
  description: "Demonoid is a Public torrent site for MOVIES / TV / GENERAL"
  language: en-us
  type: public
  encoding: UTF-8
  followredirect: true
  cookiebypass: true
  links:
    - https://www.demonoid.is/
    - https://demonoid.unblockit.pro/
  legacylinks:
    - https://www.dnoid.to/
```

When the checkbox is set to true, Cardigann would show in that indexer's config panel the cookie box and info-cookie on how to fetch the cookie, along with what ever other settings are already present in the yaml.
If the user updates the checkbox to true/false that setting is saved in the indexers/*.json file of the indexer.
If the cookiebypass key is already in the json file then the cookiebypass statement in the yaml is ignored.

Then, when the indexer is used for a search, when the cookiebypass is true, the login block is ignored, and the cookie method is used when accessing the search path.

This would have the benefit of saving us to have to constantly update Cardigann indexers to switch in/out the login block's method=post/form code with method=cookie code, and back again, whenever sites change their DDoS security, leaving it up to the user to just update their Jackett indexer config as they require.
