### ISSUE TITLE
[Sharewood] Token CSRF not used causing lot of useless requests

### ISSUE THREAD

**Issue by Zioury** [Jackett/Jackett#7810]
Hello,

I received a message from the staff complaining about the amount of requests I do.
(about 600 in less than 10 minutes...)

As they told me :
"Each time you search a torrent using the url filterTorrents (which is the right thing to do), you first login, then it redirects you to the home page and finally you are doing your research...
It seems that Jackett look for the CSRF token but it is not using it.
The correct url should look like "sharewood.tv/filterTorrents?_token=cZyMwwDyWI5XBYrozyR2CaH8l35clOCzz2OudXt1&search=&description=&uploader=&sorting=created_at&direction=desc&qty=25"
But instead URL looks like "filterTorrents?search=&description=&uploader=&sorting=created_at&direction=desc&qty=25" causing a redirection to login page then home page then filterTorrents again...

Jackett has to find a way to store the token and use it each time jackett searchs a torrent. As they check "remember me" when logging in, the stored CSRF token will not change so soon."

They told me that you can talk to them on there IRC if needed.

Thanks in advance !

**Comment by garfield69** [comment]
Team, 
so for Sharewood, the indexer extracts the CSRF token required to fill in the login form by using the **selectorinputs:** clause in the _login block_ 
https://github.com/Jackett/Jackett/blob/7a35701d12ee0944c7455283b3d471567154b225/src/Jackett.Common/Definitions/sharewood.yml#L79-L94

So if in the _search block_ we want to provide this token in the query url we build for searching, then the simplest way would be for the Cardigann processor to save the keys and values of the **selectorinputs** from the _login block_ as `.Config.$varname` variables, so they can be referenced by the _search block_.
So for example, the **_token** extracted in
https://github.com/Jackett/Jackett/blob/7a35701d12ee0944c7455283b3d471567154b225/src/Jackett.Common/Definitions/sharewood.yml#L86-L89
could be used in 
https://github.com/Jackett/Jackett/blob/7a35701d12ee0944c7455283b3d471567154b225/src/Jackett.Common/Definitions/sharewood.yml#L103-L112
by adding
```yaml
      _token: "{{ .Config._token }}"
```

Do you think enhancement to the Cardigann processor is feasable?

**Comment by garfield69** [comment]
BTW this may well apply across all UNIT3D sites (at last count there's 19).
May also prevent the need to use cookie method for blutopia

**Comment by ngosang** [comment]
> May also prevent the need to use cookie method for blutopia

Could you elaborate? Blutopia works for me with user + pass.
```
  login:
    path: login
    method: form
    form: form[action*="/login"]
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
      remember: 1
    selectorinputs:
      _token:
        selector: input[name="_token"]
        attribute: value
    test:
      path: /
      selector: a[href$="/logout"]
```

The search URL includes the token, but they are not checking it. You can remove it from the URL (we are already doing that).
`https://blutopia.xyz/torrents/filter?_token=bMjm8n7n7U6OPQsedsdmnRGPpynNcjgWl6EylwbJS&search=westworld&description=&keywords=&uploader=&imdb=&tvdb=&view=list&tmdb=&mal=&igdb=&start_year=&end_year=&sorting=created_at&direction=desc&page=0&qty=25`
