### ISSUE TITLE
CardigannIndexer: andmatch does not take into account keywordsfilters

### ISSUE THREAD

**Issue by krt-** [Jackett/Jackett#7988]
andmatch filter checks original query string in CardigannIndexer and ignores keywordsfilters.

E.g. there's such keywordsfilters section in .yml file:
```
keywordsfilters:
      - name: diacritics
        args: replace
      - name: re_replace # S01 to Cезон 1
        args: ["(?i)\\bS0*(\\d+)\\b", "Сезон $1"]
      - name: re_replace # S01E01 to Сезон 1 Серии 1
        args: ["(?i)\\bS0*(\\d+)E0*(\\d+)\\b", "Сезон $1 Серии $2"]
```
Original search query "Mandalorian S01" is replaced with "Mandalorian Сезон 1", one of the results is "Мандалорец   The Mandalorian   Сезон  1   Серии  1 8 из 8 (Дебора Чоу) [2019, фантастика, боевик, приключения, WEB DL 720p] MVO [TVShows]", but MatchQueryStringAND method tries to match result with original query and it fails.
