### ISSUE TITLE
Strange problem with selector, result from previous item

### ISSUE THREAD

**Issue by WMP** [Jackett/Jackett#8068]
### Environment

**OS**: Linux

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono]

**.Net Version**: 

**Jackett Version**: 0.14.447.0

**Last Working Jackett Version**: Dont know

**Are you using a proxy or VPN?** no

### Description
I want to adding language world (POLISH) to title, so i create this code:
```
---
  site: btgigs
  name: BTGigs
  description: "BTGigs (TG) is a POLISH Private Torrent Tracker for MOVIES / TV / GENERAL"
  language: pl-pl
  type: private
  encoding: ISO-8859-2
  links:
    - https://btgigs.info/
  settings:
    - name: username
      type: text
      label: Username
    - name: password
      type: password
      label: Password
    - name: lang
      type: checkbox
      label: Add POLISH to title if is in polish category
      default:  false
  caps:
    categorymappings:
      - {id: 36, cat: Audio/Audiobook, desc: "aBooki"}
      - {id: 27, cat: TV/Anime, desc: "Anime"}
      - {id: 1, cat: PC, desc: "Aplikacje PC"}
      - {id: 10, cat: Books/EBook, desc: "eBooki"}
      - {id: 34, cat: Movies/BluRay, desc: "Filmy/BR"}
      - {id: 4, cat: Movies/SD, desc: "Filmy/DVD-R"}
      - {id: 31, cat: Movies/HD, desc: "Filmy/HD Rip"}
      - {id: 17, cat: Movies/Other, desc: "Filmy/Inne"}
      - {id: 35, cat: Movies/UHD, desc: "Filmy/UHD"}
      - {id: 20, cat: Movies/SD, desc: "Filmy/XviD"}
      - {id: 21, cat: Console, desc: "Gry/konsole"}
      - {id: 7, cat: PC/Games, desc: "Gry/PC ISO"}
      - {id: 12, cat: PC/Games, desc: "Gry/PC Rips"}
      - {id: 28, cat: Other, desc: "GSM/PDA"}
      - {id: 19, cat: Audio/Video, desc: "Koncerty/Teledyski"}
      - {id: 32, cat: Audio/Lossless, desc: "musicDVD/DTS/FLAC"}
      - {id: 5, cat: Audio/MP3, desc: "Muzyka/MP3"}
      - {id: 26, cat: Other, desc: "Rozne"}
      - {id: 30, cat: TV/Sport, desc: "Sport"}
      - {id: 6, cat: TV, desc: "TV/Seriale"}
      - {id: 37, cat: TV/UHD, desc: "TV/UHD"}
      - {id: 29, cat: PC, desc: "Witaminki"}
      - {id: 9, cat: XXX, desc: "XXX"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  login:
    path: takelogin_action.php
    method: post
    inputs:
      username_dupa: "{{ .Config.username }}"
      password__dupa: "{{ .Config.password }}"
    error:
      - selector: td.embedded:has(h2:contains("failed"))
      - selector: td.embedded:has(h2:contains("Error"))
    test:
      selector: a[href^="logout.php"]
      path: index.php?news=1

  search:
    paths:
      - path: browse.php
    error:
      - selector: a.altlink
    inputs:
      $raw: "{{range .Categories}}c{{.}}=1&{{end}}"
      search: "{{ .Query.Keywords }}"
      incldead: 1
      tyt: 0
      lang: 0
      subcat: 0
    rows:
      selector: table[border="1"][cellpadding=5] > tbody > tr:has(a[href^="details.php?id="])
    fields:
      title_phase1:
        selector: a[href^="details.php?id="]
      description:
        optional: true
        selector: img[src^="/pic/cat_pl/"]
        attribute: src
      language:
        optional: true
        selector: img[src*="cat_pl"]
        attribute: src
        filters:
          - name: strdump
        
      title_lang:
        text: "{{ .Result.title_phase1 }}"
        filters:
          - name: append
            args: " POLISH"
      title:
        text: "{{if and (.Config.lang) (.Result.language) }}{{ .Result.title_lang }}{{else}}{{ .Result.title_phase1 }}{{end}}"
      details:
        selector: a[href^="details.php?id="]
        attribute: href
      category:
        selector: a[href^="browse.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: cat
      
      download:
        selector: a[href^="download.php/"]
        attribute: href
      imdb:
        optional: true
        selector: a[href*="www.imdb.com/title/tt"]
      date:
        selector: td:nth-child(5)
        filters:
          - name: append
            args: " +00:00"
          - name: dateparse
            args: "2006-01-0215:04:05 -07:00"
      grabs:
        selector: td:nth-child(7)
        filters:
          - name: regexp
            args: (\d+)
      size:
        selector: td:nth-child(6)
      seeders:
        selector: td:nth-child(8)
      leechers:
        selector: td:nth-child(9)
      downloadvolumefactor:
        case:
          "img[src=\"pic/ico_disk1.png\"]": 0
          "img[src=\"pic/ico_disk2.png\"]": 1
          "*": 1
      uploadvolumefactor:
        text: "1"

```
When i looking for _SOMETHING S04E09_ i have result (i remove unnecessary) code:
```
<tr>
<td align=center style='padding: 0px'><a href="browse.php?cat=6"><img border="0" src="/pic/cat_pl/cat_episodes.png" title="TV/Seriale wersja PL" /></td>
<td style='background-image:url(); background-repeat:no-repeat; background-position: right;' align=left><a href="details.php?id=513983"><b>SOMETHING MULTi 1080p NF WEB-DL DD5.1 X264-TVM4iN</b></a>

                         
                         <br> <a href='browse.php?subcat=15' style='font-size:9; color: #0055A4; text-decoration: none'>Kryminał</a>, <a  href='browse.php?subcat=12' style='font-size:9; color: #0055A4; text-decoration: none'>Dramat</a><td align="center"><a title="Szybko pobierz torrenta: SOMETHING MULTi 1080p NF WEB-DL DD5.1 X264-TVM4iN" align="center" class="index" href="download.php/513983/SOMETHING.S04E09.MULTi.1080p.NF.WEB-DL.DD5.1.X264-TVM4iN.torrent"><IMG ALT="Szybko pobierz torrenta" SRC="pic/ico_disk1.png" BORDER="0" ALIGN="center"></a></td>                                                                                                                                            
<td align="right">0</td>
<td align=center><nobr>2018-10-09<br />17:41:39</nobr></td>
<td align=center>2.62<br>GB</td>
<td align=center><a href="viewsnatches.php?id=513983">188<br>razy</a></td>
<td align=right><b><a href=peery.php?id=513983&amp;dllist=1#seeders><font color=#000000>14</font></a></b></td>
<td align="right">0</td>
</tr>
<tr>
<td align=center style='padding: 0px'><a href="browse.php?cat=6"><img border="0" src="/pic/cat_episodes.png" title="TV/Seriale" /></td>
<td style='background-image:url(); background-repeat:no-repeat; background-position: right;' align=left><a href="details.php?id=513257"><b>SOMETHING 720p HDTV X264-AVS</b></a>

                         
                         <br> <a href='browse.php?subcat=7' style='font-size:9; color: #0055A4; text-decoration: none'>Komedia</a>, <a  href='browse.php?subcat=15' style='font-size:9; color: #0055A4; text-decoration: none'>Kryminał</a><td align="center"><a title="Szybko pobierz torrenta: SOMETHING 720p HDTV X264-AVS" align="center" class="index" href="download.php/513257/SOMETHING.S04E09.720p.HDTV.x264-AVS.torrent"><IMG ALT="Szybko pobierz torrenta" SRC="pic/ico_disk1.png" BORDER="0" ALIGN="center"></a></td>                                                                                                                                                                                      
<td align="right">0</td>
<td align=center><nobr>2018-10-02<br />05:49:14</nobr></td>
<td align=center>973.47<br>MB</td>
<td align=center><a href="viewsnatches.php?id=513257">173<br>razy</a></td>
<td align=right><b><a href=peery.php?id=513257&amp;dllist=1#seeders><font color=#000000>3</font></a></b></td>
<td align=right><b><a href=peery.php?id=513257&amp;dllist=1#leechers>1</b></td>
</tr>
```

I dont understand WHY jackett thinks that both results fill this:
```
description:
        optional: true
        selector: img[src^="/pic/cat_pl/"]
        attribute: src
```

because only one result has this code: `<img border="0" src="/pic/cat_pl/cat_episodes.png" title="TV/Seriale wersja PL" />`

This is result form jacket:
```
<table id="jackett-search-results-datatable" class="dataTable compact cell-border hover stripe" role="grid" aria-describedby="jackett-search-results-datatable_info">
            <thead>
                <tr role="row"><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Published: activate to sort column ascending">Published</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Tracker: activate to sort column ascending">Tracker</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Name: activate to sort column ascending">Name</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Size: activate to sort column ascending">Size</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Files: activate to sort column ascending">Files</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Category: activate to sort column ascending">Category</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Grabs: activate to sort column ascending">Grabs</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Seeds: activate to sort column ascending">Seeds</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Leechers: activate to sort column ascending">Leechers</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="DL Factor: activate to sort column ascending">DL Factor</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="UL Factor: activate to sort column ascending">UL Factor</th><th class="sorting" tabindex="0" aria-controls="jackett-search-results-datatable" rowspan="1" colspan="1" aria-label="Download: activate to sort column ascending">Download</th></tr>
            </thead>
            <tbody>
                
                
            <tr class="jackett-search-results-row odd" data-imdb="" data-banner="" data-description="/pic/cat_pl/cat_episodes.png" role="row">
                    
                    <td>1y ago</td>
                    <td>BTGigs</td>
                    <td class="Title"><a href="https://btgigs.info/details.php?id=513983" target="_blank" data-original-title="" title="">SOMETHING S04E09 MULTi 1080p NF WEB-​DL DD5.​1 X264-​TVM4iN POLISH</a> <span class="release-labels">
<span class="label label-success">FREELEECH</span></span></td>
                    
                    <td class="fit">2.6 GB</td>
                    <td></td>
                    <td>TV</td>
                    <td>188</td>
                    <td>13</td>
                    <td>0</td>
                    <td class="DownloadVolumeFactor">0</td>
                    <td class="UploadVolumeFactor">1</td>
                    <td class="downloadcolumn">
                        <a class="downloadlink" title="Download locally" href="CUT"><i class="fa fa-download"></i></a>
                    </td>
                </tr><tr class="jackett-search-results-row even" data-imdb="" data-banner="" data-description="/pic/cat_pl/cat_episodes.png" role="row">
                    
                    <td>2y ago</td>
                    <td>BTGigs</td>
                    <td class="Title"><a href="https://btgigs.info/details.php?id=513257" target="_blank" data-original-title="" title="">SOMETHING S04E09 720p HDTV X264-​AVS POLISH</a> <span class="release-labels">
<span class="label label-success">FREELEECH</span></span></td>
                    
                    <td class="fit">973.5 MB</td>
                    <td></td>
                    <td>TV</td>
                    <td>174</td>
                    <td>4</td>
                    <td>0</td>
                    <td class="DownloadVolumeFactor">0</td>
                    <td class="UploadVolumeFactor">1</td>
                    <td class="downloadcolumn">
                        <a class="downloadlink" title="Download locally" href="CUT"><i class="fa fa-download"></i></a>
                    </td>
                </tr></tbody>
            <tfoot>
                <tr><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"><select><option value=""></option><option value="BTGigs">BTGigs</option></select></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"><select><option value=""></option><option value="TV">TV</option></select></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td><td rowspan="1" colspan="1"></td></tr>
            </tfoot>
        </table>
```

**Comment by garfield69** [comment]
The `if and` clause does not work as you might expect, because it is not a true AND.
It will take too long to explain, (and I really should tidy up the docs on this clause soon, because even I am not sure what the author has actually implemented with this one).

Besides, you don't need to use it for what I believe you are trying to achieve.
So assuming I have this correct, you simply want to add **POLISH** to the end of the title when the **cat_pl** image is present.
The following is untested since I do not have an account on BTGigs but I think it is sound
```yaml
---
---
  site: btgigs
  name: BTGigs
  description: "BTGigs (TG) is a POLISH Private Torrent Tracker for MOVIES / TV / GENERAL"
  language: pl-pl
  type: private
  encoding: ISO-8859-2
  links:
    - https://btgigs.info/

  caps:
    categorymappings:
      - {id: 36, cat: Audio/Audiobook, desc: "aBooki"}
      - {id: 27, cat: TV/Anime, desc: "Anime"}
      - {id: 1, cat: PC, desc: "Aplikacje PC"}
      - {id: 10, cat: Books/EBook, desc: "eBooki"}
      - {id: 34, cat: Movies/BluRay, desc: "Filmy/BR"}
      - {id: 4, cat: Movies/SD, desc: "Filmy/DVD-R"}
      - {id: 31, cat: Movies/HD, desc: "Filmy/HD Rip"}
      - {id: 17, cat: Movies/Other, desc: "Filmy/Inne"}
      - {id: 35, cat: Movies/UHD, desc: "Filmy/UHD"}
      - {id: 20, cat: Movies/SD, desc: "Filmy/XviD"}
      - {id: 21, cat: Console, desc: "Gry/konsole"}
      - {id: 7, cat: PC/Games, desc: "Gry/PC ISO"}
      - {id: 12, cat: PC/Games, desc: "Gry/PC Rips"}
      - {id: 28, cat: Other, desc: "GSM/PDA"}
      - {id: 19, cat: Audio/Video, desc: "Koncerty/Teledyski"}
      - {id: 32, cat: Audio/Lossless, desc: "musicDVD/DTS/FLAC"}
      - {id: 5, cat: Audio/MP3, desc: "Muzyka/MP3"}
      - {id: 26, cat: Other, desc: "Rozne"}
      - {id: 30, cat: TV/Sport, desc: "Sport"}
      - {id: 6, cat: TV, desc: "TV/Seriale"}
      - {id: 37, cat: TV/UHD, desc: "TV/UHD"}
      - {id: 29, cat: PC, desc: "Witaminki"}
      - {id: 9, cat: XXX, desc: "XXX"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  login:
    path: takelogin_action.php
    method: post
    inputs:
      username_dupa: "{{ .Config.username }}"
      password__dupa: "{{ .Config.password }}"
    error:
      - selector: td.embedded:has(h2:contains("failed"))
      - selector: td.embedded:has(h2:contains("Error"))
    test:
      selector: a[href^="logout.php"]
      path: index.php?news=1

  search:
    paths:
      - path: browse.php
    error:
      - selector: a.altlink
    inputs:
      $raw: "{{ range .Categories }}c{{.}}=1&{{end}}"
      search: "{{ .Keywords }}"
      incldead: 1
      tyt: 0
      lang: 0
      subcat: 0

    rows:
      selector: table[border="1"][cellpadding=5] > tbody > tr:has(a[href^="details.php?id="])

    fields:
      is_polish:
        optional: true
        selector: img[src*="cat_pl"]
        attribute: src
      title_phase1:
        selector: a[href^="details.php?id="]
      title_polish:
        text: "{{ .Result.title_phase1 }}"
        filters:
          - name: append
            args: " POLISH"
      title:
        text: "{{ if .Result.is_polish) }}{{ .Result.title_polish }}{{else}}{{ .Result.title_phase1 }}{{end}}"
      details:
        selector: a[href^="details.php?id="]
        attribute: href
      category:
        selector: a[href^="browse.php?cat="]
        attribute: href
        filters:
          - name: querystring
            args: cat
      download:
        selector: a[href^="download.php/"]
        attribute: href
      imdb:
        optional: true
        selector: a[href*="www.imdb.com/title/tt"]
      date:
        selector: td:nth-child(5)
        filters:
          - name: append
            args: " +00:00"
          - name: dateparse
            args: "2006-01-0215:04:05 -07:00"
      grabs:
        selector: td:nth-child(7)
        filters:
          - name: regexp
            args: (\d+)
      size:
        selector: td:nth-child(6)
      seeders:
        selector: td:nth-child(8)
      leechers:
        selector: td:nth-child(9)
      downloadvolumefactor:
        case:
          "img[src=\"pic/ico_disk1.png\"]": 0
          "img[src=\"pic/ico_disk2.png\"]": 1
          "*": 1
      uploadvolumefactor:
        text: 1
# engine n/a
```

let me know it it works
