### ISSUE TITLE
[req] ilDragGoNeRo

### ISSUE THREAD

**Issue by VMax4** [Jackett/Jackett#8148]
It's a semi-private tracker: https://ildragonero2.info/

In this tracker it's implemented the "Thank you" mechanism

Hope it will be implemented to Jacket because it's a very good tracker

Thank you all in advance :-)

**Comment by VMax4** [comment]
Looking better i think that the "Thank you" is optional

**Comment by garfield69** [comment]
where is the registration link, I seem unable to find on the home page?

**Comment by VMax4** [comment]
It's at beside the "Login" link at the top right of the page, it's written "Iscriviti"
After that you must accept the policy pushing "Accetto queste condizioni d'uso" and then you will be redirected to the rest of the registration process

**Comment by garfield69** [comment]
Thanks. could not see it before, now it smacks me in the face ;-D

**Comment by garfield69** [comment]
yeah, its not my eyesight. the page does hide the registration link for some reason
![image](https://user-images.githubusercontent.com/6933240/79277473-03df9a00-7efe-11ea-9a94-f8f673ca112a.png)

in all the kafuffle I think I managed to get my IP banned ;-D
I'll try again tomorrow.

**Comment by cadatoiva** [comment]
That's weird, it was there for me earlier today (although I didn't sign up). The direct link is: https://ildragonero2.info/forum/ucp.php?mode=register but that says signups are closed now.

**Comment by VMax4** [comment]
I think that they open signups during the day and close them in the night for some unknown reason to me :)

**Comment by VMax4** [comment]
After signup to become a regular user and being able to see the magnet links you must make a simple presentation here https://ildragonero2.info/forum/viewforum.php?f=2 
click "Nuovo argomento" ; to know what to type just copy and paste a previous presentation of somebody else :-)

**Comment by garfield69** [comment]
I give up.

I have tried on three successive days to register.
- on the first day I did not get an activation email, and when I tried to login it told me the user did not exist. By the time I got the activation email I had already managed to get my IP permanently banned :-(
On the second day, via VPN I registered and received an activation email, and when I clicked the link the site returned `The requested user does not exist.` !?!
- Today I tried the registration again, it accepted all my credentials, told me I'd be getting an activation email, but it has not arrived yet.

some one else will need to build an indexer for this one.

**Comment by garfield69** [comment]
today's activation finally arrived, and once again, failure
![image](https://user-images.githubusercontent.com/6933240/79398073-d2390280-7fd3-11ea-8373-3b7632a9332c.png)

**Comment by VMax4** [comment]
mmmm it's strange, listen i will try to make a new account from here, after that, if i have all registered and working i send you the credentials to login ;-)

**Comment by VMax4** [comment]
@garfield69 I sent you an email right now

**Comment by garfield69** [comment]
Thanks.

Is that what you think is really going on...that the site is filtering for Italian IP addresses?
And instead of telling me straight up that foreign IP are not welcome, they let me register, confirm and only when I try to login do they tell me my new account is not available!
That is so rude.

It will be a while before I have time to work on this indexer anyways, so I'll wait till next week before accessing, via an Italian IP on my Hide.me VPN.

**Comment by VMax4** [comment]
Well i'm not sure about that, i think more that some admin are checking for what they can suppose to be "strange" subscriptions and that delete the ones they judge like fak ones.
That's why making a registration from Italy pass just simple :-)

**Comment by garfield69** [comment]
ok. this sucks.

I spent the afternoon creating the indexer and got to the last part, validating that the download of the magnet worked.
Only to discover that the magnet supplied by http://mgnet.me/ is not a direct URI but just another page with the magnet link embedded.
Which will not work for Cardigann as it expects all .torrent and magnet links to be direct links to the URL or URI in question.
It cannot handle indirect links that require additional parsing of pages.

not only that, but some of the forum topics actually do not have even mgnet.me links but google search for a hash link!!!! example http://ildragonero2.info/forum/viewtopic.php?f=8&t=131&hilit=beatles WTF!

Unfortunately this means this site cannot be handled by a yaml indexer and will need to be written in C#

**Comment by VMax4** [comment]
I see :( thank you anyway for all the time spent ...

**Comment by garfield69** [comment]
current yaml which may help c# dev speed up coding of c# equivalent
```yaml
---
  site: ildragonero
  name: ilDraGoNeRo
  description: "ilDraGoNeRo is an ITALIAN Private Torrent Forum for MOVIES / MUSIC"
  language: it-it
  type: private
  encoding: UTF-8
  links:
    - http://ildragonero2.info/ # https is not supported httpOnly

  caps:
    categorymappings:
      - {id: 10, cat: Other, desc: "Regolamento"}
      - {id: 2, cat: Other, desc: "Presentazioni"}
      - {id: 15, cat: Other, desc: "Caverna del Drago"}
      - {id: 1, cat: Other, desc: "Area Release"}
      - {id: 6, cat: Other, desc: "Release INFO"}
      - {id: 19, cat: Movies/WEBDL, desc: "DVDRip-BDRip-WEBDL-[3D]"}
      - {id: 25, cat: Movies, desc: "Film Datati (fino al 2015)"}
      - {id: 23, cat: TV, desc: "Serie TV"}
      - {id: 8, cat: Audio, desc: "Musica"}
      - {id: 9, cat: PC, desc: "Applicazioni"}
      - {id: 20, cat: PC/0day, desc: "Software windows"}
      - {id: 21, cat: PC/Mac, desc: "Software mac"}
      - {id: 22, cat: PC/Phone-Android, desc: "APK Android"}
      - {id: 12, cat: Other, desc: "Richieste"}
      - {id: 28, cat: Other, desc: "Commenti Film - Serie TV"}

    modes:
      search: [q]
      tv-search: [q, season, ep]
      movie-search: [q]

  login:
    path: forum/ucp.php?mode=login
    method: form
    form: form[action^="./ucp.php?mode=login"]
    inputs:
      username: "{{ .Config.username }}"
      password: "{{ .Config.password }}"
      autologin: on
      viewonline: on
      redirect: index.php
    selectorinputs:
      sid:
        selector: input[name="sid"]
        attribute: value
      form_token:
        selector: input[name="form_token"]
        attribute: value
      creation_time:
        selector: input[name="creation_time"]
        attribute: value
    error:
      - selector: div.error
    test:
      path: forum/index.php
      selector: a[href^="./ucp.php?mode=logout"]

  download:
    selector: a[href*="/mgnet.me/"]
    attribute: href

  search:
    paths:
    #http://ildragonero2.info/forum/search.php?keywords=2020&terms=all&author=&sc=1&sf=titleonly&sr=topics&sk=t&sd=d&st=0&ch=300&t=0&submit=Cerca
      - path: /forum/search.php
    inputs:
      keywords: "{{ if .Keywords }}{{ .Keywords }}{{else}}{{ .Today.Year }}{{end}}"
      # all, any
      terms: all
      author: ""
      # subtopics? 0 no, 1 yes
      sc: 1
      # all title+body, msgonly body, titleonly duh, firstpost duh
      sf: titleonly
      # posts, topics
      sr: topics
      # a author, t date, f forum, i title, s body
      sk: t
      # a asc, d desc
      sd: d
      # 0 all, 1 1day 7, 7days, 14 2weeks, 30 1month, 90 3month, 180 6month, 365 1year
      st: 0
      # -1 everything, 0, 25, 50, 100, 200, 300 (default), 400, 500, 600, 700, 800, 900, 1000
      ch: 300
      # hidden
      t: 0
      submit: Cerca
      $raw: "{{ range .Categories }}&fid[]={{.}}{{end}}"
      # does not support imdbid search or provide imdb links

    rows:
      selector: div.forumbg > div > ul > li.row

    fields:
      category:
        selector: a[href^="./viewtopic.php?f="]
        attribute: href
        filters:
          - name: querystring
            args: f
      title:
        selector: a.topictitle
      details:
        selector: a.topictitle
        attribute: href
      download:
        selector: a.topictitle
        attribute: href
      banner:
        selector: div[data-ot]
        attribute: data-ot
        optional: true
        filters:
          - name: regexp
            args: "src=\\'(.+?)\\' "
      size:
        text: "512 MB"
      seeders:
        text: 1
      leechers:
        text: 1
      date:
        # sab 18 apr 2020, 21:40
        selector: div[data-ot]
        remove: a
        filters:
          - name: regexp
            args: "»(.+?) »"
            # strip day of week
          - name: re_replace
            args: ["lun|mar|mer|gio|ven|sab|dom", ""]
            # translate months
          - name: replace
            args: ["gen", "jan"]
          - name: replace
            args: ["mag", "may"]
          - name: replace
            args: ["giu", "jun"]
          - name: replace
            args: ["lug", "jul"]
          - name: replace
            args: ["agu", "aug"]
          - name: replace
            args: ["set", "sep"]
          - name: replace
            args: ["ott", "oct"]
          - name: replace
            args: ["dic", "dec"]
            # 24 hour clock but provided without a leading zero
          - name: re_replace
            args: [" (\\d{1}:\\d{2}) ", " 0$1 "]
            # utc for Italy
          - name: append
            args: " +02:00"
          - name: dateparse
            args: "2 Jan 2006, 15:04 -07:00"
      downloadvolumefactor:
        text: 1
      uploadvolumefactor:
        text: 1
# phpBB
```

**Comment by cadatoiva** [comment]
Thanks @garfield69, it definitely will.

**Comment by flammable-gel** [comment]
this tracker should use the same thank you mechanism as [ilcorsaroverde](https://github.com/Jackett/Jackett/issues/3189) which was recently added. Could you give it a try?

**Comment by giovannigenna** [comment]
Hi!
There are some news to get implemented this indexer ?

**Comment by ilike2burnthing** [comment]
Needs a C# contributor.

**Comment by giovannigenna** [comment]
> Needs a C# contributor.

That forum looks like MIRCREW, so it's not enough the the previous reply with yaml of @garfield69 ? I think they have updated the website and now you just need to make a like and appear the magnet link. It's looks like the same of MIRCREW

**Comment by ilike2burnthing** [comment]
Just signed up. Are registrations always open, or did I just get lucky with timing?

While I wait for verification of my account, does this issue raised here still persist? - https://github.com/Jackett/Jackett/issues/8148#issuecomment-616085783

**Comment by giovannigenna** [comment]
Oh ok, I just watching about movies, not tv shows... Do u think it's possibile to get all magnets or needs a c# dev ?

**Comment by ilike2burnthing** [comment]
No, these indexers, previously including ilcorsaroverde/icv-crew, will always be partially broken, YAML or C#. There's no way to tell if a result contains multiple torrents or not without loading the details page, thanking, and reloading every single result. As I said about ICV:

> The problem is, that's a lot of extra traffic, and if you use automation software like Sonarr then by default that's a lot of extra traffic every 15mins (if Jackett's cache is disabled). In other words, it's potentially a quick way to get your account banned for bot activity.

**Comment by ilike2burnthing** [comment]
YAML indexer added, but https://github.com/Jackett/Jackett/issues/8148#issuecomment-616085783 still exists for old torrents, so would need to be rewritten in C# to resolve that (very low priority).

The bigger issue of multiple torrents per release, hidden behind a thanks check, is unsolvable.

**Comment by garfield69** [comment]
v0.21.904

**Comment by garfield69** [comment]
On my win10 Jackett I'm getting a certificate error for ildragonero
I see the site is using a default web hosting CA so I added a CA override to the indexer
```yaml
certificates:
  - 02db451c9a07018198d21b3372f90ae8094db291 # certificate validation failed: [Subject]  CN=*.web-hosting.com
```
but It does not pass. Just me?

**Comment by ilike2burnthing** [comment]
I'm getting HTTP ERROR 500 in browser, maybe that's why?

**Comment by garfield69** [comment]
Hm. I'm able to login (eventually) and had to get browser to accept the unsecure connection several times, but it is running slow.
Browsing torrents works albeit with PHP warnings everywhere,  so maybe all these multiple issues are adding up to Jackett failing and returning the invalid CA as the first error.

**Comment by ilike2burnthing** [comment]
Certificate now valid, site loading normally, login works, but forum currently down:

`Forum being updated... We will be back online at the end of the operation. We apologize for the inconvenience.`

**Comment by ilike2burnthing** [comment]
back up

**Comment by ilike2burnthing** [comment]
Slow but back up

**Comment by garfield69** [comment]
does not pass the indexer test for me

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/issues/8148#issuecomment-1830364632

**Comment by ilike2burnthing** [comment]
back up

**Comment by garfield69** [comment]
![image](https://github.com/Jackett/Jackett/assets/6933240/8ae6e3c6-7c4e-4a19-8954-a07c38dd465e)

**Comment by ilike2burnthing** [comment]
Yea, that threw me at first as well. Obviously shouldn't be like that, but if you click on `forum/` then it takes you to the site. Working in Jackett fine too.

**Comment by garfield69** [comment]
If I add ildragonero indexer from scratch to Jackett it fails with
`Error: Il form inviato non è valido. Prova a inviarlo di nuovo.`
Just me?

**Comment by ilike2burnthing** [comment]
Same. There's a bunch of new hidden inputs. I'll take a look.

**Comment by garfield69** [comment]
I did take a side look, but I could not get it to work, with either using all the hidden inputs or by switching to cookie+UA. The cloudflare interference caused a succession of 302, 200, 403, 200 GET traffic before the home page finally got presented after a login.
Beyond my ken.

**Comment by ilike2burnthing** [comment]
```yml
settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password
  - name: flaresolverr
    type: info
    label: FlareSolverr
    default: This site may use Cloudflare DDoS Protection, therefore Jackett requires <a href="https://github.com/Jackett/Jackett#configuring-flaresolverr" target="_blank">FlareSolverr</a> to access it.

login:
  path: forum/ucp.php?mode=login
  method: form
  form: form#login
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    autologin: on
    viewonline: on
    redirect: index.php
    login: Login
  selectorinputs:
    creation_time:
      selector: input[name="creation_time"]
      attribute: value
    form_token:
      selector: input[name="form_token"]
      attribute: value
    redirect:
      selector: fieldset.fields1 > input[name="redirect"]
      attribute: value
#    redirect:
#      selector: dd > input[name="redirect"]
#      attribute: value
    sid:
      selector: input[name="sid"]
      attribute: value
  error:
    - selector: div.error
  test:
    path: forum/index.php
    selector: a[href^="./ucp.php?mode=logout&sid="]
```

That's what I was working with, but didn't get far.

As far as I can tell, the issue is that there are two `redirect` inputs sent in browser:

>**Request URL**
https://www.ildragonero2.info/forum/ucp.php?mode=login&sid=XXXXX
>
>**Query String Parameters**
mode: login
sid: XXXXX
>
>**Form Data**
username: REMOVED
password: REMOVED
autologin: on
viewonline: on
redirect: ./ucp.php?mode=login&sid=XXXXX
creation_time: XXXXX
form_token: XXXXX
sid: XXXXX
redirect: index.php
login: Login

but we're only sending one:

>WebClient(HttpWebClient2).GetResultAsync(Method: POST Url: https://ildragonero2.info/forum/ucp.php?mode=login&sid=XXXXX PostData: {username=(removed) password=(removed) redirect=./ucp.php?mode=login&sid=XXXXX, creation_time=XXXXX, form_token=(removed) sid=XXXXX, login=Login, autologin=on, viewonline=on} RawBody: )

Doesn't matter if one or both are `selectorinputs`, rather than `inputs`. Changing one of the selectorinputs to `redirect2` then uses both, but obviously doesn't work.

I had a look at CardigannIndexer's [form login block](https://github.com/Jackett/Jackett/blob/06546391e431b6d5ce4573e18ff8076bc99bb454/src/Jackett.Common/Indexers/CardigannIndexer.cs#L581), but again didn't get far (I'm guessing we can't have multiple `pairs` with the same name, but as to how to fix that...). I'm currently playing about with https://stackoverflow.com/a/3639981, but I'm pretty sure I'm wasting my time.
