### ISSUE TITLE
[Monova] showing few or no results when using common words in search

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8183]
Not sure if this is fixable by Jackett due to whatever haphazard sorting is done by Monova (definitely isn't by relevance).

Using the example of someone searching for the show `The Americans` in Jackett or (presumably) Sonarr:
- search for `americans` - you get some valid results
- search for `the americans` - you get no results

I'm guessing this is due to `andmatch` filtering out irrelevant results, which is all of them in the first few pages. Valid results do exist on Monova, but apparently it's just luck as to whether they'll be in the pages fetched by Jackett - and for searching anything containing `the`, `and`, `with`, `season`, etc., that luck has run out.

**Comment by garfield69** [comment]
We need the andmatch because monova uses a search where keywords are OR'red rather than AND'ded and as you have discovered it returns unrelated results.
Short of putting a keywords filter to remove the common keywords, I don't think there is much else we can do.
So try it and see if that improves things. see https://github.com/Jackett/Jackett/wiki/Definition-format#search for details on the keywords filter and ping me if you want me to implement it instead.

**Comment by ilike2burnthing** [comment]
Ok, so it seems the combination of the two gives the best results (without andmatch there were still problems adding keywords like season, show, or s01e01 - though using those keywords is likely to still give you few or zero results), and using the combination doesn't remove anything either.

I just used the default:
```
    keywordsfilters:
      - name: re_replace
        args: ["(?:^|\\s)[_\\+\\/\\.\\-\\(\\)]*[\\S]{0,3}[_\\+\\/\\.\\-\\(\\)]*(?:\\s|$)", " "]
```

I take it multi-page processing is only possible in C#? That's the only other option I can think of to give a better chance of getting valid results, as there doesn't seem to be a way to increase the number of results per page.

**Comment by garfield69** [comment]
so the site is delivering 25 results per page?
so you can add additional paths that include the &page=2-4 (don't get greedy and go for more, about 100 results is the aim but not a target, so don't go fetching 10 pages!)
```yaml
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}&page=2"
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}&page=3"
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}&page=4"
```

**Comment by ilike2burnthing** [comment]
Yep, that worked fine, certain keywords are getting more results, though others aren't so lucky.

Unless there's anything else you can think of, that section now looks like:
```
  search:
    paths:
      # https://monova.to/search?term=vikings+s05e05
      # https://monova.to/video
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}"
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}&page=2"
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}&page=3"
      - path: "{{if .Keywords}}search?term={{.Keywords}}{{else}}video{{end}}&page=4"

    keywordsfilters:
      - name: re_replace
        args: ["(?:^|\\s)[_\\+\\/\\.\\-\\(\\)]*[\\S]{0,3}[_\\+\\/\\.\\-\\(\\)]*(?:\\s|$)", " "]

    rows:
      selector: tr.desktop:not(tr[class="desktop  success"])
      filters:
        - name: andmatch
```

I've noticed that extratorrent and TPB (old HTML) seem to be returning unrelated results, though from initial testing it doesn't look to be exactly the same issue. If I end up finding a similar enough solution soon, should I post all three as one PR, or do them separately? Or do you want to throw this one up as a straight commit now yourself (seeing as you essentially held my hand through this lol thank you by the way)?
