### ISSUE TITLE
[req] KissSub Chinese public Anime https://kisssub.org/

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8352]
https://kisssub.org/
    35,000 torrents

**Comment by garfield69** [comment]
I can't seem to find any .torrent or magnet link?

**Comment by ngosang** [comment]
I don't know, maybe you have to be registered to show download links. The only thing I found is the infohash in the description page. We can build the magnet from there but there has to be another way.
![image](https://user-images.githubusercontent.com/10577978/80586782-bdb62a80-8a15-11ea-984f-d4bc14fc4ac2.png)

**Comment by garfield69** [comment]
this site does not provide torrents or magnets just direct download links
![image](https://user-images.githubusercontent.com/6933240/80649993-23aeba80-8ac7-11ea-95f3-aa543c6f32d4.png)

**Comment by budgetfermium** [comment]
If you press "Enable" near the bottom of @garfield69's screenshot, a script loads that allows you to see magnet links and torrent links for any of the results in KissSub.

Inspecting KissSub's RSS feed shows that the torrent files are hosted on v2.uploadbt.com in the form https://v2.uploadbt.com/?r=down&hash=_theprovidedinfohash_.

**Comment by ngosang** [comment]
@garfield69 @ilike2burnthing I think this is doable. We can get the infohash from the details URL:
https://kisssub.org/show-fb25ff3c8f10ce02de01d6c06fcebf6e2a326f3a.html => fb25ff3c8f10ce02de01d6c06fcebf6e2a326f3a
Just fill the infohash, the magnet link will be auto generated.

**Comment by garfield69** [comment]
@ngosang  have you implemented the cardigann support for using infohash in the download block?

**Comment by ngosang** [comment]
No, but it's not required in this case. Maybe I confused you.
The idea is to get all information from the torrent list. The infohash in in the torrent URL so we don't need the `download` block.

**Comment by garfield69** [comment]
Ah. I need sleep.

**Comment by ngosang** [comment]
good night!

**Comment by ilike2burnthing** [comment]
Rough attempt (mostly working):
```
---
id: kisssub
name: KissSub
description: "KissSub is a CHINESE Public torrent index"
language: zh-cn
type: public
encoding: UTF-8
links:
  - https://kisssub.org/

caps:
  categorymappings:
    - {id: 动画, cat: TV/Anime, desc: 动画 (Animated)}
    - {id: 漫画, cat: Books/Comics, desc: 漫画 (Comics)}
    - {id: 音乐, cat: Audio, desc: 音乐 (Music)}
    - {id: 周边, cat: TV/Anime, desc: 周边 (Surrounding)}
    - {id: 其它, cat: TV/Anime, desc: 其它 (Other)}
    - {id: Raw, cat: TV/Anime, desc: Raw}
    - {id: Ova, cat: TV/Anime, desc: Ova}
    - {id: 合集, cat: TV/Anime, desc: 合集 (Collections)}
    - {id: 讨论, cat: TV/Anime, desc: 讨论 (Discuss)}
    - {id: 网盘, cat: TV/Anime, desc: 网盘 (Net-a-Go)}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]
    book-search: [q]

settings: []

search:
  paths:
    # https://kisssub.org/search.php?keyword=moon+720p
    - path: "search.php?bound=content&keyword={{ if .Keywords }}{{ .Keywords }}{{ else }}{{ .Today.Year }}{{ end }}&sort_id=0&local=-1&field=title&node_id=0&external=google"

  rows:
    selector: table[id="listTable"] > tbody > tr

  fields:
    category:
      selector: a[href^="sort-"]
    title:
      selector: a[href^="show-"]
    details:
      selector: a[href^="show-"]
      attribute: href
    infohash:
      selector: a[href^="show-"]
      attribute: href
      filters:
        - name: regexp
          args: show-([0-9A-Fa-f]{40})
    date:
      optional: true
      selector: td:nth-child(1):contains("昨天")
      filters:
        - name: replace
        - args: ["昨天 ", ""]
        - name: append
        - args: " -24:00"
        - name: dateparse
        - args: "15:04 -07:00"
    date:
      optional: true
      selector: td:nth-child(1):contains("今天")
      filters:
        - name: replace
        - args: ["今天 ", ""]
        - name: append
        - args: " -48:00"
        - name: dateparse
        - args: "15:04 -07:00"
    date:
      optional: true
      selector: td:nth-child(1):not(:contains("昨天")):not(:contains("今天"))
      filters:
        - name: dateparse
        - args: "2006/01/02"
    size:
      selector: td:nth-child(4)
    seeders:
      selector: td:nth-child(5) > span
    leechers:
      selector: td:nth-child(6) > span
    grabs:
      selector: td:nth-child(7) > span
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine n/a

```
Categories can probably be more accurate, and their translations are just Google's.

Sorting can likely be added, and the search path is just the default from the site.

Date doesn't currently work (just posting whatever I tried last).

Download, details link, and the rest of the information is fine.
