### ISSUE TITLE
[enhancement] string templating for case blocks

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#8504]
in order to support #8488 downloadvolumefactor it would be really useful if the case block could support string golang templating
for example, I could code:
```yaml
      g1:
        selector: img[src$="/golden1.gif"] # freeleech
        text: 0
        optional: true
      g2:
        selector: img[src$="/golden2.gif"] # 20% discount
        text: 0.80
        optional: true
      downloadvolumefactor:
        selector: td:nth-child(2)
        case:
          img[src$="/golden1.gif"]: 0 # freeleech
          img[src$="/golden2.gif"]: 0.8 # 20% discount
          "*": 1
      downloadvolumefactor:
        # applies to torrents already having other bonuses and only the highest one is counted
        selector: img[src$="/bumped.gif"]
        optional: true
        case:
          img[title^="1%"]: "{{ if or .Result.g1 .Result.g2 }}{{ or .Result.g1 .Result.g2 }}{{else}}0.99{{end}}" 1% free (freeleech or 20% free overrides)
          img[title^="81%"]: "{{ if .Result.g1 }}0{{else}}0.19{{end}}" 81% free (freeleech overrides)
```
