### ISSUE TITLE
core: validate yaml definitions (yamllint)

### ISSUE THREAD

**Issue by ngosang** [Jackett/Jackett#8575]
I'm using this tool to validate all the yaml definitions. => https://github.com/adrienverge/yamllint

Install in Linux `sudo python3 -m pip install yamllint`

Custom rules (.yamllint)
```yaml
---
extends: default

rules:
  comments: disable
  line-length: disable
  key-duplicates: disable
  truthy: disable
```

run validations `yamllint -c .../.yamllint .../Jackett/src/Jackett.Common/Definitions/`

Report:
[yamllint.log](https://github.com/Jackett/Jackett/files/4604814/yamllint.log)

@garfield69 I can automate this in Azure Pipelines if you want.
