### ISSUE TITLE
[req] 01torrent.net

### ISSUE THREAD

**Issue by ilike2burnthing** [Jackett/Jackett#8600]
https://www3.01torrent.net/ (formerly OnTorrent)

Public

Movies, Audio, PC, TV, Other, Books

Proxy - https://01torrent.unblockit.me/

**Comment by garfield69** [comment]
the download link is on the details page and only appears when you click on an icon, which calls an ajax to showme.php with some post parms, and in turn inserts a table in the details html page with the magnet.
I think this is too complex for yaml.
needs to be written in c#

**Comment by garfield69** [comment]
on second thought, its not that different from a thankyou before step in the download block, so I'll take a second look.

**Comment by garfield69** [comment]
nah, can't figure out how to fetch the magnets.
needs JS so I think this indexer will need to be written in c#
I've included the yaml in case it helps someone figure things out.
```yaml
---
id: 01torrent
name: 01Torrent
description: "01Torrent is a Public tracker"
language: en-us
type: public
encoding: UTF-8
links:
  - https://www3.01torrent.net/
  - https://01torrent.unblockit.me/

caps:
  categories:
    "anime": TV/Anime
    "application": PC
    "book": Books
    "game": PC/Games
    "movie": Movies
    "music": Audio
    "tvshow": TV

  modes:
    search: [q]
    tv-search: [q, season, ep]
    movie-search: [q]
    music-search: [q]

settings: []

download:
  # https://www3.01torrent.net/movie/erasing-his-dark-past-2020-720p-webrip-800mb-x264-galaxyrg/163219/
  # <script type="text/javascript">
  #   $(document).ready(function(){
  #     $("#forall").on('click','#clicktype',function(){
  #       $("#showlinks").html("");
  #       var datg=$(this).attr("name");
  #       var dataString="id=163219&name="+datg;
  #       $('#load').show(200);
  #       setTimeout(function(){
  #         $.ajax({type:"POST",
  #           url:"/showme.php",
  #           data:dataString,
  #           cache:false,
  #           success:function(html){
  #             $("#showlinks").html(html)}
  #           });
  #         Ladda.stopAll();
  #         $("#load").hide(200)}
  #       ,3200)
  #     })
  #   });
  # </script>
  before:
    path: showme.php
    method: post
    inputs:
      data: "id={{ re_replace .DownloadUri.AbsoluteUri \"^.*/(\\d+)/$\" \"$1\" }}&name={{ re_replace .DownloadUri.AbsoluteUri \"^.*/(.+?)/\\d+/$\" \"$1\" }}"
  selector: a[href^="magnet:?xt="]
  attribute: href

search:
  paths:
    # https://www3.01torrent.net/search/
    - path: search/
      method: post
  inputs:
    q: "{{ if .Keywords }}{{ .Keywords }}{{ else }}{{ .Today.Year }}{{ end }}"

  rows:
    selector: table.table-striped > tbody > tr
    filters:
      - name: andmatch

  fields:
    category:
      selector: span.icomoon
      attribute: class
      filters:
        - name: split
          args: [" ", 1]
        - name: replace
          args: ["icomoon-", ""]
    title:
      selector: a.screenshot
    details:
      selector: a.screenshot
      attribute: href
    download:
      selector: a.screenshot
      attribute: href
    date:
      text: now
    size:
      selector: span.label-default
    seeders:
      text: 1
    leechers:
      text: 1
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine n/a
```
