### ISSUE TITLE
[ToTheGlory] Implement Gamez&Warez search

### ISSUE THREAD

**Issue by zenof** [Jackett/Jackett#8885]
The ToTheGlory actually have a game category open to TeraByte level and above, the search parameter is c=G comparing to c=M in movie and TVs.

List URL: https://totheglory.im/browse.php?c=G 

The corresponding categories are:

```yaml
    # 单机游戏
    PC: PC/Games
    MAC: PC/Mac

    # 微软系列
    XBOX360: Console/Xbox 360
    XBOX1: Console/Xbox
    XBLA: Console/Xbox
    XBOX+to+XBOX360: Console/Xbox

    # 索尼系列
    PS2: Console/Other
    PSP: Console/PSP
    PS4: Console/PS4
    PS3: Console/PS3
    PSV: Console/PS Vita

    # 任天堂系列
    WIIU: Console/WiiU
    WII: Console/Wii
    SWITCH: Console/Other
    NDS: Console/NDS
    NGC: Console/Other

    # 主机影视
    PS3兼容高清: Console/PS3
    PSP兼容高清&标清: Console/PSP
    XBOX360兼容高清: Console/Xbox 360
    Game+Video: Console/Other

    # 软件
    APPZ: PC
    Game+Ebook: Books/Ebook
    Ebook: Books/Ebook

    # 苹果系列
    iPhone/iPad游戏: PC/Phone-IOS
    iPad书籍: Books/Ebook
    iPhone/iPad软件: PC/Phone-IOS
```
