### ISSUE TITLE
ConCen Magnet Link incorrectly formatted

### ISSUE THREAD

**Issue by tyfen905** [Jackett/Jackett#8914]
This should be a simple fix... When downloading a torrent from Concen via Sonarr I get the following error: 

`Failed to parse magnetlink for episode 'Tucker Carlson Tonight (2020.06.05)': 'magnet:magnet:?xt=urn:btih:1b2f0ddd9eda7355ef0a835c21ffc27123f75b6a&tr=http%3A%2F%2Fconcen.org%3A6969%2Fannounce&dn=Tucker+Carlson+Tonight+%282020.06.05%29&xl=221751749': The magnet link must start with 'magnet:?'.`

If I look at the magnet link on concen.org/torrents it is valid (starts with `magnet:?`). It looks like the definition file [concen.yml](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/concen.yml) is appending "magnet:" in front of a valid magnet link, causing it to be invalid. 

Starting at line 63 of [concen.yml](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Definitions/concen.yml):
```
magnet:
      selector: td.views-field-name a
      attribute: href
      filters:
        - name: prepend
          args: "magnet:"
```
I don't have any issues downloading with magnet files from more popular trackers, so figured the issue is with the configuration for this less popular tracker.
