### ISSUE TITLE
[enhancement] arg to adjust cardigann timeago by timezone

### ISSUE THREAD

**Issue by garfield69** [Jackett/Jackett#9693]
Some sites return results with timeago values, such as `2 hours ago` 
Which unfortunately means for cardigann indexers, we cannot adjust them to the site's server time, so that for the Jackett user, the datetime is auto adjusted to their local timezone (as is the case with the dateparse function).

It would be useful if the timeago function accepted an optional argument specifying the server time zone, which once the datetime is parsed into the DateTime object would then be adjusted by that timezone offset to return the datetime as GMT.

example
```yaml
    date:
      # input `2 hours ago`
      # server time Mon, 29 Sep 2020, 19:17:24 GMT+3
      selector: time
      filters:
        - name: timeago
          args: "+03:00"
      # output `Mon, 29 Sep 2020, 14:17:24 GMT`
```
[edit] made some corrections and hopefully clarified requirements
