### ISSUE TITLE
[req] soundpark semi-private music site new engine

### ISSUE THREAD

**Issue by hidaba** [Jackett/Jackett#9748]
### Environment

**OS**: linux Docker

**.Net Runtime**: [.Net-Core/.Net-Framework/Mono] Mono

**.Net Version**:

**Jackett Version**: 0.16.1583.0

**Are you using a proxy or VPN?** [yes/no] no

### Description

https://sound-park.world/
login doesn't work, changed login page

### Logged Error Messages

Exception (soundpark): Login failed: No form found on https://sound-park.world/eng/login using form selector form[action="/login"]: Parse error

[Place any relevant error messages you noticed from the logs here.]
Now is only for registered

**Comment by bentux** [comment]
Info from Soundpark FAQ

I've an account on the previous version of the website and can't log in now

We've made a total re-design of an old SoundPark website, but saved main design. It was technically impossible to transfer all user data. If you were registered on the old website, you'll have to register one again. Also we have changes in user classes. We're really sorry about any inconvenience, but it had to happen some day. Thak You for staying with us!

**Comment by hidaba** [comment]
> We've made a total re-design of an old SoundPark website, but saved main design. It was technically impossible to transfer all user data. If you were registered on the old website, you'll have to register one again. Also we have changes in user classes. 

I've reregistered my account, in the browser I login correctly, in Jackett don't fine the new login page

**Comment by garfield69** [comment]
I see this too. I will update the indexer to bring it up to speed with the new web site design.

**Comment by garfield69** [comment]
bugger. 
the site has got a download path that I cannot resolve using a yml indexer.
this will need rewriting in C#
i'm going to delete this yml indexer and hope some c# dev will volunteer to re-write.
for reference this is what I have in yml so far
```yaml
---
id: soundpark
name: SoundPark
description: "SoundPark Semi-Private site dedicated to MUSIC."
language: en-us
type: semi-private
encoding: UTF-8
followredirect: true
links:
  - https://sound-park.world/
  - https://soundpark-club.casa/
legacylinks:
  - https://soundpark-club.com/

caps:
  categories:
    "Music": Audio

  modes:
    search: [q]
    music-search: [q, album, artist, label, year]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password

login:
  path: eng/login/
  method: form
  form: form[id="pms_login"]
  inputs:
    log: "{{ .Config.username }}"
    pwd: "{{ .Config.password }}"
    rememberme: forever
    pms_login: 1
    redirect_to: "{{ .Config.sitelink }}eng/login/"
    pms_redirect: "{{ .Config.sitelink }}eng/login/"
    trp-form-language: eng
  error:
    - selector: p.pms-login-error
  test:
    path: eng/
    selector: a[href*="eng/my-profile/"]

download:
  before:
    # https://sound-park.world/eng/lindsey-webster-back-to-your-heart-lossless-hi-res-2016/200420-2/
    path: "{{ .DownloadUri.PathAndQuery }}/?????????????/"
    method: get
  # https://sound-park.world/eng/torrent/download/?info_hash=87b6e41ba433aa16520d01105688b75c9cf652a2
  selector: p.attachment a
  attribute: href

search:
  paths:
    # https://sound-park.world/eng/?s=
    - path: eng/
  inputs:
    s: "{{if or (.Query.Album) (.Query.Artist) }}{{ or (.Query.Album) (.Query.Artist) }}{{else}}{{ .Keywords }}{{end}}"

  rows:
    selector: article[id^="post-"]

  fields:
    category:
      text: Music
    title:
      selector: a[title]
      attribute: title
    details:
      selector: a[title]
      attribute: href
    banner:
      selector: img
      attribute: src
      optional: true
    download:
      selector: a[title]
      attribute: href
    date:
      selector: time
      attribute: datetime
      filters:
        - name: replace
          args: ["T", " "]
        - name: dateparse
          args: "2006-01-02 15:04:05-07:00"
    size:
      # search page does not have size.
      text: "500 MB"
    seeders:
      text: 1
    leechers:
      text: 1
    downloadvolumefactor:
      text: 1
    uploadvolumefactor:
      text: 1
    description:
      selector: div.entry-summary
      remove: a
# engine MWT
```
