### ISSUE TITLE
[REQ]www.acgnx.se(Anime-Hentai)

### ISSUE THREAD

**Issue by berat1397** [Jackett/Jackett#9985]
Public mix anime content share torrent site.
Search engine and torrent linnks working.
Site and torrent updating and seeding.

Link: https://www.acgnx.se/

**Comment by garfield69** [comment]
@ngosang  buggered if I understand what is going on here.
I created acgnx.yml
```yaml
---
id: acgnx
name: AcgnX
description: "AcgnX is a Public site for ANIME"
language: en-uk
type: public
encoding: UTF-8
links:
  - https://www.acgnx.se/

settings: []

caps:
  categorymappings:
    - {id: 1, cat: TV/Anime, desc: "Anime"}
    - {id: 2, cat: TV/Anime, desc: "Anime English Translated"}
    - {id: 3, cat: TV/Anime, desc: "Anime Raw"}
    - {id: 4, cat: TV/Anime, desc: "Anime Non English Translated"}
    - {id: 5, cat: Audio/Video, desc: "Anime Music Video"}
    - {id: 6, cat: Audio, desc: "Audio"}
    - {id: 7, cat: Audio/Lossless, desc: "Audio Lossless"}
    - {id: 8, cat: Audio/MP3, desc: "Audio Lossy"}
    - {id: 9, cat: Books, desc: "Literature"}
    - {id: 10, cat: Books, desc: "Literature English Translated"}
    - {id: 11, cat: Books, desc: "Literature Raw"}
    - {id: 12, cat: Books, desc: "Literature Non English Translated"}
    - {id: 13, cat: TV, desc: "Live Action"}
    - {id: 14, cat: TV, desc: "Live Action English Translated"}
    - {id: 15, cat: TV, desc: "Live Action Raw"}
    - {id: 16, cat: TV, desc: "Live Action Non English Translated"}
    - {id: 17, cat: TV, desc: "Live Action Idol/Promotional Video"}
    - {id: 18, cat: PC, desc: "Software"}
    - {id: 19, cat: PC, desc: "Applications"}
    - {id: 20, cat: Console, desc: "Games"}
    - {id: 21, cat: Other, desc: "Pictures"}
    - {id: 22, cat: Other, desc: "Photos"}
    - {id: 23, cat: Other, desc: "Graphics"}
    - {id: 25, cat: Other, desc: "Other"}

  modes:
    search: [q]
    tv-search: [q, season, ep]
    music-search: [q]
    book-search: [q]

search:
  paths:
    # https://www.acgnx.se/today-1.html
    # https://www.acgnx.se/search.php?bound=content&keyword=sailor+moon&sort_id=2
    - path: "{{ if .Keywords }}search.php?bound=content&keyword={{ .Keywords }}&sort_id={{ join .Categories \",\" }}{{ else }}today-1.html{{ end }}"

  rows:
    selector: table#listTable > tbody > tr:has(a[href^="sort-"])

  fields:
    category:
      selector: a[href^="sort-"]
      attribute: href
      filters:
        - name: split
          args: ["-", 1]
    title:
      selector: a[href^="show-"]
    details:
      selector: a[href^="show-"]
      attribute: href
    magnet:
      selector: a[href^="magnet:?xt="]
      attribute: href
    date:
      selector: td:first-child
      attribute: title
      filters:
        - name: append
          args: " +00:00" # GMT
        - name: dateparse
          args: "2016-01-02 15:04 -07:00"
    size:
      selector: td:nth-child(4)
    seeders:
      selector: td:nth-child(6)
    leechers:
      selector: td:nth-child(7)
    grabs:
      selector: td:nth-child(8)
    downloadvolumefactor:
      text: 0
    uploadvolumefactor:
      text: 1
# engine HamotionCloud 1.3.5
```
but when I go to test  a keywordless search I see the indexer do the 
https://www.acgnx.se/today-1.html
(which works in the browser)
but Jackett gets a 302 redirect
```html
WebClient(HttpWebClient2): Returning Redirect => https://www.acgnx.se/today-1.html 131 bytes
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
 followed by some strange response
```
WebClient(HttpWebClient2): Returning OK => 2448 bytes <!doctype html><html><head><meta charset="utf-8"><meta http-equiv="pragma" content="no-cache"><meta http-equiv="cache-control" content="no-cache, no-store, must-revalidate"><meta http-equiv="expires" content="0"><script type="text/javascript">eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]\|\|e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('c 8={2:"t",f:"r"};6 d(){c a=3.2.k(/[a-j-9]{q}(?==)/g);s(a)w(c b=a.7;b--;)3.2=a[b]+"=0;l="+(m n(0)).o()}6 p(a){i 0<3.2.7&&(4=3.2.e(a+"="),-1!=4)?(4=4+a.7+1,5=3.2.e(";",4),-1==5&&(5=3.2.7),u(3.2.v(4,5))):""}6 h(a,b){3.2=a+"="+x(b)+";y=/;"}6 z(){d();h("A",8.2);B.C=8.f};',39,39,'007fbbfd7f381b7925fd722eb2703056007fbbfd7f381b7925fd722eb2703056cookie007fbbfd7f381b7925fd722eb2703056document007fbbfd7f381b7925fd722eb2703056c_start007fbbfd7f381b7925fd722eb2703056c_end007fbbfd7f381b7925fd722eb2703056function007fbbfd7f381b7925fd722eb2703056length007fbbfd7f381b7925fd722eb2703056data007fbbfd7f381b7925fd722eb2703056007fbbfd7f381b7925fd722eb2703056007fbbfd7f381b7925fd722eb2703056007fbbfd7f381b7925fd722eb2703056var007fbbfd7f381b7925fd722eb2703056clearCookie007fbbfd7f381b7925fd722eb2703056indexOf007fbbfd7f381b7925fd722eb2703056uri007fbbfd7f381b7925fd722eb2703056007fbbfd7f381b7925fd722eb2703056setCookie007fbbfd7f381b7925fd722eb2703056return007fbbfd7f381b7925fd722eb2703056f0007fbbfd7f381b7925fd722eb2703056match007fbbfd7f381b7925fd722eb2703056expires007fbbfd7f381b7925fd722eb2703056new007fbbfd7f381b7925fd722eb2703056Date007fbbfd7f381b7925fd722eb2703056toUTCString007fbbfd7f381b7925fd722eb2703056getCookie007fbbfd7f381b7925fd722eb270305632007fbbfd7f381b7925fd722eb2703056https://www.acgnx.se/today-1.html007fbbfd7f381b7925fd722eb2703056if007fbbfd7f381b7925fd722eb2703056f0ee86e868168e9c18aea6fa395205f5007fbbfd7f381b7925fd722eb2703056unescape007fbbfd7f381b7925fd722eb2703056substring007fbbfd7f381b7925fd722eb2703056for007fbbfd7f381b7925fd722eb2703056escape007fbbfd7f381b7925fd722eb2703056path007fbbfd7f381b7925fd722eb2703056jump007fbbfd7f381b7925fd722eb2703056e3c44ccd9c67e04c2fe36a8a32f17af4007fbbfd7f381b7925fd722eb2703056window007fbbfd7f381b7925fd722eb2703056location'.split('007fbbfd7f381b7925fd722eb2703056'),0,{}))</script></head><body onLoad="javascript:jump()"></body></html>
```
is this another one of those sites that generates html dynamically via JS ?
